### ISSUE TITLE
OS Explorer design tweaks [A1]

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1000]
OS-Explorer should serve as the homepage for OpenSpending.
I've added text and some basic layout of how things should be, but it doesn't look good aesthetically. 

Please spend a few hours in improving the design of page based on your best opinion (until we get a proper mock and wording from Sam & Cecile).

**Comment by cecilaki** [comment]
Here's the mock V1

![openspanking_next_landing_page_v2](https://cloud.githubusercontent.com/assets/6681719/15530783/1047199e-225f-11e6-8c18-1d7f294a1f30.png)

**Comment by akariv** [comment]
This issue is for a quick design improvement of the existing state until we get the detailed spec for #984 (including all the related content), which might take a few days/weeks.

@cecilaki I moved the mock to #984 where we can continue the discussion.

**Comment by cecilaki** [comment]
ok great thanks!

**Comment by pwalsh** [comment]
closing as no longer relevant. @smth is working on a new landing page integrated into the explorer.
