### ISSUE TITLE
OS Packager: publishing status error, datapackage not created

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1005]
When trying to upload  this dataset, here's the error in the publishing step: 
[Uploading JR14_Munic+Distr.zip…](this dataset )

![issue_flamish_region](https://cloud.githubusercontent.com/assets/6681719/15666401/5d2e3da0-2719-11e6-9fa9-b9613539a567.png)

**Comment by akariv** [comment]
File was not uploaded correctly it seems... @cecilaki

**Comment by akariv** [comment]
From inspecting the file, it seems that it had a BOM as its first character.
After removing this the upload passed without issues.
I'm opening an issue to support CSV files with BOM, and closing this one.
