### ISSUE TITLE
Remove publish button after file published

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1007]
When file is successfully published, remove the `publish` button because it's very confusing. 
The only call to action that should remain is "Explore and visualise your data now" 

<img width="602" alt="capture d ecran 2016-06-01 a 14 55 15" src="https://cloud.githubusercontent.com/assets/6681719/15735704/fda73534-289a-11e6-987b-d16987cde9f3.png">

**Comment by akariv** [comment]
This should be done as part of #988
