### ISSUE TITLE
Restore Landing page + Explorer for Alpha phase

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1009]

**Comment by cecilaki** [comment]
**A - Calls to Action**

<img width="500" alt="capture d ecran 2016-06-06 a 18 07 14" src="https://cloud.githubusercontent.com/assets/6681719/15830751/f16eb3f8-2c11-11e6-89bb-39c273bb7281.png">

**1 - Upload!**
Link > Packager upload page : next.openspending.org/packager/provide-data/ 

**2 - Search Datasets**
Link > Explorer landing page with Search field [+ filters ( continents / countries )?]

**B - Docs**

Replace Docs by Documentation

**C -  Stay in touch / mailing list**

Make sure the correct mailing list is linked 
<img width="533" alt="capture d ecran 2016-06-06 a 18 18 48" src="https://cloud.githubusercontent.com/assets/6681719/15830989/24baa00e-2c13-11e6-9fc1-c134434c340e.png">

**Comment by akariv** [comment]
"Make sure the correct mailing list is linked" - which one is the correct one @cecilaki ?

**Comment by pwalsh** [comment]
I suggest changing it to be a link to the forum.

**Comment by cecilaki** [comment]
I suggest adding both, then people choose how they want to engage. 
1 - by reading existing topics and conversations on the forum and ultimately participating 
2 - by subscribing to a mailing list (openspending@lists.okfn.org ) (_Do we want to kill the existing mailing list, or it's simply not a priority?_)

**Comment by akariv** [comment]
Is there even such a mailing list? I'm not on it so I don't know if it has seen any traffic lately.

**Comment by cecilaki** [comment]
Yes there's such a mailing list, not so active recently but people used to post regularly on it.
There's also an open spending dev list. 

What about something like that on the #contribute section? 

<img width="757" alt="capture d ecran 2016-06-07 a 08 45 19" src="https://cloud.githubusercontent.com/assets/6681719/15849840/6a84a46c-2c8c-11e6-93d6-a6fef9e05603.png">

**Comment by akariv** [comment]
I clicked the 'OpenSpending Community' - it brings me to a page already covering the communication channels, most of it is outdated.
I think the way to go is to leave just that link and make sure that the data in community.openspending.org is updated (+add an 'outdated' warning in relevant places).
