### ISSUE TITLE
OS Viewer: need to display all mapped levels

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#1012]
I uploaded [a file,](https://docs.google.com/spreadsheets/d/1gAWbT8HbX2bnxcLBOAcIhcZ9ROlzjZHzJes_lGqvZ8s/edit?usp=sharing) and mapped 5 levels of hierarchies (with codes and display names accordingly). All 5 levels were mapped as Economic Classification.
In OS Viewer, when clicking on the "economic classification" hierarchy, the visualization starts on level 3, skipping level 1 and 2.
![level 3](https://cloud.githubusercontent.com/assets/17012538/15903608/3350e19c-2db6-11e6-9a2f-04d9cc2fd1e7.PNG)

Expectations:
1. Have the visualization start on the first mapped level.
2. Have a list of the hierarchy levels when I click on the respective classification (in this case economic). Now the levels are showing under "Date" (when "Date" is clicked):
![date](https://cloud.githubusercontent.com/assets/17012538/15903504/c771a448-2db5-11e6-9f5c-7da2242203b2.PNG)

**Comment by cecilaki** [comment]
I've tried to reproduce the issue, and used the unique identifier in the datatype to map all hierarchies but I still can't see the 5 levels of hierarchies either, even thought the 3 first levels are showing up correctly.

See [here](http://next.openspending.org/viewer/525a389a219b4aa66f2b2b94311c76e5:test_douala_city?measure=Depenses_realisees.sum&order=Depenses_realisees.sum%7Casc&groups%5B%5D=date_2.Annee).

**Comment by akariv** [comment]
I already solved this issue - I'm testing it now and will deploy it later today.

**Comment by cecilaki** [comment]
Ok great then. Keep us updated then!
