### ISSUE TITLE
OS Explorer Results page: Add Countries and Continent full names

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1013]
**Current** > 
<img width="289" alt="capture d ecran 2016-06-13 a 17 48 06" src="https://cloud.githubusercontent.com/assets/6681719/16014885/7b273f12-3193-11e6-9702-3f712f5cb525.png">

**Expected** > 
<img width="289" alt="capture d ecran 2016-06-13 a 18 24 28" src="https://cloud.githubusercontent.com/assets/6681719/16015021/270f2524-3194-11e6-9a31-ba81cc873b32.png">

**Comment by pwalsh** [comment]
@akariv this looks like it might be a simple fix. Worth addressing while @vitorbaptista is working on the viewer?

**Comment by kravets-levko** [comment]
@pwalsh It's already fixed and deployed

**Comment by pwalsh** [comment]
Cool!
