### ISSUE TITLE
Mexico Files for Pre-Pilot

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1016]
All files to upload for pre-pilot are listed in [this repo](https://github.com/openspending/fiscal-data-package-demos/tree/master/Mexico-Pre-Pilot)

To close the issue, all of these datasets need to be cleaned, modeled and uploaded to OpenSpending.

#### Federal Level:

- [ ] Presupuesto de Egresos de la Federación - (2016)
- [ ] Proyectos Entidades Federativas (2016)
- [ ] Ramo 23 Provisiones salariales y económicas (2016)

#### Regional/Local Level:

- [ ] Gasto Federalizado (Avance Financiero) Puebla (1rst Quarter 2016)
- [ ] Gasto Federalizado (Proyectos) Ciudad de México (1rst Quarter 2016)

**Comment by pwalsh** [comment]
@cecilaki I now understand that these are *not* actionable for the pre-pilot, correct?

**Comment by cecilaki** [comment]
Yes correct.

**Comment by pwalsh** [comment]
closing because no longer relevant.
