### ISSUE TITLE
Line Charts: Years reverse on X-axis when dimension/ budget phase is changed

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1017]
**Current:** when selecting the Line Chart as a viz type, changing dimension/budget phase make the years reverse in the X-axis in the visualisation.

**Expected:** Changing dimension shouldn't affect the years order in the visualisation and should always be in the same chronological order. 

**Steps to reproduce:** 
- Select a dataset with multiple years
- Create a Line Chart visualisation
- Change the dimension/budget phase
- Check the years order in the viz

**Comment by cyberbikepunk** [comment]
Sorry folks, was playing with pycharm....

**Comment by kravets-levko** [comment]
@cecilaki Can you check whether this bug is still reproducing after refactoring?

**Comment by cecilaki** [comment]
@kravets-levko I don't reproduce after the refactoring!
