### ISSUE TITLE
Create notification in the Viewer when pivot tables result reach a display/query limit.

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1018]
**Current:** When a Pivot Table query result is too big ( > 2,000 rows) the pivot table crashes but the user is not notified his/her query has reached a limit. 

**Expected:** Display a notification to the user, inviting her/him to try another query or use the DataMine for advanced and big queries. 

<img width="834" alt="capture d ecran 2016-06-20 a 09 29 51" src="https://cloud.githubusercontent.com/assets/6681719/16187720/bd289ac4-36c9-11e6-83f7-e757ff7df3c4.png">

**Comment by pwalsh** [comment]
I think we should label this as a bug and not an enhancement.
