### ISSUE TITLE
Pivot table randomly displays years in columns by default

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1019]
**Current:** 
Pivot Tables sometimes doesn't display Years/Date in Columns by default when multiple years are present. (from #935 )

Here are a few examples for which it doesn't work:
- BOOST Paraguay Municipalities
- BOOST Moldova
- Mexico 2015 Budget

And what is displayed instead: 
<img width="422" alt="capture d ecran 2016-06-20 a 10 36 06" src="https://cloud.githubusercontent.com/assets/6681719/16189556/d59e482a-36d2-11e6-8319-29bcbcee3ac2.png">

_There must be a reason why it doesn't work though. If identified, could be something we should look at while modeling._

**Expected:** 
Date / years in Columns should be displayed by default in the Pivot table when multiple years are present. 
When available: Administrative, Economic or Functional classification in Rows

<img width="968" alt="capture d ecran 2016-06-20 a 10 17 44" src="https://cloud.githubusercontent.com/assets/6681719/16189520/b0967c0a-36d2-11e6-8905-bc319d3d68ee.png">

**Comment by kravets-levko** [comment]
@cecilaki Can you check whether this bug is still reproducing after refactoring? Thanks

**Comment by cecilaki** [comment]
Hey Levko! So no I don't reproduce it at all! Great job!
