### ISSUE TITLE
When multiple years in dataset, display the last year by default in all viz types

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1020]
**Current:** 
The visualisations created by default are aggregating all the data available

**Expected:**
The visualisations created by default are only showing the data from the most recent year available when multiple years are present.

This would apply to Maps, Treemaps, Bubble Trees, Pivot Tables

**Comment by pwalsh** [comment]
@cecilaki this should be a user story on the [user story board](https://github.com/openspending/openspending/issues/1020), which helps us track the actual use cases, and where the request comes from. I get the point of the issue but it means treating date/time dimensions as a special case, and having special handling logic for them, which, might seem reasonable, but could have an effect on other use cases for the Viewer.

**Comment by cecilaki** [comment]
Ok. I've entered a user story on the user story board (Scratch board)

**Comment by akariv** [comment]
This basically translates to: 
If no filter is selected, and there are more than one values in a datetime dimension, automatically select the largest value.
