### ISSUE TITLE
In the Viewer sidebar, filters should display the Label rather than the ID where possible

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1024]
I don't think there's too much to add about this one.

**Comment by cecilaki** [comment]
So it's fixed @akariv ?

**Comment by akariv** [comment]
Don't think it was ever broken :)
The probable cause here is a missing link between code and label. I can't really say more as there's not many details in this bug report.

**Comment by cecilaki** [comment]
So @akariv in [this visualisation](http://next.openspending.org/viewer/525a389a219b4aa66f2b2b94311c76e5:budget_helsinki_03_2016?measure=summa.sum&order=summa.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=activity_2.Tiliryhma_Account_Group&rows%5B%5D=activity_2.Tiliryhma_Account_Group&columns%5B%5D=activity_2.Tiliryhma_Account_Group), the ID appear in the Viewer sidebar and not the Labels although both exist and are supposed to be tightened. Does that illustrate this issue or is it something else? 

<img width="293" alt="capture d ecran 2016-07-18 a 12 52 51" src="https://cloud.githubusercontent.com/assets/6681719/16912781/93f42eec-4ce6-11e6-83f3-ae4ff704fd70.png">

**Comment by akariv** [comment]
Which values appear in the submenu? Are they ids or labels?

**Comment by cecilaki** [comment]
Ok I see,thanks! But then the expected title to be displayed is the label associated with the ID for all the titles where it's mentioned `_id` - I don't know if that's the same issue, if it has to do with the way the file is mapped or with what is displayed as filters in the Viewer..

**Comment by akariv** [comment]
The label for the filter is taken from the label of the <code> column (and not the <label> column). This is because filtering is done on the ids, not the labels.
Do you think this should be different?

**Comment by akariv** [comment]
Okay, closing for now.
