### ISSUE TITLE
Viewer sidebar filters should drill-down the hierarchical classification tree

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1025]
Just so that it's clear... say you have a `administration-classification` dimension with 2 levels as follows:

Level_1 | Level_2
------------ | -------------
A | 1
B | a
A | 2
B | b
B | c
A | 3

Filtering `Level_1` for `A` should restrict `Level_2` choices to `1`, `2` and `3`. This goes for all hierarchical dimensions of course.

**Comment by cecilaki** [comment]
Won't fix by design if I understood correctly. 
The hierarchies drill-down should be made only in the visualisations themselves. 
However I leave it open to discussion as it seems to be an interesting usecase behind it.
