### ISSUE TITLE
Mapping UX ingestion of currency columns could be a little more format tolerant  

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1026]
## Ouch

I was a little surprised that the UX wasn't happy ingesting formats such as `3,000 EUR`. I know that such formatting is common place in Excel and it strikes me that a little parsing would go a long way towards user friendliness. It was kind of annoying being told half way into the mapping process that I had to go back and clean my data. 
## Better

There are two ways of solving this: 
1. The automatic way: remove all sub-strings that match currency symbols, names and abbreviations.
2. The manual way: leave the user define the format.

I would go for the first option personally. 
##

**Comment by pwalsh** [comment]
Closing. This will landing in the table schema library soon enough, and thereby OpenSpending will be able to support it
