### ISSUE TITLE
OS-conductor env-vars prefixes

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1027]
The env-vars concerned are: `_access_key_id`, `_secret_access_key`, `_storage_bucket_name` and `_s3_hostname`. 

The [docs](http://docs.openspending.org/en/latest/developers/conductor/) and the [config.yml file](https://github.com/openspending/os-conductor/blob/master/config.yml) say `OPENSPENDING_`. The [code](https://github.com/openspending/os-conductor/blob/master/conductor/blueprints/datastore/controllers.py) says `OS_`.  Following the documentation causes a `KeyError` being raised.

Other env-vars are prefixed with `OS_` and cause no trouble. I don't know what is being currently used on various instances of the conductor, but I'm inclined to prefix everything with `OS_`.

**Comment by akariv** [comment]
Fixed in the docs.
