### ISSUE TITLE
Boto -> Boto3

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1028]
Boto is quirky. One example is [this bug](https://github.com/boto/boto/issues/443). No idea how much work is involved to port things to `boto3`. @akariv what is your opinion?

**Comment by akariv** [comment]
I really don't have any strong feelings towards any of these libraries.
I would say that if the current implementation of os-conductor is working, there's no need to change it. However, new implementations (e.g. gobble) might choose better libraries.

**Comment by pwalsh** [comment]
WONTFIX. Will only address in face of blocking bugs.
