### ISSUE TITLE
Openspending Wizard

### ISSUE THREAD

**Issue by HimmelStein** [openspending/openspending#1029]
here are some feedback about the OS wizard:
(1) the sample csv which I used is a tiny part of the ESIF-2014 file. currently at http://wenxion.net/pub/ESIF-14_sample1.csv http://wenxion.net/pub/esif-14_sample2.csv  This csv file does not have a column for date. a necessary condition to move to Step 3 is: at least one column should be mapped to 'date'. I have to manually add a date column, and repeat the steps again.
(2) the Date-->Other Date must have the format '%Y-%m-%d', however, it would not accept '2014-01-01'

**Comment by pwalsh** [comment]
"Constants" are being tracked in a different issue (solves the case of dates without a column in the source data).
