### ISSUE TITLE
UI / Visualisation - Pie Chart

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1036]
**Current**
- Only percentages are shown

<img width="254" alt="capture d ecran 2016-07-04 a 17 49 07" src="https://cloud.githubusercontent.com/assets/6681719/16565752/a82d03fc-420f-11e6-8c7d-20f72d0d11e4.png">

**Expected:** 
- Show total amount
- Show amount of each item of the pie chart
- Show a clear legend and/or list of items associated with amounts and share (%)

**Comment by Hazwany** [comment]
The drill down feature does not seem to work for pie chart. And as mentioned by @cecilaki, percentage only shown.

This is the view from the 1st hierarchy:
![screen shot 2016-07-06 at 1 50 51 am](https://cloud.githubusercontent.com/assets/11497391/16594250/217a147c-431c-11e6-8780-7cb435af533b.png)

Nothing happens after I click to see more detailed spending.

When I choose another visualisation such as bubble map, then I'm able to drill down for more detailed spending.

1st hierarchy:
![screen shot 2016-07-06 at 1 52 24 am](https://cloud.githubusercontent.com/assets/11497391/16594331/81474532-431c-11e6-836f-776db2cfecba.png)

2nd hierarchy
![screen shot 2016-07-06 at 1 54 20 am](https://cloud.githubusercontent.com/assets/11497391/16594383/c09434ca-431c-11e6-8b9c-73ad2b677d88.png)

It gets more interesting when I am able to see the 2nd hierarchy for pie chart. (Disclaimer: my laptop screen is pretty small but I hope you could see that pie chart only works when I include Bubble Map or Tree Map as the second visualisation.)

![screen shot 2016-07-06 at 1 55 08 am](https://cloud.githubusercontent.com/assets/11497391/16594528/6e1cfdd4-431d-11e6-9d8e-8858db39cd27.png)

Upclose on the 2nd hierachy in pie chart:
![screen shot 2016-07-06 at 1 54 27 am](https://cloud.githubusercontent.com/assets/11497391/16594541/7cad7b4e-431d-11e6-8050-f67a13bcd8c9.png)

I have also tested with Pie Chart and Tree Map. Same issue.

When I work on Bubble Map and Tree Map alone, the drill down from 1st hierarchy to the last works just fine.

**Comment by leowmjw** [comment]
@akariv FYI; my fix for this is at: https://github.com/openspending/babbage.ui/blob/feature/modern/src/bindings/vuejs/Pie.vue#L44-L71

It seemed redundant to use events during drilldown in this case; so I just used a common 'babbage-click' event passing the drilldown value.

I used a common 'update-babbage' event that all Babbage components listen to refresh itself with the new state.

```
        events: {
            'update-babbage': function (new_initstate) {
                // DEBUG:
                // console.error("FROM_PARENT_UPDATE_BABBAGE::")
                this.state = new_initstate
                this.rebuildPieChart()
            }
        },
...
        methods: {
            rebuildPieChart: function () {
                const pieChart = new PieChartComponent()
                const wrapper = document.querySelector(`div#pie-${this.pieid}`)

                pieChart.build(this.endpoint, this.cube, this.state, wrapper)
                pieChart.on('click', function (PieChartComponent, item) {
                            // DEBUG:
                            // console.error("EL:", util.inspect(item.id, {depth: 10}))
                            // item has a whole bunch of stuff; make sure you pass on only the key!!
                            this.$dispatch('babbage-click', item.id)
                        }.bind(this)
                )

            }
        },

```

**Comment by VictoriaVlad** [comment]
@akariv, @kravets-levko, Nany brought this up during today's Labs Hangouts. May I know what is the blocking point here to get this fixed?

**Comment by kravets-levko** [comment]
@VictoriaVlad It's in queue. I'm currently working on openspending/openspending#1114 and then I'll probably continue with this issue.
