### ISSUE TITLE
os-conductor: refactor to use standard project structure, remove node dependency

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1038]

**Comment by pwalsh** [comment]
@akariv what is this, and, is it still relevant?

**Comment by SillySam** [comment]
This issue should be closed

**Comment by akariv** [comment]
@pwalsh os-conductor uses a strange management system based on node an gulp while being a pure python project.

This issue is to fix that and adapt this project to the OKI standard. 
I guess this should take no longer than a day.

**Comment by pwalsh** [comment]
ok. leaving on backlog
