### ISSUE TITLE
Wrong parent with wrong value - Tree Map & Bubble Map

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#1044]
The [Ministry of Finance Treasury 2015 budget](http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:mof1_2015detailed?measure=Amount.sum&order=Amount.sum%7Cdesc&visualizations%5B%5D=Treemap&visualizations%5B%5D=BubbleTree&groups%5B%5D=administrative_classification_2.Level_1&rows%5B%5D=administrative_classification_2.Level_1&columns%5B%5D=administrative_classification_2.Level_1) has been uploaded recently and the visualisations in treemap and bubblemap shows incorrect parent with incorrect value. It suppose to be Lembaga Hasil Dalam Negeri (LHDN) **RM1,305,841,900** [_translation: Inland Revenue Board of Malaysia_] **as the parent** **not** Lembaga Pembangunan Langkawi (LADA) **RM29,201,300** [_translation: Langkawi Development Authority_].

![screen shot 2016-07-13 at 5 45 26 pm](https://cloud.githubusercontent.com/assets/11497391/16799226/53c22ee0-4922-11e6-8103-1f27ffd1309d.png)
![screen shot 2016-07-13 at 6 00 04 pm](https://cloud.githubusercontent.com/assets/11497391/16799507/b4c1a760-4923-11e6-819c-ddc725d5dbc7.png)

When looking in detail for each spending, all amounts are incorrect.

**Comment by cecilaki** [comment]
Can someone investigate this also @akariv ? Will move to next spring after estimate. thanks!

**Comment by akariv** [comment]
I didn't quite understand the expected result and the actual status.
Isn't "Lembaga Pembangunan Langkawi (LADA)" a value that appears in the 3rd level of the administrative classification (with code `050000`), and "Lembaga Hasil Dalam Negeri (LHDN)" on the 4th (with codes `060000` and `060100`)?

@Hazwany

**Comment by Hazwany** [comment]
Ah yes. You are right, @akariv. I must have missed that one out when I check the raw data back again from the OS Viewer. My apologies, Adam.

I have re-uploaded again the raw data with corrected code in the 3rd level for LHDN and LADA.

![screen shot 2016-07-18 at 11 19 30 pm](https://cloud.githubusercontent.com/assets/11497391/16919924/20d0ec36-4d3e-11e6-8f98-415397309d0b.png)

![screen shot 2016-07-18 at 11 21 42 pm](https://cloud.githubusercontent.com/assets/11497391/16920000/6e1654c2-4d3e-11e6-8182-8b4d1b28f479.png)


Drilled down worked fine for Tree Map and Bubble Map but not for Pie Chart. :-(

**Comment by akariv** [comment]
The issue with the pie-chart is the one mentioned in #1036, no?

**Comment by Hazwany** [comment]
Yes, it is. @akariv

**Comment by akariv** [comment]
Alright - so I guess I can close this one, right?

**Comment by Hazwany** [comment]
Yes, please. You may close this one. @akariv
