### ISSUE TITLE
DataMiner not opening

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1046]
DataMiner not responding when logged in. 

![la pagina rd openspending org no funciona](https://cloud.githubusercontent.com/assets/6681719/16879765/592b0df2-4ab2-11e6-9c06-c3ae7dd16359.png)

**Comment by cecilaki** [comment]
Not really sure how you can investigate this @akariv. If you have specific questions to ask to conduct a proper bug investigation, could you indicate them here? Thanks!

**Comment by akariv** [comment]
I'll try to investigate this further.
Is this still happening? Is it is, could you try and follow this procedure:
- Go to the viewer
- Log out
- Refresh the page
- Log in
- Click the 'datamine' button in the page
And let me know if this is still occurring

**Comment by KrzysztofMadejski** [comment]
Have the same with the error "Too many redirects". 

Path: While logged-in on http://next.openspending.org/viewer/086ba4db0d87a68374d5625177ae5153:jmd-expend-2017 I click [Analyse this dataset in Data Mine](http://rd.openspending.org/queries/new?queryText=SELECT%20*%20FROM%20fdp__086ba4db0d87a68374d5625177ae__jmd_expend_2017%20LIMIT%2010&focusedTable=fdp__086ba4db0d87a68374d5625177ae__jmd_expend_2017&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzEzNTk4NDYsInVzZXJpZCI6IjQxMmNmMDRjNzFmY2I5OTkwYzMwNTZhN2RkMmJmOWJiIn0.94YelOZ3rY9sF0nhPfspOFickYZDZJ-QliayRRTEV8k)

Redirects bouncing between 
![osn-bug1](https://cloud.githubusercontent.com/assets/849975/17333799/17459922-58d4-11e6-9182-4e57c18398dc.PNG)

**Comment by akariv** [comment]
@KrzysztofMadejski thanks for the debugging info! It will be really helpful in order to solve this.

**Comment by pwalsh** [comment]
FIXED>
