### ISSUE TITLE
OS-Viewer: Able to see/sort date dataset uploaded/updated

### ISSUE THREAD

**Issue by leowmjw** [openspending/openspending#1048]
I am trying to get the latest datasets for my BabbageUI app; for example: keyword "Bajet"; but it is not clear when the dataset  is uploaded/updated.  

I would like to find out new datasets that have been updated/uploaded since I last looked.  A sort would be nice; but displaying upload/update date would be sufficient.

**Comment by akariv** [comment]
Yes, we will add that.
