### ISSUE TITLE
Add new data in a concatenated existing uploaded file 

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1050]
How would a user manage to update an uploaded file on OS with new data, say a certain amount of lines corresponding to a new period of time, without having to re-upload the whole file? 

Ex: 

City X Budget file for the year 2017 who is updated every month with adding new monthly approved budget data to the original file. Assuming in this case that the new data to be added matches exactly the uploaded model. 

Would the CLI be appropriate in this case?

**Comment by pwalsh** [comment]
- This question is captured in this user story: https://trello.com/c/WkWAmylU
- The question of *how* will be answered when @akariv gets to the scoping of this work, [here](https://github.com/openspending/openspending/issues/1064)
- The CLI is likely one part of this, yes, but definitely not the solution as such
