### ISSUE TITLE
Problem loading on OS Viewer, auto drop first dataset as 'test' but not as Ministry of Defece (dataset).

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#1053]
The dataset _'[Bajet Kementerian Pertahanan 2015](http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:mod2015)'_ (Ministry of Defence 2015) has a loading problem. It will auto-drop to the first data set; which is test. This is incorrect; it should show Error Message instead.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11497391/17047421/650ed618-5010-11e6-9332-3ca1dbd60679.gif)

To view more details of this problem, see video [here](https://drive.google.com/file/d/0B7BVHpQAoqcINUhlNmR0cVBiYWM/view?usp=sharing).

**Comment by Hazwany** [comment]
Loading problem also happens from OS Packager to OS Viewer.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11497391/17048780/2dc67872-501b-11e6-85f7-9dfd70aac3a1.gif)

**Comment by akariv** [comment]
@Hazwany I found the issue and working on a fix, it will be deployed in the next few minutes.

**Comment by akariv** [comment]
@Hazwany please try again - you should be able to see your dataset now.
Also, you can now visit http://next.openspending.org/admin/ to manage the visibility of all your datasets, i.e. whether they are publicly visible or only visible to you.
