### ISSUE TITLE
Facts table horizontal scroll hides the pagination controls

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#1054]
In the OS Viewer, when a facts table has too many columns, it eventually needs to be scrolled horizontally. As both the table element and the pagination controls are both inside the same div (which has overflow-x:scroll), the pagination controls get hidden.

A suggestion is to have the table inside a separate div which gets the overflow-x:scroll attribute. I tried this in my browser's dev tools and it works fine. If it is easier for you, I can make a pull request.

**Comment by akariv** [comment]
A pull request would be much appreciated!
