### ISSUE TITLE
OS Viewer: are date time dimensions obligatory?

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#1055]
This is a portion of app.js:

```

function init(packageModel, initialParams) {
  var anyDateTimeHierarchy = _.first(packageModel.dateTimeHierarchies);
  initialParams = normalizeUrlParams(initialParams || {});
  initialParams = validateUrlParams(initialParams, packageModel);

  var defaults = getDefaultState({
    packageId: packageModel.id,
    countryCode: packageModel.meta.countryCode,
    dateTimeDimension: _.first(anyDateTimeHierarchy.dimensions).key
  });

  return _.extend(defaults, initialParams);
}
```

`_.first(anyDateTimeHierarchy.dimensions).key` assumes that there will be a date time hierarchy no matter what. Is this by design/specification?

**Comment by akariv** [comment]
It is assumed that a fiscal data set has rows containing information about
an amount of money, transferred from one party (possibly to another) at some point in time (or time period).

That being said, sometimes this information is implied (e.g. fiscal year is known but is not part of the data). For these cases, we plan to implement the ability to define 'constant' columns which will contain data outside of the data-file.
