### ISSUE TITLE
OS Packager, mapping: order of "Activity" datatype sub-menu

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#1057]
Proposal to change the order of the  "Activity" datatype sub-menu in the Packager, from
![order of activity datatype uploader](https://cloud.githubusercontent.com/assets/17012538/17114118/692b8350-5262-11e6-8d42-797c766b1d37.PNG)
to Program, Project, Subproject, Contract.

Currently it is alphabetic order.

**Comment by pwalsh** [comment]
@akariv @smth is this still relevant as a standalone issue?

**Comment by akariv** [comment]
No, closing.
