### ISSUE TITLE
OS Packager, mapping: sub-menu for the "Expenditure type" datatype

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#1058]
Proposal to add sub-menu for the "Expenditure type" datatype, including "Identifier" and "display name", (it's missing now). Was it left out on purpose?
![capture](https://cloud.githubusercontent.com/assets/17012538/17127964/3b997436-52be-11e6-894a-6fdd5175dca6.PNG)

**Comment by akariv** [comment]
If there's a need for more detailed data types, these can be easily added.

**Comment by VictoriaVlad** [comment]
@cyberbikepunk mentioned this idea. Loic, do you still see a need for this sub-menu?
