### ISSUE TITLE
Theming OS javascript apps

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1062]
# Description

There have been requests to theme OpenSpending (Next) from various partners across different projects to date. The modular nature of the OS components means that theming can be quite targeted to a specific app/ui.

As we want theming to be rather limited, so as not to introduce changes that can break the UI in subtle or significant ways, we should introduce a limited set of specific "theming hooks".

The most common, and standard, use case for theming would be a user hosting a version of an OS app (say, the Viewer), and providing theming customisation via the aforementioned "theming hooks". This gives the user all the power of a ready-to-go app for working with fiscal data, with no need to fork or heavily change the code itself in order to achieve basic visual customisation.
## User stories

https://trello.com/c/5RDPe50i
## Suggested implementation

A set of specific theming entry points can be exposed as environment variables. Optionally, for less standard cases where we might want to allow customisation of the theme, a subset of those entry points can be exposed as query parameters to each app, which would be useful for scenarios where the user is embedding components from centrally-hosted OpenSpending.
#### Common
- `OS_{APP_NAME}_PRIMARY_COLOR`
  - `?uiPrimaryColor` as query param
- `OS_{APP_NAME}_SECONDARY_COLOR`
  - `?uiSecondaryColor` as query param
- `OS{APP_NAME}_CONTEXT_COLOR` (the shade of grey/black used across the panels and so forth: if we use calculations in sass or less for various shading elements than this would be a powerful option)
  - `?uiContextColor` as query param
- `OS_{APP_NAME}_LOGO`
  - text or url to an image with pre-declared dimensions
  - `?uiLogo` as query param
- `OS{APP_NAME}_CUSTOM_STYLESHEET`
  - a url to a custom style sheet
  - do not expose as url param, as lots can go wrong
#### App specific

Some apps have special needs. Such as the Viewer, which also hosts Views with a color palette. I guess that the Views use some color palette API in D3: we could expose this directly to the user as `OS_VIEWS_COLOR_PALETTE` or similar.
# Tasks
- [ ] TBD by @akariv, I'm just visiting :)

**Comment by pwalsh** [comment]
@akariv note that the above  notes, and our discussion, were particular focussed on the GIFT use case.

We also have some OBEU use cases, and these are more related to custom installs of the packager/viewer/explorer/admin.

Please treat them all as one set of tasks.

User stories:

- https://trello.com/c/5RDPe50i
- https://trello.com/c/e2w8pBag

**Comment by pwalsh** [comment]
@akariv Please also see https://github.com/openbudgets/platform/issues/18#event-797378219

We will need to start on this work soon.

**Comment by akariv** [comment]
From the scope document:
The addition of an API to customize the styling of the OS Viewer app, while the Viewer itself is still hosted by the central OKI server
The customization will be as follows:
- The user provides a URL to a JSON file
   - For server-side installs, this URL can be provided as an environment variable
- This JSON file has a set of explicit keys and values that will be used to change key elements of the Viewer theme. These elements are:
   - Primary color: the dominant “brand” color for the Viewer
   - Secondary color: the secondary “brand” color for the Viewer
   - Context color: the color used as a basis for calculations of the “greyscale” aspects of the UI, such as panel lines and backgrounds
   - Logo: either a URL to a logo, of certain dimensions, or text to display for a logo, of a certain maximum length (dimensions and length to be defined)
   - View palette: a set of color codes for use in visualisations. The current, default palette lists 22 color codes. Using this would completely override the default palette with the listed colors
   - Font: a description of any default web font and size to use. Note that changes to font, especially size, can have unexpected consequences for a user interface, so this feature is to be used with care :)

**Comment by pwalsh** [comment]
@akariv yep, but definitely cover all the various use cases we have for the piloting and for OBEU, and expose as env vars and params (for both use cases).

If you prefer to break down into a few issues, that is ok with me, but there is a lot of commonality in terms of theming and hooks into the UI that i'd rather we get it all done across the apps in a unified effort.

**Comment by akariv** [comment]
@pwalsh I was just collecting all requirements in the issue

**Comment by akariv** [comment]
Chosen implementation is as follows.

We have a few built-in themes. Each theme is represented as a json file under `app/config/themes`. 

By default, app will use `default.json` (the default theme). If the URL contains `theme=dark`, we will try to use `dark.json` as the theme. In case it's not found, we will fall back to the default theme.

Themes always use `default.json` as a basis, so that you can override only part of the scheme (or even modify single list elements: use `{}` to use a list element unchanged and `false` to remove one).

Independent installs of our app will have a single point of modification for theming. Source installations can edit the file directly. Docker deployments can override `default.json` or add a new theme using Docker's `ADD` command.
Partners can upload a new theme via a pull-request, and refer to it in the query parameters.

Sample `defautlt.json`:
```json
{
  "colors": {
    "brand": "#3a99d9",
    "sidebar": "#2a2d34",
    "content": "#f5f5f5"
  },
  "header": {
    "links": [
      {
        "title": "Upload Data",
        "href": "/packager/"
      },
      {
        "title": "Explore Datasets",
        "href": "/explorer/"
      }
    ],
    "logo": {
      "icon": "assets/os.svg",
      "image": "assets/viewer.svg"
    }
  },
  "footer": {
    "projectLogo": {
      "image": "http://a.okfn.org/img/openspending/logo.svg"
    },
    "orgLogo": {
      "href": "http://okfn.org",
      "image": "http://a.okfn.org/img/oki/landscape-white-165x43.png"
    },
    "links": [
      {
        "title": "Privacy policy",
        "href": "https://okfn.org/privacy-policy/"
      },
      {
        "title": "IP policy",
        "href": "https://okfn.org/ip-policy/"
      },
      {
        "title": "Cookie policy",
        "href": "https://okfn.org/cookie-policy/"
      },
      {
        "title": "Terms of use",
        "href": "https://okfn.org/terms-of-use/"
      }
    ],
    "socialMedia": [
      {
        "href": "https://facebook.com/OKFNetwork",
        "icon": "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png",
        "alt": "Facebook"
      },
      {
        "href": "https://twitter.com/okfn",
        "icon": "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png",
        "alt": "Twitter"
      },
      {
        "href": "https://www.youtube.com/user/openknowledgefdn",
        "icon": "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png",
        "alt": "YouTube"
      }
    ]
  }
}
```

**Comment by pwalsh** [comment]
@akariv I commented (and approved) the PR for the Viewer. The same of Packager/Explorer/Admin will be good :), and, I also realised that my comment on allowing an env var for the theme directory will allow them all to share a theme directory, if they run on the same machine/have access to the same filesystem

**Comment by akariv** [comment]
I will open specific issues per app. 
I assume that for the viewer it is the most needed (due to embedding) while for other apps the state is different (Explorer and Admin as they're also user facing, Packager less so).

Re the theme sharing - this assumes that the theme file will be identical for all apps, but although parts might be similar, other not so much (e.g. header links might be different, logos etc.)

**Comment by pwalsh** [comment]
@akariv ok. def. need explorer for OBEU now, and possibly packager too but unclear. better to have them all though rather than revisit this again?
