### ISSUE TITLE
OS Packager: unique sampled values

### ISSUE THREAD

**Issue by KrzysztofMadejski** [openspending/openspending#1065]
Showing sample values in the "Describe your data" step could show unique values, instead of the same ones in case the first three are identical. It's nice-to-have, low-priority, because I assume user knows that data he uploads.

![osn2](https://cloud.githubusercontent.com/assets/849975/17335163/4bbed3e4-58d9-11e6-808b-ba7d3a91d529.PNG)

**Comment by pwalsh** [comment]
@akariv @smth I believe the design enhancements address this, so not sure we need to track this as a distinct issue? pls close if agreed.

**Comment by akariv** [comment]
It's actually a separate issue.
I'm not sure if it's easy to implement but it still is a good idea.

Moving to the back log for now.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. Label `prioritized` was removed a long time ago. Please feel free to re-open if this is still relevant.
