### ISSUE TITLE
OS Packager: error reporting

### ISSUE THREAD

**Issue by KrzysztofMadejski** [openspending/openspending#1066]
When there is an error, like NaN (**btw: what does it mean?**) it's really hard to see, it's easy to skip it.

![osn4](https://cloud.githubusercontent.com/assets/849975/17335506/7c9c0ed6-58da-11e6-9ffb-95d7ead203b3.PNG)

It would be great to list all errors at the bottom, where if valid data there is `Continue` step:
![osn3](https://cloud.githubusercontent.com/assets/849975/17335608/cf83e088-58da-11e6-8a96-cf776354827b.PNG)

With the NaN error I have, I got message `You should map at least a 'value' and a 'date' to continue.` whereas I should get the error message there. (If I clear the mapping for NaN I have no errors and a continue button, so I shouldn't "map at least a 'value' and a 'date' to continue").

![osn5](https://cloud.githubusercontent.com/assets/849975/17335521/8dde1324-58da-11e6-9a55-83ce46eb5069.PNG)

I'm working on [this dataset](http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:jpm2015).

**Comment by akariv** [comment]
Thanks @KrzysztofMadejski , I think I know where this is coming from.

**Comment by KrzysztofMadejski** [comment]
PS. If there is a warning (like "Incomplete type") I think it should be shown above `Continue` button in a big warning-colored box.
