### ISSUE TITLE
OS Viewer: can't drill down for all budgets

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#1069]
Unable to drill down for Bubble Map and Pie Chart. I have tried several test on all datasets that I have uploaded and I still face the same issue.

![os viewer bug](https://cloud.githubusercontent.com/assets/11497391/17390626/663b99dc-5a41-11e6-9c9b-19b42807c873.gif)

**Comment by leowmjw** [comment]
@Hazwany For the Pie drill-down; it is not implemented yet, monitor #1036 for solution that I implemented in VueJS; it just needs to be ported back to the AngularJS binding.

For the BubbleTree drill-down, root cause is the data causes r to be NaN; but was not able to figure out why:
```
app.js?14710347792693017:formatted:60550Error: <circle> attribute r: Expected length, "NaN".C @ app.js?14710347792693017:formatted:60550E.attr @ app.js?14710347792693017:formatted:60917c.draw @ app.js?14710347792693017:formatted:24647e._completed @ app.js?14710347792693017:formatted:24511update @ app.js?14710347792693017:formatted:62244update @ app.js?14710347792693017:formatted:62088loop @ app.js?14710347792693017:formatted:24240
```

The problematic code segment:
```
...
                                            break;
                                        case "r":     <============  r is NaN
                                            "rect" == r.type ? v(u, {
                                                rx: g,
                                                ry: g
                                            }) : u.setAttribute(p, g),
                                            r._.dirty = 1;
                                            break;
...
```

FYI @pwalsh @akariv

**Comment by Hazwany** [comment]
@leowmjw @akariv @pwalsh It seems that I'm able to view the break down when I delete the filter.

![screen shot 2016-09-19 at 1 28 43 pm](https://cloud.githubusercontent.com/assets/11497391/18623263/bf810950-7e6d-11e6-9e52-bce856adfc07.png)

![os-howto](https://cloud.githubusercontent.com/assets/11497391/18623270/c60987ac-7e6d-11e6-9ea0-f83b8133622c.gif)

**Comment by VictoriaVlad** [comment]
@akariv, @kravets-levko, Nany brought this up during today's Labs Hangouts. May I know what is the blocking point here to get this fixed?

**Comment by kravets-levko** [comment]
@VictoriaVlad I already have started to work on it. However, I need some time to figure out this bug - currently I actually don't know what the problem (and where in the code). I will continue working on this issue ASAP
