### ISSUE TITLE
OS Packager: data validation

### ISSUE THREAD

**Issue by KrzysztofMadejski** [openspending/openspending#1072]
It would be beneficial if OS Packager would validate the data in the final step. It is even promised in http://next.openspending.org/packager/provide-metadata step in a message box - "Congratulations! Now you can verify your Data Package and download it."

Specific example that I would expect to raise validation errors: when I choose _Budget Direction_ as a column that contain values other than "expenditure" or "revenue" no error is raised.

IMHO such errors should be raised at "Describe your data" step, or one extra step added after it.

**Comment by pwalsh** [comment]
@akariv is this still relevant

**Comment by akariv** [comment]
Well, data is validated to a certain extent while upload is done.
However, I don't think we'll validate to the point of checking for specific values (e.g. "expenditure" or "revenue") unless we ask the user to explicitly list the allowed values.

I'm closing this for now as not actionable.
