### ISSUE TITLE
Wrong HTTP status returned at endpoint package/publish

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1075]
![500 Error](https://cloud.githubusercontent.com/assets/1629834/17892487/d1678806-6941-11e6-8efa-448410d343d2.png)

`http://next.openspending.org/package/publish?publish=True` instead of `publish=true` returns status 500. It should return status 400.

**Comment by pwalsh** [comment]
@akariv still relevant?

**Comment by akariv** [comment]
No, was fixed a long time ago.
