### ISSUE TITLE
OS content contribution/activities for International Data Week 11th - 17th Sept

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1081]
The International Data Week is coming up, and OKI will be at the conference in Denver (http://www.internationaldataweek.org). 

Through its various channels, OS uses the week to point attention to OpenSpending via various content contributions.

Activities:

1. A series of tweets and Facebook posts linking to datasets on OpenSpending inviting people to explore (on the OS channels)

2. Relevant retweets of the following topics:

#openspending (examples: https://twitter.com/4lowthemoney/status/766642623759147008, https://twitter.com/tijmenschep/status/765876999575465984)

#openbudgets (including ob.eu)

#opengov

#opendata etc

3. Blog post on the experience of CSOs that have been closely involved with OpenSpending during the revamp (currently being drafted) 

4.  organize a Tech Hangout on OpenSpending (Loic and Diana, https://trello.com/c/unU64PFu/29-update-on-openspending. ) 

5. Twitter updates on OpenSpending on Jakarta, Indonesia fiscal workshop (Sept 13-14)

**Comment by danfowler** [comment]
I can help arrange the Labs (Tech) Hangout for OpenSpending!
