### ISSUE TITLE
OpenSpening blogpost: How to work with open fiscal data that hasn't been obtained yet?

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1086]
In this blogpost, we give recommendations what the community can do in order to push the Open Data agenda forward in their own country/region like (Victoria's suggestions):
- Push for an Open Data program in your country
- Collaborate with Rights to information orgs
- Organize round tables with civil servants on the topic of Open Data (to get to know their story)"

Due: First half of October 2016

**Comment by VictoriaVlad** [comment]
In preparing this blog post, I would like to start a thread on the OpenSpending discuss forum to gather ideas from the community: https://discuss.okfn.org/c/openspending.

**Comment by VictoriaVlad** [comment]
started a thread here https://discuss.okfn.org/t/your-experiences-in-obtaining-fiscal-data/3668

**Comment by DianaMPG** [comment]
@VictoriaVlad maybe we reach out to the OK chapters as well to get a greater response rate. And than we could break the topic down and identify the most frequent  cases like no data available = submit a FOI; data available only in PDFs = scrape the data;  data not really consistent etc. 
Also, we could also draw from our own experiences with the GIFT data. 
Let me know what you think.

**Comment by VictoriaVlad** [comment]
@DianaMPG, thank you for the suggestion. I will follow up to be able to finalize this blog post.

**Comment by VictoriaVlad** [comment]
Working to finalize the blog post here: https://docs.google.com/a/okfn.org/document/d/1VYfv2V-30ceXdLHD4ArqtV_bGhZbRCUdu4LmeEmbDuU/edit?usp=sharing

**Comment by VictoriaVlad** [comment]
@DianaMPG blog post was published http://blog.okfn.org/2016/12/07/how-to-unlock-the-value-of-fiscal-data-for-civil-society-experiences-from-the-openspending-community/, thank you for your help!
