### ISSUE TITLE
Signed, offline visualisations

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1088]
# Description
## Overview

We want to create signed, offline visualisations. This is a requirement as part of the [OBEU Project](https://github.com/openbudgets).

There are two related aspects to this task:
- Export a visualisation state for offline use (could be as an html document, or as an image).
- Sign the exported state to verify it is what it says it is.

There are limitations on the extent of “signing” that is possible: it will be possible for someone to present something _as if_ it was the type of thing we can “sign” - be it an html export or an image. 

So, the only way to approach signing is as a best effort approach with relevant caveats.
## Target component

The most relevant component to implement such functionality is in the OS Viewer app. This app allows users to interactively build a set of visualisations from a dataset.

OS Viewer is an ideal target for the following reasons:
- The user can create a static output from anything she can do in the “workspace” of the viewer, which means one or many visualisations
- While mostly a client side app, it has a lightweight node.js server that can be used for preprocessing and creating the export if needed
## Use cases and user stories

Some related user stories can be found here:
- https://trello.com/c/tab35bO2/
- https://trello.com/c/TclY59OZ/
## User workflow
- User interacts with OS Viewer to create a set of visualisations, after having already selected a dataset to interact with
- When user has a visualisation state that is useful, she click a “export/download a verified copy of this visualisation” button
- This starts a process that creates the required outputs, zips them, and prompts for download to the user’s download folder
#### OS Viewer (existing)
- The visualisation state to be exported is generated from the OS Viewer app
- The button to download is added to the Viewer
- Some way to get the state’s data and expose as JSON
#### Screenshot service (new, based on [WebShot](https://github.com/okfn/webshot) or some some newer solution exists)
- Generates PNG of OS Viewer state
#### Sign + Package service (new)
- Gets the data as JSON
- Gets the PNG
- Holds private key
- Creates signature
- Creates zip
- Exposes zip for download
### Outputs
- A single PNG file that reproduces the state of the OS Viewer “workspace”
- A JSON file that represents the data used to create the Viewer “workspace”
- A key pair to sign the data (public key distributed with the PNG and JSON)
- A zip file to contain all of the above. This is the file downloaded by the user
## Timeline and Effort

The feature is expected to be available as a configurable feature of OS Viewer by October 2016

**Comment by pwalsh** [comment]
https://github.com/openspending/babbage.ui/blob/master/src/api/downloader.js

**Comment by larjohn** [comment]
So I started looking around the embedded page of OS Viewer. Specifically, this one to start with: a simple [example ](http://localhost:5000/embed/pivottable/23cdc48554ae8648deff7837c025d8c0:mohe2016_detailed?lang=en&measure=Amount.sum&rows%5B%5D=administrative_classification_2.Level_1&columns%5B%5D=administrative_classification_2.Level_1&order=Amount.sum%7Cdesc)

A first thought was to implement a 'promise' handler that fires when everything is loaded & **rendered**. Then a regular event could be emitted by the handler and caught by PhantomJS. I had very bad luck with the first part, though - I tried the following:
- simply putting code in the last promise of `initEmbedded`
- same as the previous, but with zero `$timeout`
- watching `$scope.isLoading.package`, with/without zero `$timeout`
- creating a directive with minimum `priority `and using the `link `function
- watching `$viewContentLoaded`

The majority of the above methods do work in terms of running the code, but they always come **before** any content is actually rendered on the page. Removing `ng-cloak` didn't help either. I am not such familiar with angular cycles. Has anyone tried something similar with success?

My second thought was to abandon making changes to the OS Viewer at all (at least for the time being, as I haven't visited the requests part, yet). Instead, provided that PhantomJS can inject [arrive.js](https://github.com/uzairfarooq/arrive) to the page at the right moment, plus a script that makes use of it, it would be a lot simpler to handle the rendered visualization. A possible caveat is if any of the visualizations does some fancy stuff (animations?) after rendering, which arrive would not directly be notified of. Is that the case for any of the visualizations?

**Comment by pwalsh** [comment]
@larjohn I'd say, for first pass, just make phantom wait for some period of time to load the page. use that to get all your moving parts working, etc.

Then, we can talk with @akariv and @kravets-levko about a single event to fire at the end of a page render, and use that as a hook for http://phantomjs.org/api/webpage/handler/on-callback.html

**Comment by akariv** [comment]
@larjohn,  I modified `babbage.ui` so that after loading data using the `aggregate` API, it will save the results in a global, `window` bound variable:
`window_babbage_results_aggregate`.

You can wait until this value is defined and use that as the indication that the visualisation is ready.

**Comment by larjohn** [comment]
Good enough!

**Comment by akariv** [comment]
@kravets-levko 
1. Let's implement Sam's design.
2. Adding metadata tags for embed and main views

**Comment by larjohn** [comment]
Is this deployed to next.openspending.org? 

I tried this in http://next.openspending.org/viewer/embed/bubbletree/66c9cdc19a58be697d79fa5032da2c58:sturahd16?lang=en&measure=Plan.sum&groups%5B%5D=budget_line_id_2.account_id&order=Plan.sum%7Cdesc and locally as well, but it returns `undefined`.

I couldn't find this in the babbage.ui code either (https://github.com/openspending/babbage.ui/search?utf8=%E2%9C%93&q=babbage_results_aggregate)

**Comment by akariv** [comment]
Sorry , there was a typo above: 
`window._babbage_results_aggregate` is what you should look for
(as well as `window._babbage_results_facts`)

**Comment by akariv** [comment]
(and here it is in the code: https://github.com/openspending/babbage.ui/search?utf8=%E2%9C%93&q=_babbage_results_&type=Code)

**Comment by larjohn** [comment]
I can successfully access the variables right now, but it seems the browser renders the elements far later than setting this variable. 

I verified this doing the following experiment in Firefox (which supports Object.watch):

1. Load http://next.openspending.org/viewer/embed/bubbletree/66c9cdc19a58be697d79fa5032da2c58:sturahd16?lang=en&measure=Plan.sum&groups%5B%5D=budget_line_id_2.account_id&order=Plan.sum%7Cdesc and open the debugger tools
2. Put a breakpoint in the first line of the minified app.js to stop it immediately after loading next time.
3. Reload the page
4. In the console evaluate the following
`window.watch("_babbage_results_aggregate", function(){alert("variable set")})
`
5. Continue the execution to let the page load (you can now remove the breakpoint)
6. The alert comes a couple of time and a moment later the elements are rendered.

**Comment by akariv** [comment]
Okay, I'll make sure it is set after the page is rendered.
Please don't let this block you right now.

**Comment by larjohn** [comment]
Right now sealer works, with the exception that it stores an almost blank page. I can go on with structuring the report, until this is fixed.

**Comment by pwalsh** [comment]
COMPLETE
