### ISSUE TITLE
OS-client: improve test coverage

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1095]
The fiscal module, which holds the `FiscalDataPackage` class, has been through major refactoring and since then, does not have any tests anymore. Other modules need better coverage as well:
- [ ] user 
- [ ] fiscal
- [ ] search
- [ ] cli

Also:
- [ ] add a Coveralls badge

**Comment by cyberbikepunk** [comment]
I renamed the issue because several modules need improved test coverage. As of now:

```
---------------- coverage: platform linux, python 3.5.1-final-0 ----------------
Name                 Stmts   Miss  Cover
----------------------------------------
gobble/__init__.py       3      0   100%
gobble/api.py           60      8    87%
gobble/cli.py          121    121     0%
gobble/config.py        37      1    97%
gobble/fiscal.py       200    102    49%
gobble/logger.py        37      4    89%
gobble/search.py        31     15    52%
gobble/snapshot.py     114     16    86%
gobble/user.py         111     75    32%
----------------------------------------
TOTAL                  714    342    52%
```

Better coverage required for the following modules:

- [ ] user 
- [ ] fiscal
- [ ] search
- [ ] cli

Also:

- [ ] add a Coveralls badge

**Comment by pwalsh** [comment]
https://github.com/openspending/openspending/issues/1326
