### ISSUE TITLE
Token requires JSON compatible quotes

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1096]
Contrary to the [documentation](https://github.com/openspending/docs/blob/master/docs/developers/conductor.md), the token needs double-quotes for the endpoint `/search/package`. Omitting them will result in a 500 error. I would prefer changing the code than amending the docs, because none of the other API endpoints require quotes.

**Comment by akariv** [comment]
I just doubled-checked this, and the token should be passed without any quotes (you can see an example when in the developer tools network tab when you open OS-Viewer).
![screen shot 2016-09-12 at 9 56 27 pm](https://cloud.githubusercontent.com/assets/265333/18448433/dbce4eb8-7933-11e6-9d0d-3d408b274cf7.png)

**Comment by cyberbikepunk** [comment]
There's something funny going on. This [url without quotes]([Gobble] [ERROR] 500 Server Error: Internal Server Error for url: http://next.openspending.org/search/package?jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6eyJkYXRhcGFja2FnZS11cGxvYWQiOnRydWV9LCJzZXJ2aWNlIjoib3MuZGF0YXN0b3JlIiwidXNlcmlkIjoiNWRmNGE3YjA2YTk0MGM5OTJkMWM0NDUyNWRhZmY0N2IifQ.LI4KhEnkGR4WdCfamY1YhBw9Xkm1yd7Ik_r47pzNt8KX1gQ1_8tDvjzO0KVc9kfttOAFDf3vvAlWDnXzUWDGKWq-Yp8tnPYSsCisgR5mCbJs1VvUiDmmCAv3BHAcA-XREPzzkRf0YNqhZk8TE_mNIXxLNwVVMoKVQkC4svOTM07QrZeqjS8kROx2M2hyCvrvsLdGiJtPk01LFIwmPutZCJjOsF0-Z6u7keu7-h_Hf7juuu6nzaTIu5Jy6B2RoXnyzV2aN90siwYU_Y_Fg5LGbA0DnIRs-JaGJtkpRJWcAAVWRwLSn3ng4ofVua9RMGFfWDSjwUamjPCkMgxz_Pqj_Q&q=%22loic%22
Traceback (most recent call last):
  File "/home/loic/repos/gobble/gobble/search.py", line 80, in <module>
    results = search(global_query='loic', private=True)
  File "/home/loic/repos/gobble/gobble/search.py", line 59, in search
    return handle(response)
  File "/home/loic/repos/gobble/gobble/api.py", line 112, in handle
    raise error
  File "/home/loic/repos/gobble/gobble/api.py", line 109, in handle
    response.raise_for_status()
  File "/home/loic/.virtualenvs/gobble/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://next.openspending.org/search/package?jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6eyJkYXRhcGFja2FnZS11cGxvYWQiOnRydWV9LCJzZXJ2aWNlIjoib3MuZGF0YXN0b3JlIiwidXNlcmlkIjoiNWRmNGE3YjA2YTk0MGM5OTJkMWM0NDUyNWRhZmY0N2IifQ.LI4KhEnkGR4WdCfamY1YhBw9Xkm1yd7Ik_r47pzNt8KX1gQ1_8tDvjzO0KVc9kfttOAFDf3vvAlWDnXzUWDGKWq-Yp8tnPYSsCisgR5mCbJs1VvUiDmmCAv3BHAcA-XREPzzkRf0YNqhZk8TE_mNIXxLNwVVMoKVQkC4svOTM07QrZeqjS8kROx2M2hyCvrvsLdGiJtPk01LFIwmPutZCJjOsF0-Z6u7keu7-h_Hf7juuu6nzaTIu5Jy6B2RoXnyzV2aN90siwYU_Y_Fg5LGbA0DnIRs-JaGJtkpRJWcAAVWRwLSn3ng4ofVua9RMGFfWDSjwUamjPCkMgxz_Pqj_Q&q=%22loic%22
) crashes. This [url with quotes](http://next.openspending.org/search/package?jwt=%22eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwZXJtaXNzaW9ucyI6eyJkYXRhcGFja2FnZS11cGxvYWQiOnRydWV9LCJzZXJ2aWNlIjoib3MuZGF0YXN0b3JlIiwidXNlcmlkIjoiNWRmNGE3YjA2YTk0MGM5OTJkMWM0NDUyNWRhZmY0N2IifQ.LI4KhEnkGR4WdCfamY1YhBw9Xkm1yd7Ik_r47pzNt8KX1gQ1_8tDvjzO0KVc9kfttOAFDf3vvAlWDnXzUWDGKWq-Yp8tnPYSsCisgR5mCbJs1VvUiDmmCAv3BHAcA-XREPzzkRf0YNqhZk8TE_mNIXxLNwVVMoKVQkC4svOTM07QrZeqjS8kROx2M2hyCvrvsLdGiJtPk01LFIwmPutZCJjOsF0-Z6u7keu7-h_Hf7juuu6nzaTIu5Jy6B2RoXnyzV2aN90siwYU_Y_Fg5LGbA0DnIRs-JaGJtkpRJWcAAVWRwLSn3ng4ofVua9RMGFfWDSjwUamjPCkMgxz_Pqj_Q%22&q=%22loic%22) works.

**Comment by akariv** [comment]
Perhaps you're using the wrong token here?
Make sure it's the authentication token and not the permission one.

**Comment by cyberbikepunk** [comment]
This is definitely the authentication one.

**Comment by akariv** [comment]
It seems that neither URL work as the second one doesn't return any of your private datasets.
I tried to decode the token and it's most definitely the permissions one... these are its contents:
```json
{'userid': 'xxx', 'service': 'os.datastore', 'permissions': {'datapackage-upload': True}}
```

**Comment by pwalsh** [comment]
Ahem.

http://stackoverflow.com/questions/32722952/is-it-safe-to-put-a-jwt-into-the-url-as-a-query-parameter-of-a-get-request

Don't share tokens, that are persistent, like those I imagine are used by the CLI, in public, unless we have some other protection here.

**Comment by akariv** [comment]
The tokens expire after a few days, but generally speaking I agree.

**Comment by cyberbikepunk** [comment]
@pwalsh: my bad. 
@akariv: this was a gobble issue. Thanks for helping out. Solved [here](https://github.com/openspending/gobble/pull/27/commits). I'm closing this issue.
