### ISSUE TITLE
OS-client: change name from gobble to os-client

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1097]
Judging from exchanges between @akariv and @pwalsh, it would be better to have a consistent name that reflects what the program does. The other option is `os-cli` but the the program is not just a command line tool, so I would go for `os-client`.
- [ ] Rename the program
- [ ] Retire the old obsolete `os-cli` repo

**Comment by akariv** [comment]
👍 

But only once it is production ready.

**Comment by pwalsh** [comment]
moved to https://github.com/openspending/openspending/issues/1326
