### ISSUE TITLE
OS-client: user module token fetcher bugs

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1103]
There are 2 bug fixes that need to be made to the user module before the 0.2 release:
- [ ] browser link should be a `click.echo()` statement rather than `logging.critical()` since there is no console logging in production mode.
- [ ] `request_new_token()`: the `next` call to `localhost:8001` returns empty query string.

Nice to have:
- [ ] save `authentication.json`, `permissions.json` and `settings.json` in user folder

**Comment by pwalsh** [comment]
Moved to https://github.com/openspending/openspending/issues/1326
