### ISSUE TITLE
OS-Client: add progress bars during upload

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1104]
When uploading large datasets, progress bars during uploads become really important. There are two steps to the process that I need to give the user feedback on:
- [ ] S3 upload
- [ ] datastore upload

@akariv for the datastore upload, this is straight forward, since I just need to poll the `packager/status` endpoint. For the upload to S3, I need to find out how get feedback on the completion of my request. I use the `request-futures` package.

The `click` library has support for progress bars, so this seems like the obvious way to go.

**Comment by cyberbikepunk** [comment]
A couple more things need fixing: #1113 and the `FiscalDataPackage.upload`  method should return the _correct_ URL: the `viewer/` path is missing.

**Comment by pwalsh** [comment]
- [here is an example of using a callback to get progress status](https://gist.github.com/garnaat/2890351)
- [the original upload code for the cli used a callback to report when finished each file](https://github.com/openspending/os-cli/blob/8a0bbeef409bd0c0eebce08a720d2b9644d7c81f/oscli/actions/upload.py#L120)

**Comment by pwalsh** [comment]
moved to https://github.com/openspending/openspending/issues/1326
