### ISSUE TITLE
<Regression>: Filtering failing in DrillDown

### ISSUE THREAD

**Issue by leowmjw** [openspending/openspending#1109]
@pwalsh @akariv Noticed the following regression with the Filtering failing during Drildown

1) Go to the dataset: http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:jpm2016_detailed
2) Select TreeMap Visualization

3) Click on "Jumlah Jabatan Perdana Menteri"
Notice: Nothing is displayed
![screen shot 2016-09-21 at 12 14 05 pm](https://cloud.githubusercontent.com/assets/920784/18697572/fd584a8a-7ff4-11e6-9308-0fcfb9e8053f.png)

4) Remove filter
Notice: Now it displays correctly
![screen shot 2016-09-21 at 12 14 17 pm](https://cloud.githubusercontent.com/assets/920784/18697575/04570ec0-7ff5-11e6-8113-eadf80b37f7f.png)

5) Repeat for the drill down by clicking on "Mengurus"; notice the same behavior and problem

**Comment by pwalsh** [comment]
@kravets-levko can you just confirm this bug, and then when confirmed, we can check with @akariv about prioritizing it.

**Comment by kravets-levko** [comment]
@pwalsh I have seen such behavior for several times. In all cases (and also in this one) babbage api returns empty result (properly formed response with empty `cells` array). That's why I think that we should start from api part.

**Comment by kravets-levko** [comment]
Upd: yes, there is a bug, and I think it is also the cause of #1110
