### ISSUE TITLE
<Regression>: Wrong data in DrillDown

### ISSUE THREAD

**Issue by leowmjw** [openspending/openspending#1110]
@pwalsh @akariv Another serious regression noticed by my colleagues:

Steps to reproduce:
1) Go to http://vue-babbageui-demo.netlify.com/ (which is using my older VueJS port of the OpenSpending components)
2) Select Prime Minister's Department
3) Select detailed budget for 2016 "Bajet Jabatan Perdana Menteri 2016 Secara Terperinci"
4) Drilldown in TreeMap "Jumlah Jabatan Perdana Menteri" --> "Mengurus" 

Correct:
![screen shot 2016-09-21 at 12 05 29 pm](https://cloud.githubusercontent.com/assets/920784/18697483/24c8de28-7ff4-11e6-9dce-a548291c696b.png)

5) Repeat steps above [ watch out for #1109 ] on OpenSpending for the same dataset: http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:jpm2016_detailed

Incorrect (On OpenSpending): 
![screen shot 2016-09-21 at 12 05 06 pm](https://cloud.githubusercontent.com/assets/920784/18697496/3753e0ce-7ff4-11e6-8a82-ddcb9dd17ad9.png)

**Comment by pwalsh** [comment]
Likewise @kravets-levko can you confirm this bug, and then when confirmed, we can check with @akariv about prioritizing it.
