### ISSUE TITLE
Packager: one field belonging to several hierarchies

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1111]
It turns out that in the mexican case, the two hierarchies share one parent:
1. `id_ramo` > `id_ur`
2. `id_ramo` > `id_modlidad` > `id_pp`

Is it possible to implement this? Of course we could duplicate the column but I would consider this a work-around, not a permanent solution.

**Comment by cyberbikepunk** [comment]
Judging from Aura's last email, this doesn't seem to be required anymore.

**Comment by cyberbikepunk** [comment]
Actually judging from the next email I'm not so sure.

**Comment by akariv** [comment]
Judging from the amount of comments you're making here it's evident I'm not
receiving Aura's emails...

**Comment by pwalsh** [comment]
CLOSING. OUT OF DATE.
