### ISSUE TITLE
Packager: implementation of partial IDs

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1112]
In the case of Mexico, the way we've dealt with partial IDs is by concatenating IDs belonging to hierarchies in the underlying data. That's not optimal. It would be better to implement that in the packager on the fly.

**Comment by cyberbikepunk** [comment]
@DianaMPG this is the issue we're talking about on the phone.

**Comment by akariv** [comment]
Just a recap on the problem:

Suppose we have a column tuple of `code` and `title` (e.g. "2nd level functional classification code" and  "2nd level functional classification title").
We currently assume that there is a unique mapping between codes and titles - that is, a specific 2nd level functional classification code will always mean the same thing. 

However, in many cases budget files hold in these columns only parts of the code, and not the full code. To take our example, if the full 2nd level functional classification code is of the form 'XX-YY' (XX being the 1st level and YY for the 2nd level specification), we might find in the column only the 'YY' values, which are not necessarily unique.

We already have in the OS type system two kinds of code types: 'full' and 'partial', where full denotes a complete code (i.e. the 'XX-YY' form) and partial denotes the partial code (i.e. the 'YY' form). 

Currently we don't treat these two types differently, but we should. During the loading process, we need to convert the partial 'YY' values to full 'XX-YY'  ones.

**Comment by akariv** [comment]
os-data/mexican-federal-budget#19

**Comment by DianaMPG** [comment]
@akariv great!
