### ISSUE TITLE
Download a CSV from any visualisation created

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1123]

**Comment by DianaMPG** [comment]
@akariv ?

**Comment by akariv** [comment]
Not yet

**Comment by DianaMPG** [comment]
ok, thanks

**Comment by DianaMPG** [comment]
@akariv does this also touch on the possibility that every year could be downloaded separately ?

**Comment by DianaMPG** [comment]
Hi @akariv 
what is the status of this issue? Are we there yet? Thank you

**Comment by pwalsh** [comment]
@akariv ?

**Comment by vitorbaptista** [comment]
@akariv Could you provide more information here? Is it simply saving the data from the `aggregate` API request [1]? Do we have a modifier to get the data in CSV already, or only JSON?

[1] https://next.openspending.org/api/3/cubes/boost:boost-moldova-2005-2014/aggregate?cut=date_2.year%3A2014&drilldown=administrative_classification_2.admin1%7Cadministrative_classification_3.admin2&order=adjusted.sum:desc,administrative_classification_2.admin1:asc,administrative_classification_3.admin2:asc&pagesize=2000

**Comment by akariv** [comment]
No - only json atm.
And the main problem here is that we don't necessarily know the last API call that a specific visualisation made. If we knew that, we can take the data and convert it to CSV (similar to what we're doing in the Pivot Table).

**Comment by vitorbaptista** [comment]
@akariv So we would have one download button for each visualization? I was thinking of just giving the user the option to download the same data that's in the table at the bottom of the page.

**Comment by akariv** [comment]
That's the requirement. 

Downloading the data in the facts table is much easier but problematic - as there could be many many rows there which would strain the API and the client.
Plus, it wouldn't necessarily return the data  used in the chart (which is often aggregated).

**Comment by vitorbaptista** [comment]
The PRs were submitted and are pending review. As this touches many different codebases, we need to be careful with the merging order.

1. Merge https://github.com/openspending/babbage/pull/26
1.1. Upload a new version to pypi
1.1. Change `os-api` to use this new version
1. Merge https://github.com/openspending/babbage.ui/pull/71
1.1. Upload a new version to npm
1. Merge https://github.com/openspending/os-viewer/pull/169
1.1. Update the `babbage.ui` version

/cc @akariv
