### ISSUE TITLE
"Responsive" Viewer

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1125]
Context from the pilot scope document:

> The Viewer app is too complex to work on mobile phones, but we will define a minimum width on which it should work consistently (for example, for tablets), and take reasonable measures to ensure that behaviour is usable at such widths. 
> < Widths lower than the size we can manage with the various elements in the Viewer will remove some elements from view, and show a message to the user that the full data can be viewed and interacted with on large screens.
> < This should also take into account responsiveness of menus. 

So we need to:
- [ ] define a minimum width on which it should work consistently
- [ ] take reasonable measures to ensure that behaviour is usable at such widths
- [ ] handle widths below the recommended size

**Comment by akariv** [comment]
Assigning to @smth for design and definitions before implementation

**Comment by smth** [comment]
Is it fair to say that the complexity comes from the visualisations? So far [everything else](https://smth.github.io/os-mockup-viewer/viewer/vis/) is proving reasonably flexible. 

If so, I suggest that we disable all visualisation stuff below the 768px breakpoint. So what you'd get on smaller devices is just title, description and a table.

**Comment by smth** [comment]
Example of display below that width
![mobile](https://cloud.githubusercontent.com/assets/1375708/21381821/6157ff92-c755-11e6-8a57-bf66d51e26e9.jpg)

**Comment by akariv** [comment]
Perhaps for this view we can use the static image view for the
visualisations, rendered in higher res so that they could be viewed more
easily in a mobile device (e.g zoomed into etc)

WDYT?

**Comment by smth** [comment]
I wasn't aware there was a static image view, but yeah, that sounds reasonable.

**Comment by akariv** [comment]
It's not a thing exactly, but a service we need to implement anyway for the
social sharing feature

**Comment by pwalsh** [comment]
Latest work from @smth is http://p.smth.uk/os-mockup-viewer/viewer/vis/

Needs implementation.

**Comment by pwalsh** [comment]
@akariv what happened here?

**Comment by akariv** [comment]
We never got to implementing this.
The original purpose was to gracefully degrade the looks of the page for smaller screens (with reduced functionality, as well).
I guess this should take no more than a day's worth of tinkering with the site's CSS.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~2 years) as part of #1478. Label `prioritized` was removed. Please feel free to re-open if this is still relevant.
