### ISSUE TITLE
Allow non-technical users to add multiple data sources (files)

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1128]
Step 1: Allow uploading multiple files
Step 2: Somehow separate the different cards from each resource. Also, even with one resource, working with multiple cards is very hard.
Step 3: Summary of the modelling should take the resources into account (and a revamp of that is generally needed)
Step 4: Might be trivial but let's make sure we don't forget it too

**Comment by DianaMPG** [comment]
estimate of 2 days to finish

**Comment by smth** [comment]
Is the original design for step 1 still valid?

![packager_04_provide_02](https://cloud.githubusercontent.com/assets/1375708/24444224/93803ff2-145d-11e7-8e19-c784e5801478.jpg)

**Comment by akariv** [comment]
@smth yes, it looks quite alright to me.

**Comment by smth** [comment]
I've added those elements to a page [here](https://smth.github.io/os-mockup-packager/packager/provide-data/).

**Comment by pwalsh** [comment]
We've agreed that all current design iterations enable this support, but we are not going to prioritise supporting multiple files in the foreseeable future. Goes to backlog.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. Label `prioritized` was removed. Please feel free to re-open if this is still relevant.
