### ISSUE TITLE
Os-Packager: Edit column description is not intuitive

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1129]
Most users don't know that this button (top-right of each card) is clickable,

**Comment by smth** [comment]
I think it makes sense to group this with the other editable stuff. Like so https://smth.github.io/os-mockup-packager/packager/describe-data/

**Comment by akariv** [comment]
OK. I think it makes sense to implement along with #1130.

**Comment by pwalsh** [comment]
Closed in favour of https://github.com/openspending/openspending/issues/1277
