### ISSUE TITLE
Packager: Allow adding extra dimensions

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1130]
e.g. A 'constant value' dimension, which is not present on resources.

This basically means - add a new card to the list

**Comment by smth** [comment]
I have added a link to trigger this in my [current mockup](https://smth.github.io/os-mockup-packager/packager/describe-data/), but not yet tackled what happens once clicked.

What information needs to be gathered here? Is it the same as the other "cards", i.e `Title`, `Description`, `Data type`?

**Comment by pwalsh** [comment]
@smth the refined UI elements look *beautiful*.

**Comment by akariv** [comment]
@smth 
The new dimensions are similar to the others but with these differences:
- They don't have data (as in the 'data view')
- The name and the title should both be editable (and not just the title)
- They have an extra 'constant value' field
- They need to be able to be removed once added (unlike the others).

One question:
The top-right toggle switch - could you please explain what is its purpose and what would be the interaction when toggling it?

(also I agree with @pwalsh)

**Comment by akariv** [comment]
@kravets-levko I think we can start implementing this new design.

**Comment by smth** [comment]
Ah yes, my thinking for the switch was that you could choose to ignore columns that you have no intention of mapping/filling in; they would then be moved towards the end of the list. Perhaps combined with a visual indication that a column has been mapped/filled in, would allow you to easily see when you are done with this process. I was wondering whether there might be a way to intelligently, automatically disable some columns too. @akariv

**Comment by akariv** [comment]
@smth I see - since the main mapping interaction is done through the 'data type' select box, I think that having another toggle would be a little awkward. Also since you currently don't have to select datatypes for all columns anyway, so switching the toggle wouldn't make any difference from a functional point of view.
Perhaps we should revisit it while working on #1056

**Comment by smth** [comment]
The intention was to be more of a visual aid for the user, rather than necessarily having an impact on the data package (in the above mockup, all columns that contain data are grouped together), but happy to leave and revisit later.

**Comment by smth** [comment]
@akariv getting back on topic:

`name` and `title` seem very similar to me, from a user point of view. Does the user need to maintain a concept in mind for each of these? My assumption would be that once a column is given a `title`, `name` is never (or rarely) mentioned again (on the front-end). If that is the case, could `name` not be derived from title, without involving the user?

**Comment by akariv** [comment]
I think you meant `name` *could* be derived from `title`, without involving the user?
If so then yes, that's a great idea :)

**Comment by smth** [comment]
I have pushed an update to that page, it now includes:
- An added, constant value card
- Some JS to reveal a blank card when you click "Add a dimension"

**Comment by akariv** [comment]
@kravets-levko 
Just add to the resource a new property named `constant` and a value as such:
```
"constant": "Some Project"
```

**Comment by kravets-levko** [comment]
@akariv I was sure that it will be something like *virtual* columns - so user will be able to map it properly. In addition, we need to create fields for constant values in order to solve issues like [this](https://github.com/openspending/openspending/issues/1229). WDYT?

**Comment by akariv** [comment]
Sorry, I wasn't clear at all.

```
fields = [
{
   "name": "my-constant-field",
   "type": "number",
   "constant": "3.0"
}
...
]
```

**Comment by kravets-levko** [comment]
Ah, great! Thanks!

**Comment by akariv** [comment]
I must make a change to `os-types` for this to work, though.

**Comment by pwalsh** [comment]
Now implemented in https://github.com/openspending/openspending/issues/1277
