### ISSUE TITLE
Upgrade the mexican dataset 2008-2016

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1137]
Choose between the samples.

**Comment by VictoriaVlad** [comment]
@cyberbikepunk what are the names of the datasets to choose from? @DianaMPG, should I reach out to Mexico team?

**Comment by cyberbikepunk** [comment]
[Presupuesto México 2008-2016 100,000 row sample](http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-19)

[Presupuesto México 2008-2016 100,000 sample with prefixed adminstrative IDs](http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-20)

**Comment by akariv** [comment]
@VictoriaVlad @DianaMPG any update on this?
It's been more than a month since we sent the samples to the Mexican team to choose from.

**Comment by DianaMPG** [comment]
@akariv We sent two reminders but no response so far, will follow-up on it.

**Comment by Victordeleon** [comment]
@akariv sorry, just until know I'm seeing these comments.

I gave a quick look and I'm not sure If I'm perceiving the difference between the two options.

Today I sent all the OS team a mail about information actualization. We already uploaded to the URL we gave you the 2016 third trimester data base. So we were wondering how and when can we see it reflected in the Viewer.

**Comment by akariv** [comment]
@Victordeleon , all the details are in this issue:

https://github.com/os-data/mexican-federal-budget/issues/19

**Comment by Victordeleon** [comment]
Hey @akariv I'm seeing that you implemented a change in the filters functionality. Now, the administrative hierarchy filter appear when you select an upper hierarchy value. However, I'm seeing that the upper hierarchy value doesn't filter the available options in the lower hierarchy, so we wanted to ask, can we expect this functionality? I mean, that the lower hierarchy values available to filter depend on the upper hierarchy selected.

**Comment by akariv** [comment]
That's still being worked on - when it's done we will deploy it to the server.
You can follow the progress here: https://github.com/openspending/openspending/issues/1114

**Comment by Victordeleon** [comment]
Thanks @akariv so that would be something we could expect? Because that functionality could define how the administrative classification will be defined.

**Comment by akariv** [comment]
Yes, it should be ready in a few days.
