### ISSUE TITLE
Pipelines + Bootstrapping

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1145]

**Comment by cyberbikepunk** [comment]
@akariv I'm copying your feedback on the current code here:

> 
here are some comments & high-level plan for integrating bootstrap in pipeline framework
6:11 - Pipeline Templates:
   - method for transforming source description to pipeline
   - schema for validating source descriptions
   - collecting source descriptions along with pipeline specs, converting them on the fly
   - source descriptions are equivalent to pipeline specs - there's no need to explicitly write the specs to disk
   - Generally speaking - don't create boilerplate files on disk. For example, there's no need for the tool to create a 'scraper.py' template on disk.
- Extension modules
   - Domain specific code (e.g. fiscal data packages) should be moved to their own packages.
   - Templates can be defined in these extension modules
   - You can inherit templates so for example fiscal template -> eu-structural-fund template
   - You will be able to seamlessly use processors from extensions if they were installed (no need for PYTHONPATH mucking around etc.)
- read_description needs to change: we should get the information from the pipeline parameters and not disk
- Metrics and stats
   - Local DB for metrics is not really needed I think.
   - Stats should be consolidated to include pipeline execution success.
   - Getting the data should be either through the web UI or an API that will be added for that (most likely both).
- Some of the functionality should be delegated to processors. For example:
   - _get_extractor shouldn't worry about file extensions, but rather Tabulator.
   - Same for 'url' vs 'path' properties in the resource ambiguities check.
6:11 Let’s talk when you’re back to your regular self...

**Comment by cyberbikepunk** [comment]
A note on multiple resources. The current bootstrap process is a workaround. Wouldn't it be logical if the framework supported multiple resources?

```
processors: 
- resource-name: foo
  run: bar
  parameters: {}
  validate: eggs
```

**Comment by akariv** [comment]
@cyberbikepunk there's no limit in the framework for working with multiple resources.

In fact, the Mexican pipeline does exactly that - it downloads multiple files and combines them. The limit on one resource is currently in OpenSpending.
