### ISSUE TITLE
Error with long data package names

### ISSUE THREAD

**Issue by amercader** [openspending/openspending#1147]
Looks like further down the line there is a limit in the data package name, but that wasn't enforced in the Packager

![oserror](https://cloud.githubusercontent.com/assets/200230/19764175/91bfe376-9c39-11e6-81f2-94648d3f3608.png)

**Comment by amercader** [comment]
Fixed? Invalid? Duplicate? :)

**Comment by akariv** [comment]
Fixed of course!
