### ISSUE TITLE
Multiple gmail account log in via Google Chrome doesn't work on OpenSpending Next

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#1149]
Initially, in Google Chrome, I have 4 accounts logged in. It turns out that when I try to log in to OS Next to submit new dataset with selected gmail account, the log in fail.

Solution 1: I delete my history and cache
Result: doesn't work

Solution 2: remove all log in gmail accounts and remain one gmail account only
Result: able to log in

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~2 years) as part of #1478. Label `prioritized` was removed. Please feel free to re-open if this is still relevant.
