### ISSUE TITLE
Minimum requirements subsidy dataset

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1150]
@akariv @pwalsh @DianaMPG @annafralberts 

We have collectively decided to try and have a minimum dataset on the subsidy-stories website by November 23rd. This issue is an umbrella for more specific issues under the [minimum dataset milestone](https://github.com/os-data/eu-structural-funds/milestone/3) of the `eu-structural-funds` repo.

Essentially this means performing parsing, cleaning and transforming on a [subset of columns](https://github.com/os-data/eu-structural-funds/issues/282) that we have judged to be the heart of the dataset.

**Comment by DianaMPG** [comment]
@cyberbikepunk please elaborate as to the minimum dataset. you referring to the actual numbers of datasets (minimum dataset milestone is 75)?

**Comment by cyberbikepunk** [comment]
@DianaMPG This issue is about transforming all the available datasets, but concentrating on a minimum subset of columns. You can click on the link above to see which columns.
