### ISSUE TITLE
OS Packager: comma separator

### ISSUE THREAD

**Issue by lucasansei** [openspending/openspending#1157]
Hello!

I've tried to upload some sample data but got the following error:

> Duplicate Header:  The header column "," is duplicated.

As showed in the following screenshot:

![data-upload](https://cloud.githubusercontent.com/assets/20050053/20492627/994761b0-affc-11e6-869c-7e56aac1c469.png)

However, apparently, there is no comma after the column.
![dataset](https://cloud.githubusercontent.com/assets/20050053/20492669/c5c9905a-affc-11e6-853a-c3be50eaad22.png)

**Comment by akariv** [comment]
@roll any idea why this should happen? This is a GoodTables validation error.

**Comment by roll** [comment]
@akariv 
Could we have file source?
Also what's version of goodtables do you use?

**Comment by akariv** [comment]
@roll we use the online api, we don't host our own goodtables service.

As for the source file, that's a question for @lucasansei .

**Comment by roll** [comment]
@lucasansei 
could please share the source file

cc @georgiana-b (may something familiar to you with this error?)

**Comment by lucasansei** [comment]
@roll 
Hi, yes. Here is the file: https://drive.google.com/file/d/0B0ReFEqiRyglV2J6SkR5ZWpUOVE/view?usp=sharing

**Comment by roll** [comment]
@lucasansei 
thanks

**Comment by roll** [comment]
@lucasansei 
I suppose problem in spaces before/after commas in headers. Our current software have a bug processing it.

**Comment by akariv** [comment]
@lucasansei if you need assistance with removing these spaces (until we resolve this bug) just let me know.

**Comment by akariv** [comment]
Moving to backlog until new goodtables.io is deployed.
Then we'll validate that this had indeed been resolved.

**Comment by roll** [comment]
With https://github.com/openspending/openspending/issues/1157 this file works fine.
