### ISSUE TITLE
Login with Gmail

### ISSUE THREAD

**Issue by lucasansei** [openspending/openspending#1158]
While in a sample uploading call with OpenSpending International. I've encountered an issue where I had to try to login with Google 2 times and only after the second time it worked.

**Comment by akariv** [comment]
Thanks for the report - I will look into it.

**Comment by akariv** [comment]
@lucasansei - do you remember from where you tried to log in (i.e. packager, viewer, explorer etc.)?

**Comment by pwalsh** [comment]
CLOSING. FIXED.
