### ISSUE TITLE
GIFT phase II Uruguay: Data wrangling and pipelining

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1159]
Data wrangling (data cleaning, data scraping etc) & creating automated pipeline to be used for data updates (frequency to be determined)

Dataset is here:
https://drive.google.com/drive/folders/0B4mVvh--ffocYnJ3TUZBSVhwNjg

**Comment by akariv** [comment]
http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:boost-uruguay?lang=es

**Comment by VictoriaVlad** [comment]
@akariv thank you! 
Can't access the link, does it need to be published from OS Admin first?
@DianaMPG, should I plan to send to Uruguay?
