### ISSUE TITLE
GIFT phase II Croatia: Data wrangling and pipeline building

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1162]
Data wrangling (data cleaning, data scraping etc) and creating an automated pipeline to be used for data updates. 

Team Croatia won't be available before the 15th of December. 

Dataset is here:
https://drive.google.com/drive/folders/0BwJv1Xw7OyyBcGNPYm5VZWR2SlU

**Comment by VictoriaVlad** [comment]
@akariv @DianaMPG data as described by colleagues in Croatia:

"In Columns A-D there are first two levels of Organizational classification.
In columns E-J there are three levels of Program classification.
Columns K, L are third level of Functional classification.
Columns M,N are a second level Sources of financing.
Columns O-T there are three levels of Economic classification.
Column U-W are 3-year budget amount.
It's possible to attach additional columns like previous years and such."

**Comment by DianaMPG** [comment]
current situation: Croatia seems to have send a dataset they pulled out directly of a database, but not the publicly available open dataset  Adam is in contact with them to clarify.

**Comment by DianaMPG** [comment]
Update: 
The first PDF file Croatia sent was the official was the official State Budget document which they had been adopted by the Parliament. Victoria and I had requested a CSV/XLS file which they then had pulled out of their SAP databases, according to Adam's assessment. To this point, the PDF is the only publicly available source. 
https://mail.google.com/mail/u/0/#search/boris/15916df7b0555e04

**Comment by DianaMPG** [comment]
@akariv any updates?

**Comment by DianaMPG** [comment]
Dataset uploaded, awaiting feedback
