### ISSUE TITLE
GIFT phase II Guatemala: data wrangling and pipeline building

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1165]
Data wrangling (data cleaning, data scraping etc) and creating an autoamted pipeline to be used for data updates. 

Dataset:
https://drive.google.com/drive/folders/0B4mVvh--ffocWmZoa2JGRzI0bVU

**Comment by akariv** [comment]
http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:boost-guatemala-central

**Comment by DianaMPG** [comment]
@akariv thanks!
@VictoriaVlad please reach out to the Guatemala team, with Tania in cc for translation.
