### ISSUE TITLE
Embedded view shows non-translated strings

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1174]
See issue:
https://github.com/os-data/mexican-federal-budget/issues/59

**Comment by kravets-levko** [comment]
@akariv Cannot reproduce. I've found a (mexican) dataset, and tried it in different languages (links are from OS Viewer Share modal):
http://next.openspending.org/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-20?lang=es&measure=Adefas.sum&groups%5B%5D=functional_classification_2.Grupo_Funcional&filters%5Bdate_2.Ciclo%5D%5B%5D=2016&order=Adefas.sum%7Cdesc

http://next.openspending.org/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:presupuesto-mexico-20?lang=en&measure=Adefas.sum&groups%5B%5D=functional_classification_2.Grupo_Funcional&filters%5Bdate_2.Ciclo%5D%5B%5D=2016&order=Adefas.sum%7Cdesc

To continue working on this bug I need a link for broken embed.

**Comment by kravets-levko** [comment]
This url also is displayed in correct language:
http://next.openspending.org/viewer/embed/treemap/6018ab87076187018fc29c94a68a3cd2:presupuesto-mexico-2008-2016?lang=es&measure=MONTO_ADEFAS.sum&groups%5B%5D=budget_line_id_2.ID_CLAVE_CARTERA&filters%5Bdate_2.CICLO%5D%5B%5D=2016&order=MONTO_ADEFAS.sum%7Cdesc
