### ISSUE TITLE
Viewer Table sorting not reset when changing X-Axis

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1179]
Steps for reproduction:
- Open a table visualisation
- Choose an X-Axis from the left side menu
- Order by the dimension (not the measure)
- Choose another X-Axis
- Ordering is still the previous dimension

Related to https://github.com/os-data/mexican-federal-budget/issues/45

**Comment by kravets-levko** [comment]
@akariv I tried to reproduce it, but seems that everything works. Can you drop me a link to dataset where this bug occurs?

**Comment by akariv** [comment]
Okay, so you should start with this URL:
http://staging.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:presupuesto-mexico-2008-2016?lang=es

And follow the reproduction in this beautiful animated GIF
![20161206-190118_capture](https://cloud.githubusercontent.com/assets/265333/20935307/d943450e-bbe6-11e6-8252-d3363ed61d5a.gif)

Notice what happens when I click 'ID_FUNCION' - no sorting is active (and in fact sorting is active and set to an invalid value).

**Comment by akariv** [comment]
Tested now in staging, still happening :(

**Comment by akariv** [comment]
Also, now it seems that tables is not sorting by IDs any more (see for example here: http://staging.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:boost-uruguay?lang=es&measure=value.sum&groups%5B%5D=phase_2.PHASE_ID&order=phase_2.PHASE%7Cdesc&visualizations%5B%5D=Table - should be ordering by PHASE_ID and not PHASE)

**Comment by kravets-levko** [comment]
Seems that this dataset it not published.

**Comment by kravets-levko** [comment]
Figured it out, just made a stupid mistake; will fix in few minutes.
