### ISSUE TITLE
UX bug with tabular data reports

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1180]
# Description

When uploading a file to OpenSpending, one receives an error report, if the file has structural or schema errors. This report is designed to help users fix bad files before proceeding further with the modelling process for OpenSpending.

However, the report UI in OpenSpending seems to mark all empty columns as "red", indicating that an empty cell is the source of an error, even when this is not the case.

For example, see the below screenshots, which are reports for the same file, one in OS and one in GoodTables. The same error is identified (of course, it is the same reporting service), but the OS version of the report marks the empty cells in red even though this is not the error that good tables has identified.

<img width="1280" alt="screenshot 2016-12-08 08 18 38" src="https://cloud.githubusercontent.com/assets/791678/20999731/65e993ee-bd1f-11e6-899e-162e17628a21.png">

<img width="1280" alt="screenshot 2016-12-08 08 18 46" src="https://cloud.githubusercontent.com/assets/791678/20999733/661fc720-bd1f-11e6-8fd7-9d11d3c17c96.png">

**Comment by akariv** [comment]
@pwalsh is there a plan to move the template to be a part of the GT service in the current rewrite?

**Comment by pwalsh** [comment]
@akariv yes. I'll reference this there and we can wait for it.
