### ISSUE TITLE
Wrap up the save flow

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1182]
In the packager - 
- Only upload the files
- Cancel the polling of the status, the 'Explore and Visualise' and 'Manage your Datasets' buttons
- When upload is complete, redirect to the admin to continue following the upload progress
- Use the query param to highlight the currently uploading package.

**Comment by akariv** [comment]
Also:
- Make sure highlighted package is first on the list of packages

**Comment by akariv** [comment]
And don't write '0 B' if the size is unknown (we can just omit that)

**Comment by pwalsh** [comment]
@akariv still relevant?

**Comment by akariv** [comment]
@pwalsh yes, still relevant.

**Comment by rufuspollock** [comment]
@sglavoie i think you can close this one as well as per your other ones (as very old now).

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity as part of #1478. Please feel free to re-open if this is still relevant.
