### ISSUE TITLE
Viewer: Save as default view

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1187]
Allow the owner of a dataset to save a 'default view' of the dataset which will be used when the dataset is opened in the future.

This includes visualisations, filter selection, drilldown state etc.

(The motivation here is that for some datasets, opening the viewer without some filters set in place makes the data simply meaningless)

**Comment by kravets-levko** [comment]
Should that 'default view' be applied for anyone who'll try to view dataset? Probably we'll need an API for saving that data (I think that data should belong to a dataset itself, not to user).

**Comment by akariv** [comment]
Yes, anyone who opens the dataset without specifying anything in the URL.
Default parameters (if exist) should override other default behaviours (e.g. select last year etc.)

We'll add an API for that, sure - and I agree this data is dataset bound and not user bound.

**Comment by pwalsh** [comment]
@vitorbaptista this is till assigned to you. Can you provide a mini spec for the work, and then reassign to @brew

**Comment by vitorbaptista** [comment]
@brook I think the expected behavior of this task is defined in enough details from @akariv and @kravets-levko's conversation above. The exact implementation, including how/when the user will be able to save, is up to you. Let me know if you have any questions.

**Comment by brew** [comment]
Notes:

- add two directives to os-viewer:
  - `default-params`: allows package owner to set current view as default params
  - `param-controls`: allows any user to clear the params in the view (removes visualisations and other view parameters, and reset the view params to the owner-defined defaults.

- `default-params` directive will call `services/data-package-api.setDefaultParams` passing the current params 
- => `setDefaultParams` will call `/package/update_params` endpoint on os-conductor with the user jwt token and params as payload 
- => os-conductor's `/package/update_params` endpoint will check user in jwt is owner of package, and use os-package-registry to update the package model with a new `defaultParams` property. It will also use os-api-cache to clear the redis key value corresponding with the package id.

**Comment by brew** [comment]
Feature now live in production.

<img width="1274" alt="screen shot 2018-04-12 at 10 54 09" src="https://user-images.githubusercontent.com/3993/38737907-a562ca68-3f28-11e8-90e5-acf5712d4347.png">
