### ISSUE TITLE
OS Packager: Step 3, datapackage.json - Failed

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#1188]
I had an upload session with OK Chapter Japan. We got an error at step 3, not being able to finalize data publishing.

![error japan data](https://cloud.githubusercontent.com/assets/17012538/21449494/a37a640c-c8a2-11e6-94ba-28b91e704f02.jpeg)

This is how we mapped the data
![mapping japan data](https://cloud.githubusercontent.com/assets/17012538/21449539/18dec5bc-c8a3-11e6-890a-8c21baa29307.jpeg)

This is the [datafile.](https://drive.google.com/open?id=0B4mVvh--ffocU1NfaFIzZDJZU00)

**Comment by akariv** [comment]
Will be fixed through #1193
