### ISSUE TITLE
Resend Discuss invites OpenSpending

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#1189]
@DanFowler, I would like to resend the email to discuss to those who haven't redeemed their invites to Discuss - however I don't see the "invite in bulk" option. Could you please check in admin if this option was removed for me?

If we don't resend the invites by the end of the year, maybe Diana could do so in early January.

**Comment by akariv** [comment]
@DianaMPG can we close this?

**Comment by DianaMPG** [comment]
@akariv not yet, we are still waiting for @danfowler feedback, I suppose

**Comment by danfowler** [comment]
@DianaMPG Let's re-send the invites from your account and send the openspending mailing list to the devops team to be archived and t-t-t-terminated.

**Comment by pwalsh** [comment]
@DianaMPG what was the status of this?

**Comment by pwalsh** [comment]
Closing.
