### ISSUE TITLE
Integrate with URL shortener to get short sharable links

### ISSUE THREAD

**Issue by eriu** [openspending/openspending#1190]
Hi,

if i try to share a visualization on openspending e.g.
> http://next.openspending.org:80/viewer/embed/treemap/d89d5b85bfd01170cfc4c2d6569bc293:lsa-2015-ausgaben1?lang=en&measure=amount.sum&groups[]=administrative_classification_2.titelgruppe_nummer&order=amount.sum|desc

this link is very long. 
maybe you can build in a feature for short this links for sharing e.g. on twitter (140 characters limit)

thanks

**Comment by akariv** [comment]
We could add an integration with a URL shortener.
@kravets-levko , what do you think

**Comment by kravets-levko** [comment]
@akariv Yes, it's definitely a good idea.

**Comment by pwalsh** [comment]
ha! was done!
