### ISSUE TITLE
Allow user to change username once set

### ISSUE THREAD

**Issue by eriu** [openspending/openspending#1191]
there is no possibility to change the username after insert a username for the first time. If you make a mistake there no way to change the name.

**Comment by akariv** [comment]
We've currently disallowed renaming user names to avoid some security implications.
(also, there's a warning message that tells you that...)

We'll consider removing this restriction, but it's low priority for now

**Comment by sglavoie** [comment]
**FIXED**: Closing old issue without recent activity (>3 years) as part of #1478.
