### ISSUE TITLE
Allow overriding encoding detection manually

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1193]
related to #1188.

Before uploading, show next to each resource the auto-detected encoding and provide some means to change that (through a dropdown selection of possible encodings)

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) nor assignee as part of #1478. Label `prioritized` was removed a long time ago. Please feel free to re-open if this is still relevant.
