### ISSUE TITLE
OS Next Browser and API not running

### ISSUE THREAD

**Issue by tmerten** [openspending/openspending#1194]
Hey there,

I noticed that the [OS explorer](http://next.openspending.org/explorer/) does not seem to load (see attached screenshot). The API answers only very basic requests at the moment, too. E.g. info about an dataset is returned but no cuts or drilldowns.

![screen](https://cloud.githubusercontent.com/assets/3410703/21681708/b16dd6e4-d350-11e6-9fdc-b48b1d37b811.png)

Maybe someone can investigate on this.

Thank you,
Thorsten

**Comment by DianaMPG** [comment]
@tmerten thanks, we will look into it

**Comment by d2s** [comment]
Also noticed the same. Got these errors visible in the Chrome Developer Tools Console:
![screenshot from 2017-01-05 17-47-18 openspending explorer errors](https://cloud.githubusercontent.com/assets/135053/21686720/09fd75e4-d36f-11e6-98af-e18b3d0729e3.png)

**Comment by akariv** [comment]
@d2s @tmerten fixed... sorry for the downtime.

**Comment by tmerten** [comment]
@akariv thanks! Much better already :).
Unfortunately I found another problem:

http://next.openspending.org/api/3/cubes/

does not return the [promised list of datasets](http://docs.openspending.org/en/latest/developers/api/#interface) but a 404 instead.

**Comment by akariv** [comment]
Yes, that endpoint was deprecated in favour of the 
more powerful http://next.openspending.org/search/package endpoint.

(I should update the docs I guess 😊 )
