### ISSUE TITLE
No info shown when trying to edit package

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1195]
See this link for example:

http://next.openspending.org/packager/describe-data?package=https:%2F%2Fs3.amazonaws.com%2Fdatastore.openspending.org%2F6018ab87076187018fc29c94a68a3cd2%2Feu-esif-funds-beneficiaries-200-2020%2Fdatapackage.json

**Comment by pwalsh** [comment]
@akariv still relevant?

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
