### ISSUE TITLE
OS Viewer: Tree map enhancement based on WP 3 D 3.5.

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1196]
D 3.5 of WP3 OBEU had as its aim to give recommendations on how the different visualization types could be enhanced so that they meet best best practice requirements in data visualization. J++ was in charge of this report that is publicly available: 
http://openbudgets.eu/assets/deliverables/D3.5.pdf

The following recommendations can be found in the report: 

**Tree map:** 

1. Use of colors
Colors of the boxes can be used to measure a performance or a change, such as growth over time. If it’s not the case, color ranges should fit the data in for instance using different shades of one color.

2. Display of the labels
Labels are difficult to display in small spaces. For readability purposes, the visualisations framework should not display labels that are too long. Instead, these long labels should be displayed on tap or hover on a box of the visualization.

3. Presentation of node details
When the reader selects a node in a tree map, she should see the available details either in a tooltip window or in the sidebar. If the detail is substantial in size, it is best to push it into a sidebar. Simpler data can show up in a box like tooltip.

**Comment by vitorbaptista** [comment]
1. Use of colors
I agree. I think the treemap should have a single colour, as it doesn't add any information. I did this on a dataviz project a few years ago, see http://orcamento.inesc.org.br/2015.

2. Display of the labels
We don't display labels that don't fit the rectangles already. I'll add tooltips to allow the users to check the values of the smaller rectangles.

3. Presentation of node details
Same as (2)

**Comment by DianaMPG** [comment]
@vitorbaptista is this ready for testing? also for the gov partners who suggested the enhancements?

**Comment by vitorbaptista** [comment]
@DianaMPG This just needs to be deployed (cc @akariv)
