### ISSUE TITLE
OS Viewer: Pie Chart enhancement based on WP 3 D 3.5.

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1197]
D 3.5 of WP3 OBEU had as its aim to give recommendations on how the different visualization types could be enhanced so that they meet best best practice requirements in data visualization. J++ was in charge of this report that is publicly available:
http://openbudgets.eu/assets/deliverables/D3.5.pdf

The following recommendations can be found in the report:

**Pie Chart**

1. Limitation of 5 categories per chart
A chart with too many values is difficult to read and understand. It decreases the understanding and impact of the visualization.

In order to avoid these traps, **we can either display a warning message to the final user if she has more than 5 categories to display or group smaller values into an “other” or “miscellaneous” category.**

2. Limit the range of colors used 
Following aesthetic minimalism guidelines can convey the message more efficiently.
Edward Tufte suggests **to remove all elements that are not related to data and actively interfere with the reading and understanding of a visualisation**  (Tufte, 1983).

3. Extension: The donut chart visualisation
Donut charts are interesting as they allow the reader to directly see the absolute values of each slice and of the total.

**Comment by vitorbaptista** [comment]
Currently, when you click on a pie chart's slice, it drills down into that category, similar to clicking on a treemap rectangle. For example, go to https://next.openspending.org/viewer/boost:boost-moldova-2005-2014?measure=%22adjusted.sum%22&groups%5B%5D=%22administrative_classification_2.admin1%22&filters%5Bdate_2.year%5D%5B%5D=2014&order=%22adjusted.sum%7Cdesc%22&visualizations%5B%5D=%22PieChart%22&lang=en and click on any of the slices. You'll notice that the chart changes.

What should be the behaviour of clicking on a "Other" slice? We can't do the same as with other categories, as we don't know which category you want to drill down into. I see two possibilities:

* Don't allow clicking on the "Other" category
* Disable the pie chart's drilling down feature entirely

@DianaMPG @akariv What do you think?

**Comment by DianaMPG** [comment]
@vitorbaptista I never noticed that there is a different behaviour between clicking the pie chart's slices directly and clicking on the categories underneath the pie chart. I usually click the slices directly and not the categories. 

And I must admit -  making sense of "Other/local/central" is quite confusing to figure out, as in relation to clicking slices directly.

But getting rid of the drilling down feature would maybe be counterproductive, what do you think @akariv
