### ISSUE TITLE
OS Viewer: Bar chart enhancement based on WP 3 D 3.5.

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1200]
D 3.5 of WP3 OBEU had as its aim to give recommendations on how the different visualization types could be enhanced so that they meet best best practice requirements in data visualization. J++ was in charge of this report that is publicly available:
http://openbudgets.eu/assets/deliverables/D3.5.pdf

The following recommendations can be found in the report:

**Bar Chart**

1. Labelling the axes
Labelling the axes helps the final user to understand the data at glance. In the visualisations framework, the y-axis should display the currency.

2. Avoid the legend when only one data category is used
When only one data category is used (in the screenshot above, the amount of money) the legend is unnecessary. The title can already contain all needed information or the x-axis can be labelled directly.

3. The use of colors
The color of the bars should be the same for the bars of the same category. Color consistency is important and increases the legibility for readers.

**Comment by pwalsh** [comment]
@vitorbaptista what is the status.

**Comment by brew** [comment]
@brew to follow up with @vitorbaptista.

**Comment by vitorbaptista** [comment]
Everything from the [first message](#issue-199868889) is done. The remaining issue is that different categories have the same colour (they should have different colours). For example:

![bar chart with all categories with same colour](https://user-images.githubusercontent.com/76945/34678150-2853d848-f48a-11e7-9746-8b8cc084d4c0.png)

https://openspending.org/viewer/boost:boost-moldova-2005-2014?measure=%22adjusted.sum%22&groups%5B%5D=%22administrative_classification_2.admin1%22&series%5B%5D=%22expenditure_type_2.exp_type%22&order=%22adjusted.sum%7Cdesc%22&visualizations%5B%5D=%22BarChart%22&lang=en

Apart from that, I don't think there's anything left here.

**Comment by brew** [comment]
This coloured category issue should not be fixed:

https://openspending.org/viewer/boost:boost-moldova-2005-2014?measure=%22adjusted.sum%22&groups%5B%5D=%22administrative_classification_2.admin1%22&series%5B%5D=%22expenditure_type_2.exp_type%22&order=%22adjusted.sum%7Cdesc%22&visualizations%5B%5D=%22BarChart%22&lang=en

<img width="639" alt="screen shot 2018-01-31 at 15 56 12" src="https://user-images.githubusercontent.com/3993/35633029-2d18c71c-06a0-11e8-9a78-cc1d6122949c.png">

Is this issue now closed?

**Comment by vitorbaptista** [comment]
Fixed
