### ISSUE TITLE
OS Viewer: Pivot table doesn't open

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1201]
In OS Viewer, trying to open a Pivot table doesn't work. 

Try for example:
http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:boost-uruguay?lang=en&measure=value.sum&rows%5B%5D=activity_PROGRAM1.PROGRAM1&columns%5B%5D=date_2.YEAR&filters%5Bdate_2.YEAR%5D%5B%5D=2016&order=value.sum%7Cdesc&visualizations%5B%5D=PivotTable

**Comment by akariv** [comment]
The problematic URL is:
http://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:boost-uruguay?lang=en&measure=value.sum&rows%5B%5D=activity_PROGRAM1.PROGRAM1&columns%5B%5D=date_2.YEAR&filters%5Bdate_2.YEAR%5D%5B%5D=2016&order=value.sum%7Cdesc&visualizations%5B%5D=PivotTable

We see Pivot table loading in progress but nothing happens. 
In the console we see an error, I looks like it's related to the 'too much data' message.

**Comment by kravets-levko** [comment]
@akariv It should be fixed in the latest version of Babbage.UI. Can you try just to re-deploy OS Viewer with latest version of dependencies?
