### ISSUE TITLE
OS Viewer: embed first impression of dataset in OS Viewer in context

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1206]
Feedback from team Uruguay (GIFT pilot)

When opening a dataset in OS Viewer, the first impression can be intimidating and not really meaningful, especially to those user who are not acquainted with working with budget and spending data. 

In order to make it more approachable, here are two suggestions:

1. Default visualization type when opening dataset in OS Viewer
2. Add a title to put the seen into context (something along the lines): This is the complete data set

**Comment by akariv** [comment]
Point (1) is covered in #1187
(2) is the dataset description which is fully controllable by the user, so they can choose the proper text and add it there.
