### ISSUE TITLE
Filter x visualisation

### ISSUE THREAD

**Issue by sedmih** [openspending/openspending#1207]
My comments are based on playing with Draft budget Praha 10 – 2017. 
At the moment you can do visualizations through narrower and narrower filtering – e.g. you go from the top level down. In some cases it would be useful to skip some of the levels of the classification. E.g. show the most detailed level of functional classification in case of all the investments (= top level of economic classification).

**Comment by akariv** [comment]
Hey @sedmih - not sure I follow.
Can you explain a little more about your use case?

**Comment by sedmih** [comment]
Still using the Praha 10 case: I have one level of administrative classification, four levels of economic classification and five levels of functional classification. 
Here (http://next.openspending.org/viewer/7327ef5d946f328defdaaba6ebb74c41:praha10_2017_draft?lang=en&measure=budget.sum&groups%5B%5D=functional_classification_o1.o1&filters%5Beconomic_classification_d1.d1%5D%5B%5D=5&filters%5Beconomic_classification_d2.d2%5D%5B%5D=51&filters%5Beconomic_classification_d3.d3%5D%5B%5D=516&filters%5Beconomic_classification_polo.polo_ka%5D%5B%5D=5169&order=budget.sum%7Cdesc&visualizations%5B%5D=Treemap) is visualization of one item in the 4th level of economic classification polozka: 5169 - Nákup ostatních sluzeb and the 1st level of functional classification. But I would like to show more detail e.g. 2nd level functional classification, but for all expenditure, not only one of the function.
Thus the total amount would not be divided into 4 categories but let say 20. I.e. I would select all functions at the 1st level, and than all functions at the 2nd level would be shown.
I hope it is clearer.

**Comment by akariv** [comment]
I see - I think that this level of flexibility is not something that's possible in the OS-Viewer user interface (for reasons of simplicity and user friendliness).
However, you can probably get to the state you want by carefully crafting the URL in the Embedded visualisation mode (i.e. setting the correct dimension for the grouping and removing un-needed filters).

**Comment by sedmih** [comment]
OK, thanks.
