### ISSUE TITLE
GIFT Croatia: equalize grand total to the one published in official budget document

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1208]
@akariv This change request is referring to the email sent by team Croatia in which an example is attached as xls

Email was sent to you on 30/01/

relates to #1163

**Comment by akariv** [comment]
@DianaMPG did we decide not to act on this?

**Comment by DianaMPG** [comment]
@akariv I'm still waiting for Boris' feedback because this would involve to upload a new datasets, from what I understand.
