### ISSUE TITLE
GIFT Croatia: Conversion rates

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1209]
Conversion rate is pulled from the European Central Bank (we use the one from January 1st on the fiscal year). We don't plan on using user provided conversion rates.

relates to #1163

**Comment by DianaMPG** [comment]
@akariv this is useful for European countries but for countries in Latin America?

**Comment by akariv** [comment]
For Latin America we pull from US Federal Exchange.
Either way we got it covered for any country and currency starting from 1972.

**Comment by DianaMPG** [comment]
@akariv ok
We might discuss this at the roundtable call, team Uruguay had some concerns about inflation etc.

**Comment by DianaMPG** [comment]
update: Paul provides feedback how to handle this
