### ISSUE TITLE
Viewer: Missing translations

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1218]
e.g. for `es`

Loading... -> Cargando...
Loading the data. Please wait... -> Cargando los datos. Por favor espere...

**Comment by DianaMPG** [comment]
@kravets-levko can I close this issue?

**Comment by kravets-levko** [comment]
@DianaMPG Yes, that translations (and some other) should be available

**Comment by DianaMPG** [comment]
Thanks @kravets-levko will close
