### ISSUE TITLE
Display errors in Firefox in OS-Admin

### ISSUE THREAD

**Issue by mlukasch** [openspending/openspending#1219]
At http://next.openspending.org/admin/
in Firefox:
![os_admin_display_error_firefox](https://cloud.githubusercontent.com/assets/17597578/22880103/2f8ba020-f1e1-11e6-952f-d9ceb6527957.PNG)
Chrome & IE works for me.

**Comment by vitorbaptista** [comment]
@mlukasch Could you explain the error you saw? I tried and can't see a UI difference between Chrome and Firefox.

**Comment by pwalsh** [comment]
closing as can't reproduce. @mlukasch is no longer working on OBEU so I don't expect an answer.
