### ISSUE TITLE
Budget download per year 

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1222]
Users should be able to download the budget per year

**Comment by pwalsh** [comment]
I think this is closely related to https://github.com/openspending/openspending/issues/1123

@akariv can we do both in one PR?

**Comment by akariv** [comment]
This is unrelated with #1123... reopening.

**Comment by vitorbaptista** [comment]
@akariv Could you expand on what's required here? Where do you envision this functionality to be located? Any specific requirements, etc.

**Comment by akariv** [comment]
This is quite simple actually.
We need to modify the budget loading pipeline so that it creates an extra resource per year.
All the code changes should be in the `datapackage-pipelines-fiscal` module.
