### ISSUE TITLE
OpenSpending/Open Data for Tax Justice: What is feasible in regards to OpenSpending 

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1223]
With the call with tax justice on the 2nd of March, this is the reading material. 

Question is what is feasible in regards to OpenSpending

http://datafortaxjustice.net/what-do-they-pay/#country-by-country-reporting-civil-society-proposals-and-the-oecd-standard

http://datafortaxjustice.net/what-do-they-pay/#what-are-the-prospects-of-a-public-database-from-existing-information-sources

http://datafortaxjustice.net/what-do-they-pay/#building-a-pilot-civil-society-database

**Comment by pwalsh** [comment]
Closing as March 2nd was a long time ago ;)
