### ISSUE TITLE
Problem with custom theming in OS-Explorer

### ISSUE THREAD

**Issue by mlukasch** [openspending/openspending#1226]
Hello,
was updating OS-Explorer to the latest version.
Im using this directory with my custom themes:
https://github.com/openbudgets/integration/tree/master/docker-config/os-explorer/prod_themes
for OS-Explorer:
https://github.com/openspending/os-explorer/tree/master/app/scripts/services/themes

I might be wrong. But it seems that these custom theme files are not used in the end.
Maybe it is this script?
https://github.com/openspending/os-explorer/blob/master/gulpfile.js

(Should I rather use an older commit or is this feature maybe not supposed to be maintained any longer.)
Thanks

**Comment by akariv** [comment]
Could you explain how you're using the themes in the prod_themes directory?

**Comment by mlukasch** [comment]
I mount the folder in the docker-compose-file:
    os-explorer:
        image: openbudgets/os-explorer
        build: ./os-explorer
        volumes:
          - ./os-explorer/prod_themes:/app/app/scripts/services/themes
        expose:
          - "8000"
        environment:
          - WORKDIR=/apps

**Comment by mlukasch** [comment]
Here my compose-file:
https://github.com/openbudgets/integration/blob/master/docker-config/prod.yml

And here is the OS-Explorer-Dockerfile which is basically the one from OpenSpending:
https://github.com/openbudgets/integration/tree/master/docker-config/os-explorer

Thanks a lot.

**Comment by mlukasch** [comment]
Sorry @akariv for wasting your time. Was using an old default.json file as pattern.
Will report back if it works with the new one.

**Comment by mlukasch** [comment]
No the default.json wasnt outdated actually. Here is the link to the explorer:
http://eis-openbudgets.iais.fraunhofer.de/explorer/

**Comment by mlukasch** [comment]
The older commit 4d1f2c51a67a08f50a988eb8f9061db9123f0648 is working and I will use that one the time being.

**Comment by mlukasch** [comment]
The error was on my side. Was able to use the latest commit. http://eis-openbudgets.iais.fraunhofer.de/explorer/ 
Sorry for causing trouble.
