### ISSUE TITLE
OS-Packager Mapping KeyError (Python)

### ISSUE THREAD

**Issue by pierorex** [openspending/openspending#1228]
While uploading a new dataset using OS-Packager we received a Python KeyError.

This is the mapping used:
![os-packager-mapping-errored](https://cloud.githubusercontent.com/assets/9373636/23945774/1e4b65ee-0978-11e7-82d2-2b9e2ec2d810.png)

This is the error:
![os-packager-error](https://cloud.githubusercontent.com/assets/9373636/23945783/278c7b5c-0978-11e7-9e69-91418fbca767.png)

This occured in a workshop today with @badmotor @fathoni @mlukasch @HimmelStein

**Comment by pwalsh** [comment]
@badmotor @fathoni @HimmelStein @pierorex can you provide a file to reproduce this? Closing as this is old, but if you have a file, please add here and I'll reopen

**Comment by fathoni** [comment]
Hi @pwalsh , [here](https://www.dropbox.com/s/tl41ev6tqnmxrgg/AUSTRALIAN%20dataset%20-%20UNdata_Export_20170314_144935861.csv?dl=0#) is the data sample.

**Comment by akariv** [comment]
Hi - issue is a spurious empty line at the end of the input file.

I'll open an upstream issue with the library that we're using, but in the
meantime please make sure that all lines in the file correspond to actual
rows.

**Comment by fathoni** [comment]
I see. The dataset above was exported from UN's data portal. Perhaps, for now, the error message can be simplified - asking the users to check spurious empty line at the end of the input file.

**Comment by akariv** [comment]
Well, the UN is known for many great things - valid CSVs is not one of them :)
