### ISSUE TITLE
Allow default date

### ISSUE THREAD

**Issue by pierorex** [openspending/openspending#1229]
When the user-given dataset does not include a 'date' field, OS-Packager doesn't allow to upload it, thus forcing the user to update his dataset manually, re-upload again and re-map again, A cool new feature would be to allow the user to set a default to every row from the csv directly within OS-Packager, perhaps something like an input field asking for a default year to include in all transactions.
 
This was discussed in a workshop at Fraunhofer IAIS with @badmotor @fathoni @mlukasch @HimmelStein

**Comment by kravets-levko** [comment]
Hi @pierorex! Thank you for your feedback. Are you talking about something like [this](https://github.com/openspending/openspending/issues/1130)?

**Comment by pierorex** [comment]
@kravets-levko I don't think so, that issue is about a toggle to turn columns on/off. What we're talking about in this issue is about a way to define a default value for columns that are mandatory in order to get accepted by OS-Packager, such as 'date'

**Comment by kravets-levko** [comment]
That issue is about adding *constant-value* columns - *virtual* columns that does not exist in CSV file and should add the same constant value for all rows. It may be any value, and it may be mapped as regular column, - and it may be *date* as well. Is that the thing you wish?

**Comment by pierorex** [comment]
@kravets-levko Ah, great! Yeah, that might work. Adding a virtual date column would overcome the validation and allow the user to complete his upload.

**Comment by kravets-levko** [comment]
About that issue - it's already in progress, so you may watch it. I'll also notify you here when it will be available to try.

**Comment by pierorex** [comment]
Thank you!

**Comment by pwalsh** [comment]
closing as this is tracked elsewhere.
