### ISSUE TITLE
OS-Packager fails tests

### ISSUE THREAD

**Issue by skarampatakis** [openspending/openspending#1230]
Hi,

I am trying to set up a local instance of OS-Packager following you instructions.
It builds successfully but when I run the tests it fails.
[test.txt](https://github.com/openspending/openspending/files/849826/test.txt)

Please find attached the output. Am I missing something? 

I continued with using the OS-packager after all, but I cannot pass through mapping step. I select a year column and an amount column but a next button never shows. Additionally, when choosing an amount column for every edit I make the box collapses. And I have to reselect the box to expand. After that, my edit is there but it happens again for every edit I make. 

Please inform if you need any additional info about this. 
Thank you in advance.

**Comment by kravets-levko** [comment]
Hi @skarampatakis! Thank you for your feedback. Seems that it is rather an issue with tests and not with the app; I'll take a closer look at it as soon as it will be possible.

**Comment by skarampatakis** [comment]
Hi @kravets-levko. Thank you for your response. As I mentioned it is not just the tests, but also the app, as the next button is never showing. This is something indicated by the test logs also if understand correctly. I will try to install the app using docker, as I had a similar issue with cosmopolitan, when trying to follow the instructions from readme.

I will this probably today and inform on any update.

**Comment by kravets-levko** [comment]
Hm, seems that this issue is more serious that I thought. Anyway, I cannot check it right now, but will do it ASAP (probably today, but a bit later)

**Comment by skarampatakis** [comment]
Hi, 
I have tested with docker and I got the same results. 
The next thing I tried was to copy the app.js from your online instance and put it on my public folder. And it seems to be working!

During npm install I got these warnings
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
```
I don't know if this is the source of the problem. Or maybe an outdated version from github? Which branch should I clone?

**Comment by kravets-levko** [comment]
The latest version of the app is in the `master` branch, so you should use it. Which branch did you use when you encountered this issue?

About WARNs: just ignore them; we cannot fix them because that dependencies are not direct dependencies of OS Packager. They are not affecting the app, it should work.

**Comment by skarampatakis** [comment]
I am using the master branch.

**Comment by skarampatakis** [comment]
Hi,
Are there any updates on this?

**Comment by akariv** [comment]
@skarampatakis tests should pass now.

**Comment by skarampatakis** [comment]
Hi @akariv, 
Just tested and was able to test the app locally. Thank you for your support.
