### ISSUE TITLE
OS-viewer return error

### ISSUE THREAD

**Issue by wk0206** [openspending/openspending#1231]
I follow this [link](http://docs.openspending.org/en/latest/developers/viewer/) to install viewer locally.
but I met some problem, such like d3-plugins is not fit for the latest version [d3,](https://github.com/d3/d3-plugins) file-saver can not found
`ERROR in ./app/front/scripts/index.js
Module not found: Error: Cannot resolve module 'file-saver/FileSaver.js' in /home/wang/OP/os-viewer/app/front/scripts
 @ ./app/front/scripts/index.js 23:19-53
`

I solve these by install these modules manually, finally I can run
`npm run build`
`npm start`

and when I visit page, it return such error
` root@wang-Inspiron-7548:/home/wang/OP/os-viewer# npm start

> os-viewer@0.1.0-alpha start /home/wang/OP/os-viewer
> node index.js

Listening on :4000
Trace: Error: Failed loading data from https://next.openspending.org/api/3/info/undefined/package
    at /home/wang/OP/os-viewer/app/services/utils.js:38:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at /home/wang/OP/os-viewer/app/services/utils.js:43:15
    at process._tickCallback (internal/process/next_tick.js:103:7)
`
Do you have any idea with the final [link](https://next.openspending.org/api/3/info/undefined/package)?
Does this link available outside the intranet? Or it is already removed.

**Comment by liyakun** [comment]
+1 I have the same issue.

**Comment by akariv** [comment]
See the sequence in the Dockerfile for exact installation instructions:
```
npm install -g napa
napa eligrey/FileSaver.js:file-saver
napa d3/d3-plugins:d3-plugins
npm install
npm run build
```

I'll update the Readme with these exact instructions.

**Comment by liyakun** [comment]
@akariv I test the [os-viewer](https://github.com/openspending/os-viewer) with docker container, but the "Failed loading data from https://next.openspending.org/api/3/info/undefined/package" issue is still there. Do you know the reason? thanks.

**Comment by akariv** [comment]
Which URL are you trying to open?

OS-Viewer can only be used in either of these scenarios:
- by specifying a specific dataset in the URL
- when logged in, it will automatically choose a dataset from the user's
datasets.

**Comment by liyakun** [comment]
@akariv I tested viewer from my localhost with url "http://172.17.0.2:8000/6018ab87076187018fc29c94a68a3cd2:at-austria-2014-2020-erdf?lang=en", and the viewer container listens on 172.17.0.2:8000

**Comment by akariv** [comment]
Hi @liyakun 

I'm sorry for the very long response time - I believe the problem you were seeing might have been related to http/https mismatches. Is that possible?

We've made a few modifications to the code to address that, if you could please pull from master and retry that would be great.

**Comment by liyakun** [comment]
@akariv I deployed the newest os-viewer from openspending github repository by using provided docker configuration files. I got the following errors:

- The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
- Please contact the website owners to inform them of this problem.


when I visit https://172.17.0.2:8000/06879188a2463cdee721a09a3da65cde:cmr_ca_municipal2015?lang=en, where 172.17.0.2 is the ip address of the os-viewer docker container.

**Comment by akariv** [comment]
Hi @liyakun, when working locally you should use `http` and not `https`.

**Comment by liyakun** [comment]
@akariv it works great with `http`.
