### ISSUE TITLE
Sankey diagram shows hierarchy different from what's defined in the URL

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1234]
For example, go to https://next.openspending.org/viewer/boost:boost-moldova-2005-2014?measure=%22adjusted.sum%22&groups%5B%5D=%22economic_classification_econ1.econ1%22&filters%5Bdate_2.year%5D%5B%5D=2014&order=%22adjusted.sum%7Cdesc%22&visualizations%5B%5D=%22Sankey%22&lang=en. This is what I see:

![Chart with wrong data being displayed](https://cloud.githubusercontent.com/assets/76945/25898257/44941390-3583-11e7-8178-ab184557c03f.png)

Even though everything shows as if the data displayed is the "Economic Classification", the actual chart displays data from "Administrative Classification". If you click again in the "Economic Classification" hierarchy, you'll get the correct chart:

![Chart with correct data](https://cloud.githubusercontent.com/assets/76945/25898284/6d0be2ee-3583-11e7-95f0-ae07812bb93f.png)

**Comment by vitorbaptista** [comment]
I started debugging this issue, and here's what I found so far. The function that starts populating the visualization's parameters when the page is loaded is :

```javascript
function init(packageModel, initialParams) {
  var anyDateTimeHierarchy = _.first(packageModel.dateTimeHierarchies);
  initialParams = normalizeUrlParams(initialParams || {}, packageModel);
  initialParams = validateUrlParams(initialParams, packageModel);

  var defaults = getDefaultState({
    packageId: packageModel.id,
    countryCode: packageModel.meta.countryCode,
    dateTimeDimension: anyDateTimeHierarchy ?
      _.first(anyDateTimeHierarchy.dimensions).key : null
  });

  return _.extend(defaults, initialParams);
}
// https://github.com/openspending/os-viewer/blob/04a243ac97fb76ff5ef6b308d2bc7ca269df2d8e/app/front/scripts/services/os-viewer/params.js#L192-L205
```

The important call is `validateUrlParams()`. That function works like:

```javascript
function validateUrlParams(params, packageModel) {
  var result = {};

  result.lang = params.lang;
  result.theme = params.theme;

   // ...

  var type = _.first(visualizations).type;
  var defaults = {};
  switch (type) {
    // Initialize the default params in the "defaults" object,
    // depending on the visualization "type"
    // In this bug, the switch will end up on the following:
    case 'drilldown':
    case 'sortable-series':
      initCommonParams(defaults, packageModel);
      if (type == 'sortable-series') {
        defaults.series = [];
      }
      break;
    // ...
  }
  defaults.filters = {};

  // At this point, "defaults.source" and "defaults.target" were set by
  // updateSourceTarget() called by initCommonParams() to the group on
  // "packageModel.dimensions[0].key", which is
  // "administrative_classification_2" in this bug's example

  // Then we'll overwrite all values in "defaults" with the values from
  // the received "params", adding the results to "result".
  // I think this is the same as "result = $.extend({}, defaults, params)"
  _.each(defaults, function(unused, key) {
    result[key] = params[key] || defaults[key];
  });
  // After this point, we have:
  // results = {
  //  groups: ["economic_classification_econ1.econ1"],
  //  source: "administrative_classification_2.admin1",
  //  target: "administrative_classification_3.admin2",
  // }
  // which seems to be an invalid state (the source/target should be defined based on the groups).

  // ..

  return result;
}
// https://github.com/openspending/os-viewer/blob/04a243ac97fb76ff5ef6b308d2bc7ca269df2d8e/app/front/scripts/services/os-viewer/params.js#L139-L190
```

The problem seems to be that the `params` we get from the URI don't have a `source` or `target` values, so they get the default values (i.e. the values we get considering the first package's dimension). A potential solution is to add `initialParams = updateSourceTarget(initialParams, packageModel)` between the `normalizeUrlParams()` and `validateUrlParams()` calls in the `init()` function I pasted above. This will add the `source` and `target` values to `initialParams`, which will be used by `validateUrlParams()` instead of the defaults.

However, as I'm still understanding the codebase and the test suite is quite small, I'm not sure if there are unwanted side-effects for this solution. @akariv What do you think? Do you see any potential issues with this solution?

**Comment by akariv** [comment]
@kravets-levko would know best.

**Comment by kravets-levko** [comment]
Hi @vitorbaptista! You can add `updateSourceTarget` call into `validateUrlParams` - `init` is called only once at application start (as far as I remember), but `validateUrlParams` may be called when navigating using browser's history (but you can check this to be sure).

**Comment by vitorbaptista** [comment]
@kravets-levko Instead of changing `validateUrlParams()`, I changed `init()` to use `updateFromParams()`, which is quite similar to what `init()` was already doing, with the difference that it calls `updateSourceTarget()`. Basically, `updateFromParams()` gets a blank default state from `getDefaultState()`, while `init()` set some default attributes based on the received `packageModel`.
