### ISSUE TITLE
Buttons not displayed correctly on the OS Admin page

### ISSUE THREAD

**Issue by johanricher** [openspending/openspending#1237]
I've successfuly imported data in OS (using https://next.openspending.org/).

## How it should appear (taken from the [OBEU tutorial](https://github.com/openbudgets/pipeline-fragments/tree/master/FDPtoRDF/documentation/user%20documentation)): 

![osadmin](https://github.com/openbudgets/pipeline-fragments/raw/master/FDPtoRDF/documentation/user%20documentation/run-external-hooks.png)

## How it appears for me:

![osadminbug](https://cloud.githubusercontent.com/assets/10212787/26114636/187d4846-3a5e-11e7-92ec-23bf48207dda.png)

The three dots in particular are invisible, you have to hover around to find them.

**Comment by akariv** [comment]
Which OS/browser are you using? Which versions?

**Comment by johanricher** [comment]
Firefox on Windows 10, latest versions. Will try again on Ubuntu / Chrome.
I'll keep you posted.

**Comment by johanricher** [comment]
I tested on Chrome/Chromium on Windows and Ubuntu: no display bug. So it would appear that the software has compatibility problems with Firefox.

**Comment by brew** [comment]
Tested on Firefox Win/10, and can't reproduce the issue. I suspect the original issue was a failure to load the page fonts or font icon files.
