### ISSUE TITLE
Issues with authentication flow in certain conditions

### ISSUE THREAD

**Issue by skarampatakis** [openspending/openspending#1238]
Hi, I have installed os-packager locally. I successfully run the dev server and made the appropriate mapping of a sample csv file. At the end, in order to publish my data I have to push the "Login to Publish" button. When I click on it, it opens a new tab on my browser but then the tab closes immediately. The same happens with the top right login button. I think it is supposed to redirect me to the default openspending platform to authenticate myself. Is it something wrong with my configuration or it is a bug?

**Comment by skarampatakis** [comment]
@pwalsh 
Maybe I have to say that I am running also a proxy on host/packager/ in front of http://localhost:5000/, but I had the same issue without the proxy. I get correctly redirected to Google's OAuth service and authenticate succesfully but then i get redirected to /logged-in instead of /packager/logged-in and I get a 404. I have no other debug output either on the monitor of node nor on the browser console. 

This is the config/index.js from my local instance. You can test my instance in http://bioweb.math.auth.gr/packager/. Please inform what other info is required. Thank you in advance

```
'use strict';

var path = require('path');
var nconf = require('nconf');

const DEFAULT_HOST = '//next.openspending.org';
const DEFAULT_BASE_PATH = '/packager';

nconf.file({
  file: path.join(__dirname, '/../../settings.json')
});

var conductorHost = process.env.OS_PACKAGER_CONDUCTOR_HOST || DEFAULT_HOST;

// Options for frontend
var frontendOptions = {
  conductor: {
    authLibUrl: conductorHost + '/user/lib',
    conductorUrl: conductorHost + '/datastore/',
    conductorInfoUrl: conductorHost + '/datastore/info',
    publishUrl: conductorHost + '/package/upload',
    statusUrl: conductorHost + '/package/status',
    pollInterval: process.env.POLL_INTERVAL || 3000
  },

  adapterUrl: process.env.FDP_ADAPTER_URL ||
    DEFAULT_HOST + '/fdp-adapter/convert',

  proxyUrl: 'proxy?url=',
  osViewerUrl: process.env.OS_VIEWER_URL || DEFAULT_HOST + '/viewer/',
  osAdminUrl: process.env.OS_ADMIN_URL || DEFAULT_HOST + '/admin/'
};

// this is the object that you want to override in your own local config
nconf.defaults({
  env: process.env.NODE_ENV || 'development',
  debug: process.env.DEBUG || false,
  app: {
    port: process.env.PORT || 5000
  },
  frontend: frontendOptions,
  basePath: process.env.OS_PACKAGER_BASE_PATH || DEFAULT_BASE_PATH,
  snippets: {
    ga: process.env.OS_SNIPPETS_GA || null
  }
});
```

**Comment by pwalsh** [comment]
@skarampatakis provide a printout of the the environment variables you have set (if any)

**Comment by akariv** [comment]
We've had issues getting login to work when working from localhost.

If you could host the website on `dev.openspending.org`, port 80, it should work ok.
You could do that by adding an entry to your `/etc/hosts` file.

**Comment by skarampatakis** [comment]
@akariv but how would this work on a public server? I mean, we plan to deploy the Packager on mydomain.com. Will I be able to do so? I will try your suggestion and report if this is working on my case.

@pwalsh I have not set any environment variables. this is the output of process.env
```
{ LC_PAPER: 'el_GR.UTF-8',
  LC_ADDRESS: 'el_GR.UTF-8',
  XDG_SESSION_ID: '854',
  LC_MONETARY: 'el_GR.UTF-8',
  TERM: 'xterm',
  SHELL: '/bin/bash',
 
  LC_NUMERIC: 'el_GR.UTF-8',
  SSH_TTY: '/dev/pts/8',
  USER: 'sotos',
  LC_TELEPHONE: 'el_GR.UTF-8',
 
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
  QT_QPA_PLATFORMTHEME: 'appmenu-qt5',
  LC_IDENTIFICATION: 'el_GR.UTF-8',
  
  LANG: 'en_US.UTF-8',
  LC_MEASUREMENT: 'el_GR.UTF-8',
  SHLVL: '1',
 
  LANGUAGE: 'en_US',
 
 
  XDG_RUNTIME_DIR: '/run/user/1000',
  LC_TIME: 'el_GR.UTF-8',
  LC_NAME: 'el_GR.UTF-8',
  _: '/usr/bin/node',
  OLDPWD: '/home/dbpedia/NetBeansProjects/os-packager/app' }
```

**Comment by akariv** [comment]
Yes, the base path setting is exactly meant for allowing you to host on any internal path.

Login only works on authorised domains, so there are two options:
- Host OS-Conductor on your own and create your own OAuth2 credentials with your source.
- We add your domain to the list of authorised sources for OpenSpending.

**Comment by pwalsh** [comment]
> We add your domain to the list of authorised sources for OpenSpending.

Which we will do for the official OBEU domain ( cc @badmotor )

**Comment by skarampatakis** [comment]
@akariv 

> Seems like the base url is not configured correctly - OS_PACKAGER_BASE_PATH should not be set, or have the correct value based on your setup.

What is the correct value? 

If I understand correctly there is nowhere defined as an env variable as seen from my process.env output. So the packager uses the DEFAULT_BASE_PATH. 

As you see I have set
```
const DEFAULT_BASE_PATH = '/packager/';
```

Below you can see also my apache settings

```
<VirtualHost *:80>

    ProxyPreserveHost On
	
    ProxyPass /v1/ http://localhost:8000/v1/
    ProxyPassReverse /v1/ http://localhost:8000/v1/

    ProxyPass /packager/ http://localhost:5000/
    ProxyPassReverse /packager/ http://localhost:5000/

    <Proxy *>
        allow from all
    </Proxy>
    ServerName bioweb.math.auth.gr

</VirtualHost>
```

Is there something else I should look for? I still get redirected incorrectly to /logged-in instead of /packager/logged-in. Or this is something that is configurable through OS Conductor as you said?

I have tried also to use the dev.openspending.org but then I am redirected to dev.openspending.orglogged-in and fails. Somehow the slash is cut out. If you have any hint here...

About the two solutions you are suggesting, I see the second one as a problem for the OBEU platform purposes. If someone deploy his own instance, he would need to contact you in order to allow his domain on your auth service. It is OK for testing purposes but I have my long-term concerns.  

So the follow up question would be what are the requirements of setting up the whole OS platform? Would it be a big overhead for the platform, resource and effort wise, in order to have a user friendly data modeling interface?

**Comment by akariv** [comment]
Try setting DEFAULT_BASE_PATH to be  'packager', without the slashes.

As for own instance - if someone deploys their own instance of OS-Packager but wishes to use OpenSpending auth and datastore, I would like to have some sort of control on which instances are allowed to do that to make sure that the modified version of OS-Packager is up to date and does not do anything "bad" (for multiple aspects of bad).

Since all components of OpenSpending can be deployed independently I don't see that as a problem - in case you want complete control, simply deploy your own version of OS-Conductor with your set of credentials.

Let's move this discussion outside of this GitHub issue, though.

**Comment by skarampatakis** [comment]
I have set the base path without the slashes and had the same result. 

I removed completely the base path and changed the proxy path and now I got redirected after authentication to ```http://dev.openspending.orglogged-in/```

I stopped apache and run node on :80. The same result as above. 

All other paths are working properly and the interface renders as it is supposed to in any case except the login link. 

From the root on  ```dev.openspending.org``` I see on the console something like this
```
https://next.openspending.org/user/check?next=http://dev.openspending.orglogged-in
```

From any other path ie ```dev.openspending.org/provide-data``` I see
```
https://next.openspending.org/user/check?next=http://dev.openspending.org/logged-in
```
Would you require any more info? Is it supposed that I could get logged in? 

I agree with what you have said about security issues. These would be my concerns also. I am just trying to figure out what is required in order to have the OS Packager running on our server. And in any other server it might be deployed. So I keep that if we want to have a standalone service we have to get the whole platform, datastore included. 

I will share with you an alternative I have in mind shortly. Thank you again for your support.

**Comment by akariv** [comment]
@skarampatakis the default settings allow you to host locally (without a base path).
Setting DEFAULT_BASE_PATH to be 'packager' should allow you to host on the `/packager/` path - but it also depends on your frontend config (and I'm not that familiar with Apache).

As for the login issues, I fixed the problem and it should work now from localhost:5000 as well (no need for dev.openspending.org).

**Comment by skarampatakis** [comment]
Hi @akariv, 

I still can't get connected. Now I get 

```
The site at https://next.openspending.org/oauth/google_callback?state=something&code=4/bsomehting_else__XK2HnY# has experienced a network protocol violation that cannot be repaired.
```

**Comment by akariv** [comment]
This is a browser error... are you using Firefox by any chance?

**Comment by skarampatakis** [comment]
Yes. Tried with Chrome:

and got stack here.

```
https://accounts.google.gr/accounts/SetSID
```

On the console I get this error
```
app.js?14960622179082590:5 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","params":{"next":"http://localhost:5000logged-in"},"withCredentials":true,"url":"https://next.openspending.org/user/check","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""}
```

Might be related

**Comment by akariv** [comment]
Could you attach the complete console log?

**Comment by skarampatakis** [comment]
I changed the cosmopolitan api to match your public instance. 
I also defined ```debug: true```. But now I get nothing on the console. Just opens a new tab when I click Login button. Sometimes at random it throws the above message on the console.

**Comment by akariv** [comment]
What's the URL of the new tab?

Also, can you try and find the request to next.openspending.org/user/check,
and paste the body and response for that request?

**Comment by skarampatakis** [comment]
If I delete cache and cookies it redirects to google where I successfully authenticate. But afterwards, it redirects to https://accounts.google.gr/accounts/SetSID and stack there. 

If I try again with a previously successful attempt, it just opens a new blank tab ```about:blank```
![screenshot from 2017-05-29 17-33-55](https://cloud.githubusercontent.com/assets/2419820/26553612/1d23e666-4495-11e7-889a-f8a2cc3bf156.png)


I have multiple instances of these requests.

https://next.openspending.org/user/check?next=http:%2F%2Flocalhost:5000logged-in
 please notice that there is not '/' between port and path if of any meaning.

```
{
  "authenticated": false,
  "providers": {
    "google": {
      "url": "https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=791676150192-bc2q51rttplg10c82gcl7a62ckfaquuj.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fnext.openspending.org%2Foauth%2Fgoogle_callback&scope=email+profile&state=somethingy9sb2NhbGhvc3Q6NTAwMGxvZ2dlZC1pbiIsImV4cCI6MTQ5NjA2OTEzMn0.ixn-KTaZYdo5ustHH1jVvU5hJyeaWA-O1q-C5kySmIY"
    }
  }
}
```

**Comment by akariv** [comment]
The missing '/' issue is occurring only in these situations:
- Trying to login from the packager's landing page
- The packager is hosted in root ('/') 

I will definitely fix this issue but as there seems to be a very simple workaround I don't consider this as very urgent.

As to the `about:blank` / `https://accounts.google.gr/accounts/SetSID` issues:
Tried to reproduce locally but didn't succeed - managed to log in without issues with the original code.
Can you please try and see if this problem occurs to you in `next.openspending.org`?

**Comment by skarampatakis** [comment]
No, I can successfully login on next.openspending.org.

**Comment by skarampatakis** [comment]
Steps to reproduce
- install packager from scratch
- run server
- open localhost:5000 from incognito in Chrome
- push login button
- Authenticate yourself through google 
- You get the redirect to https://accounts.google.gr/accounts/SetSID with an empty page
- Every time you push the login button you get the same page until clear cache. 

Tested with 
 - Ubuntu Chrome & Firefox latest versions
- Windows 7 Chrome, Firefox and IE latest versions.

**Comment by liyakun** [comment]
> I get correctly redirected to Google's OAuth service and authenticate succesfully but then i get redirected to /logged-in instead of /packager/logged-in and I get a 404.

This also happens in https://github.com/openbudgets/platform/issues/39. @skarampatakis have you sloved this problem? @akariv any plan to fix this? Thanks.

**Comment by akariv** [comment]
Login from os-packager main page was resolved in latest master branch.

**Comment by skarampatakis** [comment]
I can confirm that this issue has been fixed. Thank you.
