### ISSUE TITLE
Platform availability: Add additional monitoring and alerts to the OpenSpending platform

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1239]

**Comment by vitorbaptista** [comment]
Just adding it here so we don't forget later: we also need to monitor the build status of our Docker containers, otherwise the build can fail without us noticing (see https://hub.docker.com/r/openspending/os-packager/builds/ for an example)

**Comment by pwalsh** [comment]
@vitorbaptista 

You did most of this already.

Can you lay out for @brew 

- [ ] What we *are* monitoring
- [ ] What we still *need* to monitor
- [ ] Task list for remaining monitor integrations required
- [ ] Steps for documenting the monitoring, ideally at docs.openspending.org ( https://github.com/openspending/docs )

@brew 

When we get the list of what has ben done, and what is remaining, please provide and estimate on remaining work ( and sync with myself and @vitorbaptista for any questions )

**Comment by vitorbaptista** [comment]
@brook I have only set up the status.openspending.org. I started looking into how to send NGINX's logs to the DataDog, but it's a quite involved process that I didn't finish. From my research, the flow was from NGINX to Papertrail, then on Papertrail we would create saved search queries, that would send stats (like number of rows) to DataDog.

My priority would be:
1. Make sure all webserver logs are going to Papertrail (so we're able to debug issues in production)
1. Enable Sentry across our apps
1. Log and monitor HTTP errors on DataDog
1. Monitor the build status of our Docker images

**Comment by brew** [comment]
We already have a logspout container running in our stack, which aggregates logs from other containers on the same node, if they write to stdout/stderr, and pushes them to Papertrail.

We need to get our nginx frontend container to write logs to stdout/stderr. This is achieved in this commit: openspending/os-nginx-frontend@04f2df781a53dc375e5c4ec652c4274d7ff23cff by changing nginx.conf in a way that allows writing to stdout/err. This blog post was helpful: https://blog.froese.org/2014/05/15/docker-logspout-and-nginx/.

So, we now have useful frontend logging in Papertrail. The next step will be to get specific status code data into DataDog...

**Comment by brew** [comment]
A short guide for adding Docker hosted nginx log visualisation to DataDog: https://hackmd.io/s/B1XZILlxf

**Comment by brew** [comment]
Sentry already enabled for:
- openspending/os-conductor

Sentry added to:
- openspending/os-api
- openspending/os-explorer
- openspending/os-packager

**Comment by pwalsh** [comment]
@brew happy with coverage.

Can we get all docs consolidated in a single place somewhere. Ideally docs.openspending.org in terms of what is related to system config, and then, in our private infra doc at OKI for config secrets

**Comment by brew** [comment]
- Changed the way clientside apps (os-admin and os-explorer) are configured for Sentry, so they can use DSN values obtained from an env var.

- Added config documentation for apps that use Sentry: http://openspending.readthedocs.io/en/latest/developers/#monitoring

**Comment by brew** [comment]
Developer details pertinent to the OKI instance of OpenSpending have been added to the [OpenSpending Handbook](https://docs.google.com/a/okfn.org/document/d/1HmZbAeudPC4MBBi8VwWiyzL7cQRgtWP14BFLmQvz-Yc/edit?usp=sharing) (private link)

**Comment by pwalsh** [comment]
Closing this, as it was done in December.
