### ISSUE TITLE
Platform availability: Add status page 

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1240]
Add a publicly accessible status page that shows, in real time, 
the health and availability of the various components of the 
OpenSpending platform

**Comment by pwalsh** [comment]
The status page setup has been done by @vitorbaptista and tested out by @brew 

As far as I see, the remaining tasks are:

- [ ] Confirm that the setup is done. @vitorbaptista to provide additional steps if not
- [ ] Add all documentation for the status page setup (docs targeting developers) to docs.openspending.org ( https://github.com/openspending/docs )
  - [ ] This *must* include instructions for the developers maintaining OpenSpending (i.e: the OKI Product Team) for how to add a notification. I assume the scenarios for adding notifications are to (i) broadcast an emergency downtime, and (ii) broadcast notice for a future downtime, (iii) broadcast notice of a new feature, or an enhancement of an existing feature, or a bug fix that may impact users, to land on production
  -  [ ] This must include instructions for users to get notifications
- [ ] Write an email to GIFT ( @pwalsh or @DianaMPG can do this ) to announce the monitoring is live, and how pilot partners can sign up for the monitoring service
- [ ] Announce the monitoring feature on Twitter

**Comment by brew** [comment]
- OpenSpending status page live at https://status.openspending.org
- User-facing documentation for subscribing to status notifications added to docs: https://docs.openspending.org/en/latest/developers/#status-and-incident-notifications
- Maintainer focussed information about the system we use for status monitoring, and creating ad-hoc incident reports, available in the [OpenSpending Handbook](https://docs.google.com/a/okfn.org/document/d/1HmZbAeudPC4MBBi8VwWiyzL7cQRgtWP14BFLmQvz-Yc/edit?usp=sharing) (private link)

**Comment by pwalsh** [comment]
Closing as done in December.
