### ISSUE TITLE
Platform availability: Requirements document

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1242]
Produce requirements document for WP 2

**Comment by DianaMPG** [comment]
@akariv what´s the status?

**Comment by pwalsh** [comment]
@DianaMPG this is my task, not that of @akariv 

Status is that it is not done. I'm waiting for the launch of next.*

**Comment by pwalsh** [comment]
This task was done in a very ad hoc manner between myself and Vitor, when developing the notification system.
