### ISSUE TITLE
Online tutorial on how to upload and map budget data

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1244]
The idea is to help data publishers to upload budget data (first timers and/or regulars) on OS Packager. 
The tutorial gives basic outlines around dataset requirements as well as how to map the columns of your dataset.

**Comment by pwalsh** [comment]
@DianaMPG has anything been started here?

**Comment by DianaMPG** [comment]
Tania and I decided that it would be more helpful to translate the intro to OpenSpending to Spanish since the Spanish speaking partners are becoming more. Oscar translated it. 

https://docs.google.com/document/d/1_S8Jqux4CTTRDH_4TcG5hTZ0xOSn9C4TYrBYs8uu8Ks/edit

**Comment by jobarratt** [comment]
OK so this is no longer a deliverable for GIFT III that needs to be close. I have removed the labels, but keeping the issue as i think it is still important to do.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. Please feel free to re-open if this is still relevant.
