### ISSUE TITLE
Online tutorial on how the pipeline works 

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1245]
Idea is to create an online tutorial to explain how the pipeline works to pull requests and merge.

**Comment by pwalsh** [comment]
@DianaMPG did anything start here?

**Comment by pwalsh** [comment]
@DianaMPG was this done? It is not assigned.

**Comment by DianaMPG** [comment]
@pwalsh

**Comment by DianaMPG** [comment]
@jobarratt
As a first step, Lieke had worked on an update of the OpenSpending documentation
https://docs.google.com/document/d/1eUP3hEwOD4N7Vc1JEl7uQ5la2FCi67wnBi2ggsf82fg/edit#

In a next step, Adam and I were supposed to work on an online tutorial but we couldn´t find a time slot, so this is still open.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. Label `prioritized` was also removed a long time ago. Please feel free to re-open if this is still relevant.
