### ISSUE TITLE
Spending Data exploration: Blog post on Open Contracting

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1246]
Blog posts on the landscape around Open Contracting

**Comment by pwalsh** [comment]
@DianaMPG could you elaborate on this please?

**Comment by DianaMPG** [comment]
@pwalsh as part of the WP 5, you decided that some content around the "landscape of Open Contracting would be a good thing. We haven´t specified anything yet since this content was originally not due until November. 

If we see other options for dissemination which would make more sense, we can always go back and suggest them to GIFT. We did so with the Intro to gov partners - instead of blog posts we translated the Intro into Spanish for some of our Spanish speaking  gov partners.
