### ISSUE TITLE
Spending data exploration: Requirements document

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1250]
A requirements document for what a proper implementation of transactional spending data in 
OpenSpending would need. 

This will also be implemented in OpenSpending documentation.

**Comment by DianaMPG** [comment]
links to #1312

**Comment by pwalsh** [comment]
We need GIFT to provide data to make progress here.

In the meantime, we may be able to receive some suitable data from Mexico, as Lorena will send me an example on how they are addressing the link between the OFDP and Open Contracting Data Standard and transactions.

If the data is volumes enough, it may be a good start for the spending data exploration.

**Comment by pwalsh** [comment]
@DianaMPG Assigned to myself as I am responsible for the requirements document.

**Comment by DianaMPG** [comment]
@pwalsh 
we were also hoping to get the spending data of the US treasury. That´s why we pro-actively reached out and I have suggested this to GIFT. First contacts and calls were established and it is highly likely that we meet them in Washington next month. To have their data on board in addition to the data from Mexico, that would be ideal.
