### ISSUE TITLE
v1 of OFDP: Blog post 

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1253]
A blog outlining the v1 specification, published on OKI blog and disseminated via various channels.

**Comment by akariv** [comment]
Draft for blogpost is here:
https://docs.google.com/document/d/1_twsLXcKz1FRo8C67aDGyyr2EEqW1eQNDkNlXfT0Yzc/edit#heading=h.l56ps9m7ndg

It's pretty ready to use, I think.

**Comment by pwalsh** [comment]
Looks good to me.

@DianaMPG ?

**Comment by pwalsh** [comment]
https://blog.okfn.org/2018/05/28/introducing-version-1-of-the-fiscal-data-package-specification/
