### ISSUE TITLE
Avoid installing dependencies from git if they're available on NPM

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1262]
At least, if we have to install from git, we should pick a specific version, otherwise our builds aren't reproducible.

For example, we install c3 and pivottable from git's master on babbage.ui (see https://github.com/openspending/babbage.ui/blob/f6c46dd2ecdd01c1b6d37f4b162bf88e0bcdcf4b/package.json).

**Comment by kravets-levko** [comment]
I don't know how about `pivottable`, but with `c3` there was a bug - it was impossible to build app using `c3` from `npm` with strange `node-gyp` errors. I think, you should try - maybe something changed since that time.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. Label `prioritized` was removed a long time ago. Please feel free to re-open if this is still relevant.
