### ISSUE TITLE
Use npm-shrinkwrap on all our NodeJS apps

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1264]
Unless we pin all of our exact dependencies (direct and indirect), we can't guarantee that the code that was tested is the code that's being run in production. As our list of dependencies grow, the risk of one of them changing and breaking our code also grows. To avoid this, we must pin everything to known versions. On node, the tool to do this is `npm-shrinkwrap`.

To be clear, we should only use shrinkwrap on apps, not libraries. The distinction is that libraries are supposed to be imported by others, to be used in their code, so they should work with the largest number of dependencies' versions.

Going over the OpenSpending organisation, these are the apps I found:

- [ ] https://github.com/openspending/os-viewer
- [x] https://github.com/openspending/os-admin
- [x] https://github.com/openspending/os-packager
- [x] https://github.com/openspending/os-explorer

We should use `npm-shrinkwrap` in all of them.

**Comment by brew** [comment]
@vitorbaptista We no longer have npm-shrinkwrap.json files in these apps. Does package-lock.json provide that functionality now? Can we close this issue?

**Comment by vitorbaptista** [comment]
@brook yes, `package-lock.json` is the new `npm-shrinkwrap`. If all of our
nodejs apps have it, this can be closed.
