### ISSUE TITLE
CSVs with commas inside quotes are incorrectly parsed by packager

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1268]
Given the CSV:

```csv
quoted_value,value
"This should be a ""single, unique row"", for real",This should be another row
```

The correct parsing would be:

| quoted_value | value |
| --- | --- |
| This should be a "single, unique row", for real | This should be another row |

However, it is parsed as:

| quoted_value | value | | |
| --- | --- | --- | --- |
| This should be a "single | unique row"" | for real" | This should be another row |

Which causes the import to fail. This bug might be related to #1157

**Comment by pwalsh** [comment]
@vitorbaptista do you know exactly where this fails in the Packager?

**Comment by vitorbaptista** [comment]
@pwalsh No, I haven't debugged it, just figured out the smallest CSV that triggered the bug. It might be a bug on `datapackage-py`, or whatever else we use to load the CSV.

**Comment by akariv** [comment]
Since we use CSV dialect sniffing (in goodtables) to determine the properties of the file (delimiter, quoting etc.), then a very short CSV is actually not a very interesting case.
This is because sniffing works better as more text is available.

Not to say that this isn't a real bug, but better find a real-world example that exemplifies it.

**Comment by pwalsh** [comment]
@akariv that is correct too.

My main concern now is whether this error in handling is coming from the old goodtables service, and the gap from us updating to the newer one.

**Comment by akariv** [comment]
Old goodtables uses Python's own sniffer IIRC - do you know if the new service does something different in this department?

**Comment by pwalsh** [comment]
@akariv no, you are right, it is the same.

**Comment by brew** [comment]
The example csv above is currently being parsed correctly, possibly fixed by https://github.com/openspending/os-packager/pull/116. Closing.
