### ISSUE TITLE
OS Viewer: Localization of the interface

### ISSUE THREAD

**Issue by skarampatakis** [openspending/openspending#1271]
Currently UI of OS viewer is only shown in English. How can we change UIs language to match user preferences? 

I know that there is the ```lang``` parameter on the url qs but it is not so practical for many use cases. Is there a language selector button? Or could we use browser preferences to detect the preferred language? 

Both could be perfect!

Another question is how could I contribute translation of the interface in Greek Language. Is there something like https://translation.io/ or https://el.transifex.com/ set? Or I have to fork the repo and create a PR?

**Comment by pwalsh** [comment]
@skarampatakis 

A PR for the language contributions is the way to go.

For language selection, can you explain how a URL param for language is not practical? I'd like to understand your use cases and how this does not support them. 

We don't intend to add a language selector button.

**Comment by skarampatakis** [comment]
@pwalsh 
About the PR, we will do it the sooner possible. 

About language selection options, let suppose the typical common OS Viewer user. And let suppose he/she cannot read anything in English, the default language of OS Viewer. Is it somehow indicated that he has to change the URL parameter in order to get the desired language, and again if it is available? 

A possible workaround would be a language chooser on the landing page, so the user selects the desired language for the whole platform and then all URLs are constructed with the language param set. 

> We don't intend to add a language selector button.

Is there a valid reason for this? 

Language selection is so common and found in almost all localized platforms nowadays.

**Comment by pwalsh** [comment]
> Is there a valid reason for this?

It is a product decision. "Valid" or "invalid" is a relative. 

We are enabling localisation for use in custom instances of the apps, or as an API via the query parameter. The canonical instance of OpenSpending is in English by default for the foreseeable future. Embeds of the Viewer UIs, and custom instances if the Viewer, can choose a language using the param. That is already a lot of flexibility around language selection and we are not prioritising more at this time.

> Language selection is so common and found in almost all localized platforms nowadays.

There are many common features on many used platforms. Like with any good software development process, we need to make decisions on the importance of some features over others.

**Comment by skarampatakis** [comment]
OK.
