### ISSUE TITLE
os-packager "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1272]
Hi, I deployed the os-packager by using docker container with provided docker configuration file. I encountered the "TypeError: Failed to fetch" when I save one data package. Anyone knows why this happen? thanks.
![image](https://cloud.githubusercontent.com/assets/7370334/26721686/1107ab9c-478d-11e7-9ac3-f56efce31ad6.png)
By the way, I already login.

**Comment by pwalsh** [comment]
Hi @liyakun

When submitting bug reports, please provide steps to reproduce.

**Comment by liyakun** [comment]
@pwalsh sorry, this issue is produced by the following steps with dataset Modified_Ejecucion_2017_ingresos_001_OOAA.csv:

- upload data to http://eis-openbudgets.iais.fraunhofer.de/packager/provide-data
- model resource at http://eis-openbudgets.iais.fraunhofer.de/packager/describe-data
- fill forms at http://eis-openbudgets.iais.fraunhofer.de/packager/provide-metadata
- save package at http://eis-openbudgets.iais.fraunhofer.de/packager/download-package

The last step produces the described error.

**Comment by pwalsh** [comment]
Can you provide the file too please.

**Comment by liyakun** [comment]
[Modified_Ejecucion_2017_ingresos_001_OOAA.zip](https://github.com/openspending/openspending/files/1047572/Modified_Ejecucion_2017_ingresos_001_OOAA.zip)
@pwalsh this is the file.

**Comment by akariv** [comment]
@liyakun are you using a local installation of OS-API? 
Can you try uploading the file in next.openspending.org and see if the problem persists?

**Comment by liyakun** [comment]
@akariv there is not deployment of https://github.com/openspending/os-api.git on Fraunhofer server.

**Comment by akariv** [comment]
So which server are you uploading to?
As at the moment the only domains allowed to login to openspending.org are
*.openspending.org, and you can't upload to openspending without logging
in...

**Comment by pwalsh** [comment]
@liyakun @badmotor 

Is `eis-openbudgets.iais.fraunhofer.de` going to be the final domain for end users? We can add the domain to the auth whitelist, but as discussed elsewhere, we want to minimise the domains on this whitelist.

**Comment by liyakun** [comment]
@akariv I don't know it is necessary to have os-api deployment on Fraunhofer server to make os-packager work. I just keep the default settings of os-packager.

@pwalsh  `eis-openbudgets.iais.fraunhofer.de` is going to be the final domain for end users with a certain time.

Does it mean that we have two options, deploying os-api on the Fraunhofer server or adding  `eis-openbudgets.iais.fraunhofer.de`  to the whitelist ?

**Comment by akariv** [comment]
Hi @liyakun, turns out that some default values for URLs of OS services were set incorrectly.
You can override them locally or simply pull from latest master and re-deploy locally.
Please let me know if that works for you.

**Comment by pwalsh** [comment]
> Does it mean that we have two options, deploying os-api on the Fraunhofer server or adding eis-openbudgets.iais.fraunhofer.de to the whitelist ?

Yes. I discussed this with Sotiris last week too.

**Comment by akariv** [comment]
BTW, if not hosting OS-API or OS-CONDUCTOR there then no need for adding to
the whitelist.

**Comment by pwalsh** [comment]
@akariv ok.

**Comment by liyakun** [comment]
@akariv I re-deployed the os-packager on the server, but it still does not work.

**Comment by akariv** [comment]
It doesn't look like the updated code is on your server.
Make sure this commit is in your code base as well 
https://github.com/openspending/os-packager/commit/746ee750ddf0d3f64f78230c9c1fdf978ab89bdc

**Comment by liyakun** [comment]
@akariv sorry, I thought the docker will clone the newest. It is updated now and works, thanks.
