### ISSUE TITLE
Paginating results on package search

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#1273]
Is it possible to also define the from parameter like we do for the size parameter?

https://next.openspending.org/search/package?size=5&from=7

and 

https://next.openspending.org/search/package?size=5&from=10

give back the same result. 

I can see [here ](https://github.com/openspending/os-package-registry/blob/master/os_package_registry/package_registry.py#L165) that from_ always starts from 0, but I am not sure how it actually works and if it is the right spot to modify.

I need the pagination functionality to implement infinite scrolling for the Indigo app of OpenBudgets.eu.

**Comment by akariv** [comment]
Currently this is not supported - but feel free to open a PR and I will
gladly accept.

**Comment by pwalsh** [comment]
I changed the title to match the feature request. This is is a nice enhancement to add but relatively low priority at present, as the proposed use case can be supported without it.

As @akariv indicates, a PR for this would be most welcome!

**Comment by larjohn** [comment]
@pwalsh I suppose you mean that infinite scroll anyway uses all the previous pages plus the new one, so it is supported with just the size parameter, although not as efficient. 

I will contribute a PR but it may take some time.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. The author of the issue has not followed up with a PR yet and the use case is reported to be already supported in other ways. Please feel free to re-open if this is still relevant.
