### ISSUE TITLE
how local deployment of os-admin got updated with os-admin deployed at openspending?

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1275]

**Comment by pwalsh** [comment]
Hi @liyakun 

I'm not sure I understand the question. In your case, how you deploy OS Admin depends entirely on the deployment setup you maintain at Fraunhofer.

For OpenSpending, and all other work at Open Knowledge, we use continuous deployment and other "modern" software practices for platform deployment.

Can you help me understand better what you need assistance with exactly?

**Comment by liyakun** [comment]
@pwalsh thanks for you reply. The senario is that, I upload data through os-packager on my local deployment, after publishing it, then I have option to "Manage your datasets". If I click on "Manage your datasets", then I will be redireted to openspending os-admin, and I can see all the datasets that I published.

If I have a deployment of os-admin on my local(or Fraunhofer server), is that possible to get the list of datasets that I published on openspending?

The os-admin has been deployed on Fraunhofer server by Maik, I have this question is because that if the deployment of os-admin on Fraunhofer cannot be updated with the os-admin on openspending, then it is not necessary to have os-admin deployed on Fraunhofer server.

**Comment by liyakun** [comment]
one example to show:

![image](https://user-images.githubusercontent.com/7370334/26874426-d5022fe2-4b7d-11e7-9f50-98c72d239b0b.png)

**Comment by pwalsh** [comment]
@liyakun ( cc @larjohn  @skarampatakis @badmotor @akariv )

This is about configuration. You have to configure your server correctly, to, for example, point to your local OS Admin. 

Also, the list of datasets from the OBEU triple store (via Rudolf) is not identical to the list on OpenSpending. 

You need to understand the whole architecture of OBEU at Fraunhofer, and then configure the components from OS to follow suit.

If there is a bug or a missing configuration in the OS components, we will address it, but, this issue as opened is just about the configuration, which has been done completely by the Fraunhofer team at OBEU and I don't know how I can help you with that.

We can talk abut it on the next technical call, but ultimately, everything I can help with is as above.

**Comment by liyakun** [comment]
@pwalsh thanks, from my current understanding, after uploading dataset to openspending, if the user run external hook, then the data will also go to OBEU triple store, otherwise it will not. I think this is why the list of datasets of OBEU triple store is not identical to the list on OpenSpending.

Currently, we already deployed os-packager on Fraunhofer server, I don't know whether should I change the link of "Manage your datasets" to os-admin on Fraunhofer server or keep the original one. 

Maybe a short question, after the data has been uploaded to OpenSpending server, how os-admin on OpenSpending got updated?

**Comment by pwalsh** [comment]
@liyakun updated, meaning, "how does the user see her datasets"?

By looking at the code on OS Admin, it looks like the update [happens with this `updatePackagesAndMetrics` function](https://github.com/openspending/os-admin/blob/master/app/scripts/controllers/main.js#L29), and the [os-admin service module](https://github.com/openspending/os-admin/blob/master/app/scripts/services/os-admin/index.js) communicates with the service that provides the data.

Like @larjohn did with OS Viewer, it might be needed to make this configurable to point to a Rudolf API endpoint.

**Comment by skarampatakis** [comment]
Can it be configured to use both endpoints?

**Comment by pwalsh** [comment]
@liyakun @skarampatakis

> Can it be configured to use both endpoints?

How, when, why?

Why don't you first start with a design document for what we are trying to achieve here: the data flow, the user flow, and so on.

Then, we take this design document and understand how to achieve it based on the tools and available configuration. 

Then, if one of the components is missing the ability to configure towards a certain, clear use case, and the use case is reasonable and makes sense, we see what needs to be done in any actual code base to meet the end goal.

At the moment, there is no clarity or purpose or design to what is going on. It seems that code is being deployed, and then an issue opened per configuration problem confronted. It is an inefficient way to develop public-facing software.

**Comment by skarampatakis** [comment]
Sorry for the bombing out of nowhere question. This is a completely different issue. I will document a proper issue when we have resolved all other issues.
