### ISSUE TITLE
Design for Landing Page

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1278]
# Description

The design for the proper release of OpenSpending Next.

Based on mock at https://docs.google.com/document/d/19acar_RiaesyRyCqw2rEOVGf7P7PgIKS9zHSH66eTAI/edit

# Tasks

- [x] Initial mocks
- [x] HTML mock

**Comment by smth** [comment]
![os_01_home_04](https://user-images.githubusercontent.com/1375708/26880638-edd2a8da-4b8c-11e7-82ad-f9237c2cbb14.jpg)

**Comment by smth** [comment]
HTML version here: 
- http://p.smth.uk/os-mockups/
- https://github.com/smth/os-mockups

**Comment by pwalsh** [comment]
Thanks @smth it looks great.

**Comment by pwalsh** [comment]
Implementation will occur in https://github.com/openspending/openspending/issues/1279
