### ISSUE TITLE
Implementation for Landing Page

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1279]
# Description

Based on the design implemented on https://github.com/openspending/openspending/issues/1278. It's available on http://p.smth.uk/os-mockups/ (repository at https://github.com/smth/os-mockups).

# Tasks

- [ ] Implement https://github.com/openspending/openspending/issues/1278

**Comment by pwalsh** [comment]
#1278 is now done, and can be actioned

**Comment by vitorbaptista** [comment]
Fixed via https://github.com/openspending/os-explorer/pull/14
