### ISSUE TITLE
OS packager UX: clear instructions after saving data package has failed

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1283]
Just had a case when saving the json data package failed (due to faulty metadata description), but the 
csv was apparently ready. 

There are no clear instructions or options offered for the user what to do next in such a case. 
Go back to the metadata description? Start the upload process again?
 
<img width="1427" alt="bildschirmfoto 2017-06-14 um 10 21 49" src="https://user-images.githubusercontent.com/21264753/27122818-1fa5650a-50ec-11e7-9180-da8b92e7b886.png">
<img width="1438" alt="bildschirmfoto 2017-06-14 um 10 21 37" src="https://user-images.githubusercontent.com/21264753/27122819-1fa8a364-50ec-11e7-84e8-cb2e06ec1b57.png">

Of course we can click Step 3 to - in this case - go back to the metadata description and correct it.
And then click safe data package again. this is only after trying out.

**Comment by pwalsh** [comment]
@akariv can you reproduce this? Can we do something along the ones of what @DianaMPG suggests?

**Comment by akariv** [comment]
Problem was that validation flow was broken, thus this schema error was not caught in phase 3.
Fixed via https://github.com/openspending/os-packager/commit/b8b34994fdf38936952cead3e3503f4ba99accff
