### ISSUE TITLE
Logging in on Explorer only works once

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1285]
# Steps to reproduce

1. Go to https://next.openspending.org/explorer/
1. Click on the "Login / Register" link in the top right. This should log you in.
1. As a logged in user, log out using the links in the top right. The text should become "Login / Register" again.
1. Click on the "Login / Register" again. We expect to be able to log in again, but nothing happens.

# Potential culprit

The `LoginService` login() method checks if the login `href` is set at https://github.com/openspending/os-explorer/blob/f96bf7e2850e03e5da41dd8ce082fb2b82bd64cf/app/scripts/services/login/index.js#L77. This `href` is set by check() in the same file (see https://github.com/openspending/os-explorer/blob/f96bf7e2850e03e5da41dd8ce082fb2b82bd64cf/app/scripts/services/login/index.js#L71), when the login isn't successful. When the login is successful, it's never set, so you're unable to login again.

**Comment by akariv** [comment]
IIRC this had been fixed in the viewer/packager, but I guess the fix wasn't
propagated to explorer.

**Comment by pwalsh** [comment]
@akariv can you please fix this.

**Comment by akariv** [comment]
Fixed via https://github.com/openspending/os-explorer/commit/026f78a9e3202dcd168a6b1b3bfe115d0d2c8b70
