### ISSUE TITLE
Extract our changes to bootstrap to "os-styles"

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1286]
We customized Twitter's Bootstrap by forking it into https://github.com/openspending/os-bootstrap and changing their code. This makes it hard for us to upgrade bootstrap, as our code is intertwined with theirs. As part of #1279, I created the https://github.com/openspending/os-styles repository to aggregate all our base stylesheets.

The end-goal is to have all stylesheets and their related assets (e.g. fonts) in a single repository, which is then loaded using `npm` into the projects that need it. The project-specific stylesheets will remain in their own repositories, but the base styles would be in `os-styles`. Part of this move is moving the code from `os-bootstrap` to `os-styles`, which requires us extracting our custom changes from bootstrap.

This issue involves extracting our custom code from `os-bootstrap` into `os-styles`, and importing `bootstrap` from `npm` to build what we have now.

**Comment by pwalsh** [comment]
@vitorbaptista do you have any idea how much time this could take?

**Comment by vitorbaptista** [comment]
@pwalsh It depends on how much we customized `os-bootstrap`, and how hard it'll be to extract our changes. My guess would be around a week.

**Comment by pwalsh** [comment]
Moving this to backlog.

@vitorbaptista @brew this will be a good one to pull out of backlog if we move through other things quickly enough.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2.5 years) as part of #1478. We are only migrating the data from OpenSpending to DataHub right now and the plan would be to merge the data into datahub.io, so this should not need further attention.

Please feel free to re-open if this is still relevant.
