### ISSUE TITLE
Add Google Analytics tracking to all next.* apps

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1291]
We are about to close down old OS, and replace with next (yes, really, finally). We need to install the tracking code for basic usage data. This needs to be installed for Packager, Viewer, Explorer.

**Comment by kravets-levko** [comment]
@pwalsh https://github.com/okfn/os-private-issues/issues/43

**Comment by pwalsh** [comment]
@kravets-levko yes, I thought I had tasked this! @akariv why don't we see this in production?

**Comment by kravets-levko** [comment]
it was implemented some time ago, and most likely is available on production. But it should be enabled in a config for each app.

**Comment by vitorbaptista** [comment]
@akariv Can we close this?

**Comment by akariv** [comment]
Yes, just need to make sure that the sites are indeed reporting to ga. I
don't have the creds to check.

**Comment by pwalsh** [comment]
everything is tracking except explorer, and the problem with explorer is captured in another open issue.
