### ISSUE TITLE
OS Packer build error from docker file

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1297]
Line 14 in [Dockerfile](https://github.com/openspending/openspending/blob/master/docker-config/os-packager/Dockerfile) should be `RUN cd app && npm run build`

**Comment by pwalsh** [comment]
@vitorbaptista can you check.

**Comment by vitorbaptista** [comment]
@liyakun Nice catch, thanks! @akariv Are those Dockerfiles still used? I'm asking because I thought we used https://github.com/openspending/os-packager/blob/master/Dockerfile for `os-packager`, for example.

**Comment by akariv** [comment]
Yes, these docker files are obsolete, we should remove them.
We're now using the Docker files in each of the repositories.

**Comment by vitorbaptista** [comment]
@akariv Does this mean we can safely remove all of https://github.com/openspending/openspending/tree/master/docker-config ?

**Comment by akariv** [comment]
I believe that we can remove most of it.
I'd like to keep the docker compose files for running the system locally,
but these need to be adjusted as they might have gone outdated in the past
months.

**Comment by pwalsh** [comment]
This issue can be closed, but @akariv we really need you to approve or review #1320

**Comment by akariv** [comment]
@pwalsh @vitorbaptista I reviewed #1320 - while the Dockerfiles were indeed removed, a lot of other stuff was removed as well - including everything related to the development environment.

If we want to allow people to run this environment locally, we will need to update the docker-compose files, based on the current deployment, so that it's back up again.

**Comment by pwalsh** [comment]
@akariv how do we know exactly what can be removed, and what can't? Reassigning to @brew

**Comment by akariv** [comment]
I marked the important stuff in the PR.

**Comment by pwalsh** [comment]
Closing. The original issue refers to a docker file no longer in use. see: https://github.com/openspending/os-packager/blob/master/Dockerfile
