### ISSUE TITLE
OS Viewer: Donut chart visualization

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1298]
Relates to #1197

**Comment by pwalsh** [comment]
@vitorbaptista this is still assigned to you. If work needs to be done, can you provide a description of the work, and, reassign to @brew

**Comment by vitorbaptista** [comment]
Nothing was done here. To fix this task, you'll need to add a new donut chart visualization. Maybe the same library that does the pie chart is able to do a donut chart, so it would require minimal code. If that's not the case, and we require a new library to do a donut chart, I wouldn't do it.

A donut chart has the same use as a pie chart (showing parts-to-whole). Some implementations differentiate the two by adding information in the empty space inside the donut, like:

![sample donut chart](https://user-images.githubusercontent.com/76945/34668117-d2700be8-f463-11e7-83cb-7c58f79e3e0a.png)

But that's not enough to justify adding a new library IMHO.

**Comment by pwalsh** [comment]
We are using C3 I think, so this should be easy then:

http://c3js.org/samples/chart_donut.html
