### ISSUE TITLE
Aggregate summaries are simply the first row of the results

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1299]
For example, see https://openspending.org/api/3/cubes/boost:boost-moldova-2005-2014/aggregate?cut=date_2.year:2014&drilldown=functional_classification_2.func1&order=adjusted.sum:desc&pagesize=30. The important parts are:

```javascript
{
  total_cell_count: 21,
  cells: [
    {
      "functional_classification_2.func1": "10 Social care and social insurance",
      "_count": 12627,
      "executed.sum": 17997007015.29,
      "approved.sum": 18133884900,
      "adjusted.sum": 18499833884.5
    },
    // ...
  ],
  summary: {
      // Note that this is the same as cells[0]
      "functional_classification_2.func1": "10 Social care and social insurance",
      "_count": 12627,
      "executed.sum": 17997007015.29,
      "approved.sum": 18133884900,
      "adjusted.sum": 18499833884.5
  }
  // ...
}
```

This seem to be a bug introduced by https://github.com/openspending/babbage/commit/08d331702ff9590af4b0ccdd70b3f87fa73e2cc4#diff-f075de08403be9696f33acb4efb640ac. Specifically where it moves the `summary` variable to the last lines of `aggregate()`. As we change the query `q` as we go through the code, we're potentially getting a different `summary` value than what we did before.

This bug also breaks our pie charts, as we use the summary values to calculate the "Others" slice on pie charts with more than 5 categories.

**Comment by vitorbaptista** [comment]
I added a sample test case that shows this bug on https://github.com/openspending/babbage/pull/27. @akariv I wasn't able to fix it because I don't understand the optimizations you've done on https://github.com/openspending/babbage/commit/08d331702ff9590af4b0ccdd70b3f87fa73e2cc4#diff-f075de08403be9696f33acb4efb640ac. Could you take a look?

**Comment by akariv** [comment]
I'm leaving this branch with a probable fix - could you please take a look
to see if it helps?

**Comment by akariv** [comment]
`fix/restore-summary-row` is the name of the branch

**Comment by vitorbaptista** [comment]
@akariv That worked :v:
