### ISSUE TITLE
Fix os-api build

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1301]
Master is failing since https://github.com/openspending/os-api/commit/a30fdea204e5517a06d4a0ae42aadf4ba7652427 was merged (see https://travis-ci.org/openspending/os-api/builds/261508270). The problem seems to that we forgot to commit the `tested-ok.txt` file.

/cc @akariv

**Comment by pwalsh** [comment]
@akariv please :)

**Comment by brew** [comment]
Fixed by openspending/os-api@65615dff6914134182b64561e1a96c7d810c2b5a and openspending/os-api@4f3b5d5281d13a3e3ad62011c96d72c168bc5e29
