### ISSUE TITLE
Explore integration of tools from Open Knowledge Greece into core

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1304]
@cbratsas @larjohn

Lazarus, can you provide a brief overview about the current tools (KPIs, Indigo) so we can explore how we can integrate into the OpenSpending platform directly, over time. Having a brief overview of each tool may also be useful for the community and we can see if there is any more general interest out there.

For each tool, something like:

- Name
- Short description
- Use case(s)
- Babbage API compatibility (e.g.: 80%, 95%)

**Comment by pwalsh** [comment]
@larjohn as requested, I assigned to you.

**Comment by pwalsh** [comment]
@cbratsas @larjohn I'm happy to discuss this any time. For now, it is on our backlog.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~3 years) as part of #1478. Please feel free to re-open if this is still relevant.
