### ISSUE TITLE
Fix links in footer of OpenSpending homepage

### ISSUE THREAD

**Issue by StephenAbbott** [openspending/openspending#1306]
Following images/logos in footer of OS homepage do not link. Add links to logos:

• OS Packager = https://openspending.org/packager/
• OS Viewer = https://openspending.org/s/
• Adessium Foundation = http://www.adessium.org/
• GIFT = http://www.fiscaltransparency.net/
• Hewlett Foundation = http://www.hewlett.org/
• OpenBudgets.eu = http://openbudgets.eu/

**Comment by pwalsh** [comment]
@brew can you jump on this one first please.
