### ISSUE TITLE
Explorer can't access the environment variables

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1311]
The issue is that the Explorer is a frontend app, so it only have access to the env variables when it's being built. Unfortunately, this would mean that a container would have the configuration built-in, so we can't reuse it among staging and production, for example.

This is the reason that the Explorer doesn't have the Google Analytics code set, and search results in https://staging.openspending.org/s/ link to the datasets in https://openspending.org.

I started working on this on https://github.com/openspending/os-explorer/pull/19, but couldn't find a solution yet.

**Comment by pwalsh** [comment]
@vitorbaptista this is the exact, and only, reason the other apps on OS, and, other frontend apps at OKI, run in a light Node shell - to be able to configure with environment variables.

**Comment by brew** [comment]
This needs to be solved as part of #1333. Apps like os-admin create urls with openspending.org domain regardless of the base url env var.
