### ISSUE TITLE
Update code for Fiscal Data Package v1 support

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#1314]
# Description

We have a CLI, and other code that implements support for Fiscal Data Package (there are several [open issues](https://github.com/openspending/openspending/milestone/38) for the CLI, which may be related to work that happens here). This code needs to support v1 of the spec, and, needs a compatibility layer to convert v0.3 to v1 ([required for this](https://github.com/openspending/openspending/issues/1256)).

# Tasks

- [x] Identify all relevant code paths / libraries
- [x] Update all

**Comment by akariv** [comment]
The places that touch the data package, modify it or parse it are:
- os-packager (when creating a datapackage)
- os-packager also uses os-types internally (to create the model and get information about the types)
- os-packager also parses a package in edit mode
- os-conductor (and dpp-fiscal) read a package and then create a new one
- os-viewer reads the package to show stuff correctly to the user
- os-admin and os-explorer possibly use some properties from the package as well

My suggestion is for OS to create dual-version packages - i.e. packages that are v0.3 compliant (with the OpenSpending custom properties, as is today), and add to them the required properties to make them compliant with v1.
This will allow most of the current code to remain unchanged, as it will continue to see the same package structure it's currently seeing.

The main places that will need to be updated are:
- os-types - for adding the new properties to the schema and for making sure that the list of allowed types is compliant with the one in the standard
- dpp-fiscal - for possibly adding some required metadata to the datapackage itself

**Comment by brew** [comment]
To expand on what Adam says above, some notes...

The main change we are concerned with as the FDP spec moves from v0.3 to [v1](https://github.com/frictionlessdata/specs/blob/master/specs/fiscal-data-package.md), is where fiscal modeling concepts are defined. It has moved from a dedicated top-level `models` property, to a `columnType` property on each field in the resource schema. Additionally, some of the `types` have changed (as defined in [`os-types`](https://github.com/openspending/os-types) lib).


### Create new datapackage with os-packager

An inital package is created with os-packager, using [`os-types.fieldsToModel()`](https://github.com/openspending/os-types/blob/1865584ff87d4953c09bf4990b39b852c4d3081a/src/index.js#L273) to build the `model` property and resource schema. We'll want to change the basic package os-types creates to remove the `model` property and write the equivalent `columnType` property to the resource schema instead. This is consumed, and rearranged by the [`app/services/package.createFiscalDataPackage`](https://github.com/openspending/os-packager/blob/907882fcbf2d85e280919c127c52027471c405c1/app/services/package.js#L103) method in os-packager. We can either change the results returned from os-types, or change the resultant FDP in the `createFiscalDataPackage` method. We'll probably have to do a little of both.


### Datapackages created with os-conductor/os-data-importers and datapackage-pipelines-fiscal

When a resource is uploaded to OpenSpending, datapackages are built and stored in a datastore (AWS S3 at present), ElasticSearch, and resource data itself in a Postgres database. This is all accomplished by the [datapackage-pipelines-fiscal](https://github.com/openspending/datapackage-pipelines-fiscal) lib, either as part of a call from os-packager to os-conductor, which builds up a [`fiscal.source-spec.yaml`](https://github.com/openspending/os-conductor/blob/40dec2b5d71f5bdd9a1b5e145b647ed4404ccf7e/conductor/blueprints/package/controllers.py#L128) definition for the dpp-fiscal pipeline, or directly from [os-data-importers](https://github.com/openspending/os-data-importers) using predefined static `fiscal.source-spec.yaml` files (e.g. for [Mexico](https://github.com/openspending/os-data-importers/blob/e8aa1a42950b0434c12841eca6464210c12c8e6a/america/mexico/fiscal.source-spec.yaml)).

Again, os-types is used to create an initial datapackage structure in the dpp-fiscal [`model`](https://github.com/openspending/datapackage-pipelines-fiscal/blob/0f07f7032b6255c086c94e0ea072708c725ce197/datapackage_pipelines_fiscal/processors/model.py) processor, as part of the [`denormalized`](https://github.com/openspending/datapackage-pipelines-fiscal/blob/0f07f7032b6255c086c94e0ea072708c725ce197/datapackage_pipelines_fiscal/flows/denormalized.py#L170) pipeline flow.


### Edit existing datapackage

Handled by os-packager which takes an existing datapackage origin url (from the datastore), and loads it using the [`app/services/package.loadFiscalDataPackage`](https://github.com/openspending/os-packager/blob/907882fcbf2d85e280919c127c52027471c405c1/app/services/package.js#L228) and other supporting methods for loading resources. Adjustments in this area are needed to support FDP v1 while continuing to be able to read v0.3 formatted datapackages.

Editing a v0.3 datapackage and subsequently saving it will automatically upgrade it to FDP v1.


### Reading datapackages

Several apps read datapackage metadata from ElasticSearch, including os-admin and os-explorer. These apps both use calls to os-conductor, which itself uses [os-package-registry](https://github.com/openspending/os-package-registry) to return results from ElasticSearch. I don't think anything other than datapackage metadata is required by these apps and no adjustsments should be necessary to support FDP v1.

os-viewer makes extensive use of [os-api](https://github.com/openspending/os-api) (and hence os-package-registry (ElasticSearch) and [babbage](https://github.com/openspending/babbage) (Postgres)) to request and return datapackage metadata and resource data to drive babbage.ui visualisations.

A little confusingly, babbage cube concepts and FDP model concepts share similar nomenclature. i.e. Models, Measures, and Dimensions. While these are general kept separate, there is some object merging when the viewer loads the datapackage, e.g. in [`data-package-api.createPackageModel`](https://github.com/openspending/os-viewer/blob/c9cbd9640b2e97f7b67045a2b697ec5ab70399af/app/front/scripts/services/data-package-api/index.js#L366) where measures and dimensions are defined for babbage. This will potentially need updating to support FDP v1.

**Comment by brew** [comment]
Dear reviewer,

There are two main changes to bring Open Spending up to FDPv1 spec:

1) Changing the resource schema property `osType` to `columnType`
2) Updating fiscal model field types to reflect FDPv1 [budget taxonomies](https://github.com/frictionlessdata/specs/blob/464ea60e17fbd41ea73f9501b63e4bb6977a2b93/specs/fiscal-data-package--budgets.md)  

Here are the PRs for the four repositories that implement these changes:

- os-types: https://github.com/openspending/os-types/pull/9
- os-conductor: https://github.com/openspending/os-conductor/pull/37
- os-packager: https://github.com/openspending/os-packager/pull/122
- datapackage-pipelines-fiscal: https://github.com/openspending/datapackage-pipelines-fiscal/pull/13

os-types and datapackage-pipelines-fiscal are dependencies of os-conductor and os-packager. They are currently released as pre-release versions, and all app have been deployed to staging.openspending.org for review. Once review is complete, I'll release proper versions and update relevant dependencies.

To do:

- update the os-data-importer `fiscal.spec.yaml` definitions with updated fiscal field types

**Comment by brew** [comment]
@akariv Can you review the changes detailed in the above comment?

**Comment by akariv** [comment]
@brew sure, on it.

**Comment by akariv** [comment]
Done @brew, great work!

**Comment by brew** [comment]
Thanks!

**Comment by brew** [comment]
This is done and deployed.
