### ISSUE TITLE
Add client-side validation for the datapackage identifier

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1317]
When uploading a new dataset via the packager, we need to pick a unique identifier on the 3rd step. This has to be lowercase only, numbers, letters, and `-`, `_` or `.`. However, we only validate it in the backend, so if the user picks an invalid name, she'll only otice after his upload fails. Worse, with a cryptic Python traceback.

To make it friendlier, we should validate in the frontend as well.

**Comment by brew** [comment]
There is 'as you type' validation for the unique identifier:

<img width="987" alt="screenshot 2019-03-04 at 11 34 03" src="https://user-images.githubusercontent.com/3993/53731068-8bd92080-3e71-11e9-8eb8-7e99c9dea079.png">
