### ISSUE TITLE
Set minimum bar chart height

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1321]
Depending on the scale of the bar chart, it can end with height 0 (i.e. invisble). That should never happen.

**Comment by brew** [comment]
@vitorbaptista Could you explain this a little more? When you say it should never happen, what should happen instead?

**Comment by vitorbaptista** [comment]
@brew Imagine we have 2 bars with values 1000000000 and 1000. The second one is so small that, in the scale, it ends up having height 0. This means that the user can't hover on it, click on it, or anything. Instead, the bars should have a minimum height, so instead of 0 the height would be 1, 5, or whatever looks better.

**Comment by brew** [comment]
This isn't easily achievable within C3 (which babbage.ui uses). No mechanism is provided to ensure a minimum height, without changing the underlying data, which would be more misleading (https://github.com/c3js/c3/issues/1935).

Currently, the tooltip displaying the data value is easily available for each bar, so it is possible to see these values.

Logarithmic plots are another possibility, but again, aren't currently supported within C3, without changing the underlying data values (https://github.com/c3js/c3/issues/252).

**Comment by vitorbaptista** [comment]
@brew What about using CSS? There's a `min-height` property that might solve this.

**Comment by brew** [comment]
I looked into using `min-height`, `height` and a few other CSS options, but nothing like that seemed to work.

**Comment by pwalsh** [comment]
As noted in https://github.com/openspending/openspending/issues/1321#issuecomment-352028681 we have a hard technical limitation with this. Can't fix, closing.
