### ISSUE TITLE
Bubble tree can't show negative values

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1322]
On https://github.com/openspending/os-viewer/pull/165, I implemented a feature to change the bubble's colour depending if they were negative or positive. However, bubbletree itself doesn't support it (see https://github.com/okfn/bubbletree/blob/daf73591476eabbc94a3ef95ea45e3854646e59b/src/js/bubbletree.js#L146 and https://github.com/openspending/babbage.ui/blob/2905409f26108ff859f925e5e2481fce8acd0b8e/src/components/bubbletree/index.js#L51-L55).

**Comment by pwalsh** [comment]
Relates to #1319

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~3 years) as part of #1478. Related issue #1319 has not received attention either. Please feel free to re-open if this is still relevant.
