### ISSUE TITLE
Updating data package not working

### ISSUE THREAD

**Issue by michaeljokf** [openspending/openspending#1323]
I am having trouble updating an existing datapackage that is already stored on OS next. 
I wanted to change a column mapping. Went to "edit" datapackage and updated the column and saved the dataset. I then checked in the OS admin page to see that if it updated (it did, due to new time and the changed "private setting").
When I look in the viewer I can see that the column mappings did not change. Furthermore, if I click back onto "edit" again, the original mapping appears and I can see that the changes did not process. 
I tried this three times this morning. It did not work for:
my id: a6a16b964a7e784f99adecc47f26318a 
dataset: moers-no-negative

**Comment by pwalsh** [comment]
@akariv can you please check this.

**Comment by vitorbaptista** [comment]
I was able to reproduce this. My steps were:

1. Go to the admin page
1. Edit one of my datasets
1. Change one of its column's DataTypes
1. Proceed and save the new dataset

After I received the success message, I went back to the admin page to edit the same dataset, and its DataType wasn't changed. It was the same as before.

**Comment by akariv** [comment]
I'm trying now to reproduce this issue by following both @michaeljokf and @vitorbaptista 's steps but without success.
Can either one of you please try to reproduce and see it the problem persists?

**Comment by michaeljokf** [comment]
I thought that @vitorbaptista had fixed it?! It was working again in December and I used it quite a lot! Will let you know if it stops working at some point...
