### ISSUE TITLE
[Discuss] Fix link to datasets in the old OpenSpending

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1324]
For example, https://openspending.org/big-lottery-fund-grants doesn't work, while https://legacy.openspending.org/big-lottery-fund-grants does.

Per @rufuspollock:
> Is there any way to fix this? It is quite a big deal to lose all those links and all the associated googlejuice, plus web breakage? I'd imagine that just getting a list of all the old datasets and implementing a simple lookup and redirect would be pretty easy (?)

There are basically two strategies to develop this: importing the data into OpenSpending Next, or redirecting to the legacy OpenSpending:

* Redirecting to legacy OpenSpending
    This could be done relatively easily (1~2 days), even if only via a lookup list as @rufuspollock suggested. However, this is a short term solution, as it requires us to keep running the legacy OpenSpending. We're already running it to support the old API anyway (see https://github.com/openspending/openspending/issues/1303), so this is OK, even though it just buys us some time (we'll still have to deal with the issue later).
* Importing the data into OpenSpending Next
    I don't know how complex this would be, and we would still have to add a few redirects, as the routes have changed, but this is the only long-term solution to keep the data.

We also don't know how many people are trying to access the old datasets, so we can't measure how many people are impacted by the current state.

@akariv @pwalsh @DianaMPG Thoughts?

**Comment by rufuspollock** [comment]
@vitorbaptista did we not import the old data across in the end then?

**Comment by pwalsh** [comment]
The old data should be in OS Next.

@akariv please let us know what your recommendation is here.

**Comment by akariv** [comment]
Once the data is in OS, we can add redirects to OS-Viewer for each of these urls.
Before that, we can add redirects to the legacy server.
It shouldn't take more that a few hours work.
