### ISSUE TITLE
OS-viewer doesn't work

### ISSUE THREAD

**Issue by hantongliu** [openspending/openspending#1325]
Hi @pwalsh , OS-viewer doesn't work properly today. It shows a 503 error when requesting this url: http://cors-anywhere.herokuapp.com/next.openspending.org/user/check?next=http:%2F%2Fapps.openbudgets.eu%2Fviewer%2Faragon-2007-income__3209b

**Comment by pwalsh** [comment]
@akariv @vitorbaptista 

Can someone please confirm, deny, fix, or close this issue. Thx.

**Comment by vitorbaptista** [comment]
@hantongliu I'm not sure about the `cors-anywhere.herokuapp.com`, but vising the OpenSpending page directly is working, https://next.openspending.org/user/check?next=http:%2F%2Fapps.openbudgets.eu%2Fviewer%2Faragon-2007-income__3209b.

I'm closing this issue, as it appears to have been an intermittent problem. Please reopen it if you're still seeing this problem.
