### ISSUE TITLE
OS-Viewer HTTPS error when deployed on OBEU server

### ISSUE THREAD

**Issue by pierorex** [openspending/openspending#1327]
I'm receiving this error from os-viewer
![os-viewer-https-error](https://user-images.githubusercontent.com/9373636/32723899-75b48052-c86f-11e7-930d-dfa0cd012a20.png)

It says there's a resource being loaded by HTTP internally, which blocks the HTTPS loading of the site.

Original error message:
> Mixed Content: The page at 'https://apps.openbudgets.eu/viewer/embed/bonn-budget-exp-2017__6b525?lang=de&theme=None&visualizations=Treemap&groups%5B%5D=currency.currency&measure=amount.sum' was loaded over HTTPS, but requested an insecure script 'http://apps.openbudgets.eu/user/lib'. This request has been blocked; the content must be served over HTTPS.

**Comment by pwalsh** [comment]
@pierorex looks like a config issue on the OBEU server. Check all your env vars for anything that points to an http:// base.

https://github.com/openspending/os-viewer/blob/master/app/config/index.js
