### ISSUE TITLE
Negative Numbers in OS

### ISSUE THREAD

**Issue by michaeljokf** [openspending/openspending#1328]
I still do not completely understand what OS does with negative numbers. I have always assumed they are just summed up when the aggregation happens on the higher level. 
It is the case for Germany (and probably other countries) that expenditures are not necessarily just negative or just positive but can include both cases (similarly for revenues). Is this considered? 

And why does the Treemap not seem to work for negative numbers? If you select "Einnahmen", "2017" and "Administrative Classification" for this: id: a6a16b964a7e784f99adecc47f26318a dataset: moers-negative 
This is what I am looking at: https://openspending.org/viewer/a6a16b964a7e784f99adecc47f26318a:moers-negative?measure=%22Betrag.sum%22&groups%5B%5D=%22administrative_classification_2.Ebene1%22&filters%5Bdate_2.Jahr%5D%5B%5D=2017&filters%5Bdirection_2.HH_Art%5D%5B%5D=%22Einnahmen%22&order=%22Betrag.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en 

The treemap breaks down and does not work for negative numbers. Does this suggest that I would have to change the algebraic sign? So turn all - into + and other way around? That would lead to the right result.

Is this how OS is intended? or did I make a mistake along the way?

**Comment by vitorbaptista** [comment]
@michaeljokf Visualizations like the treemap and pie charts don't work when there are mixed negative and positive values. Please check https://github.com/openspending/openspending/issues/1319#issuecomment-328057649 for an explanation on why.

Right now, these visualizations only correctly for datasets with only positive values. On #1319 we're thinking on how to make them also work for negative-only values, but there's no ETA on that. In the meantime, you can either change your data to contain only positive values, or use another visualization (e.g. bar charts).

I'm closing this issue, but please feel free to add your thoughts to #1319 or ping me on https://gitter.im/openspending/chat.

**Comment by michaeljokf** [comment]
thank you Vitor! I appreciate the info and will look at the other tread!
