### ISSUE TITLE
Duplicates Validation Packager

### ISSUE THREAD

**Issue by michaeljokf** [openspending/openspending#1330]
I am attaching a screenshot. How does OS deal with intended duplicates? What you have right now does not allow for ANY duplicates. I do not see how this behavior makes sense. Have you had this for a while? If you have budget data on a lower level (more like spending data) then it will often happen that you have the same bookings with the same amount... 
In my opinion there should only be a "warning" that the dataset includes duplicates and not prohibiting you from uploading it completely...
![screenshot 2017-12-01 13 12 58](https://user-images.githubusercontent.com/22743376/33482613-3634659e-d69a-11e7-88dc-96a852f7b1d7.png)

**Comment by michaeljokf** [comment]
Having this issue again today and I am not sure this is how OpenSpending should be working. Again it is nice to be warned about duplicates, but why does OS not allow for any duplicate lines to be read into the data? Do I need to add an budget line ID for the data so that the line varies? I guess that is the easiest fix?!

![screenshot 2018-01-25 17 17 26](https://user-images.githubusercontent.com/22743376/35399140-e39fbaf6-01f3-11e8-9468-366b9bad119e.png)

**Comment by akariv** [comment]
Yes, at the moment each line needs to be uniquely identifiable and referrable.
Even for spending data, having multiple payments for the same account, still usually contain some sort of transaction id (or even timestamp).
If these are not available, then adding a unique line id is the current solution.

In the future, we might add an automatic fix for duplicate lines, summing them together to a single aggregated line.

**Comment by michaeljokf** [comment]
Ok, good to know! Really irritated me for a minute, but I guess it makes sense! Will just add an ID in case this comes up again. Thanks @akariv

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. The author of the issue has found a working solution. Please feel free to re-open if this is still relevant.
