### ISSUE TITLE
datapackage.json - Waiting in queue for an available processor

### ISSUE THREAD

**Issue by ralfthesing** [openspending/openspending#1336]
Hello, I want to save a budget on openspending. But I get the following message since yesterday (the process stops): datapackage.json - Waiting in queue for an available processor.

**Comment by akariv** [comment]
Thanks for reporting, I'll see what's wrong.

**Comment by florent-andre** [comment]
Same here for this datapackage : 
https://openspending.org/package/status?datapackage=https://s3.amazonaws.com:443/datastore.openspending.org/74ad33ef9a3354fe679b79fe4accff12/budget-assemblee-nationale-france/datapackage.json

Thanks.

**Comment by florent-andre** [comment]
ok, this was due to the same issue as here (underscore) : https://github.com/openspending/openspending/issues/1357

**Comment by brew** [comment]
Closed as a duplicate of #1367.
