### ISSUE TITLE
Datapackage publication failed

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#1337]
I am trying to upload a dataset and the publication process failed at the datapackage level.
Is there anything I need to do ?
What are the validation errors ?

<img width="1241" alt="capture d ecran 2018-01-25 a 12 23 31" src="https://user-images.githubusercontent.com/6681719/35386108-182fe044-01cb-11e8-8b94-dd70c964db1a.png">

**Comment by pwalsh** [comment]
hey @cecilaki !!

@akariv @vitorbaptista

**Comment by cecilaki** [comment]
hey @pwalsh :) yeah, I was super proud of my mapping ^^

**Comment by akariv** [comment]
@cecilaki thanks for reporting this - we need to add these validation errors to the error message here (otherwise it is a bit cryptic, I agree)

**Comment by cecilaki** [comment]
Indeed. Would be good to also include a message to know if some action is required on the user side as well.

**Comment by cecilaki** [comment]
Hi @akariv, any ETA for this issue?
