### ISSUE TITLE
Tidy up inclusion of os-auth-client libs by os-conductor

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1339]
Currently, the javascript auth client lib (https://github.com/openspending/os-auth-client) is generated locally, then manually copied to `os-conductor/conductor/blueprints/user/lib/lib.js`, where the python os-conductor flask app makes it available at the `/user/lib` endpoint. 

The endpoint is referenced by script tags in the html templates used by the various Open Spending apps (os-packager, os-viewer, os-explorer, os-admin) so the auth client actions become available for use by the angular applications. 

The `authenticate` and `authorize` services provided by the auth client are used in each app by a login service or factory (generally in the app's `scripts/services/login/index.js`).

A good reason to request the client lib from conductor, instead of including it as a dependency in each OS app, is so conductor can ensure the client lib is always compatible with conductor's own endpoints, as they are tightly coupled.

Instead of generating then copying over the compiled file to os-conductor manually, conductor should fetch the lib as a normal npm dependency and copy it across to the lib directory during build time.

Gulp is already used by os-conductor, so we could use it to manage the copying. However, this would further increase os-conductor's dependence on gulp, which conflicts with https://github.com/openspending/openspending/issues/1038 that suggests removing the node/gulp dependency entirely (as os-conductor is primarily a python application).

**Comment by DianaMPG** [comment]
@brew does this issue relate to OS Viewer enhancement for GIFT III phase

**Comment by brew** [comment]
Not specifically. I capture general issues as I encounter them so they don't get lost.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. This is about Phase III, Phase IV is already closed. Please feel free to re-open if this is still relevant.
