### ISSUE TITLE
Improve Docker support for easy in production install

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1340]
Currently we have some docker related files within https://github.com/openspending/openspending that aren't directly used for deployment of development, but for reference. These are unmaintained and not actively developed.

We also have a docker-cloud stackfile on docker-cloud used to manage the production deployment of the openspending platform.

As part of #1333, we intend to develop a clear, versioned, reusable and reproducible docker-compose script to create a Open Spending installation.

The docker-compose file will live in this repository and reference images hosted on docker hub. Individual application will manage their own Dockerfiles.

- [x] Tag application images to specific build hashes, don't use `latest`
- [x] Allow some apps to be optional (e.g. redash, sentry, datadog)
- [x] Improve each app Dockerfile to make better use of docker caching
- [x] Improve each app Dockerfile to reduce unversioned dependencies 
- [x] Document which env vars MUST, SHOULD and MAY be set
- [x] Document additional dependencies and how to specify them, such as postgresql, s3-like datastore - suitable warning if these aren't defined
- [x] Move all relevant static vars to env vars (e.g. os-admin has openspending.org urls hardcoded into a [config file](https://github.com/openspending/os-admin/blob/98804d7c09d356a0e22be482a3ec473bc5de44c1/config.js)).

Ideally the resultant docker-compose.yml could be the basis for the docker-cloud stackfile, but they aren't directly compatible, so we may need to maintain them separately.

**Comment by brew** [comment]
Several OS app require further work to make them amenable to being 'dockerized'. This includes updating each Dockerfile to make better use of caching, and remove use of git to clone apps. A consistent pattern for passing configuration settings from the environment to each Angular app, so service urls can be customised. Better handling of `authClient.services` and snippets loading (both rely on configuration settings being available).

- [ ] os-admin
- [ ] os-explorer
- [ ] os-packager
- [ ] os-viewer

**Comment by brew** [comment]
This issue is nearly finished. We have a strategy for deploying to Docker from successful travis builds, which I'd like to rollout across the major apps of the platform, and refer to specific Docker image tags in the docker-compose.base.yml file in this repository:

- [ ] os-explorer
- [x] os-viewer (https://github.com/openspending/os-viewer/pull/178)
- [ ] os-admin
- [ ] os-packager
- [ ] os-conductor
- [ ] os-api
- [ ] os-fdp-adapters

**Comment by pwalsh** [comment]
@brew can this now be closed?

**Comment by brew** [comment]
Yes. Any further improvements will be clarified when we get a chance to pilot it.
