### ISSUE TITLE
Problems with validation

### ISSUE THREAD

**Issue by Lunerock** [openspending/openspending#1343]
Hey

as u you can see in the screenshot, I got some problems with validating the data. Can you help or tell me, what I should do different please?

![image](https://user-images.githubusercontent.com/29628321/36662612-34577b92-1adf-11e8-819f-d36c519eec15.png)

**Comment by brew** [comment]
This issue is over a year old and doesn't provide sufficient information to investigate. Feel free to reopen if you continue to have this problem and can provide more details.
