### ISSUE TITLE
openspending/openspending.org repository

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1345]
Currently, the platform 'openspending' is synonymous with the website instance 'openspending.org'. We've been doing work to enable easy installation of the platform for development and production (#1340 and #1341), which has resulted in a clearer deployment strategy for the platform and a better distinction between the platform and .org site (#1344).

I'd like to further separate out the concerns of the platform and .org website by creating an `openspending/openspending.org` repository that makes use of the `openspending/openspending` docker strategy, but maintains the additional services and concerns of the openspending.org instance. I'd like the Nginx frontend application to be maintained there, along with the docker cloud stackfile, and for the https://github.com/openspending/os-nginx-frontend repository to be deprecated.

openspending.org is a little complicated by the fact we host with Docker Cloud, and its use of a docker-stack file rather than docker-compose. I don't want to pollute the platform repository with openspending.org specific implementation details.

WDYT @pwalsh @vitorbaptista @akariv ?

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. Please feel free to re-open if this is still relevant.
