### ISSUE TITLE
Redis persistence error intermittently  breaks os-api

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1347]
Redis is used as a key/value cache for API results by os-api (using the [os-api-cache](https://github.com/openspending/os-api-cache/) library).

Periodically, Redis is unable to persist RDB snapshots to disk and os-api is unable to server requests.

We can temporarily fix the issue by restarting the redis container.

By default, Redis will stop working if background saving of snapshots fail. This can be configured to allow Redis to continue working with:

> $ redis-cli
> config set stop-writes-on-bgsave-error no

Although this doesn't address the root cause.

https://sentry.io/open-knowledge/openspending-production/issues/435780505/

```
ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
(10 additional frame(s) were not displayed)
...
  File "os_api/cache.py", line 34, in return_cached
    response = cache.get_from_cache(package_id, o.query, o.path)
  File "os_api_cache/os_cache.py", line 19, in get_from_cache
    return super(OSCache, self).get(context, params)
  File "os_api_cache/base_cache.py", line 14, in get
    pickled = self._get(context, params)
  File "os_api_cache/redis_cache.py", line 29, in _get
    self.redis_connection.expire(key, self.timeout())

ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
```

**Comment by akariv** [comment]
We should go back to using Memcache for the cache, and remove redis from
the critical path here.

**Comment by brew** [comment]
We get this warning when rebooting the Redis server: 

`WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

I'll look into having the Dockerfile set this flag.

**Comment by brew** [comment]
And more info: https://redis.io/topics/faq#background-saving-fails-with-a-fork-error-under-linux-even-if-i-have-a-lot-of-free-ram

**Comment by brew** [comment]
This has been fixed by setting `sysctl vm.overcommit_memory=1` on our Docker host machines and restarting Redis.
