### ISSUE TITLE
Upgrade OS-Conductor boto dependency to boto3

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1348]
To support a broader range of S3 compatible object stores, such as [Minio](https://minio.io/), we would need to upgrade our python S3 library, boto2, to boto3. There are defaults that boto 2 uses that are incompatible with Minio. We would need to set config options, `signature_version='s3v4'` and `region_name='us-east-1'` (https://docs.minio.io/docs/how-to-use-aws-sdk-for-python-with-minio-server).

Method calls would need to be migrated from boto2 to boto3.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
