### ISSUE TITLE
Travis fails if PR isn't from origin due to failed Docker push

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1349]
Several of the apps in Open Spending build a Docker image and attempt to push it to docker hub if tests pass in Travis. Docker hub credentials are stored as encrypted env vars in the .travis.yml file associated with each repo. These [secure env vars aren't available for untrusted builds](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml), so the Travis run will fail at this point, even if tests pass. See comments here for further details: https://github.com/openspending/os-conductor/pull/30

Only build and push Docker images if the PR is from the origin repository.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. Please feel free to re-open if this is still relevant.
