### ISSUE TITLE
Open Spending Alert System 

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1351]
The Mexico Secretariat of Treasury and Public Credit team prepared the following analysis of the Alert system functionalities in the https://openspending.org/ website, and that are implemented at  https://status.openspending.org/.

The webpage has a Status module which is separated into the Platforms and Components that Open Spending users have. The Platforms section has: the webpage, API v2 and API v3; the Components section includes: Viewer, Packager and Admin. Each platform or component has attached to it its current status, which displays the last update date. 

The second module has a weblog that reports the incidents that have taken place, presented by date. 

Questions and suggestions

Could the Pipeline load be added to the Components’ section? If it is otherwise included in the Packager component, how can a Pipeline error be identified? 

The reason for this is that the team responsible for updating the Packager information uses that mean and sometimes the Pipeline does not show when its mal functioning, and it only stops the loading process. 

The Admin component: does it refer to the account created for the manual updating of data? Because, as they understand, that is the Packager. If this is not the case, to what component does it refer? 
The Alert System shows the date of the last updating of the platform or component, but it woudl be very useful to know abput the changes involved in the new version or update. (The request is not a detailed description of the update, butperhaps a link to the Github repository to verify in detail if this will affect in the data upload or in their own developments, such as the Treemap of the Programs page that uses the Open Spending API).

For the first module, they need a way to create a notification or report  as users of the  Open Spending tool, in case that they detect that it is not working well,  and for it to be addressed and solved. 

Similarly, given that the OS team carries out periodic updates following a self established calendar, Mexico requests implementing some sort of an early notification of upcoming updates, so that they can prevent situations where they need to use the platforms or components at a moment where OS has scheduled some web service cut or interruption due to updating. 

Mexico’s suggestions could be implemented in the second module, which has only one type of update and service status incident report log offered by Open Spending. That is where they believe the functionalities of this development could be expanded, aiming to have a timely communication about the status and updates of the platforms and components.

**Comment by brew** [comment]
There are four main tasks here:

1. Look into providing an addition endpoint for datapackage-pipelines dashboard that will return the success status of the last pipeline run as an HTTP status code. This can then be used by our CachetHQ status page setup to provide basic pipeline status reporting.

2. Use the existing status page system to provide notification for large changes that may affect the stability of the platform. We make regular changes to the platform, often daily, so advanced notice will only be provided for updates that are expected to cause downtime.

3. The 'Admin' part of the status page refers to https://openspending.org/admin, and the status provides an indication whether this section of the platform is available or not. The 'Packager' is technically a separate component, though the two are obviously related. 

4. Look into customising the status page to add a link to gitter and github issues page as a means for users to seek support and make the developers aware of issues.

**Comment by brew** [comment]
@jobarratt Possible actions for your review from the above:

1. Add datapackage-pipeline status as a component of the availability status page (status.openspending.org)

2. Add support contact details to head of status page.

3. Pro-actively use the status page to provide notifications for large changes that may affect platform availability or stability.

**Comment by brew** [comment]
The outstanding issue here was to provide pipeline status for the status page. Pipeline status is now available from the [os-source-specs](https://github.com/openspending/os-source-specs) repository. I think this can now be closed. WDYT @sandervdwaal ?

**Comment by sandervdwaal** [comment]
I agree - if there are more specific requests we will open a new issue.
