### ISSUE TITLE
Field "id" can't cast value "1" for type "string" with format "default"

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1352]
I tried to upload a csv dataset into openspending platform,  the dataset is similar with [Merzenich](https://openspending.org/viewer/6c38343baba9d47c1b8efedff36836c4:merzenich1?lang=en). Then the following error was thrown.

> Field "id" can't cast value "1" for type "string" with format "default"

The above error seems to be related with the configuration at [config.py](https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/config.py).

**Comment by brew** [comment]
Fixed by https://github.com/openspending/os-conductor/pull/33.
