### ISSUE TITLE
Multiple fields within one package file

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1355]
@akariv I have uploaded one csv file [iri_test](https://openspending.org/viewer/5537104a902b0847bb7b474225eced5a:iri_test?lang=en) on 2nd-May-2018 which contains exactly the same data with the csv file I uploaded [packtest](https://openspending.org/viewer/5537104a902b0847bb7b474225eced5a:packtest?lang=en) before that. However, the generated package files [iri_test_package](https://datastore.openspending.org/5537104a902b0847bb7b474225eced5a/iri_test/final/datapackage.json) [packtest_package](https://s3.amazonaws.com/datastore.openspending.org/5537104a902b0847bb7b474225eced5a/packtest/datapackage.json) contains different information.

I am not sure whether this is an issue, but the generated [iri_test_package](https://datastore.openspending.org/5537104a902b0847bb7b474225eced5a/iri_test/final/datapackage.json) file does contain some information that I am not expected.

Could you give me some information why this happened? Thank you very much!

**Comment by akariv** [comment]
Hey @liyakun -

What's the different information that you've encountered that's was unexpected?

**Comment by liyakun** [comment]
@akariv Thanks for your quick reply. It seems that the package file also keeps information from "example-data__2016.csv", "example-data__2017.csv" and "example-data__2018.csv". I think that they might be the files split from the original file by "year", but I am not sure.

**Comment by akariv** [comment]
Yes, these resources are automatically added for source data that spans over more than one fiscal year.

**Comment by liyakun** [comment]
Is this feature newly added to the package file? It seems that if there is only one fiscal year, there is also a duplication of it, for example [recenter_2017](https://datastore.openspending.org/5537104a902b0847bb7b474225eced5a/recenter_2017/final/datapackage.json). Is it possible to avoid this? Thanks.

**Comment by liyakun** [comment]
@akariv Is there a documentation about how the newest package file works? For example, if there is at least two csv files in each package file, does it mean that there are actually two seperate csv files split from the original uploaded file? 

I am asking this because the new package file causes the failure of the pipeline. Thanks.
