### ISSUE TITLE
'Save as default' shouldn't appear for non-logged-in users

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1358]
<img width="515" alt="screen shot 2018-05-20 at 8 41 30" src="https://user-images.githubusercontent.com/265333/40276110-f341b5ca-5c09-11e8-94f7-5e482f392e07.png">

**Comment by brew** [comment]
Fixed by https://github.com/openspending/os-viewer/commit/be6b5b6886859da3214b9832af87240d99d54eae
