### ISSUE TITLE
small decimal returned when integers were uploaded

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1360]
The 2014 actual expenditure (audited outcome) for Transport department is expected to be  49147098000 :

[estimates-of-national-expenditure-south-africa-2017-18-fraction-test.xlsx](https://github.com/openspending/openspending/files/2045094/estimates-of-national-expenditure-south-africa-2017-18-fraction-test.xlsx)

but the API returns 49147098000.00001:

https://openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a:estimates-of-national-expenditure-south-africa-2017-18/aggregate/?drilldown=financial_year.financial_year%7Cbudget_phase.budget_phase&cut=vote_number.department%3A%22Transport%22&pagesize=300

**Comment by jbothma** [comment]
This isn't super urgent for me but might might indicate a problem with using floats instead of decimals somewhere.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
