### ISSUE TITLE
Error: Failed to load package data

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1361]
Hi, I was trying to upload a csv file which is about 64.4Mb, and it contains 413839 rows including the header. 

It took about an hour to load data, and then an error was thrown as follows:

![image](https://user-images.githubusercontent.com/7370334/40618951-78e72a90-6293-11e8-9110-8cd6fce432b1.png)

But it seems that the package file was already available at [package.json](https://datastore.openspending.org/5537104a902b0847bb7b474225eced5a/bonn2017kdvzslim/final/datapackage.json). 

Could you have a look? Thanks.

**Comment by brew** [comment]
This is very likely the same issue as #1367, which should now by fixed.
