### ISSUE TITLE
visualizations don't work

### ISSUE THREAD

**Issue by florent-andre** [openspending/openspending#1363]
Actually this type of visualizations says "no data to display", but data come back from request : 
- pie chart
- donnut chart
- bar chart
- line chart

For example : 
https://openspending.org/viewer/74ad33ef9a3354fe679b79fe4accff12:budget_mairie18?measure=%22Mandate_Titre_apres_regul.sum%22&visualizations%5B%5D=%22LineChart%22&lang=en

**Comment by jbothma** [comment]
Not sure if it's the same issue, but it's not clear why the bar chart has nothing to show here but the other options do https://openspending.org/viewer/b9d2af843f3a7ca223eea07fb608e62a:estimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes?measure=%22value.sum%22&groups%5B%5D=%22programme_number.programme_number%22&series%5B%5D=%22economic_classification_2.economic_classification_2%22&filters%5Bdepartment.department%5D%5B%5D=%22Agriculture%22&filters%5Bfinancial_year.financial_year%5D%5B%5D=2018&order=%22value.sum%7Cdesc%22&visualizations%5B%5D=%22BarChart%22&visualizations%5B%5D=%22Table%22&visualizations%5B%5D=%22Radar%22&lang=en

**Comment by brew** [comment]
@florent-andre @jbothma Thank you both. This should now be fixed.
