### ISSUE TITLE
Partial package stored in Elasticsearch

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1366]
os-explorer search was [reported as broken](https://gitter.im/openspending/chat?at=5b30a71d960fcd4eb920d3ff). This was due to a partially complete package in Elasticsearch which was missing the `package` property, required by the result parsing code. 

A fix was written to check each package and filter out results without a `package` property (https://github.com/openspending/os-explorer/commit/f439a9e8f64b4201fe972ace43b4796dbb3daa12). 

While this fixes the immediate issue, it doesn't address why a partial complete Elasticsearch package entry was created in the first place. One possibility is that a basic entry is created, then updated with full information during the upload process. If this process is interrupted, the partial entry remains.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
