### ISSUE TITLE
Ensure package index can be recreated from S3 datastore

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1369]
We rely on the ElasticSearch packages index for correct functionality of Open Spending. While theoretically this can be recreated from the AWS datastore (which is considered the source of truth for the application), we should ensure this is possible, both in practise, and in a timely manner.

- [ ] A script to validate `packages` index in ElasticSearch against AWS datastore datapackages.
- [ ] A script to recreate `packages` index in ElasticSearch against AWS datastore datapackages.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
