### ISSUE TITLE
Combine frontend micro-services

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1370]
Open Spending frontend applications are separated into a micro-services architecture, with network communication between each service using HTTP APIs. While this theoretically allows decoupling of services and potentialyl rapid development iteration, in practise, this has led to losing functional and visual cohesion across the application, and repetition of common services.

By combining them into one frontend application, we would aim to:

- simplify development
- ensure a coherent visual identity across each app
- communicate directly between each app using APIs
- share common services frameworks (similar AngularJS services are currently replicated across apps)

Application candidates for this:

- os-packager (datapackage uploader)
- os-admin (user package list)
- os-explorer (home page and search)
- os-viewer (package detail and visualisation)

We would still want to ensure a separation of concerns along the same lines as currently exist.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. Data will be migrated to the DataHub.io platform. Please feel free to re-open if this is still relevant.
