### ISSUE TITLE
Combine backend micro-services

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1371]
Open Spending backend services are separate python Flask applications, communicating via network APIs. 

Currently, these app are tightly bound in functionality, and arguably little benefit to keeping them separate. These apps can be brought together and served as separate Flask Blueprints.

Application candidates for this:

- os-conductor (user management, datastore management,  various 'misc' functionality, upload datapackages with dpp-fiscal)
- os-api (reading from the Open spending database, used by os-viewer)
- os-fdp-adapters

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. Data will be migrated to the DataHub.io platform. Please feel free to re-open if this is still relevant.
