### ISSUE TITLE
cannot start working on openspending

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [openspending/openspending#1373]
Hi,
I’m trying to start working om Openspending following the instructions. Would appreciate some help getting there. I'm using window 10 (home) and  the old docker toolbox. As such that works as expected. 

On 192.168.99.100  I’m getting these responses:
	Port 9200:  ES : some json
	Port 4567: Fake3: some xml
	Port 6379: Redis: some error-text probably because request this looks like a security attack
	Port 5432: Postgress: error-empty-response, probably because of invalid length of startup packet

The beginning of the tracelog mentions something of an invalid record length..

db_1               | 2018-07-01 20:07:20.736 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1               | 2018-07-01 20:07:20.736 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1               | 2018-07-01 20:07:20.744 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
os-fdp-adapters_1  | ls: /app/.git: No such file or directory
os-fdp-adapters_1  | working from /app
frontend_1         | standard_init_linux.go:190: exec user process caused "no such file or directory"
openspending_frontend_1 exited with code 1
db_1               | 2018-07-01 20:07:20.891 UTC [18] LOG:  database system shutdown was interrupted; last known up at 2018-07-01 19:37:00 UTC
db_1               | 2018-07-01 20:07:23.318 UTC [18] LOG:  database system was not properly shut down; automatic recovery in progress
db_1               | 2018-07-01 20:07:23.324 UTC [18] LOG:  redo starts at 0/15E0D80
db_1               | 2018-07-01 20:07:23.324 UTC [18] LOG:  invalid record length at 0/15E0DB8: wanted 24, got 0
db_1               | 2018-07-01 20:07:23.324 UTC [18] LOG:  redo done at 0/15E0D80

Further more the installation of the os-api is corrupted. The next bit is repeated many times in the tracelog

os-api_1           | 2018-07-01 20:07:38,219 - elasticsearch - WARNING - HEAD http://es:9200/packages [status:N/A request:0.005s]
os-api_1           | Traceback (most recent call last):
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
os-api_1           |     (self.host, self.port), self.timeout, **extra_kw)
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
os-api_1           |     raise err
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
os-api_1           |     sock.connect(sa)
os-api_1           | ConnectionRefusedError: [Errno 111] Connection refused
os-api_1           |
os-api_1           | During handling of the above exception, another exception occurred:
os-api_1           |
os-api_1           | Traceback (most recent call last):
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
os-api_1           |     response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
os-api_1           |     _stacktrace=sys.exc_info()[2])
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 333, in increment
os-api_1           |     raise six.reraise(type(error), error, _stacktrace)
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
os-api_1           |     raise value
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
os-api_1           |     chunked=chunked)
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
os-api_1           |     conn.request(method, url, **httplib_request_kw)
os-api_1           |   File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
os-api_1           |     self._send_request(method, url, body, headers, encode_chunked)
os-api_1           |   File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
os-api_1           |     self.endheaders(body, encode_chunked=encode_chunked)
os-api_1           |   File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
os-api_1           |     self._send_output(message_body, encode_chunked=encode_chunked)
os-api_1           |   File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
os-api_1           |     self.send(msg)
os-api_1           |   File "/usr/local/lib/python3.6/http/client.py", line 964, in send
os-api_1           |     self.connect()
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
os-api_1           |     conn = self._new_conn()
os-api_1           |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
os-api_1           |     self, "Failed to establish a new connection: %s" % e)
os-api_1           | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f42c0e066d8>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by brew** [comment]
The os-api error happens while Elastic Search is starting up. os-api will keep restarting until ES is available, where it should then start up normally. This shouldn't take very long though, so if os-api keeps crashing, then something else may be wrong.

**Comment by GeraldGrootRoessink** [comment]
Good to know. Indeed in the end there is an ES connection.  But still, even after redoing the installation, results are the same.  Localhost refuses connection.

**Comment by brew** [comment]
Perhaps you're running another web server on port 80 on your local machine? It's probably not a good idea to run this on port 80 anyway, so  I've committed a change to serve the application on port `8080`, instead of `80`. Pull the most recent version of this repo, and try again, this time browsing `localhost:8080`.

If you still encounter problems, please show me the command you run, the contents of your `.env` file, and the error you receive.

**Comment by GeraldGrootRoessink** [comment]
@brew: Appreciate the help. 
No luck sofar. Chrome calls this ERR_CONNECTION_REFUSED.  It's a timeout I suppose. There's no response.
## Pulled images:
$ docker image ls
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
openspending_frontend          latest              fb58ccd08c31        13 hours ago        19.1MB
ull_frontend                   latest              fb58ccd08c31        13 hours ago        19.1MB
elasticsearch                  latest              bbb1111fe3d3        40 hours ago        486MB
postgres                       latest              730027eb9d78        42 hours ago        236MB
sickp/alpine-nginx             latest              aa321d898ef7        6 days ago          18.3MB
redis                          latest              71a81cb279e3        7 days ago          83.4MB
postgres                       10-alpine           e273e6bfba1c        7 days ago          39.5MB
memcached                      latest              c26edf253ee4        7 days ago          58.8MB
openspending/os-explorer       latest              c184c5bd7df2        9 days ago          430MB
redis                          3.2-alpine          4a1abd138341        2 weeks ago         20.7MB
memcached                      alpine              ac8ecd7127f3        3 weeks ago         8.07MB
openspending/os-explorer       352af9b             52c39be2ef0f        6 weeks ago         428MB
openspending/os-viewer         8f8d705             868e62a4d2ed        6 weeks ago         301MB
openspending/os-viewer         latest              868e62a4d2ed        6 weeks ago         301MB
openspending/os-packager       9781954             2e61625edd34        6 weeks ago         268MB
openspending/os-packager       latest              2e61625edd34        6 weeks ago         268MB
openspending/os-admin          6a19a0d             5dbd0762c175        6 weeks ago         216MB
openspending/os-admin          latest              5dbd0762c175        6 weeks ago         216MB
openspending/os-conductor      latest              582e26e1c18a        6 weeks ago         429MB
openspending/os-api            6e482ac             7aee296ddcfd        7 weeks ago         402MB
openspending/os-api            latest              7aee296ddcfd        7 weeks ago         402MB
openspending/os-conductor      4cf4a14             bc9fe456acfa        7 weeks ago         427MB
openspending/os-fdp-adapters   a851623             b9475875cdba        2 months ago        374MB
openspending/os-fdp-adapters   latest              b9475875cdba        2 months ago        374MB
hello-world                    latest              e38bc07ac18e        2 months ago        1.85kB
openspending/fakes3            latest              99b9f0b8242b        3 months ago        41.6MB
elasticsearch                  1.5                 a9f376ad5951        20 months ago       344MB
### Used command
$ docker-compose -f docker-compose.base.yml -f docker-compose.dev-services.yml up
### .env file
OS_BASE_URL=http://localhost:8080

OS_API_ENGINE=postgresql://postgres@db/postgres
OS_ELASTICSEARCH_ADDRESS=es:9200
OS_API_CACHE=redis
OS_CONDUCTOR_ENGINE=postgresql://postgres@db/postgres

#OAuth credentials for OS-Conductor
#(see https://github.com/openspending/os-conductor#oauth-credentials)
OS_CONDUCTOR_SECRETS_0="eJyN1dmuo0gSBuBXKZ1bug47mJH6gh3MYnYM8g1mM4sTsy+teffxqemRekY9peI2RSgU+Wd8f3y8hmpJpvzzlT8//vHt4/vXx4myan5zXPab5agB64nfNDH6cXIDhqqKL1blWFbjWVtkD3cIYHdzTG0uUqpAZFudI4N1S46/VOeQLBYeyFNgqEO4cHbH34DEvhh7dZThbg/2ubJKKup74C3yIxxHndQNY3FO9fV6eUm+dkSJW0aJPaG6afDr1BvcDSCS7Ao1N9yf4hMIbkeViJlsjwpyz1ecM9I0R0Ov1Jz9vuAmLkHlmclOq9XsG7M9Mly5AQJDkFZpCI+8aiSk76zlAouWTD/ysrPjbJoUlrE0qyokbtRz8jWf0eOxZLac5SkEx28ge7pRTu5hkQ1S/njai8X5gUIo+qSjxdUz9+t8xOt0QRcKtVN0hmu6NMZBuYYQkY61ewN4K6xVZakl1aMPj6Xtc8ahBjTUCWbIULfqiM90qyqwNsux3XviSsnS+wS"
OS_CONDUCTOR_SECRETS_1="q2HYNIIQ3MB6jU6qNMRAh3yer7eG8FMpVU/Nedqn0IdFw7WJugkzir8JPNdNh8t21xpVUNi9WrRsYBJHJnhQ/R2fBt9/TQPyc7qeiGBPaf0pbYAWcbwFp6ISykpT6haCKtI9PCb/SWXSG37e5j4QkrBo2+Ft3TcGjudApOSXiwFqP13OBbJAGXNPNNn7n6FOyUKmS2UUH0Va6RM67h42qBIutjdeBrhIqNRnzdJUkq+e+5XFpvt9XUSOBN7stASxf12gt4RfGrLf98PwKe9+FEDaMzS/QK1c1GH3QZHrnmDxY4mRXWqkNzEmgjWEjhzyrQpZz+8XUnQVOYgTuSEgybgBNtyqyRL6MRJZhxYFCeKsNmYW7JCmvPkGohKIC++JaEYnpcdsrFkNnNhEFPDmIcKZ3hTtE692V6tqAM9H9FKnr0QgXPri3UuJBnsKZlUiz3Mqd6BSpowzzdXs8+iG/11erO27g1NNGXz4EiKiEYrEw+1ktryQrclk+IkklmDsdki"
OS_CONDUCTOR_SECRETS_2="msLsSKdGE5T9Udegjjj55RRGhu4GGsJYX2VBSwuaf2IKCPuS4OT60Khm1yiy1MvWv1DCDcRuou1Vlb7vjbvhNP9bkOxQ28qD2WL1eY7tKdHmz8CktUMW/rLCc0YZmxtbb6LNC+bw0wfLFmu3p0grboEIldQ5b0b8BGmPGqQVq7zAohnEl/VHimKVlvn2XTv+TXiFOUe/Oja/oU96cNiy8H1c+237Vx+vWyxCM/ml05R4RmW05OBX4+shw5VDsuEQb2XhF5bdgvDA4nJxr5oW1x8IAsFGGyYXeEG5Bfd7O2kSE8xGCP6ZnQD6eyCVw+7lLBT1A+Menhh6moOuxMmzldt54buw2CR+/AmuN7kqdaZhuvsigei9Buzkx6X6evWXNsqCZ4DHXv91KnZ4FIsnAL8dX1abRzVZN13QAGNwDarpodQZKCHAPRGvX3R9eYnq8G12Ne2+eA6CqecODcBaLJvWNfGrUNH5UxLRzL4e/90LsYkW45RkXS3pydbFIdSPFET"
OS_CONDUCTOR_SECRETS_3="cRo9KGP5sgGWUexnivkO9xdGl6N5Ph4dqltJs14it+TbF4Gb2tcafNFTJMD2sLK8Xrc6VNUFsx0OdDIl/oV3iKmLuYiJHiYdMsA67EJZuPunSi92nbLOrnHOVUwpNKylGlces0rm0XazMPcaKECj1b70sYruI+yyzMpy5qTE3VWOfi9q+34cuZA4hrBWSrg+ILCaNXKgVzEMe4ZFxb1zm3qxdXYkNTkePemWnTG/v33G/gBjmgKfwvRx2/fPsquK9v8c8zTIZ8+m3z/AoycLzG6fHeqoqSPOLhaNh6vekN8/fCa722V/g11ls/pKv/fynFqzZpc2fSPppKZFeHe2kkse3mrd2K/zvny/wt4Az8z8FcEfO+Dnxj4KwLewM8M/BUBb+BnBv6KgO8KPzHwVwS8gf8Y+JdE/M99/SUMf6aAZlCKplASQRnsO0GgDTMnAwnSBMMI8rGcMJRCx6QbhhRhkM/k9Ro//11gHvMh7cCUg+kz7Z4f//wXsJP+cA=="

#AWS S3 (FakeS3 used for development)
OS_ACCESS_KEY_ID=fakes3
OS_SECRET_ACCESS_KEY=fake123
OS_S3_HOSTNAME=fakes3
OS_STORAGE_BUCKET_NAME=fake-bucket

**Comment by brew** [comment]
That all looks correct. I'm not sure what else to suggest. Perhaps it's worth upgrading the Windows Docker toolkit, and use the more recent Windows Docker installer instead? https://docs.docker.com/docker-for-windows/install/

**Comment by brew** [comment]
This ticket has been inactive for a while so will be closed. If you need further help on this issue, feel free to reopen, or create a new issue.
