### ISSUE TITLE
502 Error to get countries in os-packager

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1374]
Hi, page https://cosmopolitan.openspending.org/v1/countries/?format=json is not accessible. 
"Error 502 Bad gateway" was returned.

**Comment by pwalsh** [comment]
works now for me, from here. infrastructure provider issue?

**Comment by brew** [comment]
I believe so. It works now, but we're continuing to keep an eye on it. I'll close this issue, but feel free to open again if it remains a problem.
