### ISSUE TITLE
Make datapackage email address optional and configurable

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [openspending/openspending#1375]
Just uploaded a serious dutch dataset on education on open spending.  Very pleased with the possibilities.  There's a crucial privacy issue  though.  The emailaddress I used to login on the platform is publicly visible.  That is not what I want. Questions or remarks are welcome naturally but not in my private email box. I want to change this tot my employer's.

**Comment by brew** [comment]
Thanks for the report, and I totally understand your concern.

At the moment, datapackages are published to the datastore with the email address of the Google account used to log into Open Spending, and this isn't configurable. Ideally, the email address would be both optional, and configurable as metadata for the datapackage during its creation with OS-Packager. We will look into solution for this, and I'll update on this issue.

In the mean time, I've manually removed your email address from the datastore, for all datapackages your account has created.

Be aware that subsequent updates you make to existing datapackages will overwrite them with your login email address again. And also for any new datapackages your create.

If your employer email is a Google account, you'll be able to login with that email address and use it to create new datapackages.

**Comment by sglavoie** [comment]
**FIXED/CLEANUP**: Closing old issue without recent activity (>2 years) as part of #1478. A fix was brought and the author has not replied back. Please feel free to re-open if this is still relevant.
