### ISSUE TITLE
suggestion: uri 's to identify things

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [openspending/openspending#1376]
The following dataset is about schools in the Netherlands

https://openspending.org/viewer/ed6eb7eb49eb2620da97599cfeae0456:balansen-onderwijs-nl-v0-4-9?measure=%22balanswaarde.sum%22&groups%5B%5D=%22bevoegd_gezag.bevoegd_gezag%22&order=%22balanswaarde.sum%7Cdesc%22&visualizations%5B%5D=%22Treemap%22&lang=en

Each school is identified with a resolvable uri. It is an hyperlink and it allows us to normalize the data globally. So if a user wants to know more about it he or she could get it bij clicking the hyperlink.  However the os-viewer doesn't support  hyperlinks   In my view that would be a nice feature.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>2 years) nor assignee as part of #1478. Please feel free to re-open if this is still relevant.
