### ISSUE TITLE
Error while validating the csv file

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1378]
Hi, I was uploading a csv file in http://openbudget.kdvz-frechen.de/packager/, but during calling the goodtables.io api, my browser was trying to access "http://openbudget.kdvz-frechen.de/packager/proxy?url=undefined" in the provide-data step. Do you have ideas about this? thanks.

**Comment by liyakun** [comment]
Hi, the same issue also happens in openspending platform, please have a look at it asap, thanks a lot.
![image](https://user-images.githubusercontent.com/7370334/43205344-745575fa-9023-11e8-8f39-f0a42b06eeeb.png)

**Comment by liyakun** [comment]
Hi, the steps to reproduce the issues is as follows:
1. Go to https://openspending.org/packager/provide-data
2. Click "Upload a file" button and upload a csv file, there are sometimes the following error were thrown by the web browser
    
![image](https://user-images.githubusercontent.com/7370334/43394629-aa558ca4-93fb-11e8-8cf9-f7e76876621c.png)

**Comment by brew** [comment]
@liyakun Thanks for the report. This is an issue with the goodtables service (https://github.com/frictionlessdata/goodtables.io/issues/317), which we think should now be resolve. Please let us know if you continue to have problems with this.
