### ISSUE TITLE
Search without diacritics

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1379]
Currently, diacritics are significant when searching Open Spending for datasets using os-explorer. So, 'Mexico' will return different results than 'México'. We should be more forgiving of user input without accents and other diacritics and allow a liberal search terms. Relevant ElasticSearch docs: https://www.elastic.co/guide/en/elasticsearch/guide/1.x/asciifolding-token-filter.html

**Comment by sandervdwaal** [comment]
Report by @LorenaGIFT seems to fit this description: 
> something that I have noticed and Uruguay has also pointed out, the Mexican Dataset does not appear on the search. Could you please check on that as well? Further expanding on that, two datasets for Mexico do come up, which are the tests I made while deciding if adopting the OFDP in 2015, is there a form of cleaning the clutter?

Search for 'Mexico' results in the 2 old test datasets, 
search for 'México' results in the recently uploaded datasets.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~1 year 4 months) as part of #1478. The data will be migrated, cleaned and merged into DataHub.io, which uses a different platform. Please feel free to re-open if this is still relevant.
