### ISSUE TITLE
Support requests by Croatian government

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1385]
Here are the activities identified by Croatia as the ones for which they would need our technical support:

- [x] - To delete existing data in OPFD, as they were meant for pilot purpose.
- [x] - To translate left part of menu into Croatian an potentially to change some things
- [x] - To change header of report for uploading – this is probably most difficult part as pipeline has to be modified
- [x] - To send new dataset for uploading
- [x] - To establish regular procedure for uploading dataset periodically

**Comment by brew** [comment]
@sandervdwaal 

> - To delete existing data in OPFD, as they were meant for pilot purpose.

I don't understand the request. Can you expand, and create a separate issue if necessary.

> - To translate left part of menu into Croatian an potentially to change some things

I believe OS supports some level of translation, as Mexico uses it. Where it says 'left part of menu', which page are we talking about? The viewer?

> - To change header of report for uploading – this is probably most difficult part as pipeline has to be modified

I don't know what this refers to.

> - To send new dataset for uploading

Again, I don't understand what's being requested here. Support to create new datasets on OS?

> - To establish regular procedure for uploading dataset periodically

This looks like the established requirement to improve the os-data-importers: https://github.com/openspending/openspending/issues/1381

**Comment by akariv** [comment]
>> To delete existing data in OPFD, as they were meant for pilot purpose.

> I don't understand the request. Can you expand, and create a separate issue if necessary.

There are a few datasets under the main openspending account that were added at some point (iirc through os-data-importers). We can delete or unpublish them.

>> To translate left part of menu into Croatian an potentially to change some things

> I believe OS supports some level of translation, as Mexico uses it. Where it says 'left part of menu', which page are we talking about? The viewer?

Only the viewer supports translations atm, and it can be added by adding a translations json file (there are already ones for Spanish, German etc.)

>>To change header of report for uploading – this is probably most difficult part as pipeline has to be modified

> I don't know what this refers to.

>> To send new dataset for uploading

> Again, I don't understand what's being requested here. Support to create new datasets on OS?

I'm guessing this means making some modifications to the pipeline (title, sources), and re-running it?

>> To establish regular procedure for uploading dataset periodically

> This looks like the established requirement to improve the os-data-importers: #1381

Or at least have a similar process as the with the Mexico govt. tech team (in the meantime).

**Comment by brew** [comment]
@sandervdwaal I've added some detail about os-viewer translations to the ticket: https://github.com/openspending/openspending/issues/1389

**Comment by jobarratt** [comment]
@sandervdwaal do you have an update on the second bullet point?

On the regular process for uploading, can we tick this off? I assume the process is that they email us the data as and when it is ready?

**Comment by jobarratt** [comment]
@sandervdwaal do you have any info on the unticked Bullet? 'To change header of report for uploading – this is probably most difficult part as pipeline has to be modified'? Otherwise we think this ticket can be closed.

**Comment by sandervdwaal** [comment]
I'm asking Boris about this.

**Comment by jobarratt** [comment]
@tlacoyodefrijol What's the status of this card, can we close?

**Comment by tlacoyodefrijol** [comment]
Yes, these actions have been completed. Closing issue.
