### ISSUE TITLE
Link to OpenSpending Community site not working

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1387]
When going to the Packager and starting the process to upload a budget file, the page shows a button 'OpenSpending Community' in the bottom right corner. Nothing happens when I click it.

I expect it to take me to http://community.openspending.org in a new window.

**Comment by brew** [comment]
@sandervdwaal The community site is very out of date. I suggest we remove the broken link, rather than fix it.

**Comment by brew** [comment]
Closed by https://github.com/openspending/os-packager/commit/3942b4b6d7d95a41c71f7305c8d6ae0dcfcc5916.
