### ISSUE TITLE
Remove pilot Croatia datasets

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1388]
Identify and remove old datasets created as part of a pilot with Croatia. These should be removed from both Openspending.org and os-data-importers.

**Comment by jobarratt** [comment]
To be actioned once https://waffle.io/openspending/openspending/cards/5b9b7e700ac3d7001af619ff have been completed.

**Comment by brew** [comment]
There are two datasets related to Croatia:

https://openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:croatia-budget-plan?lang=en - this is created by the [os-data-importers spec](https://github.com/openspending/os-data-importers/blob/2ebdf73b7ce50743893a95d8265fc30b216dff40/europe/croatia/fiscal.source-spec.yaml)

https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:croatia-budget-plan?lang=en - doesn't look like there is an owner for this, as no owner relates to the idhash, 667df60aa07c34260eae9b55b2778712. Possibly this was uploaded as a test before adding to os-data-importers.

I suggest removing both.

**Comment by jobarratt** [comment]
@tlacoyodefrijol can you please confirm/find out whether or not this can be actioned, and then pass over to Viktor to action
