### ISSUE TITLE
os-viewer translation for Croatia

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1389]
Translations for os-viewer use [node-polyglot](http://airbnb.io/polyglot.js/). Translation files are in the [os-viewer/translations directory](https://github.com/openspending/os-viewer/tree/8f8d705383aa982e1a8d318774fc8aef515da95e/translations). Copy the `en.json` file, renaming it with the [two-letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) for the language, i.e. `hr.json`. For each `key: value` in the file translate the value.

To view a viewer page in the translated language, add a `lang=hr` query string value to the url. E.g., for a Spanish view of a dataset, `lang=es`: 

https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:presupuesto_mexico?lang=es 

We may not have all strings in the viewer available for translation, e.g. the 'Reset View' and 'Reset to Defaults' buttons aren't in the translations file. We should identify strings that need to be added for translation.

**Comment by brew** [comment]
Instructions for translations provided to Croatia. Awaiting feedback.

**Comment by brew** [comment]
I've added the translations for os-viewer, they can be seen here as an example: https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:presupuesto_mexico?lang=hr

There are a few strings we missed, for the new Viewer Defaults feature. These would be good to also have translated, namely:

```json
{
  "Save View as Default": "Save View as Default",
  "Reset View": "Reset View",
  "Reset to Defaults": "Reset to Defaults",
  "This will save the current view as the<br>default for all users of this dataset.<br>Are you sure?": "This will save the current view as the<br>default for all users of this dataset.<br>Are you sure?",
  "Yes": "Yes"
}
```

@sandervdwaal Can you request these additional strings from Croatia?
@tlacoyodefrijol It would be good to update the es version of the translations file with these too. Can you help with that? It's a matter of translating the strings above.

**Comment by sandervdwaal** [comment]
@brew Updated file has been received by email, including the new text labels. Can you please ensure to use this new file as Boris indicated there were updates to other strings as well.

**Comment by brew** [comment]
This is done. I'll close this and create a new one for the Spanish updates.
