### ISSUE TITLE
“An error occurred while transferring the file” - help

### ISSUE THREAD

**Issue by cchhss123** [openspending/openspending#1390]
I encountered a problem.

I had setup OpenSpending platform in my machine. (setup OpenSpending platform by Docker containers via Docker Compose)

When I try to upload a file in “packager/provide-data” page (Provide a CSV file containing fiscal data).
This message was showing as “2017 general budget_Capital Account.csv - Failed
An error occurred while transferring the file.”

Someone can help guide the direction to solve the problem.

my .env as follows
OS_BASE_URL=http://etiweb.ddns.net
REDASH_SERVER_NAME=

OS_API_ENGINE=postgresql://postgres@db/postgres
OS_ELASTICSEARCH_ADDRESS=es:9200
OS_API_CACHE=redis
OS_CONDUCTOR_ENGINE=postgresql://postgres@db/postgres

# OAuth credentials for OS-Conductor
OS_CONDUCTOR_SECRETS_0=".....euo1gWAN....."
OS_CONDUCTOR_SECRETS_1=".....OdBVRsU7p1pH....."
OS_CONDUCTOR_SECRETS_2=".....XJAT2bCAyaF....."
OS_CONDUCTOR_SECRETS_3=".....FkHde16q5MLjcR....."       

# AWS S3 (FakeS3 used for development)
OS_ACCESS_KEY_ID=fakes3
OS_SECRET_ACCESS_KEY=fake123
OS_S3_HOSTNAME=fakes3
OS_STORAGE_BUCKET_NAME=fake-bucket

# If using the fake-s3 docker container for development, openspending/fakes3
USE_FAKE_S3=True
OS_S3_PORT=4567

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1.5 years) nor assignee as part of #1478. The author has not followed up and neither did contributors to this project as of yet. Please feel free to re-open if this is still relevant.
