### ISSUE TITLE
Updated Links to BOOST

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1391]
The BOOST Website has different URLs.

Old format: `http://wbi.worldbank.org/boost/****`

New format: `http://boost.worldbank.org/****`

Old links continue to work with the new format.

**Comment by sandervdwaal** [comment]
This is now fixed in https://github.com/openspending/os-data-importers/pull/53

**Comment by brew** [comment]
Do you want this redeployed?

**Comment by sandervdwaal** [comment]
Yes please redeploy this, thanks!

**Comment by sandervdwaal** [comment]
This should let the Uruguay BOOST data re-appear on openspending.org (as well as data from Guatemala)
