### ISSUE TITLE
Upload new data for 2016, 2017 and 2018

### ISSUE THREAD

**Issue by jobarratt** [openspending/openspending#1392]
Croatia will send a new budget file for 2016, 2017 and 2018 for OKI to load into the platform

**Comment by jobarratt** [comment]
Comment from Croatia. @brew are you able answer this? If not please an you discuss with @sandervdwaal  throughout the week as he will not be availible in sprint planning. Data will be provided 'in the next two weeks' and we should action immediately. The deadline is the 28th, though this is obviously dependent on them getting the data to us. 

"as to About replacing existing data with new dataset for 2016, 2017, and 2018, maybe I should clarify that Croatian budget is 3-year budget, but new budget is created and approved by Parliament every year. That’s mean that plan for year +1 and year +2 from previous budget year can be modified in the current budget year. As I understand, with every dataset upload, existing year would be updated. However, it’s possible that some budget lines do not exist anymore in a new budget. So, when we upload new budget, there is possibility that some lines which do not exist anymore will stay unmodified and will not be deleted. Do you have any recommendations regarding this issue, or maybe I am seeing it wrong and it’s not an issue? There are probably more complex solutions, as introducing budget version with budget year as budget version ID, but maybe it’s too complicated for now."

**Comment by brew** [comment]
Resources are replaced as a whole. If the resource is replaced, all lines will be updated.

**Comment by brew** [comment]
Current status: WIP fiscal.source-spec files created for Croatia, split across to datasets (2016-2018, 2018-2020). Croatian titles given for each column. Uploaded to staging server awaiting approval before being added to https://github.com/openspending/os-source-specs master branch and production.

**Comment by sandervdwaal** [comment]
I'm asking Boris whether we need specific budget phases to each year, and whether he's happy with how the data is on staging. Once he is, we can upload on the main OS

**Comment by brew** [comment]
Uploaded to production here:

2016-2018: https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:croatia-budget-plan-2016-2018?lang=en
2018-2020: https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:croatia-budget-plan-2018-2020?lang=en

**Comment by jobarratt** [comment]
@tlacoyodefrijol please update card with the latest info and whether let the others know if you need any support to move this forward.

**Comment by tlacoyodefrijol** [comment]
Boris sent the new files for 2017, 2018 and 2019. 
Actions are:
- We need to confirm if the fiscal specs (see above) include all the headers and upload them to the staging site. 
- Remove the old datasets from staging and production site.
- Once uploaded and mapped, share staging data with Lorena and Boris for approval to move to Production. 

I'll forward the email with the new files to @nightsh for upload.

**Comment by LorenaGIFT** [comment]
When could we have the updated dataset online to share with BOOST team?
