### ISSUE TITLE
suggestion: "done" button when adding vizs to viewer

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1395]
When adding visualisations in Viewer, it's sometimes confusing that I need to click the cross to hide the viz addition modal dialog. I forget that I can add multiple. People might expect the dialog to hide itself after adding a viz.

I think a little "Done" button at the bottom right where it tends to be would be handy to make that part of the flow really clear. 

![openspending-viewer-add-chart](https://user-images.githubusercontent.com/235801/46469076-9adc7980-c7d2-11e8-8299-65fe9f79228f.png)

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1.5 years) nor assignee as part of #1478. The author has not followed up and neither did contributors to this project as of yet. Please feel free to re-open if this is still relevant.
