### ISSUE TITLE
suggestion: Help user represent the data correctly.

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1396]
For certain datasets it's crucial that the user disaggregates or filters by Financial Year and Budget Phase.

I tried to add the following description to [this dataset](https://openspending.org/viewer/b9d2af843f3a7ca223eea07fb608e62a:estimates-of-provincial-expenditure-south-africa-2018-19-ec-social-dev?measure=%22value.sum%22&rows%5B%5D=%22economic_classification_2.economic_classification_2%22&rows%5B%5D=%22economic_classification_3.economic_classification_3%22&columns%5B%5D=%22programme_number.programme_number%22&order=%22value.sum%7Cdesc%22&visualizations%5B%5D=%22PivotTable%22&lang=en) but they didn't show up in the UI
> It's very important to filter and/or drill down by Budget Phase and Financial Year. If you don't, your visualisation will combine the totals for different phases or years and misrepresent the data.

I don't know how feasible it is to add hard constraints to datasets where that's a thing, but alternatively it'd be nice if it could be a clear warning. Failing that, if the description could be clearly shown when the user tries to use the column things on the left in Viewer.

In the worst case, it could be something I add to the top of the dataset description.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>1.5 years) nor assignee as part of #1478. The author has not followed up and neither did contributors to this project as of yet. Please feel free to re-open if this is still relevant.
