### ISSUE TITLE
suggestion: Better feedback on duplicate key errors

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1398]
When our national treasury data owners will be uploading datasets, the python stack trace of a duplicate key error probably won't help them much to resolve the error.

I suggest catching the error, and presenting a simpler message message like "More than one row with the exact same classification dimensions", and an option to show a detailed/advanced message containing the stack trace.

If that's hard given the existing API, perhaps just put the simpler message right at the top with some white space before the stack trace.

**Comment by jbothma** [comment]
here's an example of a stack trace as shown in Packager at the moment https://github.com/openspending/openspending/issues/1397

**Comment by brew** [comment]
Thanks - I agree. It's a common issue, and there should be a clearer message.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>1.5 years) as part of #1478. The referenced issue has been closed by its author. Please feel free to re-open if this is still relevant.
