### ISSUE TITLE
Packager Fiscal and Unknown custom date format not picked up

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1399]
```csv
BudYear,Department,Econ2,FinYear,Value
2016,The Presidency,Current payments,2016-01,21168
2016,The Presidency,Current payments,2016-01,2652
2016,The Presidency,Current payments,2016-01,268
2016,The Presidency,Current payments,2016-04,11
2016,The Presidency,Current payments,2016-04,51
2016,The Presidency,Current payments,2016-04,463
2016,The Presidency,Current payments,2016-04,185
```

fiscal year date
![openspending-packager-fiscal-date-format](https://user-images.githubusercontent.com/235801/46667945-61897c80-cbcb-11e8-9443-4581fac31fd6.png)
![openspending-packager-fiscal-date-format-error](https://user-images.githubusercontent.com/235801/46668064-bb8a4200-cbcb-11e8-98f0-60cae0012c54.png)

unknown mapping date
![openspending-packager-unknown-mapping-date-format](https://user-images.githubusercontent.com/235801/46667946-62221300-cbcb-11e8-8fb1-1a8f63fbbd8d.png)
![openspending-packager-unknown-mapping-date-format-error](https://user-images.githubusercontent.com/235801/46668063-baf1ab80-cbcb-11e8-99a5-a958d4389f32.png)

**Comment by jbothma** [comment]
A workaround for now is adding the data with the type `unknown dimension #1 code (unknown ❯ string-1 ❯ code)`

**Comment by sandervdwaal** [comment]
I've experienced the same for Argentinian spending data.
Not just when mapping to date:generic, but also to date:fiscal:activity-approval. 

> ERROR   :Field "impacto_presupuestario_fecha" can't cast value "2018-01-13 00:00:00" for type "date" with format "fmt:%Y-%m-%d"
> -----
> ERROR   :Field "impacto_presupuestario_anio" can't cast value "2018" for type "date" with format "fmt:%Y-%m-%d"
> -----
> ERROR   :Field "impacto_presupuestario_mes" can't cast value "1" for type "date" with format "fmt:%Y-%m-%d"

In all cases it tries to map the %Y-%m-%d instead of what I specified.

**Comment by jjalcolea** [comment]
Hi. We've also stumbled into this bug (Spain)... :-(
Any estimation on when it will be solved? I've seen it's in the backlog of GIFT Phase IV...

Thanks,

Juanje.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>7 months) as part of #1478. [GIFT Phase IV](https://github.com/openspending/openspending/projects/1) was closed and data is about to be migrated to DataHub.io. Please feel free to re-open if this is still relevant.
