### ISSUE TITLE
When the data is loading into the DB, it looks like nothing is happening

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1400]
There is a progress bar but it isn't moving.

Perhaps it could show an infinite progress bar for that status.

Even better would be to show a "Progress last checked: 2018-01-01 14:..." or something to show there is life even if we can't tell the progress in detail?

I know that it's progressing now and can check the browser's network log, but non-tech users might think it's broken and not know to wait and check.

**Comment by brew** [comment]
Agreed - we did fix the issue where progress simply didn't complete, but this is a separate problem. I'm thinking we perhaps remove the progress bar completely, and have a series of checks for each step that illuminate to show they are complete.
