### ISSUE TITLE
OS Viewer says "No data to display" when there was an error

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1402]
I suggest you show a message like "Something went wrong" and if possible what they can do to rectify or investigate.

I tend to think a non-scary notice that something went wrong is more useful to users than making it appear like everything's ok but for some puzzling reason you don't get the expected outcome.

In this case there was a server error because of another issue which I'll raise in a separate bug.
![openspending-viewer-hidden-error](https://user-images.githubusercontent.com/235801/47200947-5c20f480-d378-11e8-9bb5-bb882b9d2682.png)

**Comment by nightsh** [comment]
The flow as I see it:

* os-viewer exposes a downloader method which is used to grab datapackages
* visualisation is powered by babbage-ui, which uses the above downloader to get the package
* if there's any issue with the request, an error is thrown in the viewer downloader module
* babbage-ui does not properly treat the error and it shows some canned messages according to a set of rules

Now, if that is correct, I am missing a few bits:

* how can I get a hold of the error message? I tried a few things around the `fetch` API docs and our downloaders, nothing seems to be the right way
* if the error is thrown in the viewer, then it needs to be propagated downstream as well (?)
  * however, if I attempt to `catch` the `throw` in the viewer downloader, it breaks the flow down the line, as some other things (`getJSON()`) seem to rely on it not returning an error?

At the moment I don't see how the messages in babbage-ui could be extended to include the error payload, probably parsed. It's annoying, as I can see them being used throughout the code, however my attempts to extend them were not successful.

I feel like I'm spiraling and in the need of help.

**Comment by nightsh** [comment]
Development so far:

* babbage-ui makes a request through os-viewer
* when the response comes back, babbage-ui checks the status code
* if status > 400 then it throws an error

All the components have to catch that error and emit it further. They don't work the same way, but ultimately they all end up doing some basic promise chains. The suggested implementation adds a new flag and conditionally sets the error message within the scope of their directives so it can be shown in templates.

The tricky part was following up on the promise chain, and throwing in the right places to help the server error reach the template.

**Comment by nightsh** [comment]
Corresponding PRs sent:

* openspending/os-viewer#186
* openspending/babbage.ui#75
