### ISSUE TITLE
Bar chart embed URL doesn't update upon each change

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1404]
Not sure if this is just for bar chart or for any views.

Expected behaviour
-------------------------

If I add a bar chart and set some filters to get the view I want, then open the short URL on the embed code popup, I expect to see the view I just generated

Actual behaviour
---------------------

I actually get the default view (what I saw when I just opened the dataset in OS viewer, before setting the filters and things.

Steps to reproduce
-------------------------

1. Open an dataset like https://openspending.org/viewer/b9d2af843f3a7ca223eea07fb608e62a:amount-kind-test?
2. Add a bar chart viz
  2.1 Note the default view  (Administration at 1.1 Million)
3. Filter `kind` to _Virements and shifts due to savings_
4. Note the chart shows positive and negative bars
5. Get the embed URL by clicking on the HTML tag icon in the top right (e.g. http://tinyurl.com/y7f95c29)
6. Open that in a new tab
7. Note it shows the default view of the dataset (Administration at 1.1 Million)

Workaround
----------------

1. When you have the view you want to embed, copy the URL of the full OS Viewer from the address bar, e.g. https://openspending.org/viewer/b9d2af843f3a7ca223eea07fb608e62a:amount-kind-test?measure=%22amount.sum%22&groups%5B%5D=%22programme.programme%22&filters%5Bkind.kind%5D%5B%5D=%22Virements%20and%20shifts%20due%20to%20savings%22&order=%22amount.sum%7Cdesc%22&visualizations%5B%5D=%22BarChart%22&lang=en
2. Get the embed code now
3. Open that in a new tab and see that it's what you wanted

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1.5 years) as part of #1478. There was no follow-up nor assignee on this one. Please feel free to re-open if this is still relevant.
