### ISSUE TITLE
CSV download provides invalid CSV when values contain commas

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1405]
If this is using the babbage built-in CSV output, it's probably caused by babbage building its own CSV https://github.com/openspending/babbage/issues/5#issuecomment-435022733

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>1.5 years) as part of #1478. There was no follow-up nor assignee on this one. Please feel free to re-open if this is still relevant.
