### ISSUE TITLE
Support for non-integer fiscal year

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1406]
In South Africa, financial year is generally written 2018/19 or 2018-19 but OpenSpending currently requires financial year to be an integer.

Apparently financial year rarely is a perfect calendar year - so I imagine a lot of regions needing this change.

As a workaround, I'm using the staring year, which is convention among some, but it might be confusing to non-experts and is frowned upon by some experts.

**Comment by akariv** [comment]
I think that 'rarely' is probably an exaggeration -
https://en.wikipedia.org/wiki/Fiscal_year
Still, I understand the need. We could add another type for 'string based'
fiscal years - as far as OpenSpending goes, it doesn't care if the year
dimension is an integer or a string (in theory, at least).

**Comment by jbothma** [comment]
Sounds like a sensible way of approaching it. Thanks for the response.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>1.5 years) as part of #1478. The author of the issue seems happy with the reply he received and did not follow up since then. Please feel free to re-open if this is still relevant.
