### ISSUE TITLE
Additional os-viewer translations for es

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1410]
Since we added the Viewer Defaults feature, we need to update translations to include strings in the new UI elements:

```json
{
  "Save View as Default": "Save View as Default",
  "Reset View": "Reset View",
  "Reset to Defaults": "Reset to Defaults",
  "This will save the current view as the<br>default for all users of this dataset.<br>Are you sure?": "This will save the current view as the<br>default for all users of this dataset.<br>Are you sure?",
  "Yes": "Yes"
}
```

**Comment by tlacoyodefrijol** [comment]
Spanish translation @brew 
`{
  "Save View as Default": "Guardar Como Vista Predeterminada",
  "Reset View": "Reiniciar Vista",
  "Reset to Defaults": "Volver a Predeterminado",
  "This will save the current view as the<br>default for all users of this dataset.<br>Are you sure?": "Esto guardará la vista actual como<br>predeterminada para todos los usuarios de este conjunto de datos<br>¿Estás seguro(a)?",
  "Yes": "Sí"
}`

**Comment by brew** [comment]
Thanks @tlacoyodefrijol !

**Comment by brew** [comment]
Closed by https://github.com/openspending/os-viewer/commit/292464200bd5f5e8e299fe5a13b5aceef636f326.
