### ISSUE TITLE
Allow upload of predefined fiscal mapping within os-packager

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1416]
Currently, data publishers map fiscal types against columns in their data with a series of dropdowns, as a step in os-packager. For some users, who are regularly updating data formatted in the same way, this can be repetitive and potentially error-prone. It would be useful to provide a way for users to provide a predefined mapping against their data, as an alternative to manually selecting types with the dropdowns.

Perhaps by providing a file upload for a resource schema to use. These schemas could be derived from existing datapackage.json files.

**Comment by hanecak** [comment]
+1 from me. I'm now able to download consolidated and quite detailed budget data as JSON for several Slovak municipalities, thus I can automate following:

1. convert the data into CSV, possibly split into several files (say one per year, to avoid performance bottlenecks for both Open Spending platform and users who would like to get and open the CSVs)
2. I can generate Fiscal Data Package (i.e. descriptive JSON file + ZIP all together if necessary)
3. on first run: create and upload the package to Open Spending
4. on subsequent runs: get new or updated data, package it and submit to Open Spending

What I've identified for this so far:

* https://github.com/openspending/gobble - looks a good option for this use-case but it is not clear whether it currently actually works ans seems to need quite some works (see #1326)
* use/adapt existing API https://docs.openspending.org/en/latest/contributors/load/ - but it looks "for internal use only" thus I'm not sure if I (as external user) can access that API and get an API key for it

My use-case: I've created this by manually uploading CSV and assigning columns in Packages:

https://openspending.org/viewer/1ae301d0fb4c5bd535ce8e2eadf7a668:presov.sk-program-budget-2016

Now I want to generate and upload updated data via CLI/API/..., avoiding repeated clicking.

Side note: I might be able to help hacking gobble, but hacking platform itself might be too much for me.

**Comment by hanecak** [comment]
Thank you very much for implementing this.

A follow-up question, since I'm maybe doing something wrong. Is following work-flow OK?

1. download `datapackage.json` from existing "Presov 2016" example (https://openspending.org/viewer/1ae301d0fb4c5bd535ce8e2eadf7a668:presov.sk-program-budget-2016)
2. prepare CVS with 2017 data and load it into OS Packager, step 1
3. adjust `datapackage.json` (all "2016" replaced with "2017", the rest kept as is), load that with "Upload schema" into OS Packager, step 2

Step 3 is failing for me with:

```
Problem loading the schema file. Must be a valid datapackage, dataresource, or tableschema.
```
