### ISSUE TITLE
Automated OS Packager upload monitoring (production testing)

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1417]
It would be great to identify problems with the OS Packager upload service early.

it's difficult to ensure that all the parts of a microservice architecture that need to work together don't get broken accidentally by an update to one part, and it's probably frustrating to discover that something was broken several days after that work and having to come back to it.

## Suggestion

Daily automated upload and checks that the upload was successful

For example:

cron-based Travis-CI "build" that uses Selenium to upload a small datasetonce a day

Title like _Test Dataset 2018-12-14_
ID like `test-dataset-2018-12-14`

just a few rows and columns

1. e.g. 04:00 UTC, upload dataset
  - This would "fail" if the UI indicated any errors, and "succeed" if the UI indicates the upload completed successfully
2. e.g. 05:00 UTC, Check the dataset in OS Admin and OS Viewer that it was uploaded correctly and presents correctly in those apps
  - This would "fail" if the dataset isn't found, or the status isn't shown as successful, or it's not usable in OS Viewer
3. e.g. 04:00 UTC delete all test datasets older than 1 week
  - This should only fail if it failed to delete datasets. It doesn't need to fail if there aren't datasets to delete.

Travis-CI cron jobs don't allow you to set the time they should run, so to get the hour delay to let the dataset import completely, they might need to be triggered by something that does allow time-based triggers e.g. real cron or another free service https://docs.travis-ci.com/user/cron-jobs/

**Comment by jbothma** [comment]
I've recently done a bit of UI testing run by Travis-CI using Python, so I can help most-easily with that.

**Comment by jbothma** [comment]
These tests should be "loose"-enough that they don't break every time small changes are made to the user interface - just check that things work at a high level. 

e.g.

- Dont check the content of every single label
- Do check the main indication of success given by the UI
- Do check that the data really is uploaded and visible in some form in Viewer
- Do check that the API endpoint is set up and actually returns data for _some_ query

**Comment by brew** [comment]
Thanks @jbothma. I'm off now until the New Year, but would like to get a response to you as soon as I get back. I'm happy in principle to have a suite of production tests for the packager UI though, so feel free to explore this in the mean time.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>1.5 years) as part of #1478. The project [GIFT Phase IV](https://github.com/openspending/openspending/projects/1) was closed. Please feel free to re-open if this is still relevant.
