### ISSUE TITLE
OK Internet Explorer bug

### ISSUE THREAD

**Issue by jobarratt** [openspending/openspending#1420]
Is there something we can do so that Internet Explorer opens the visualizations? The MoF of Croatia only uses Internet Explorer and the visualizer does not finish loading:

**Comment by tlacoyodefrijol** [comment]
Some more details from Boris

- OS is W7x64 Enterprise SP1
- See screenshot for version of IE 
<img width="215" alt="screen shot 2019-02-05 at 12 06 28" src="https://user-images.githubusercontent.com/5587545/52294293-8a820a00-293e-11e9-9d29-9ae96423eefb.png">
