### ISSUE TITLE
os-packager database progress mis-reporting

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1421]
As part of #1413, we fixed up the database loading progress bar to use a different strategy. Instead of reading progress of processed resource rows, it now reports progress of successful pipeline steps against total steps. Total steps is currently a [hardcoded number in os-conductor](https://github.com/openspending/os-conductor/blob/e6fbba5230bce71112bce45c932e1b3151c9ecc0/conductor/blueprints/package/controllers.py#L201-L201). 

However, the actual total number of steps possible when processing a dataset is variable depending on the data present in the dataset, and specification generated. So progress is often [mis-reported](https://github.com/openspending/openspending/issues/1413#issuecomment-459685680).

Will need to have dpp-fiscal report the number of steps it is going to undertake, so os-conductor can perform the correct calculation.

**Comment by otterbotter** [comment]
Hi @brew 

Sorry to be the bearer of bad news again, but I ran into the same issue as before:
![failed](https://user-images.githubusercontent.com/7869992/52162684-717c1d80-26e0-11e9-927d-8b14838d71a0.PNG)

This is while I was re-uploading this dataset:
https://openspending.org/viewer/b9d2af843f3a7ca223eea07fb608e62a:expenditure-time-series-v2

The error happened after it was stuck on 11% for quite a while - though, keep in mind, this is a large dataset.

**Comment by brew** [comment]
@otterbotter No problem. Do you remember how long it took before erroring? The status key expires after 60mins, but is renewed after each step. So, if any one step takes longer than 60mins then this issue will reoccur. I can set the key expiration longer if necessary.

**Comment by otterbotter** [comment]
@brew It was definitely running for at least 60 minutes by the time the error occurred.

I've double checked again now - it seems like the dataset never updated. It is a large dataset, but is it possible that it's still running now? 

In my profile tab, the dataset still shows this red error (which I've experienced before, but it eventually goes away after the dataset has been updated). But it's been running for almost two days now, so not sure that it will finish.

![profilefailed](https://user-images.githubusercontent.com/7869992/52180997-66ff7800-27f5-11e9-8aae-8edf73f974d0.PNG)

**Comment by brew** [comment]
Looking at the logs, it seems like this didn't complete for some other reason. The reason the notification goes away in some instances is because some other part of the pipeline writes to it after it has expired, bring it back to life again! But in this instance it looks like, first the status key expired, then one of the subsequent pipeline processes failed, so the key was never brought back to life.

I've again increased the key expiry from 60mins to 24hours. That should at least alleviate the initial failure. I'd suggest trying again. I've your data from the previous issue locally with no problem.

**Comment by jbothma** [comment]
I just tried to upload but lost connection before loading into the database completed. I called it something like Budgeted and Actual expenditure.

It's not in admin right now but I'll check back later to see if it shows up.

**Comment by jbothma** [comment]
Apologies for the delay.

We have some issues with preparing the dataset. I think our issues with uploading so far were because of duplicate composite keys.

**Comment by brew** [comment]
@jbothma I'm working on a similar issue with data containing duplicate keys here: https://github.com/openspending/openspending/issues/1419

You might be interested in a couple of scripts I have for resolving the issue in different ways:

- removing duplicates: https://gist.github.com/brew/7d3297eafdbb728cb86aef97f5ce4652
- aggregating duplicate values: https://gist.github.com/brew/813706202385c79009e18e39dc39b0ed

**Comment by jbothma** [comment]
Thanks!
