### ISSUE TITLE
Uruguay functional-classification title issue

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1424]
While updating the BOOST Uruguay dataset (https://github.com/openspending/os-source-specs/pull/13), we identified that the FUNC2 column definition was missing. This has been added, but the title suggested by the variable definitions in the [data source](http://boost.worldbank.org/Data/boost/boostcms/files/field/country-attachments/boost_uruguay_v0.9_2011-2017_spanish.xlsx) is a duplicate of an existing title.

<img width="485" alt="screenshot 2019-02-20 at 15 06 12" src="https://user-images.githubusercontent.com/3993/53102124-fcec1000-3522-11e9-9f86-7078467418cd.png">

For now, I've changed the title to 'Fun Programa' (https://github.com/openspending/os-source-specs/blob/ed6ef9e0985ed5e6d04fe7e697a8b60c329b659c/america/uruguay/fiscal.source-spec.yaml#L29-L38), but this should be changed to a more appropriate title.

**Comment by sandervdwaal** [comment]
@tlacoyodefrijol can you please check this with Uruguay?

**Comment by jobarratt** [comment]
complete
