### ISSUE TITLE
Occasional CRITICAL WORKER TIMEOUT error with os-conductor

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1425]
During a package upload, os-conductor gunicorn workers restarted with a `[2019-02-20 14:59:02 +0000] [15] [CRITICAL] WORKER TIMEOUT (pid:17)` error. Not sure if it was caused by the package upload process or just bad timing.

This is a specific instance of this general class of issue: https://github.com/openspending/openspending/issues/1430

**Comment by brew** [comment]
Perhaps set up an alert in Strackdriver Metrics to monitor and report this error so we can see it in context.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
