### ISSUE TITLE
Update documentation for new developers

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1426]
Ensure documentation is up to date, with a view to getting new developers up to speed with starting development on the Openspending platform. 

Installation, testing and local development instructions should be on the individual repo READMEs and [openspending/openspending](https://github.com/openspending/openspending), and out of date instructions removed from [docs.openspending.org](https://docs.openspending.org) (https://github.com/openspending/docs).

- openspending
  - [x] [README](https://github.com/openspending/openspending)
  - [x] Read the Docs
- os-nginx-frontend
  - [x] [README](https://github.com/openspending/os-nginx-frontend)
  - [ ] Read the Docs
- os-explorer
  - [x] [README](https://github.com/openspending/os-explorer)
  - [x] Read the Docs
- os-packager
  - [x] [README](https://github.com/openspending/os-packager)
  - [x] Read the Docs
- os-viewer
  - [x] [README](https://github.com/openspending/os-viewer)
  - [x] Read the Docs
- os-admin
  - [x] [README](https://github.com/openspending/os-admin)
  - [x] Read the Docs
- os-api
  - [x] [README](https://github.com/openspending/os-api)
  - [x] Read the Docs
- os-conductor
  - [x] [README](https://github.com/openspending/os-conductor)
  - [x] Read the Docs
- os-auth-client
  - [x] [README](https://github.com/openspending/os-auth-client)
  - [x] Read the Docs
- os-fdp-adaptors
  - [x] [README](https://github.com/openspending/os-fdp-adaptors)
  - [ ] Read the Docs
- os-api-cache
  - [x] [README](https://github.com/openspending/os-api-cache)
  - [ ] Read the Docs
- os-package-registry
  - [x] [README](https://github.com/openspending/os-package-registry)
  - [ ] Read the Docs
- os-data-importers
  - [x] [README](https://github.com/openspending/os-data-importers)
  - [x] Read the Docs
- os-source-specs
  - [x] [README](https://github.com/openspending/os-source-specs)
- repository-agent
  - [x] [README](https://github.com/openspending/repository-agent)
- datapackage-pipelines-fiscal
  - [x] [README](https://github.com/openspending/datapackage-pipelines-fiscal)
  - [x] Read the Docs
- os-types
  - [x] [README](https://github.com/openspending/os-types)
- os-dpp-runner
  - [x] [README](https://github.com/openspending/os-dpp-runner)

**Comment by roll** [comment]
@brew 
Here's my quick overview and try to run things. 
Here I do things if I (which is not far away from reality=):
- have no idea about OpenSpending
- a designer who just needs to run some app and fix some design OR
- something similar
So I just try to do what readmes say. 
Sorry if there are mistakes from my side I had very limited time to try a lot)

---

- [ ] ReadTheDocs
    - [ ] developers-contributors-users - for me it was kinda confusing classification. I mean Code contributorss vs Data contributors
    - [ ] getting started sections is kinda confusing because it contains links to following sections in the middle (breaking read as a book flow)
    - [ ] I wouldn't bind user-facing docs with any mentions of underlaying services (as a user I probably don't care that app's name is "Viewer" etс). But I'm not sure on it..
    - [ ] https://docs.openspending.org/en/latest/contributors/prepare/ - goodtables cli example outdated
    - [ ] https://docs.openspending.org/en/latest/contributors/use/ - empty
- [ ] openspending
    - cannot start service db/es/.. `ERROR: for openspending_db_1  Cannot start service db: driver failed programming external connectivity on endpoint openspending_db_1 (eb8a82aa15366ed6d4e19373686714105f8c4faa59af96398d6ee68c81fee082): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind`
- [x] os-explorer
    - no .env.example
    - no OS_BASE_URL explanation for dev
    - no docs/notes about docker build
    - no node@8 requirement in the readme
- [x] os-packager
    - no OS_BASE_URL explanation for dev
    - no node@8 requirement in the readme
    - no docs/notes about docker build
    - OS_PACKAGER_BASE_PATH= is required no optional
    - npm test - fails
    - npm start - no images/css/etc
- [ ] os-viewer
    - no .env.example
    - no OS_BASE_URL explanation for dev
    - no node@8 requirement in the readme
    - npm install - super weird but fails with a lot of ENOENT: no such file or directory (fixed by removing package-lock.json)
    - no npm test in readme
    - OS_VIEWER_BASE_PATH= is required not optional
    - no docs/notes about docker build
    - npm start
        - loading if base=localhost
        - redirect to openspending if base=openspending
- [x] os-admin
    - no OS_BASE_URL explanation for dev
    - no node@8 requirement in the readme
    - no docs/notes about docker build
- [ ] os-api
    - no .env.example
    - no docs/notes about docker build
    - no command to install dependencies in readme
    - python dev_server.py - fails because I need to setup services (should I use info from the "testing" session for dev?)

**Comment by roll** [comment]
And BTW the work on docs is very impressive in overall :+1:

**Comment by brew** [comment]
Thanks - can you tell me what command you used when you received the `ERROR: for openspending_db_1 Cannot start service db` error?

**Comment by roll** [comment]
@brew 
Sorry I missed it out
```
docker-compose -f docker-compose.base.yml -f docker-compose.dev-services.yml  up
```
My error is something like this https://github.com/docker/compose/issues/3277

**Comment by brew** [comment]
Perhaps this is a docker-compose issue? Which version are you running (`docker-compose -v`)? I'm using `docker-compose version 1.23.2, build 1110ad01`.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) nor assignee as part of #1478. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
