### ISSUE TITLE
As a data owner I would like to be able to link back to my portal homepage from OpenSpending Viewer

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1429]
When people view our datasets in OS Viewer, we would like them to easily see that they are related to the vulekamali data portal and find their way to the portal.

If we embed OpenSpending Viewer in our site and people share the embed on social media, or if we share links to specific views of data in OpenSpending, we want people to find their way to vulekamali to find more documentation and contextualisation of the data.

Currently the owner profile doesn't seem to be featured on a dataset view in OS Viewer.

It would probably be good if the owner, owner profile image, and a link of the owner's choosing, and perhaps contact details, could be shown in OS Viewer.

In the interim, we can probably place this information in dataset descriptions.

HackDash has something like that - the little link icon on a dashboard can link back to an "event site":

![hackdash-homepage-link](https://user-images.githubusercontent.com/235801/54076253-3c9c5100-42b2-11e9-93e8-48367b5c4fb8.png)

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. The author did not follow up yet. Please feel free to re-open if this is still relevant.
