### ISSUE TITLE
Example of how an OFDP high-quality dataset should look like

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1431]
In order to push governments to improve publication, we want to have an example dataset of what they should aim for when publishing using OFDP. 
This should be the "gold standard". We can use worked examples of the dataset. See [OCDS](http://standard.open-contracting.org/latest/en/schema/reference/?highlight=example#worked-example)

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
