### ISSUE TITLE
Automate deployment to Kubernetes

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1432]
Currently, we have a workflow based on Github --> Travis --> Docker Hub, when work is committed to the master branch for each component application. We use the git commit hash as a Docker image tag, and reference that within our Kubernetes deployment. Kubernetes deployments are then carried out manually. We would like to improve this by automating the Kubernetes deployment step. This is an Open Knowledge organisation-wide issue.

There are some suggestions for implementation in okfn/devops#122. Other suggestions are to investigate gitops deployments: https://www.weave.works/technologies/gitops/.

LInked to okfn/devops#122.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
