### ISSUE TITLE
Pipeline progress gets stuck after updating os-data-importers

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1433]
If os-data-importers is updated, all the pipelines will be rerun. Sometimes progress stops and not all pipelines complete. This is usually fixed by clearing the Redis database used to manage pipeline status, and restarting the os-data-importers pod. Perhaps Redis should be run from inside the os-data-importers pod, rather than in a pod of its own to ensure it is cleared and ready?

To workaround this I usually `FLUSHDB` the redis databases `5` and `10`, and restart os-data-importers. It's odd that this is necessary, as these databases are flushed as part of [os-data-importers initialisation process](https://github.com/openspending/os-data-importers/blob/a93bc7c7f15454dc5b8ee7864ba492ecd9bd68e4/initialize.sh#L14-L15).

On the OKI cluster, this is the procedure:

1) Log in to the redis pod:
```sh
$ kubectl exec -n production openspending-data-importers-production-redis-master-0 -it bash
```

2) Flush databases `5` and `10`:
```sh
$ redis-cli -n 5 FLUSHDB
$ redis-cli -n 10 FLUSHDB
```

3) Exit the pod!
```sh
$ exit
```

4) Replace the os-data-importers pod
```sh
kubectl get pod openspending-data-importers-production-<pod-id> -n production -o yaml | kubectl replace --force -f -
```

**Comment by sandervdwaal** [comment]
Don't know if it's related, but the pipeline again didn't fully run successfully.
Croatia has a second pipeline and it keeps 'waiting to run' https://pipelines.openspending.org/source-specs/os-source-specs/europe/croatia

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
