### ISSUE TITLE
Pipelines automatically re-run each time os-data-importers is restarted

### ISSUE THREAD

**Issue by brew** [openspending/openspending#1434]
Rerunning all the pipelines is super-slow (hours). Perhaps they shouldn't automatically rerun by default each time os-data-importers is redeployed. This would likely require only re-initialising Redis if it hasn't already been initialised. Perhaps also retaining the artifact files that are created by dependent pipelines. Potentially tricky to retain pipeline state between redeployment without tricky bugs.

Related to #1433.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) nor assignee as part of #1478. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
