### ISSUE TITLE
Mexican dataset disappeared from OS unexpectedly 

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1435]
Reported by Lorena: 

> A Mexican dataset used for the helpdesk announcement starts loading but then sends the user to the search page instead of opening. This is the one:
https://openspending.org/viewer/667df60aa07c34260eae9b55b2778712:presupuesto_mexico?lang=en

I noticed that any URL for the OS Viewer that doesn't refer to an actual dataset has this same behaviour:  https://openspending.org/viewer/[whatever] will show the viewer page as it tries to load the dataset, then redirects to the frontpage if it fails. I think the user experience can be improved here so that the user knows what's going on (creating separate issue for that).

**Comment by sandervdwaal** [comment]
URL works again after the pipelines have rerun successfully. @akariv do you know how the dataset can have disappeared? Are they deleted when the pipeline gets rerun for example? Is there a way to prevent deletion during pipeline running?

**Comment by akariv** [comment]
I can't say exactly -  generally pipelines that haven't changed shouldn't re-run at all.
But there was some data corruption in the pipelines state, so it might explain it.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. There is also duplicate data at this point. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
