### ISSUE TITLE
Improving OS Viewer flow when trying to load non-existing dataset

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1436]
Any URL for the OS Viewer that doesn't refer to an actual dataset provides the following user experience when trying to load it in the browser (eg. : https://openspending.org/viewer/non-existing-dataset:id ):

1. The OS Viewer page gets displayed
2. Inside the OS Viewer page, a throbber is shown to indicate a dataset is being loaded
3. The user gets redirected to the frontpage https://openspending.org without any indication that something went wrong.

No feedback is given to the user about the fact that she tried to view a non-existing dataset. 
Keeping in mind that users will usually end up on this URL only when they know there should be a dataset there, an error message is more appropriate, eg:

*Dataset could not be loaded.*

Is there is more technical information available about what went wrong? Then we can consider showing that too. 

It's good to give people an option on what to do next. I'm thinking of two alternatives:
1. Integrate the search box that's currently on the homepage, if that's possible? 
2. Display a link to the OS Explorer, eg. https://openspending.org/s or https://openspending.org/s/?viewAll

**Comment by LorenaGIFT** [comment]
If the reason is that it could not be loaded indeed (not the case of not existent), could we get a notice as well and then the message could display such action? "Dataset could not be loaded. Open Spending will look into it", otherwise "Dataset could not be loaded. Let us know what happened to openspending-support@...."

About the alternatives, it could say "You can try searching for more datasets here" and option 1 would be best, but either are good.

**Comment by sandervdwaal** [comment]
Let's go with this error message: 

_"Dataset_ could not be loaded. Let us know what happened to openspending-support@okfn.org"_

Promising we'll look into it without the user letting us know implies that we track these kinds of request which I believe is not easily possible (@akariv correct me if I'm wrong)

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
