### ISSUE TITLE
Can't properly map two types of subprojects 

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1437]
The spend data file from Argentina has a structure that has two types of sub-projects: 'actividad' (activity)  and 'obra' (public work). Other countries in Latin America have a similar distinction between these separate types of sub-projects, but it's not possible in the FDP to map these separately, as there's only: 
> activity:generic:project:code
> activity:generic:project:label
> activity:generic:subproject:code
> activity:generic:subproject:label

The suggestion is to create a new type of subproject, at the same level as the current one (so a child of `activity:generic:project:code` to be able to distinguish between these two.

**Comment by sandervdwaal** [comment]
This needs a change in the FDP spec, which is logged here: https://github.com/frictionlessdata/specs/issues/626

**Comment by akariv** [comment]
The way to accomplish this is to add a project type column Type, as this describes the project and is not an actual 'sub-project'.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
