### ISSUE TITLE
Unexpected duplicate-key error for dataset with extended classifications

### ISSUE THREAD

**Issue by sandervdwaal** [openspending/openspending#1438]
When using the OS Packager to upload a dataset with Argentinian spending data, it throws a duplicateKeyExpection when the data itself does not contain duplicate rows.

![image](https://user-images.githubusercontent.com/420482/55174745-495be880-517e-11e9-9155-4e7c905ac90e.png)

As the image shows, there's an extensive mapping of several levels of functional and administrative classifications, as well as several levels of activity. 
The 10k rows are all unique wrt these classifications, but still the duplicate key exception is thrown:

> Key (activity_id, administrative_classification_id, administrator_id, date_id, economic_classification_id, fin_source_id, functional_classification_id)=(19, 1, 166, 1, 1, 1, 127) already exists.

It is expected that multiple rows will exist with this top level classifications, because there are further levels of these classifications which makes the overall row unique.

**Comment by sandervdwaal** [comment]
The datafile I'm aiming to upload is here: https://drive.google.com/open?id=1BptgX4PyPVa_h3_2JZhBtdpWk3TLCiHL

It says 100k but in fact it's 10k rows, total file size 10MB

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (>1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
