### ISSUE TITLE
Upload status retrieval fails with no way to track upload state

### ISSUE THREAD

**Issue by otterbotter** [openspending/openspending#1442]
This is related to an issue that was apparently resolved in https://github.com/openspending/openspending/issues/1367

The ID of the specific dataset that I'm uploading is `budgeted-and-actual-national-expenditure-v6`

Upon uploading a larger dataset, the progress bar fails to fetch the latest state of the upload.
This is frustrating since there's no way to track if the upload actually failed or if it's still in progress.
![stillfailing](https://user-images.githubusercontent.com/7869992/55951066-a2378080-5c56-11e9-91f0-d2295aeb4d88.PNG)

**Comment by jobarratt** [comment]
@nightsh we will address this next week but if you have time to take a look before that it would helpful as this is an big blocker for SA

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (~1 year) as part of #1478, _"last week"_ doesn't apply anymore :smile:. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
