### ISSUE TITLE
Install Jenkins on cluster to replace dpp dashboard

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1445]
- Install Jenkins on cluster
- Make sure that it has access to secrets required for writing to DBs
- Create tasks to run new openspending-dataflows for specific partners
- Create partner users that only have access their task

**Comment by jobarratt** [comment]
@akariv can this be closed? The note in the Roadmap says so.

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (~1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
