### ISSUE TITLE
Change Open Knowledge International text to Open Knowledge Foundation in OpenSpending website footer

### ISSUE THREAD

**Issue by StephenAbbott** [openspending/openspending#1447]
On Monday 20th May 2019, we will announce that Open Knowledge International is rebranding back to Open Knowledge Foundation. As part of this announcement, I am working my way round lots of our websites to update any OKI references to OKF.

In the footer on https://openspending.org, there is a sentence which reads 'An Open Knowledge International project in collaboration with Open Knowledge Germany, Open Knowledge Greece, and the wider open fiscal data community'.

Could this please be changed to read 'An Open Knowledge Foundation project in collaboration with Open Knowledge Germany, Open Knowledge Greece, and the wider open fiscal data community'?

The OKI white transparent logo in the footer will automatically update to a new OKF version after I make changes to the [branding.okfn.org assets stored on Github](https://github.com/okfn/branding/tree/master/branding/assets).

**Comment by jobarratt** [comment]
@StephenAbbott we are looking at this for this week. Added to current sprint

**Comment by tlacoyodefrijol** [comment]
@StephenAbbott this has been changed, but just as a heads up, the footer grabs the logo from https://github.com/okfn/a/tree/master/a/img/oki, we would need to update that source for it to change the footer in OpenSpending.

**Comment by nightsh** [comment]
Deployed in [2ffc400865d1611f2ee90dc58879385380108873](https://github.com/okfn/devops/commit/2ffc400865d1611f2ee90dc58879385380108873)
