### ISSUE TITLE
Create a new Pipeline for Argentina

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1448]
Argentina has updated their budget/spending files to a new structure. We need to start a pipeline to upload their data to OpenSpending. The mapping is available in the country files. 
Dataset to use is here https://datos.gob.ar/dataset/sspre-presupuesto-administracion-publica-nacional-2019/archivo/sspre_170

@akariv will use the updated pipeline process to test with this dataset

**Comment by tlacoyodefrijol** [comment]
The Argentinian data is now ready for publication. Pull request is done [here](https://github.com/openspending/os-source-specs/pull/21). 
@lorenagift there are two fields that weren't mapped. 
- ultima_actualizacion_fecha
- credito_pagado
We will map `ultima_actualizacion` as a `date` and `credito_pagado` is a regular `amount`. Once done, we will run the pipeline and the Argentina data will be up in a couple of hours.

**Comment by LorenaGIFT** [comment]
@tlacoyodefrijol ok I will wait for the result and to send it to Gustavo

**Comment by nightsh** [comment]
https://openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:credit_and_full_budget_expenditures_for_the_current_fiscal_year_of_the_national_public_administration?lang=en
