### ISSUE TITLE
Issues with numbers and characters in Croatian Dataset

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1449]
We have updated the Croatian Data from 2016 to 2019 but there are a few errors in the characters and the amounts. Description from Croatian Gov below.

> On the first view, without detail checking, I noticed character set problem:
`Opæe javne usluge`

This is probably due to changing the file and issues with encoding. Verify there are no errors like this when changing the original datasets. 

> and thousand separator problem:
`1.68 Milijarda`

> This should be 16,8 milijuna (16 800 000).  Milijarda would be 16 800 000 000.
In CSV file, the number for economic code 323 (above is the sum for 3 economic codes, so it's slightly different) is 16.100.000,00 (with Croatian regional settings) precisely it is in Croatian words 16 milijuna(millions) i(and) 100 tisuća(thousands). It's not 1,61. Here it's is a possible problem with the decimal separator in the upload process caused by different regional settings.

> n Croatian, 1 milijun = 1.000.000,00, and 2 milijuna, 3 milijuna, but 101 milijun (one hundred and one milijun).  I would use milijuna because it will cover 99% of cases, but I will have to ask for some language advice and let you know.
1 milijarda = 1.000.000.000,00
The same as with milijun, it's 1 milijarda, 2 milijarde, 3 milijarde . . .5 milijardi,  6 milijardi, but 101 milijarda,  102 milijarde. Same as above.

> In Croatian, 1 milijun = 1.000.000,00, and 2 milijuna, 3 milijuna, but 101 milijun (one hundred and one milijun).  I would use milijuna because it will cover 99% of cases, but I will have to ask for some language advice and let you know.
1 milijarda = 1.000.000.000,00
The same as with milijun, it's 1 milijarda, 2 milijarde, 3 milijarde . . .5 milijardi,  6 milijardi, but 101 milijarda,  102 milijarde. Same as above.

It seems like the separator is confusing OS into thinking the numbers are different. We need to make sure it's being correctly read.

**Comment by nightsh** [comment]
Would be useful to have the datasets hosted externally, so it would be easier to maintain / update them. In this case, we would not be in charge of updating datasets, but only of re-running the pipelines, which might ease everyone's work.

As for the decimals, I'll have another look at the source spec. If we get newer data sets aligned to different standards (i.e. [ISO 31-0](https://en.wikipedia.org/wiki/ISO_31-0#Numbers)) it might be easier to parse but we'll need to change the data package spec.
