### ISSUE TITLE
Workflow for updating existing data

### ISSUE THREAD

**Issue by chk1** [openspending/openspending#1451]
I have trouble figuring out the "correct" workflow for updating an existing data set. I have uploaded fiscal data some time ago and now there's new data for the upcoming year, I keep all data in a single big CSV.

In another issue (https://github.com/openspending/openspending/issues/1403) I found this information:

> It looks like I can replace the datapackage by giving it the same ID in OS Viewer.

I tried that and the outcome is that in OS Admin I says that my package was updated, but
- it still shows the old file name in OS Viewer
- the new year does not appear in visualization options/filters in OS Viewer
- new data not found in the table

My data set id: `7f037f45d2f473af5e754509a5bc9667:muenster-haushalt`

If it is not possible (or recommended) to update existing data, is there a way to obtain the "schema file" that can be uploaded instead of me filling in all fields in OS Packager? I would like to place this in my git repo to have a reproducible workflow. I tried the file obtained from `https://openspending.org/api/3/info/<id>/package` but using that fails in the OS Packager with this message: `No matching fields in the schema` (CSV header on the updated file is the same as in my existing data)

**Comment by chk1** [comment]
Any guidance, please?

**Comment by schlos** [comment]
+1

I'm also having same issue of trying to use schema file instead of using GUI to click through all fields config.

**Comment by chk1** [comment]
I got a response regarding schema files on the OKF forums https://discuss.okfn.org/t/updating-an-existing-dataset/8586/2

I found it hard to work with, still unable to update, I've not done any more testing since

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing issue as part of #1478. Data will be migrated to the DataHub platform. Please feel free to re-open if this is still relevant once the migration has taken place.
