### ISSUE TITLE
Review Dominican Republic upload

### ISSUE THREAD

**Issue by jobarratt** [openspending/openspending#1454]
To review the recent upload of data to OpenSpending by the Dominican Republic

**Comment by tlacoyodefrijol** [comment]
Link to the datasets 2014-2019
https://openspending.org/s/?q=dominicana

**Comment by akariv** [comment]
'OpenSpending works best when working on a full budget database and not on a series of aggregated views of the data. If you could send us a full, denormalized dataset it would be best.'
