### ISSUE TITLE
Issues with decimals in Argentina and Croatia datasets

### ISSUE THREAD

**Issue by nightsh** [openspending/openspending#1456]
These could've been two separate issues, but as they're both small and somewhat related I'm gonna bundle them up in one piece.

- [x] Argentina
  - the values in the source spreadsheets have up to 8 decimals, ~yet the pipeline shaves off most of them~ but viewer only displays two - we need to keep the very precise numbers we've got *(L.E.: do we?)*
- [x] Croatia
  - decimal separator was lost and the decimals incorporated into the integer part (e.g. 79474158,81 became 7947415881)

**Comment by nightsh** [comment]
Update: Argentina pipeline seems to maintain the decimals. The issue is probably on the viewer side, will investigate.

**Comment by nightsh** [comment]
PR is obsolete, as the issue was in tableshema-py instead, which @akariv fixed and we both tested to see it works. I will rerun the pipeline using the updated lib and close the PR.

**Comment by nightsh** [comment]
Here's what I found so far, further investigation will be conducted only if needed (i.e. this is considered an issue):

- os-viewer doesn't do anything to the values
- babbage.ui uses a value formatter in its templates, as follows:

```html
          <span ng-if="tableData.headers[$index].numeric">{{ valueFormatter(row) }}</span>
```

However, I'm not sure this is an issue. I would wait for feedback on Argentinian data first.

**Comment by tlacoyodefrijol** [comment]
Related to the publication of Argentina in #1448
