### ISSUE TITLE
Remove all API calls from babbage-ui that fetch the Babbage model

### ISSUE THREAD

**Issue by nightsh** [openspending/openspending#1464]
The current implementation of babbage-ui makes an API call to fetch the Babbage model.
The task is to remove that call and use a model (same model, for now) provided / passed by os-viewer.

- [x] amend babbage-ui to not call the API for the model
- [x] amend os-viewer to pass down the model to babbage-ui
- [x] check for any side effects (documentation, tests, etc.)
- [x] publish a new babbage-ui release & deploy changes

*Linked to #1444*

**Comment by akariv** [comment]
I reviewed all PRs and it's good to go for completing the last step.
