### ISSUE TITLE
Argentina data update

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1465]
When updating the pipeline to the new monthly budget and spending report, the download of the dataset is hanging and not allowing to run the pipeline. There seems to be a specific error. 
@nightsh has more specific details about it below

**Comment by nightsh** [comment]
To follow-up on this:

The "download" button on [this page](https://datos.gob.ar/dataset/sspre-presupuesto-administracion-publica-nacional-2019/archivo/sspre_164) leads to [this file](https://www.presupuestoabierto.gob.ar/datasets/2019/credito-mensual-2019.zip) but I cannot retrieve it:

> www.presupuestoabierto.gob.ar’s server IP address could not be found.
> DNS_PROBE_FINISHED_NXDOMAIN

Maybe there's an issue with how data is stored? Or maybe I'm doing something wrong, in which case I'll be happy to amend the source code so it would retrieve the data.

**Comment by tlacoyodefrijol** [comment]
@nightsh the Argentinian team sent a few observations about their data. Observations are as follow:

>  Our dataset is expressed in millions, so the budget total and most of the totals are in "Millions of millions". In Argentina we called this "a billion"
  Please note that here in Argentina a billion is "1.000.000.000.000" and in USA and many countries this number is known as "a trillion" 
  I think that you have to put "Billion" or "Trillion" instead of "Million" and "Million" when you use "Miles"

I think this is because their dataset is captured in millions already. So the Viewer is only showing the "Thousands", not the thousands of millions. Is there a way to capture this in the pipeline?

>Measures (medidas)
                    The order of the measures should be: 
                           vigente
                           comprometido
                           devengado
                           pagado
       
>Jerarquias (hierarchies)
 In many menus (hierarchies or filters) and/or graphics you should show the descriptions of the classifications, not only the ids. For example: in "economic classification" or "functional classification" 

We're currently only seeing IDs. Attached screenshot for reference. We should be seeing the descriptions for each field. Probably a mapping issue. 
<img width="1403" alt="Screen Shot 2019-06-24 at 17 33 05" src="https://user-images.githubusercontent.com/5587545/60056367-4356a480-96a6-11e9-9ac5-542ba444c37e.png">
                      
>   Actividad: 
It's wrong to use "activity" as a single classification. You should replace for "program", cause the "activity" is a part of the program hierarchy. 
And, the most important thing is that the "program" depends of the administrative classification. The id of the program is not unique. For example, there's a lot of program_id = 16 and they are different if they depend on different jurisdiccion, subjurisdiccion, entidad, servicio. You should be running this query in order to see the combinations:
"select distinct (jurisdiccion_id, subjurisdiccion_id, entidad_id, servicio_id, program_id.....) from Arg_dataset....."                        
So, you have to take care about it cause where you want to navigate into a treemap (for example) the description of the program is wrong

This one is related to #1443. I think @akariv is more familiar with how to fix this issue. 

>Clasificacion Administrativa: 
You should avoid showing "Sector and subsector" cause they have always the same values "1". The best to do is avoid Character too (i know there are different values there). 
                           The administrative classification should be: 
                                    `jurisdiccion_id, subjurisdiccion_id, entidad_id, servicio_id`
            
>Object Class classification:
You are not showing the object_class classification ('inciso_id, Principal_id, Parcial_id, Subparcial_id`). It is important to use it, it shows people what are the things you are spending on (for example...buying computers, paper, etc.). 

>Administrador:
I assume that this field corresponds to Unidad Ejecutora. The best way to show it is with the jurisdiccion (`id + desc`) + Unidad_Ejecutora

>Fecha:
I don't think that `Fecha` is relevant to put then as a hierarchy. Now is shown only one date and perhaps it's better not to show it. Otherwise is better to put something like "month"

>Clasificacion funcional:
I think you are using the wrong fields. The functional classification only have 2 levels (`finalidad` and `function`) and you are using a deeper hierarchy. Please check it.
Also in this case it's better to show the complete hierarchy (`finalidad_id + finalidad_desc + funcion_id +Funcion_desc`) instead of having 2 levels

>Filtros (filters)
programa_id: the most important thing is that the "program" depends of the administrative classification. The id of the program is not unique. For example, there's a lot of program_id = 16 and they are different if they depend on different jurisdiccion, subjurisdiccion, entidad, servicio. 

                      
>Sector_id: it always have the same value. Make no sense to have it. 

>Unidad Ejecutora: The best way to show it is with the `jurisdiccion` (id + desc) + `Unidad_Ejecutora`.
                                 
>Economico_id: you should put the description 
                 `Impacto presupuestario_ano`: replace it with Ejercicio_presupuestario

>Finalidad_id: you should put the description with the code

**Comment by tlacoyodefrijol** [comment]
- The values in the source spreadsheets have up to 8 decimals, yet the pipeline shaves off most of them but viewer only displays two - we need to keep the very precise numbers we've got (L.E.: do we?)
