### ISSUE TITLE
Incorrect encoding when downloading Croatian data

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1468]
When you download any of the CSVs for Croatian data, the content has a different encoding and shows strange characters. 
<img width="1514" alt="Screen Shot 2019-07-02 at 12 12 10" src="https://user-images.githubusercontent.com/5587545/60532347-ba052a80-9cc2-11e9-8595-33b577767d82.png">

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (~1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
