### ISSUE TITLE
Mexico data not updating correctly

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1471]
Mexico updated their 2019 and reported the Viewer and the Json it is not bringing the fields of:

1. DESC_CONCEPTO
2. DESC_CAPITULO
3. DESC_PARTIDA_ESPECIFICA

https://openspending.org/api/3/cubes/667df60aa07c34260eae9b55b2778712:presupuesto_mexico/facts/?cut=ID_RAMO.ID_RAMO:%2212%22|ID_MODALIDAD.ID_MODALIDAD:%22U%22|ID_PP.ID_PP:%225%22|CICLO.CICLO:2018&pagesize=100000
![image011](https://user-images.githubusercontent.com/5587545/62638931-141d8f00-b904-11e9-8deb-832ef44a5ee3.jpg)

https://openspending.org/api/3/cubes/667df60aa07c34260eae9b55b2778712:presupuesto_mexico/facts/?cut=ID_RAMO.ID_RAMO:%2212%22|ID_MODALIDAD.ID_MODALIDAD:%22U%22|ID_PP.ID_PP:%225%22|CICLO.CICLO:2019&pagesize=100000
![image012](https://user-images.githubusercontent.com/5587545/62638978-27c8f580-b904-11e9-9565-ccceb9f3ee57.jpg)

**Comment by akariv** [comment]
From what I can see, there was a change in June to the name of the dataset:

```diff
commit a24b2f8331f1a1ffd4729e64e3528e5639cf68bb
Author: Transparencia Presupuestaria <trans_presupuestaria@hacienda.gob.mx>
Date:   Fri Jun 21 13:46:56 2019 -0500

    Update fiscal.source-spec.yaml

diff --git a/america/mexico/fiscal.source-spec.yaml b/america/mexico/fiscal.source-spec.yaml
index 4305c87..fe5a1be 100644
--- a/america/mexico/fiscal.source-spec.yaml
+++ b/america/mexico/fiscal.source-spec.yaml
@@ -1,6 +1,6 @@
 title: "Presupuesto México 2008-2019"
-dataset-name: Presupuesto_mexico
-resource-name: presupuesto_mexico
+dataset-name: Presupuesto_mexico_2008_2019
+resource-name: presupuesto_mexico_2008_2019
```

Which means that the data update in August happened on that dataset and not on the 'correct' one:
https://openspending.org/api/3/cubes/667df60aa07c34260eae9b55b2778712:presupuesto_mexico_2008_2019/facts/?cut=ID_RAMO.ID_RAMO:%2212%22|ID_MODALIDAD.ID_MODALIDAD:%22U%22|ID_PP.ID_PP:%225%22|CICLO.CICLO:2019&pagesize=100000

<img width="902" alt="Screen Shot 2019-08-29 at 19 01 09" src="https://user-images.githubusercontent.com/265333/63956598-6a0ece00-ca8f-11e9-9b92-f050a2316838.png">

I reverted the dataset name now and the data will update (hopefully) to the correct dataset.
