### ISSUE TITLE
Old OS visualization for Uruguay

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1472]
The government of Uruguay is using an old OpenSpending visualization that they have modified and show in their website. 
Now that their data is published on OS, they want to find if they can:
1. Use the visualization as a standalone feature on their website, without using the old OS instance. 
Visualization is here https://transparenciapresupuestaria.opp.gub.uy/inicio/presupuesto-nacional/a-d%C3%B3nde-van-nuestros-impuestos
2. Connect their recently uploaded data through the API to populate the visualization. Current JSON structure is here https://transparenciapresupuestaria.opp.gub.uy/advni/datos/aggregate2019.json

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (~1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
