### ISSUE TITLE
Push data into AWS

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1473]
When publishing, push the resulting denormalized data (i.e., before normalization occurs) to an AWS bucket.

- [x] Create a `dataflows-aws` library
- [x] create a `dump_to_aws` processor with similar semantics to `dump_to_path` (you can take inspiration - or most of the code - from `datapackage-pipelines-aws`)
- [ ] In the publication flow, replace the part where data is dumped locally to a `dump_to_aws` call (or do it only if correct env vars are defined)

**Comment by roll** [comment]
The lib is done:
- https://github.com/frictionlessdata/dataflows-aws
- https://pypi.org/project/dataflows-aws/

**Comment by sglavoie** [comment]
WONTFIX/CLEANUP: Closing old issue without recent activity (~1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
