### ISSUE TITLE
Create combined datapackage with all resources

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1474]
We want to create a data-package which contains links to all different resources in the same OS Package (e.g. one resource per uploaded year data file)

This datapackage would be stored on AWS and its URL would be placed in the `origin-datapackage` property in the Package Registry record (i.e. in elasticsearch).

- [ ] Add to the publication phase another step
- [ ] In this step, scan all existing configuration
- [ ] Locate those with the same taxonomy_id and dataset-name
- [ ] Calculate  the location of their AWS data files (see issue #1473)
- [ ] Create datapackage with url-resources pointing to those resources
- [ ] Push datapackage.json to AWS
- [ ] Store resulting URL in package registry

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. GIFT Phase IV was closed. Please feel free to re-open if this is still relevant.
