### ISSUE TITLE
Allow editing of field properties in UI

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1475]
While DGP supports custom field options in the mapping / taxonomy (e.g. `decimalChar`, `format` or `currency`), it's still not supported via the UI.

We'd like to be able to edit these options in the UI in the mapping phase -allow adding custom properties to each field.

**Comment by jjalcolea** [comment]
Not sure if this is relate or not to this issue, but the importer is apparently ignoring the currency information in the JSON file. After loading the file, in the UI it applies US dollars to all amounts, even if they are explicitly defined as EURos in the descriptor, i.e.: 
`"measures": {
      "credito_inicial": {
        "source": "credito_inicial",
        "title": "credito_inicial",
        "currency": "EUR",
        "direction": "revenue",
        "phase": "proposed"
      }`

Thanks,

Juanje.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~1 year) as part of #1478. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
