### ISSUE TITLE
Argentina classification issues

### ISSUE THREAD

**Issue by tlacoyodefrijol** [openspending/openspending#1476]
Clasificacion Administrativa:
You should avoid showing "Sector and subsector" cause they have always the same values "1". The best to do is avoid Character too (i know there are different values there).
The administrative classification should be:
jurisdiccion_id, subjurisdiccion_id, entidad_id, servicio_id

Object Class classification:
You are not showing the object_class classification ('inciso_id, Principal_id, Parcial_id, Subparcial_id`). It is important to use it, it shows people what are the things you are spending on (for example...buying computers, paper, etc.).

Administrador:
I assume that this field corresponds to Unidad Ejecutora. The best way to show it is with the jurisdiccion (id + desc) + Unidad_Ejecutora

Fecha:
I don't think that Fecha is relevant to put then as a hierarchy. Now is shown only one date and perhaps it's better not to show it. Otherwise is better to put something like "month"

Clasificacion funcional:
I think you are using the wrong fields. The functional classification only have 2 levels (finalidad and function) and you are using a deeper hierarchy. Please check it.
Also in this case it's better to show the complete hierarchy (finalidad_id + finalidad_desc + funcion_id +Funcion_desc) instead of having 2 levels

Filtros (filters)
programa_id: the most important thing is that the "program" depends of the administrative classification. The id of the program is not unique. For example, there's a lot of program_id = 16 and they are different if they depend on different jurisdiccion, subjurisdiccion, entidad, servicio.

Sector_id: it always have the same value. Make no sense to have it.

Unidad Ejecutora: The best way to show it is with the jurisdiccion (id + desc) + Unidad_Ejecutora.

Economico_id: you should put the description
Impacto presupuestario_ano: replace it with Ejercicio_presupuestario

Finalidad_id: you should put the description with the code

There is also an issue with subprojects. See #1437.

**Comment by tlacoyodefrijol** [comment]
Fix is mostly done, Lorena shared a few extra observations. Comments are below. 

Date is still a Hierarcy:
![unnamed](https://user-images.githubusercontent.com/5587545/68430156-2ca47c00-0175-11ea-8452-c544e87a94e5.png)

Instead of object_classification it should read "Objeto del Gasto"
![unnamed-1](https://user-images.githubusercontent.com/5587545/68430183-3d54f200-0175-11ea-9cb6-57045f4dc436.png)

Why is there a Hierarchy called Desconocido 
![unnamed-2](https://user-images.githubusercontent.com/5587545/68430210-43e36980-0175-11ea-99b0-6b7073e4903c.png)

There seems to be an error on the mapping. On this screenshot she's looking at the Administrative Classification but the treemap reads "Administración Nacional de la Seguridad Social", and the bread crumbs read "0-Servicio de la Deuda Pública".
![unnamed-3](https://user-images.githubusercontent.com/5587545/68430222-48a81d80-0175-11ea-9949-dc7035f8d464.png)

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>8 months) as part of #1478. Data will be migrated and merged into the DataHub.io platform. Please feel free to re-open if this is still relevant.
