### ISSUE TITLE
Clean up issue tracker (July 2020) - triage, close  etc

### ISSUE THREAD

**Issue by rufuspollock** [openspending/openspending#1478]
Currently 85 open issues, 5 open milestones and a GIFT Phase IV project board.

Let's get these triaged and anything old closed so we have a clean space to work from.

TODO: see issue like this on f11s and use that for inspiration.

**Comment by sglavoie** [comment]
@rufuspollock — **Done.**

* There might still be a couple of issues that can be closed. They are now all cleanly triaged in the board: https://github.com/openspending/openspending/projects/2

**Comment by sglavoie** [comment]
**FIXED**: Closing because everything was closed, no more action needed.
