### ISSUE TITLE
OS accepts models which it can't visualise

### ISSUE THREAD

**Issue by mk270** [openspending/openspending#579]
The model file referenced from the install docs does not have "drilldowns" after the right manner, and this causes an exception in the javascript attempting to render them

**Comment by mk270** [comment]
would it be possible for OS to commit to a particular set of input/model formats/schemas for some time period. such that interoperating implementations of some components can be developed?

**Comment by pudo** [comment]
Have you looked at: https://github.com/openspending/fiscal-data-package :)

**Comment by mk270** [comment]
Have you looked at how often that changes? Is there any credible undertaking to freeze that spec for long enough for independent implementations? (This is a serious question, not snark / log-rolling etc)

**Comment by pudo** [comment]
I'm going to try and implement it this month. Good question, but it's probably more important to get it right than to freeze it. Seemed to me like there might be a bit of work left.

**Comment by pwalsh** [comment]
@mk270 we don't expect wide implementations on the spec at this stage, but we are:

1. Iterating on the spec in public, with the goal of getting it right, rather than arbitrarily freezing it
2. Building out tooling ourselves, which can serve as reference implementation for others

**Comment by mk270** [comment]
You're never going to get a single implementation, even your own, if you keep iterating the spec like this. We've had half a decade to sort this out. It's obviously not working.

**Comment by pwalsh** [comment]
@mk270 ok, thanks :).

**Comment by rgrp** [comment]
@mk270 really appreciate the sensible forces of conservatism. I think you've gone from something still not being perfect to it not work. We are making huge progress here - hold in there and we'll have something i think you can be proud of :-)

**Comment by mk270** [comment]
I'm glad to hear some participants do not regard conservatism as unconditionally and unequivocally wrong.

**Comment by pudo** [comment]
In fact, the entire Node.js community appears to be pillared on such
principles.

**Comment by mk270** [comment]
I love it when you talk dirty!
