### ISSUE TITLE
Add fields to Import new dataset

### ISSUE THREAD

**Issue by anderspeders** [openspending/openspending#581]
Currently we have the following data fields:
Title
Identifier
Category
Currency
Countries
Languages
Description

I'd suggest that we add the following fields:
Name of publisher of the data: (Ie. French Ministry of Finance)
URL for original data source of the data: (NOT the datahub) 
Did you clean or edit the data before uploading: (Yes/No Check box)

WHY add these fields:
We're seeing a growing amount of privacy requests regarding the data. This has highlighted that it would be useful to know more about each dataset available in OpenSpending. The information could also be relevant for other users with interests in issues of data validity. 

Any thoughts?

**Comment by rgrp** [comment]
@pudo stated in #834 

This is a bit crazy, but I think part of the difficulty of navigating OpenSpending right now is that we're asking people to name things which don't really have a name. Instead, we should be getting them to describe the dataset in much more detail, including details such as these: 

* What is the name of the administrative body to which it applies? 
* What is the level of government that this applies to? 
* What stage in the budget cycle does this dataset most represent?
* What is the name of the political body which decided it?
* Where was it initially published on the web? 
* When was it initially published? 
* What is the temporary extent and granularity of the data?
