### ISSUE TITLE
Fix flakes errors

### ISSUE THREAD

**Issue by trickvi** [openspending/openspending#690]
Pyflakes is a software that runs through source code and identifies errors such as unused imports. Running pyflakes on openspending results in 166 pyflakes errors (current version). These should all be fixed to keep the code clean.

To see the errors I would recommend installing flake8 (runs pyflakes and more), navigating to the root of the repo and running:

```
flake8 --select=F openspending
```

The output should be a few lines of this format:

```
openspending/model/meta.py:11:1: F401 'relationship' imported but unused
```

All of these lines should be fixed (for example by removing `import relationship` from openspending/model/meta.py). I recommend fixing one file per commit to keep the code reviews easy.

**This is an easy ticket to work on to get to know the code base.**

**Comment by rachelwarren** [comment]
Hi, I would be interested in taking this on. Going to fork and take a look at it right now.
