### ISSUE TITLE
Website - Timeline page broken

### ISSUE THREAD

**Issue by heatherleson** [openspending/openspending#803]
The OpenSpending website may need an adjustment.

Page: http://community.openspending.org/about/timeline/
Expected Result: Timeline and Map coexist with content on the site
Actual Result:
![j9](https://cloud.githubusercontent.com/assets/1216707/2893927/7724384c-d54d-11e3-9b72-81a07ee6cdd1.png)

Browser: FF (latest)
OS: Mac (latest)

**Comment by rgrp** [comment]
INVALID. Replacing with https://trello.com/c/RGuPHSpU/115-fix-openspending-timeline-page as we will keep issue tracker for tech platform.
