### ISSUE TITLE
Internal Server Error on OpenSpending.org

### ISSUE THREAD

**Issue by schlos** [openspending/openspending#823]
Hi,

After adding new source files, I'm keep getting "Internal Server Error". Then when I return to the dataset dashboard page, it will display that data is being loaded:

"Let me see... The data is now being checked to see if it can be imported. This should not take very long."

And source file is in "STILL ANALYSING" stage for very long time. Actually it stayed like that overnight.

Now, I tried also with same dataset source file which worked before, but not it was reproducing same problem - it's stuck in "STILL ANALYSING" stage.

Steps to reproduce problem:
1. Create new dataset
2. Go to Manage - Dashboard tab - Add a source
3. Select e.g. 
http://zagreb.open.hr/open-spending/zg/RASF_Grad_Zagreb_2010-2011-2012_edit-template.csv
or
http://zagreb.open.hr/open-spending/zg/21_2002-2010_v3.csv
or
http://zagreb.open.hr/open-spending/zg/21_2002-2010_v3-1.csv
4. Hit Create button
5. Wait for some time till page load. Check if you'll get "Internal Server Error" page.
6. Go to Dataset - Manage - Dashboard tab, check source file status. Verify if it's stuck in "STILL ANALYSING" status.

It looks similar to #453.

Cheers,
Miroslav

**Comment by k0shk** [comment]
Hello! This problem appeared again...
