### ISSUE TITLE
Social media share button doesn't show.

### ISSUE THREAD

**Issue by hagino3000** [openspending/openspending#826]
On Firefox or Chrome, share buttons doesn't shown. 

## Safari (it works)
![buggybubbletree_-_testcase_bug_bubbletree_-_openspending_ _new_issue_ _openspending_openspending](https://cloud.githubusercontent.com/assets/98253/5123782/b0298fa2-70f2-11e4-97f5-1987d4e7e9cd.png)

## Chrome or Forefox (Failed to load sharebutton script)
![buggybubbletree_-_testcase_bug_bubbletree_-_openspending](https://cloud.githubusercontent.com/assets/98253/5123792/ca8ef620-70f2-11e4-9133-db4aa1ebe777.png)

**Comment by koddsson** [comment]
This has been fixed with #830 then?

**Comment by tryggvib** [comment]
@koddsson Ah yes, should have been closed then. Closing now. Thanks!

**Comment by koddsson** [comment]
:)
