### ISSUE TITLE
trackers on website

### ISSUE THREAD

**Issue by jasontrublu** [openspending/openspending#839]
Hi,

In the discussion about adding out county's financial data to OpenSpending, there was the issue that your website uses quite many trackers/external code (google analytics, google API, twitter, facebook). This currently blocks the progress, as this is a sensible topic in Germany. 

Are these really necessary? Can you provide a possibility to use the website without being tracked?

**Comment by tryggvib** [comment]
Is it just that it is being tracked by external trackers or that it is being tracked at all? We use the trackers at the moment to see where we could improve based on measurements (i.e. how many people click on this etc.) but that's mostly Google Analytics.

Recently we switched sharing via twitter/facebook/g+ on view pages like this one: https://openspending.org/iceland_spending_cofog/views/cofog-breakdown#/~/total is that what you mean?

**Comment by jasontrublu** [comment]
trackers from the same webserver wouldn't be much of a problem (although they still might scare some folks), but external trackers like google analytics are currently a very bad idea (at least in germany, with hith demand in data protection among some political circles)

**Comment by rgrp** [comment]
@jasontrublu people can block google analytics if they wish e.g. use disconnect. We're likely to continue using some form of web analytics so we have a sense of the use of different parts of the site. Unless we hear more I suggest we'll close as WONTFIX.
