### ISSUE TITLE
The "Save Dimensions" buttons seems to be broken.

### ISSUE THREAD

**Issue by konstin** [openspending/openspending#843]
We have tried to upload a .csv file from 3 different computers with chrome and firefox and on none of them the "Save Dimensions" button did do anything except reloading the page. We even tried to re-upload an existing budget, but this also didn't work.

**Comment by pwalsh** [comment]
Hi @konstin 

We're checking it out

**Comment by stevieflow** [comment]
I've been able to upload a csv (from: https://gist.githubusercontent.com/stevieflow/f3c4a41dfffd38ce93a3/raw/98198911904b67d5d3bb69e49e56642f1152ff43/gec-test.csv)

![data](https://cloud.githubusercontent.com/assets/1209944/8258321/de3cd03e-16ab-11e5-9b26-3b067d4aded5.png)

URL of model : https://openspending.org/trace_test (sorry  - it's not live)

I then start to create/save dimensions: 

![dimensions](https://cloud.githubusercontent.com/assets/1209944/8258351/23624310-16ac-11e5-860d-d65d69a5ec95.png)

But.. if I click away from the Dimensions & Measures tab (even though I've saved my current dimensions), and then back ... they're gone:

![magic](https://cloud.githubusercontent.com/assets/1209944/8258386/65900998-16ac-11e5-9ad5-cd10e1c0d456.png)

``scratches head``

Support details: https://gist.github.com/stevieflow/076b89ccd4a092097538

**Comment by konstin** [comment]
I discussed the problem on irc and the conclusion was that the can't do anything about this problem, but instead they are working on fully rewritten backend.

**Comment by tryggvib** [comment]
Hi @stevieflow and @konstin 

The dimension editor is horrible at feedback. It's even worse than horrible it just doesn't do it. You have to be really careful to follow the rules. Every dataset must have ``amount`` and ``time`` dimensions. If you have ``to`` or ``from`` dimensions they must be **compound**. Every dataset must have a unique id **but** a dataset cannot have a dimension called ``id``.

I know this is just horrible and non-trivial but try again with all this in mind and see if it works.

**Comment by konstin** [comment]
I tried to change the unique id and for the first time I got a feedback from the button, but unfortunately it was an internal server error. (The dataset is called `muc_test_1`.)
