### ISSUE TITLE
Source Import For CSV Returns No Columns and Wrong Column Counts

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#846]
![screen shot 2015-10-28 at 12 44 20 pm](https://cloud.githubusercontent.com/assets/11497391/10780039/f40d1ff2-7d73-11e5-9191-cd70c7a897a9.png)
![screen shot 2015-10-28 at 12 56 52 pm](https://cloud.githubusercontent.com/assets/11497391/10780041/f5dbba6e-7d73-11e5-97bf-e15dbf5fbf99.png)

Source file; https://drive.google.com/file/d/0B7BVHpQAoqcIT2UwY1Q1Ukk2SDA/view?usp=sharing

**Comment by pwalsh** [comment]
@danfowler

**Comment by danfowler** [comment]
Hi @Hazwany, it looks like you are not linking directly to the CSV file, but rather to the Google Drive viewer page.  

I had luck changing the link to the following direct CSV export: 

https://docs.google.com/spreadsheets/d/124utUicrzqWcBA2UI6VeABJkFYp_A-OCDTwL79RRx88/export?exportFormat=csv

That is, I removed `/edit?usp=sharing` at the end and replaced it with `/export?exportFormat=csv`

Can you try this and see if it resolves your issue?

**Comment by Hazwany** [comment]
Hi @danfowler 

It works! Thank you!

![screen shot 2015-10-29 at 9 13 58 am](https://cloud.githubusercontent.com/assets/11497391/10807717/8cce75e8-7e1d-11e5-8211-b6c75951f3a4.png)
