### ISSUE TITLE
Can we move OSEPs in here?

### ISSUE THREAD

**Issue by pudo** [openspending/openspending#849]
@rgrp we talked today about having this as a central repo to coordinate activities from. I wonder if you would be opposed to moving the OSEPs into ``design/osep``?

**Comment by pwalsh** [comment]
My preference is to archive the OSEP repository, and the OSEP concept. 

Of course, a bunch of the info there is important and would be moved into some roughly technical documentation on OpenSpending Next. 

OSEP as a concept can pretty much be managed in this main issue tracker until such a point that the size of the community of contributors warrants the formality of the OSEP process.

**Comment by rgrp** [comment]
@pwalsh i'd vote to keep OSEPs - i think we may need them again in future and certainly in continuing development of OS Next.

I thought original idea was to move OSEPs into dotorg but I'm not too bothered where it gets amalgamated ;-)

**Comment by pwalsh** [comment]
Yes, if we are keeping the OSEP concept let's move it to dotorg.

**Comment by pwalsh** [comment]
closing in favour of https://github.com/openspending/community.openspending.org/issues/67
