### ISSUE TITLE
validation error at Step 3 on OS packager

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#850]
I have a question regarding an error on OS packager. As soon as I try to provide metadata on the dataset I am getting a "validation error." Is it that I'm not mapping the data correctly (only assigning amount and date)? I tried uploading this link: https://raw.githubusercontent.com/openspending/fiscal-data-package-demos/master/boost-moldova/data/boost-moldova-2014.csv. I would appreciate some guidance!
Please see a screenshot:
![validation error on os packager](https://cloud.githubusercontent.com/assets/17012538/12885845/cf997810-ce71-11e5-91a6-a496820c679f.JPG)

**Comment by akariv** [comment]
Fixed here: https://github.com/openspending/os-packager/commit/67fdbe5b827b80d3c2b6b5a0aa50d5ccb094ff91
