### ISSUE TITLE
Add 'decimal separator' selection in mapping phase

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#851]
While trying to map the data from this [data set](http://data.sinarproject.org/dataset/federal-government-ministerial-budget-2016/resource/59ec592b-46f2-489b-82ad-f356b55a6f4b) the "Amount" column was not recognized as such by the tool. 

<img width="897" alt="capture d ecran 2016-02-08 a 10 58 25" src="https://cloud.githubusercontent.com/assets/6681719/12887943/54e81b3c-ce6f-11e5-9014-c8c0f730d4dd.png">

@danfowler is investigating

**Comment by pwalsh** [comment]
The presence of commas guarantees that this *is* a string. We do have a format that allows this in JSON Table Schema, but adding support for it in this UI and the loader from FDP to the database will require work.

**Comment by cecilaki** [comment]
Ok @pwalsh - In that case, we should advise users to check that detail while they prepare their dataset prior to submission. A sort of basic checklist before submitting the dataset for upload & mapping. This wouldn't require additional work in the current UI.

For which cases do we allow commas? An idea for a future iteration would be to add a validation step while doing the quality check to make sure the commas are present for a particular and allowed reason. And this would for sure require some UI work.

**Comment by cecilaki** [comment]
By the way, same issue with this dataset > https://discuss.okfn.org/t/openspending-for-dummies/1817/8 
@danfowler if the commas are the issue, we should let this user know and rectify his dataset. 
<img width="899" alt="capture d ecran 2016-02-08 a 14 48 34" src="https://cloud.githubusercontent.com/assets/6681719/12888685/3104e52a-ce73-11e5-958e-016e106b7c65.png">

**Comment by pwalsh** [comment]
@cecilaki I think we should allow commas for amounts. It is a job for computers to deal with, not humans. We just need to schedule a fix. Meantime, yes: tell people that we can't have commas in amounts.

**Comment by akariv** [comment]
We need to add a 'decimal separator' selection between `,` and `.` (once we know the decimal separator we can simply ignore all other non-digit characters)
The we should use it locally and also save it to the FDP for the API loader to use (format TBD)

**Comment by rgrp** [comment]
@akariv @pwalsh the question of defining the separate is something i thought about in JTS for decimals - perhaps we should add a "decimalSeparator" to options for `number` http://dataprotocols.org/json-table-schema/#field-types-and-formats. I also think that if we do allow "," in number we should probably clarify that in JTS with a warning to implementors that "," may be allowed.

**Comment by akariv** [comment]
@rgrp a side note - I found it a little surprising that "," is so widely used (see here: https://en.wikipedia.org/wiki/Decimal_mark#/media/File:DecimalSeparator.svg).
Perhaps we should consider making `decimalSeparator` a mandatory option, just to acknowledge that no value is a 'natural' default value?

**Comment by rgrp** [comment]
@akariv can you open an issue on this here https://github.com/dataprotocols/dataprotocols/issues

**Comment by akariv** [comment]
Opened: https://github.com/dataprotocols/dataprotocols/issues/246

**Comment by pwalsh** [comment]
@cecilaki I see this is assigned to @danfowler but there is nothing he can do here. I'm re-assigning to @akariv who can then distribute accordingly.
