### ISSUE TITLE
a message by installing openspending

### ISSUE THREAD

**Issue by HimmelStein** [openspending/openspending#852]
Hi, 
i tried to install this system, and encountered an error message, which suggests me to contact the author.
with many thanks

----------------------
OS: Mac OS Yosemite 10.10.5
 
$ docker -v
Docker version 1.10.0, build 590d5108
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.10.0   
$ docker-machine -v
docker-machine version 0.6.0, build e27fb87
$ vi /etc/hosts
 
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost 
192.168.99.100  api.dev.openspending.org
192.168.99.100  packager.dev.openspending.org
192.168.99.100  conductor.dev.openspending.org
 

[code]
ESC[36mos-packager  | ESC[0mnpm ERR! Failed at the fiscal-data-packager@0.0.1 start script 'node index.js'.
ESC[36mos-packager  | ESC[0mnpm ERR! This is most likely a problem with the fiscal-data-packager package,
ESC[36mos-packager  | ESC[0mnpm ERR! not with npm itself.
ESC[36mos-packager  | ESC[0mnpm ERR! Tell the author that this fails on your system:
ESC[36mos-packager  | ESC[0mnpm ERR!     node index.js
ESC[36mos-packager  | ESC[0mnpm ERR! You can get their info via:
ESC[36mos-packager  | ESC[0mnpm ERR!     npm owner ls fiscal-data-packager
ESC[36mos-packager  | ESC[0mnpm ERR! There is likely additional logging output above.
ESC[36mos-packager  | ESC[0mnpm ERR! Please include the following file with any support request:
ESC[36mos-packager  | ESC[0mnpm ERR!     /repos/os-packager/npm-debug.log
ESC[34mos-conductor | ESC[0m[2016-02-09 23:07:32 +0000] [20] [ERROR] Exception in worker process:
ESC[34mos-conductor | ESC[0m[2016-02-09 23:07:32 +0000] [21] [ERROR] Exception in worker process:
ESC[33;1mos-api       | ESC[0m[2016-02-09 23:07:44,075: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@mq:5672//: [Errno -4] Non-recoverable error.
ESC[33;1mos-api       | ESC[0m[2016-02-09 23:07:44 +0000] [91] [ERROR] Exception in worker process:
ESC[33;1mos-api       | ESC[0m[2016-02-09 23:07:44 +0000] [92] [ERROR] Exception in worker process:
ESC[33;1mos-api       | ESC[0m[2016-02-09 23:07:44 +0000] [94] [ERROR] Exception in worker process:
ESC[33;1mos-api       | ESC[0m    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
ESC[33;1mos-api       | ESC[0m    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
[/code]

**Comment by akariv** [comment]
Hi @HimmelStein ,

I'm sorry for this inconvenience... we're still in active development so some glitches are unavoidable.

Just to make sure you're working with the latest versions of all packages, can you please make sure that you pulled openspending/openspending to the latest master, as well as each of the repositories under repos/* ? There have been many changes lately which could have caused some incompatibility there.

After that, please edit your /etc/hosts file to conform with the latest version - now you only need two entries: for `dev.openspending.org` and `fakes3`.

Please lmk how it looks after the update.

**Comment by HimmelStein** [comment]
Hi, thanks for the quick response. 

here is the current message
------
os-packager  | module.js:340
os-packager  |     throw err;
os-packager  |     ^
os-packager  | 
os-packager  | Error: Cannot find module 'bluebird'
os-packager  |     at Function.Module._resolveFilename (module.js:338:15)
os-packager  |     at Function.Module._load (module.js:289:25)
os-packager  |     at Module.require (module.js:366:17)
os-packager  |     at require (module.js:385:17)
os-packager  |     at Object.<anonymous> (/repos/os-packager/app/index.js:3:15)
os-packager  |     at Module._compile (module.js:435:26)
os-packager  |     at Object.Module._extensions..js (module.js:442:10)
os-packager  |     at Module.load (module.js:356:32)
os-packager  |     at Function.Module._load (module.js:313:12)
os-packager  |     at Module.require (module.js:366:17)
os-packager  | 
os-packager  | npm ERR! Linux 4.1.17-boot2docker
os-packager  | npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
os-packager  | npm ERR! node v4.2.4
os-packager  | npm ERR! npm  v2.14.12
os-packager  | npm ERR! code ELIFECYCLE
os-packager  | npm ERR! fiscal-data-packager@0.0.1 start: `node index.js`
os-packager  | npm ERR! Exit status 1
os-packager  | npm ERR! 
os-packager  | npm ERR! Failed at the fiscal-data-packager@0.0.1 start script 'node index.js'.
os-packager  | npm ERR! This is most likely a problem with the fiscal-data-packager package,
os-packager  | npm ERR! not with npm itself.
os-packager  | npm ERR! Tell the author that this fails on your system:
os-packager  | npm ERR!     node index.js
os-packager  | npm ERR! You can get their info via:
os-packager  | npm ERR!     npm owner ls fiscal-data-packager
os-packager  | npm ERR! There is likely additional logging output above.
os-packager  | 
os-packager  | npm ERR! Please include the following file with any support request:
os-packager  | npm ERR!     /repos/os-packager/npm-debug.log

-----

**Comment by akariv** [comment]
Hey @HimmelStein , can you please send me the output of `docker-compose -f dev.yml build --no-cache os-packager`?

**Comment by HimmelStein** [comment]
$ docker-compose -f dev.yml build --no-cache os-packager 
Building os-packager
Step 1 : FROM gliderlabs/alpine:latest
 ---> 169fc2bfcef7
Step 2 : RUN apk add --update python
 ---> Running in 750b90e647e7
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.3/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.207234d0.tar.gz: No such file or directory
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.3/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.231b5af5.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
ERROR: Service 'os-packager' failed to build: The command '/bin/sh -c apk add --update python' returned a non-zero code: 1


==========
such ERROR: http:/...: temporary error (try again later) appears very often.

**Comment by pwalsh** [comment]
Looks like the issue is the upstream package index?

**Comment by akariv** [comment]
Either that or the virtual machine fails to reach the internet for some
reason.
If the problem persists then you should check the VirtualBox settings.

**Comment by HimmelStein** [comment]
here is the Docker env.

$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/tdong/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell: 
# eval $(docker-machine env default)

i do not know how to do with the issue of 'upstream package index'.

**Comment by HimmelStein** [comment]
$ docker run -it ubuntu bash
Unable to find image 'ubuntu:latest' locally
Pulling repository docker.io/library/ubuntu
docker: Error while pulling image: Get https://index.docker.io/v1/repositories/library/ubuntu/images: dial tcp: lookup index.docker.io on 131.220.148.54:53: server misbehaving.
See 'docker run --help'.

**Comment by HimmelStein** [comment]
here is a problem

**Comment by HimmelStein** [comment]
the above problem is solved by adding "nameserver 8.8.8.8" into /etc/resolv.conf

**Comment by akariv** [comment]
So after this setup issue was resolved, you should probably rebuild your
docker images:

`docker-compose -f dev.yml build --no-cache`

**Comment by HimmelStein** [comment]
the result is the same

$ docker-compose -f dev.yml build --no-cache
Building os-packager
Step 1 : FROM gliderlabs/alpine:latest
 ---> 169fc2bfcef7
Step 2 : RUN apk add --update python
 ---> Running in 565f6ba6b71c
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.3/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.207234d0.tar.gz: No such file or directory
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.3/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.231b5af5.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  python (missing):
    required by: world[python]
ERROR: Service 'os-packager' failed to build: The command '/bin/sh -c apk add --update python' returned a non-zero code: 1

**Comment by akariv** [comment]
where did you add nameserver 8.8.8.8 exactly?
On the host machine or in the virtual machine?

**Comment by HimmelStein** [comment]
/etc/resolv.conf

**Comment by akariv** [comment]
You probably need to change it in the virtual machine where all the action
is happening...

`docker-machine ssh default`

**Comment by HimmelStein** [comment]
add it to the virtual machine  

$ docker-compose -f dev.yml build --no-cache
Building os-packager
Step 1 : FROM gliderlabs/alpine:latest
 ---> 169fc2bfcef7
Step 2 : RUN apk add --update python
 ---> Running in ce54d0ecde62
fetch http://alpine.gliderlabs.com/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libbz2 (1.0.6-r4)
(2/10) Installing expat (2.1.0-r2)
(3/10) Installing libffi (3.2.1-r2)
(4/10) Installing gdbm (1.11-r1)
(5/10) Installing ncurses-terminfo-base (6.0-r6)
(6/10) Installing ncurses-terminfo (6.0-r6)
(7/10) Installing ncurses-libs (6.0-r6)
(8/10) Installing readline (6.3.008-r4)
(9/10) Installing sqlite-libs (3.9.2-r0)
(10/10) Installing python (2.7.11-r3)
Executing busybox-1.24.1-r7.trigger
OK: 51 MiB in 21 packages
 ---> fe1013b9e9aa
Removing intermediate container ce54d0ecde62
Step 3 : RUN apk add git
 ---> Running in 74dc771d0962
(1/6) Installing openssl (1.0.2f-r0)
(2/6) Installing ca-certificates (20160104-r2)
(3/6) Installing libssh2 (1.6.0-r0)
(4/6) Installing curl (7.47.0-r0)
(5/6) Installing pcre (8.38-r0)
(6/6) Installing git (2.6.4-r0)
Executing busybox-1.24.1-r7.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 69 MiB in 27 packages
 ---> e74cd5185995
Removing intermediate container 74dc771d0962
Step 4 : RUN apk add nodejs
 ---> Running in 7848686811e3
(1/4) Installing libgcc (5.3.0-r0)
(2/4) Installing libstdc++ (5.3.0-r0)
(3/4) Installing libuv (1.7.5-r0)
(4/4) Installing nodejs (4.2.4-r1)
Executing busybox-1.24.1-r7.trigger
OK: 93 MiB in 31 packages
 ---> 1504972458d5
Removing intermediate container 7848686811e3
Step 5 : RUN git clone http://github.com/openspending/os-packager.git app
 ---> Running in 6580ef0141d2
Cloning into 'app'...
 ---> b55daf17cbbc
Removing intermediate container 6580ef0141d2
Step 6 : RUN cd app && npm install --only=prod
 ---> Running in 65b529ae4095
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN optional dep failed, continuing fsevents@1.0.7
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> utf-8-validate@1.2.1 install /app/node_modules/zombie/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.17-boot2docker
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/zombie/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> bufferutil@1.2.1 install /app/node_modules/zombie/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.17-boot2docker
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/zombie/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

**Comment by akariv** [comment]
So far it looks like a successful build (you can ignore the optional dep failures)... did you try running it after it completed?

**Comment by HimmelStein** [comment]
Step 39 : CMD echo working from $WORKDIR && cd $WORKDIR && echo OS-API DB: $OS_API_ENGINE && /startup.sh
 ---> Running in 4d24cdc43cbf
 ---> 666fb566bdc1
Removing intermediate container 4d24cdc43cbf
Successfully built 666fb566bdc1

**Comment by HimmelStein** [comment]
open a browser and type http://dev.openspending.org/, still see 
Unable to connect
Firefox can't establish a connection to the server at dev.openspending.org.

**Comment by akariv** [comment]
Just to make sure - did you re-run the container setup using
./docker-run-dev.sh after the build finished?
Also - did you make the changes in your /etc/hosts as I advised earlier?

**Comment by HimmelStein** [comment]
i just run $ docker-compose -f dev.yml build --no-cache

**Comment by akariv** [comment]
Then you need to follow the instructions from
https://github.com/openspending/openspending

Make sure you have the correct entries in /etc/hosts and then jump on to:

   - Now go into the docker-config folder, and start the docker containers:
   ./docker-start-dev.sh

Adam

**Comment by HimmelStein** [comment]
i am doing it right now. many thanks!

-tiansi

**Comment by HimmelStein** [comment]
hanged at 

os-api       |   File "/usr/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
os-api       |     Arbiter(self).run()
os-api       |   File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 206, in run
os-api       |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
os-api       |   File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 302, in halt
os-api       |     self.stop()
os-api       |   File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 347, in stop
os-api       |     time.sleep(0.1)
os-api       |   File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
os-api       |     self.reap_workers()
os-api       |   File "/usr/lib/python3.5/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
os-api       |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
os-api       | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
os-api exited with code 1

**Comment by HimmelStein** [comment]
type $ docker-compose -f dev.yml build --no-cache again

hang at

Removing intermediate container 55665fec4e5c
Step 6 : RUN cd app && npm install --only=prod
 ---> Running in 5e22624078db
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.

maybe need to clean-up what have been installed

**Comment by HimmelStein** [comment]
proceed to the following, and hanged

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.1.17-boot2docker
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/zombie/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

**Comment by HimmelStein** [comment]
leave it running, and back to see it tomorrow

**Comment by HimmelStein** [comment]
$ docker-compose -f dev.yml build --no-cache 
ended with success

$ ./docker-start-dev.sh  hanging
os-api       | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "db" to address: Try again
os-api       | 
os-api       | [2016-02-11 06:10:28 +0000] [94] [INFO] Worker exiting (pid: 94)
os-api       | [2016-02-11 06:10:28 +0000] [84] [INFO] Shutting down: Master
os-api       | [2016-02-11 06:10:28 +0000] [84] [INFO] Reason: Worker failed to boot.
os-api exited with code 3
os-packager  | npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.67.0.tgz
os-packager  | npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
os-packager  | npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.67.0.tgz
os-packager  | npm WARN retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
os-packager  | npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.67.0.tgz

**Comment by pwalsh** [comment]
@HimmelStein it *really* looks like you are having networking issues. Before we continue with this, can you try a simpler Docker deployment and ensure that it works on your machine.

https://docs.docker.com/mac/

That will enable us to rule out issues specification to your own machine.

**Comment by HimmelStein** [comment]
did it before installing openspending
i will try again today
thanks

**Comment by HimmelStein** [comment]
$ docker run dtsatdocker/docker-whale
 _________________________________________ 
/ QOTD:                                   \
|                                         |
| I looked out my window, and saw Kyle    |
| Pettys' car upside down,                |
|                                         |
| then I thought 'One of us is in real    |
| trouble'.                               |
|                                         |
\ -- Davey Allison, on a 150 m.p.h. crash /
 ----------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/

**Comment by HimmelStein** [comment]
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
dockerconfig_os-api         latest              1b2030197c9e        8 hours ago         321.4 MB
dockerconfig_os-conductor   latest              eb94c04846db        8 hours ago         320 MB
dockerconfig_fakes3         latest              92806fcaba6b        8 hours ago         167.6 MB
dockerconfig_frontend       latest              18dc04436d9b        8 hours ago         134.5 MB
dockerconfig_os-packager    latest              56a84098c2cd        8 hours ago         270.9 MB
<none>                      <none>              ffed1c5f8c2c        8 hours ago         82.26 MB
<none>                      <none>              81e6f8a7f553        9 hours ago         82.26 MB
<none>                      <none>              c31d2ddfab69        9 hours ago         82.26 MB
<none>                      <none>              666fb566bdc1        10 hours ago        321.4 MB
<none>                      <none>              6c2a2f4b35c9        10 hours ago        320 MB
<none>                      <none>              eead0c2ffb1b        10 hours ago        134.5 MB
<none>                      <none>              9ff1a926ee80        10 hours ago        270.8 MB
<none>                      <none>              93c843d892d4        10 hours ago        167.6 MB
<none>                      <none>              b55daf17cbbc        10 hours ago        82.26 MB
<none>                      <none>              4976c299053c        33 hours ago        322.2 MB
<none>                      <none>              dcf4111d5308        34 hours ago        321.3 MB
<none>                      <none>              9359fa34fd5b        38 hours ago        245.2 MB
<none>                      <none>              ff916778ef16        39 hours ago        245.2 MB
<none>                      <none>              abb570fffe50        46 hours ago        245.2 MB
<none>                      <none>              f80158ee50c9        47 hours ago        245.2 MB
<none>                      <none>              2041954b24d4        47 hours ago        245.2 MB
<none>                      <none>              9492e7a3f561        47 hours ago        245.2 MB
<none>                      <none>              b4e583028e22        47 hours ago        245.2 MB
<none>                      <none>              e70d86858c18        47 hours ago        245.2 MB
<none>                      <none>              062add71a45f        2 days ago          245.2 MB
<none>                      <none>              ed4164d3dcc3        2 days ago          320 MB
<none>                      <none>              ffef318c38cb        2 days ago          255 MB
<none>                      <none>              55002a54e0b2        2 days ago          245.2 MB
<none>                      <none>              2c8088d95726        2 days ago          245.2 MB
<none>                      <none>              bc8330c8b429        2 days ago          245.2 MB
<none>                      <none>              2fcf7dc92719        2 days ago          245.2 MB
<none>                      <none>              9990bb42f13e        2 days ago          245.2 MB
<none>                      <none>              ee32cc3851f1        2 days ago          245.2 MB
<none>                      <none>              7a8332bdb227        2 days ago          245.2 MB
<none>                      <none>              432a786fe149        2 days ago          245.2 MB
<none>                      <none>              487795cd7554        2 days ago          245.2 MB
<none>                      <none>              c279ea234446        2 days ago          245.2 MB
<none>                      <none>              3c81a8e0ea15        2 days ago          245.2 MB
<none>                      <none>              4913f51fbc48        2 days ago          245.2 MB
<none>                      <none>              7f67aec7cf7a        2 days ago          245.2 MB
<none>                      <none>              147466530212        2 days ago          245.2 MB
<none>                      <none>              287d38ac344f        2 days ago          167.6 MB
<none>                      <none>              0576db0121b5        2 days ago          134.5 MB
<none>                      <none>              eb954222f3fd        2 days ago          271.4 MB
<none>                      <none>              1979be28f249        2 days ago          92.07 MB
<none>                      <none>              35414e09ac4b        2 days ago          85.81 MB
<none>                      <none>              1875d70bb610        2 days ago          85.81 MB
<none>                      <none>              d13af9248ab6        2 days ago          85.81 MB
<none>                      <none>              0e4c80e4268d        2 days ago          85.81 MB
dtsatdocker/docker-whale    latest              75d782b89ba1        2 days ago          274.3 MB
lphoward/fake-s3            latest              6d6773ddfdac        2 days ago          167.6 MB
dockerconfig_mq             latest              f89315b44e05        12 days ago         305.1 MB
rabbitmq                    latest              f89315b44e05        12 days ago         305.1 MB
dockerconfig_db             latest              b2b0df88a221        2 weeks ago         263.8 MB
postgres                    latest              b2b0df88a221        2 weeks ago         263.8 MB
dockerconfig_cache          latest              55d905269fc2        2 weeks ago         132.2 MB
memcached                   latest              55d905269fc2        2 weeks ago         132.2 MB
nginx                       latest              99e9abbaeceb        2 weeks ago         134.5 MB
ubuntu                      latest              3876b81b5a81        3 weeks ago         187.9 MB
gliderlabs/alpine           latest              169fc2bfcef7        3 weeks ago         4.794 MB
gliderlabs/alpine           3.3                 d8d1da811c07        3 weeks ago         4.794 MB
hello-world                 latest              690ed74de00f        4 months ago        960 B
docker/whalesay             latest              6b362a9f73eb        8 months ago        247 MB

**Comment by akariv** [comment]
@HimmelStein @pwalsh turns out that there have been breaking changes with docker between versions 1.9 and 1.10.

I've updated the code to be compatible to 1.10, so @HimmelStein needs to pull the repository to the latest master and rebuild the containers. Please be patient as building takes time and it usually doesn't just "hang"...

**Comment by HimmelStein** [comment]
ok. i will try, with more patience, thanks!

**Comment by HimmelStein** [comment]
<img width="1440" alt="bildschirmfoto 2016-02-11 um 11 17 28" src="https://cloud.githubusercontent.com/assets/5571821/12973979/d4cad220-d0b0-11e5-83ed-ed0ce6febacd.png">

many thanks!

**Comment by akariv** [comment]
Great! please ping me if you encounter any other issues.

**Comment by HimmelStein** [comment]
will do

**Comment by HimmelStein** [comment]
to summarize: (1) nameserver 8.8.8.8 shall be added to the /etc/resolv.conf file of the docker-machine
(2) inconsistency between Docker 1.9 and Docker 1.10 requires some changes in the source code
(3) more patience
:-)

**Comment by akariv** [comment]
Yes (2) was solved by upgrading the configuration, for (1) & (3) I'll add
some comments in the README file.
