### ISSUE TITLE
Error at Step 4 on OS packager

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#853]
Step 3 was completed successfully, I encountered an issue at Step 4 on uploading the same dataset (https://raw.githubusercontent.com/openspending/fiscal-data-package-demos/master/boost-moldova/data/boost-moldova-2014.csv)
![capture](https://cloud.githubusercontent.com/assets/17012538/12946874/391dc298-d000-11e5-9e2d-743e38fa7211.JPG)

**Comment by pwalsh** [comment]
duplicates https://github.com/openspending/openspending/issues/878
