### ISSUE TITLE
403 when trying to publish a datapackage

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#863]
On the packager, when trying to publish a datapackage, I have this error > 

<img width="381" alt="capture d ecran 2016-02-19 a 16 31 46" src="https://cloud.githubusercontent.com/assets/6681719/13179889/67bd6b62-d726-11e5-8c21-815c1d334c2d.png">

**Comment by akariv** [comment]
This was caused due to incompatibility in resource names: 
A slugified name was used for the upload, while the original name was used in datapackage.json

Turns out that @cecilaki has a real knack for those edge-cases :smile:
