### ISSUE TITLE
[packager] can't validate step 3 / Missing required property: model

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#864]
Error in validating step 3 after mapping this file:
[ministerial-budget-2016---ministries.csv.zip](https://github.com/openspending/openspending/files/142289/ministerial-budget-2016---ministries.csv.zip)

<img width="530" alt="capture d ecran 2016-02-23 a 11 23 07" src="https://cloud.githubusercontent.com/assets/6681719/13248739/6820d5b0-da20-11e5-9c22-478ffcc8c774.png">

**Comment by akariv** [comment]
Yes, that's the result of the schema change... I'll deploy the updated code
in an hour or so

**Comment by cecilaki** [comment]
Ok good, thanks, so step 3 works fine now.
But I have also the 403 issue reported in #[863] for step 4 (https://github.com/openspending/openspending/issues/863)
