### ISSUE TITLE
Detect CSV dialect when packaging data

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#866]
* Detect dialect
* Create a CSV dialect descriptor (http://dataprotocols.org/csv-dialect/)
* Persist the descriptor as part of the whole package, perhaps at `csv-dialect.json`, alongside `datapackage.json`

**Comment by rgrp** [comment]
@pwalsh why a separate csv-dialect.json? Tabular Data Package already supports specifying the dialect info and in fact all tabular data package tools should use that info. From [the spec](http://dataprotocols.org/tabular-data-package/#specification):

> If a CSV file does not follow these rules then its specific CSV dialect MUST be documented. The resource hash for the resource in the datapackage.json descriptor MUST:
> 
> * Include a dialect key that conforms to that described in the CSV Dialect Description Format

**Comment by pwalsh** [comment]
I stand corrected ( @akariv :) ). I've missed that part of the spec and no tools use it AFAIK.
