### ISSUE TITLE
Add hook for complete data validation before publish to datastore

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#871]
The validation in step 1 is on n rows as per the sample size. If the data is being published on to the OpenSpending Datastore, the first task should be to run a complete validation pipeline via the GoodTables API and stop on first error.

**Comment by pwalsh** [comment]
@akariv 

This is quite critical, as earlier steps work on a sample. So, we could still have faulty data that will only be picked up when trying to load FDP -> Babbage.

@kravets-levko I'm think this will require IndexedDB, similar to what you did for state management (maybe using the same implementation, as you store files).

In any event, this is after #873

**Comment by akariv** [comment]
@pwalsh I don't think this is needed, as data is validated during the
process of the upload.
If we fail validation we currently return an error to the user which can
fix the model / file as necessary, without affecting the data in the API.

**Comment by pwalsh** [comment]
@akariv 

yes you are right. It would make more sense for this full validation to be on the server anyway, and we do currently return an error. 

I think that we then need some way to declare a FDP on the datastore as incomplete or broken. WDYT?

**Comment by akariv** [comment]
Perhaps we can delete it from the datastore if we encounter an error.
But since all the data on the datastore is user-specific anyway, then it's
not a big deal I think if something is broken there - it should be the
user's responsibility to upload valid files.

**Comment by pwalsh** [comment]
Seeing as we need to add the ability to edit existing data packages, then labeling something as incomplete (or similar) will be better than removal, so yes, I agree. 

In a case like we discuss here, all the modeling is likely correct, and just the data source has some issues, that the user could fix and upload again.

And actually: maybe that is it - we just leave those packages on the data store, and when we allow the user to edit package, then she may fix it and the rest of the flow would work.

**Comment by pwalsh** [comment]
So, I'm closing this issue now.
