### ISSUE TITLE
Provide + model multiple files

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#872]
After MVP.

cc @smth @akariv 

cc @danfowler as while there is ample discussion around normalized data in a range of closed issues on the spec, and also back to some discussion on the forum, there is still no proper consideration of it IMHO.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. Please feel free to re-open if this is still relevant.
