### ISSUE TITLE
OpenSpending new logo

### ISSUE THREAD

**Issue by rgrp** [openspending/openspending#875]
I've noticed we seem to have a new OS logo with the OS sort of merged. This looks pretty nice.

1. Is there a plan to adopt this as a new logo? I'm +1 but had not seen an issue or thread on this.
2. I have a small suggestion: what about making the S more into a $ so it looks a bit like O$? I think this would convey the money aspect of it nicely ...

**Comment by akariv** [comment]
@smth

**Comment by smth** [comment]
1. Yes, that is the plan. The branding is still ongoing, but you can get a better sense of it [here](http://labs.openspending.org/os-style-guide/)
 2. This might work, if it was subtle. I'll raise it with the team.

**Comment by pwalsh** [comment]
Closing this as @smth is working on branding, and not a clear action to get from this ticket.
