### ISSUE TITLE
Still can't publish the data 

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#878]
A new error !  <img width="1194" alt="capture d ecran 2016-03-07 a 12 31 46" src="https://cloud.githubusercontent.com/assets/6681719/13571355/4f4898c4-e46c-11e5-86d3-76031691e30e.png">

**Comment by akariv** [comment]
Oh, that's the old 'semicolons instead of commas in CSV' issue. There's a
set of outstanding issues waiting to fix that.

**Comment by cecilaki** [comment]
Oh nice to know! Well so that fix would (finally) allow me to publish data? :p

**Comment by pwalsh** [comment]
@cecilaki you can publish data now. semi-colon separated CSV is a thing, but not a very common thing. There should be a range of other data sources that you can publish without issue (I hope!).

**Comment by cecilaki** [comment]
@pwalsh I'm doomed :) 
So I tried with another dataset from the Municipality of Paris and have another error, I guess it come from the accents? 
<img width="1193" alt="capture d ecran 2016-03-07 a 17 18 32" src="https://cloud.githubusercontent.com/assets/6681719/13577104/c5a71b82-e488-11e5-9534-4b99f7e167fd.png">

**Comment by pwalsh** [comment]
:(. No idea on this one. Team will check :).

**Comment by akariv** [comment]
I think that this one is also a semicolon separated CSV file... what is the
source of these files?

**Comment by cecilaki** [comment]
@akariv I've used this CSV file as source > 
[Muncipality_Paris_2015_Comptes_arrondissement.csv.zip](https://github.com/openspending/openspending/files/162089/Muncipality_Paris_2015_Comptes_arrondissement.csv.zip)
