### ISSUE TITLE
Geoviz: Modals and labels

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#881]
Remove labels and add a modal to display them instead.

**Comment by cecilaki** [comment]
Issue with the Transnistria region at the East. Looks like no name is attributed to it in the dataset so it generates an issue when we click on it on the map. 
<img width="736" alt="capture d ecran 2016-03-09 a 14 18 37" src="https://cloud.githubusercontent.com/assets/6681719/13637854/cc966ab0-e609-11e5-9d02-3c87d5d8fc1a.png"> and 
<img width="603" alt="capture d ecran 2016-03-09 a 12 54 49" src="https://cloud.githubusercontent.com/assets/6681719/13637861/d59adaa6-e609-11e5-8c62-ffba1e45214c.png">

**Comment by kravets-levko** [comment]
@cecilaki It's a flaw of GeoJSON object that we are currently using for this vis - it really does not contain `name` property for this region. Hope it will be fixed in cosmopolitan API and we'll then start using valid data for map.

**Comment by cecilaki** [comment]
Ok! So no way to fix this currently?

**Comment by pwalsh** [comment]
no fix, but @cecilaki at least this is the actual file we were supplied, so it is a problem in the source from BOOST.

**Comment by cecilaki** [comment]
Sure! Got it @pwalsh and @kravets-levko !
