### ISSUE TITLE
Problem logging in at final step

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#882]
Reproduce:

1. Model data, etc.
2. At final step, click login (user intention is to publish, and user was not yet logged in)

Result: 500 error

cc @pudo

**Comment by akariv** [comment]
Did this happen on the dev environment or the staging server?

**Comment by pudo** [comment]
This was on http://s145.okserver.org/packager/. The 500 showed after I was redirected from Google sign-in.

**Comment by akariv** [comment]
Fixed in https://github.com/openspending/os-conductor/pull/9
