### ISSUE TITLE
[UX] dropdown menu needs fixing

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#883]
When trying to select from dropdown menu, the bar is way far to the right (need to zoom out to reach it). When working with http://os-viewer.herokuapp.com/boost-moldova/ 
![dropdown menu need repair](https://cloud.githubusercontent.com/assets/17012538/13671235/6496119e-e6d7-11e5-81f1-f09b9f82516a.JPG)

**Comment by pwalsh** [comment]
Hey @VictoriaVlad 

Seeing as we are just about to redo the ui in #874 this is a WONTFIX.
