### ISSUE TITLE
error when starting OS project

### ISSUE THREAD

**Issue by mlukasch** [openspending/openspending#884]
Hello dear OpenSpending-developers,

so far I have executed the instructions from https://github.com/openspending/openspending in order to run the application locally on my Macbook.

I get this error message during build process by Docker:
`os-viewer_1    | gyp ERR! build error
os-viewer_1    | gyp ERR! stack Error: not found: make
os-viewer_1    | gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:19)
os-viewer_1    | gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
os-viewer_1    | gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
os-viewer_1    | gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
os-viewer_1    | gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
os-viewer_1    | gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
os-viewer_1    | gyp ERR! System Linux 4.1.19-boot2docker
os-viewer_1    | gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
os-viewer_1    | gyp ERR! cwd /repos/os-viewer/node_modules/utf-8-validate
os-viewer_1    | gyp ERR! node -v v4.3.0
os-viewer_1    | gyp ERR! node-gyp -v v3.3.0
os-viewer_1    | gyp ERR! not ok
os-viewer_1    | npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
os-viewer_1    | npm WARN install:utf-8-validate@1.2.1 Exit status 1
os-viewer_1    | npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
os-viewer_1    | npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8`

And I get a 404 by nginx when trying to open the site http://dev.openspending.org/  in my browser.
In the logs I see:
`frontend_1     | 2016/03/14 10:27:18 [error] 17#17: *1 "/etc/nginx/html/index.html" is not found (2: No such file or directory), client: 192.168.99.1, server: dev.openspending.org, request: "GET / HTTP/1.1", host: "dev.openspending.org"
frontend_1     | 192.168.99.1 - - [14/Mar/2016:10:27:18 +0000] "GET / HTTP/1.1" 404 143 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4" "-"`

Can you please help me how to solve?
Thanks in advance

**Comment by pwalsh** [comment]
Hi,

Can you do the following please:

```
docker-machine upgrade
docker-machine regenerate-certs
```

then:

```
# get latest changes
git pull

# remove some repos
rm -r repos/tabulator-py && rm -r repos/babbage.fiscal-data-package && rm -r repos/babbage && rm -r repos/datapackage-py && rm -r repos/os-api && rm -r repos/os-conductor && rm -r repos/os-viewer && rm -r repos/os-packager
```

Then follow these steps again:

https://github.com/openspending/openspending#setting-up-the-development-environment


Also: http://dev.openspending.org/  should 404: go to http://dev.openspending.org/packager/ instead.

**Comment by pwalsh** [comment]
@mlukasch please let us know if he above steps work. Several people are now running without issues since these changes.

**Comment by pwalsh** [comment]
@mlukasch I'm closing, as no answer, and we are sure this is resolved due to the several people now running the docker setup
