### ISSUE TITLE
OS-client release 0.2

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#886]
# Description

The CLI has been tested and used for many internal tasks, including migrating the old OpenSpending database to the new flat file store. However, there are some things to finalize before widespread usage.
# Tasks
- Integrate with a conductor instance, and replace the hardcoding of fake user keys 
- config system uses `None` - do not require .openspendingrc because of default config?
- odd problem with `goodtable` - version `0.5.6` still uses `jtskit` in the code. As a workaround we install `jtskit<0.5`
- (potentially large task) reimplement make model as an interactive data modeler on command line
- Ensure full data validation
- Allow pushing part of datapackage (example: update only the data source file)
- Update docs

**Comment by akariv** [comment]
We're actually re-writing the entire thing.

**Comment by pwalsh** [comment]
@akariv can we have a list of features that will be implemented in the rewrite?
