### ISSUE TITLE
`aggregate` API request for returning `label-for` values

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#888]
From @borysyuk 

Other improvement is "how to use dimensions which have `label-for` definition". If we use `babbage.ui components` we should setup some fields `tile`, `cut`, group and etc and if some dimension have `label-for` I will put `label-for` field into `babbage.ui` (because we want to display as example: "Mayoralty of Condrita" instead '0008') then `babbage.ui` send this `label-for` field to API for filtering or grouping. So it works. But we will get problems if values of `label-for` field aren't unique. Example: 
'0008' code has description ''Mayoralty of Condrita" and 
'0009' code has description ''Mayoralty of Condrita".
This approach is not good when you work with `drill-down`. Because, when you click on some chart item I we will get value of `description` ('Mayoralty of Condrita') instead of `code` ('0008')
I think, will be better if we use `code` fields in `babbage.ui` components and API will return `label-for` value for every field in `aggregate` request.
So we can change `babbage.ui` and it will show all information using `label-for` fields but will use `code` for API requests and `drill-down` procedure.

**Comment by akariv** [comment]
This was already resolved, closing now.
