### ISSUE TITLE
OpenSpending Docker Dev keeps freezing

### ISSUE THREAD

**Issue by leowmjw** [openspending/openspending#891]
Have failed multiple ties when running **docker-start-dev.sh**
```
...
Step 7 : RUN npm --version
 ---> Using cache
 ---> 7a5850ea8a59
Step 8 : RUN cd app && npm install
 ---> Running in 3d95ac2f8f9e
<frozen/timeout>
```
Example output:
https://gist.github.com/leowmjw/e573959029edc6c7e776

Anyway to bypass or to run manually?

**Comment by akariv** [comment]
`npm install` can take a very long time to complete initially (more than 15 minutes in some cases).
How long have you waited for it to complete?

**Comment by leowmjw** [comment]
Still running after 1 hour 😟

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Tue, Mar 15, 2016 at 11:07 PM -0700, "Adam Kariv" <notifications@github.com<mailto:notifications@github.com>> wrote:


npm install can take a very long time to complete initially (more than 15 minutes in some cases).
How long have you waited for it to complete?

**Comment by pwalsh** [comment]
Hi @leowmjw 

I think your particular issue is a network issue, based on what you've put here.

However, we've now probably solved some other issues, so can you do the following please:

```
docker-machine upgrade
docker-mahine regenerate-certs
```

then:

```
#get latest changes
git pull

# remove some repos
rm -r repos/tabulator-py && rm -r repos/babbage.fiscal-data-package && rm -r repos/babbage && rm -r repos/datapackage-py && rm -r repos/os-api && rm -r repos/os-conductor && rm -r repos/os-viewer && rm -r repos/os-packager
```

Then follow these steps again:

https://github.com/openspending/openspending#setting-up-the-development-environment

**Comment by leowmjw** [comment]
@pwalsh Much faster; but still failing at below step; maybe was not uploaded to the Docker hub?

```
...
Pulling cache (openspending/cache:latest)...
Pulling repository docker.io/openspending/cache
ERROR: Network timed out while trying to connect to https://index.docker.io/v1/repositories/openspending/cache/images. You may want to check your internet connection or if you are behind a proxy.
exit status 255
bash-3.2$ docker pull openspending/cache:latest
Pulling repository docker.io/openspending/cache
Network timed out while trying to connect to https://index.docker.io/v1/repositories/openspending/cache/images. You may want to check your internet connection or if you are behind a proxy.
b
```

**Comment by pwalsh** [comment]
@leowmjw network timed out, so not much I can do. All the images are on DockerHub.

**Comment by leowmjw** [comment]
@pwalsh ok thanks, just wanted to make sure. I'll keep trying, see if I can get a better network

**Comment by leowmjw** [comment]
Got it running .. finally, after a few times Kitematic restart :)
