### ISSUE TITLE
TreeMap: Mouseover for details on small items

### ISSUE THREAD

**Issue by kaerumy** [openspending/openspending#893]
![image](https://cloud.githubusercontent.com/assets/1060743/13846031/12887984-ec7f-11e5-9a82-1dbd297bbcc4.png)

Would it be possible to have additional details on smaller items on mouseover?

**Comment by pwalsh** [comment]
Hi @kaerumy 

Thanks for the feedback! This is a great idea, but as we are re-designing this app right now, it is a bit early for design requests. Please keep an eye on https://github.com/openspending/openspending/issues/874 and then, when we launch the alpha in early april, we can address issues like this.
