### ISSUE TITLE
Viewer UI/UX Feedback

### ISSUE THREAD

**Issue by leowmjw** [openspending/openspending#894]
For dataset: http://s145.okserver.org/viewer/ministry-budgets-malaysia-2016-revised?measure=amount.sum&groups=entity

Viewer UI/UX feedback from my colleague:

```
sweemeng March 16th at 11:49 AM  
* Pie chart can be bigger, but hard to read....
* treemap label should be a float
```

**Comment by pwalsh** [comment]
Hi @leowmjw 

As noted here https://github.com/openspending/openspending/issues/893 let's wait for #874 before feedback on the UI, as it is simply not the final UI yet. When we announce the public alpha release ( see here for details https://discuss.okfn.org/t/openspending-next-status-update/2249 ) then, that will be the time for ui/x feedback.
