### ISSUE TITLE
Walkthrough examples for end user docs

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#896]
In the [OpenSpending documentation](http://docs.openspending.org/en/latest/), the section for end user documentation is broken into three parts:

* [Explore](http://docs.openspending.org/en/latest/users/explore/#walkthroughs)
* [Interact](http://docs.openspending.org/en/latest/users/interact/#walkthroughs)
* [Export](http://docs.openspending.org/en/latest/users/export/#walkthroughs)

For each section, I've added placeholders for "walkthroughs", with steps we need to cover. When the UIs of each app are ready, someone needs to flesh out these walkthroughs for end users.

@cecilaki

**Comment by VictoriaVlad** [comment]
Draft steps for "Explore," "Interact," and "Export" in OS documentation is available here, page 1&2, https://goo.gl/5SYR0R

**Comment by pwalsh** [comment]
@VictoriaVlad 

I've made some comments. In addition to the comments, we need good screenshots for pretty much every step. Screenshots that highlight the particular part of the UI being talked about.

**Comment by pwalsh** [comment]
@VictoriaVlad I've also made the document open for public viewing and commenting.
