### ISSUE TITLE
Always recode data package resources to utf-8

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#897]
Users add data sources that are encoded in a range of encodings. We cannot change that, and we want to be liberal in what we accept. 

However, we do want to ensure that once the data goes to the OpenSpending datastore, it is all available in a single encoding: utf-8. 

We want to do this so that:
- All apps and services that process the datastore data further can _expect_ that data is encoded in utf-8
- All data exported back out of OpenSpending is in a consistent format

In order to do this, we need to add a [`Processor` to Tabulator](https://github.com/frictionlessdata/tabulator-py/tree/master/tabulator/processors) that creates, as a side effect, a recoded file from the input. this recoded file can then be stored as the resource, replacing the original (which should also be kept - details TBD).

@akariv

**Comment by akariv** [comment]
Related to #902

**Comment by pwalsh** [comment]
@akariv I'm inclined to close this. Data uploaded by pipelines is probably recoded to utf-8 right? So, is it worth adding a service to do this for packager-loaded data? If you think we should do it, then pls comment, and we can keep open on the backlog.

**Comment by pwalsh** [comment]
@akariv ??
