### ISSUE TITLE
Walkthrough examples on contributor docs

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#899]
In the [OpenSpending documentation](http://docs.openspending.org/en/latest/), the section for data contributor documentation is broken into three parts:

* [Prepare](http://docs.openspending.org/en/latest/contributors/prepare/#walkthroughs)
* [Package](http://docs.openspending.org/en/latest/contributors/package/#walkthroughs)
* [Load](http://docs.openspending.org/en/latest/contributors/load/#walkthroughs)
* [Use](http://docs.openspending.org/en/latest/contributors/use/#walkthroughs)

For each section, I've added placeholders for "walkthroughs", with steps we need to cover. When the UIs of each app are ready, someone needs to flesh out these walkthroughs for end users.

@cecilaki

**Comment by VictoriaVlad** [comment]
In regards to "Prepare" walkthrough, the current draft says: "Use packager to add a data source, and show the UI for the GoodTables error report". In my understanding, GoodTables is integrated with the Packager, thus in the text, can we suggest contributors to modify their files according to DataValidations results (which uses GoodTables)?

In regards to "Load" the current draft seems to be an internal note. Should it be modified for the final user, describing step by step with the scenario of one data source?

**Comment by pwalsh** [comment]
Just do it however you think makes sense, don't worry about the notes I left there when I first created this.

**Comment by VictoriaVlad** [comment]
Draft steps for "Prepare," "Package," and "Load" in OS documentation is available here, page 3 https://goo.gl/5SYR0R

**Comment by pwalsh** [comment]
@VictoriaVlad 

I've made some comments. In addition to the comments, we need good screenshots for pretty much every step. Screenshots that highlight the particular part of the UI being talked about.

**Comment by pwalsh** [comment]
@VictoriaVlad I've also made the document open for public viewing and commenting.
