### ISSUE TITLE
OS Viewer Cyrillic and Latin letters

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#901]
I uploaded a .csv file to http://s145.okserver.org/packager/ in Macedonian, thus with Cyrillic letters. In the Viewer, some of the words were converted from Cyrillic to Latin, for example from "Дотации" to "dotatsyy", while some stayed in Cyrillic, such as "Година".

Some of the words did not convert completely, for example Буџет converted to "bu-et", with a "-" instead of letter "џ".

 My recommendation is to consider leaving all the words in Cyrillic, if possible.

![cyrillic vs latin letters](https://cloud.githubusercontent.com/assets/17012538/13952704/798a65ce-f040-11e5-8524-39baeb1c260d.jpg)

**Comment by akariv** [comment]
Victoria, can you please send me the  CSV file so I can try and reproduce
the issue?
