### ISSUE TITLE
OS Packager - add possibility to upload files in excel format/Google docs link

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#902]
In order to accommodate more users, the recommendation would be to let the user upload files in Excel to the Packager.

If possible, accepting a Google Doc link would also make the OS Packager more accessible.

**Comment by akariv** [comment]
@pwalsh - perhaps we need a sort of spreadsheet normalizer service (maybe an extension to goodtables), that re-encodes any table format as a utf-8 csv file?

**Comment by pwalsh** [comment]
@akariv yes, it would be best. I have looked pretty deeply into doing proper Excel support in JS, but no existing solutions support streaming reads, so it would def. be more manageable to have a service that uses Python which can ingest the excel file (for instance), open it and read/convert a stream out.

As for Google Sheets support, it is on the roadmap for Tabulator. I guess when we refactor GoodTables to use tabulator internally we'll be able to build stuff like this more easily. I'm trying to prioritise that refactor.

**Comment by akariv** [comment]
We start with the possibility to have URLs for files other than CSV.
e.g. `https://raw.githubusercontent.com/openspending/os-fdp-adapters/master/os_fdp_adapters/excel-adapter/tests/test.xls`

Upon every URL, we hit the fdp-adapter endpoint: 
`http://next.openspending.org/fdp-adapter/convert?url=https://raw.githubusercontent.com/openspending/os-fdp-adapters/master/os_fdp_adapters/excel-adapter/tests/test.xls`

 - If this file type is not supported, we get a `404` and we should proceed as before (assuming this is a csv/json file based on extension).
 - If this file type is supported, we will get a valid `datapackage.json` file, which we can use in the same flow as the already existing "json-based-modelling" (i.e. issue #982). Note that the resources in this case will not be in the datastore so we should make sure that they are downloaded and uploaded during the process.

(we can still assume only one resource per datapackage.json file)

Please also update instructions and texts as necessary.
