### ISSUE TITLE
Hide email authentication in the Viewer URL link/on page

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#903]
I've noticed my email in the Viewer URL, it is possible to hide it?

http://s145.okserver.org/viewer/emailhere@gmail.com:aerodrom-municipality-macedonia?measure=donatsyy.sum&groups=datetime

The same goes for the page
![email authentification](https://cloud.githubusercontent.com/assets/17012538/13953010/606f1592-f042-11e5-9deb-aaace8775291.JPG)

**Comment by akariv** [comment]
Yes, that's actually part of this sprint. I'll update the issue when it's
resolved.
