### ISSUE TITLE
OS Viewer : Add more user guidance in the command sidebar

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#906]
1 - Clearly indicate the budget phase to select to initiate the viz if multiple phases

When menu open
<img width="288" alt="capture d ecran 2016-03-30 a 00 43 53" src="https://cloud.githubusercontent.com/assets/6681719/14128052/1bcfc110-f615-11e5-851a-c8781e93f10e.png">

When menu closed
<img width="290" alt="capture d ecran 2016-03-30 a 01 17 09" src="https://cloud.githubusercontent.com/assets/6681719/14128063/2e81a22e-f615-11e5-8daa-d47ea0facf88.png">

( _the way it's represented doesn't integrate proper UI kit guidelines in terms of font hierarchies. To be adjusted accordingly. Wording might not be super. It's just the general idea _ ) 

2 - Indicate the "Group by" action

By year if multiple years in the dataset + Other if applicable

<img width="289" alt="capture d ecran 2016-03-30 a 01 11 22" src="https://cloud.githubusercontent.com/assets/6681719/14128097/8e11c9d0-f615-11e5-82d9-95fbd547705d.png">

3 - The rest to be continued after wording validation.

**Comment by pwalsh** [comment]
1. Multiple measures are not necessarily phases of a budget, so we can't code such logic arbitrarily, unless the FDP actually declares that these measures are phases ( @akariv @danfowler )

2. Good idea, as long at it makes sense generically ( @akariv )

**Comment by akariv** [comment]
Yes, right now FDP provides little information regarding measures (in fact, nothing more than the phase which is not applicable in many cases).
Re the left bar - Levko's last commit changed its functionality quite a bit, let's reasses once it's deployed.

**Comment by cecilaki** [comment]
@akariv yes. Let's see what it changes. 
@pwalsh Definitely to have this logic used generically. I was thinking it should be present  if, of course, the condition is met. Like "if the FDP declares multiple phases" then display this. Was wondering if the phase would be a necessarily information to indicate when mapping the amount. ( for further filtering or display in the explorer )

**Comment by akariv** [comment]
@cecilaki this is the time to see what is still missing :)

**Comment by akariv** [comment]
@cecilaki bump

**Comment by pwalsh** [comment]
@akariv can we close this?

**Comment by pwalsh** [comment]
OLD. CLOSING.
