### ISSUE TITLE
OS viewer : add user guidance to use the viz navigation buttons

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#907]
Not very clear how to navigate back and forth in the treemap. 

An idea would be to better indicate where the action button is
(_wording might not be perfect_)

<img width="126" alt="capture d ecran 2016-03-30 a 01 28 03" src="https://cloud.githubusercontent.com/assets/6681719/14128216/d31fab90-f616-11e5-8b61-e9f6a65f1dab.png">

If possible place the drill down navigation right above the viz 

<img width="967" alt="capture d ecran 2016-03-30 a 01 28 16" src="https://cloud.githubusercontent.com/assets/6681719/14128255/1c3c427a-f617-11e5-973c-c47dfff7436d.png">

**Comment by pwalsh** [comment]
+ 1 on some wording to indicate that this is state navigation.

It can't be specific like "treemap navigation", as it is actually global navigation for the viewer.

-1 on moving to left.

UX suggestion: making it a fixed position widget (so it is available as the user scrolls down), with wording and more visual emphasis, so that it is more visible as a core action to the user. ( @smth WDYT? )

**Comment by akariv** [comment]
It should be part of the vis as it should also appear in the embed.

**Comment by pwalsh** [comment]
@akariv it definitely should be part of the embed in general, but the first task for @borysyuk on having single view embeds was just to render the desired state, so, we can iterate on the single view embeds in near future.

**Comment by akariv** [comment]
OK - but let's keep in mind that when embedding, drilldown will still work - except you wouldn't be able to back-up (which feels a little broken to me). 
We should probably have a 'navbar' control which will be included in the embed along with the drilldown-able charts.

**Comment by smth** [comment]
These are new to me. Do we have a working example of what they do?

**Comment by pwalsh** [comment]
so, it should be opened as a ticket so there is visibility for the enhancements required.

**Comment by cecilaki** [comment]
+1 on navigation part of the embed for the reasons described by @akariv . User should still be able to navigate within the viz even if embedded. 

About wording. I originally thought of 'Back / Return' but it describes only one type of action and exclude the other possibility. What about only 'navigation', is that specific enough?

**Comment by cecilaki** [comment]
State navigation guidance: 

- Add a « Navigation » title above the navigation button. Needs to be generic and not tiled to a specific viz type.
- The navigation should be part of the single embed viz container
( _what if the user has multiple viz opened on the page and wants to navigate in a specific one, it's currently impossible, the navigation operates only in the top viz_)
- Single embedded viz should not be static
- User should be able to navigate through a single embedded viz when embedded. 
- From UX perspective, quoting @pwalsh "add a more visual emphasis, so that it is more visible as a core action to the user."

**Comment by smth** [comment]
As far as I can see, looking at http://os-viewer.herokuapp.com/405f5e1681d4b6673fbfc0ceb196fe47:boost-armenia-2006-2014?measure=adjusted.sum&groups[]=activity.program&rows[]=activity.program&columns[]=activity.program these controls navigate the history of the page, not just the a single visualistation (includes changing of filters). Presuming that this is not going to change, my preference here would be to remove them and let the user use their browser controls. (Do these controls behave any differently to the browser back and forward buttons?)

In regards to navigating a treemap, particularly when embedded, I think the breadcrumb idea (discussed in https://github.com/openspending/openspending/issues/908) is potentially a better solution.

**Comment by cecilaki** [comment]
@akariv @smth >

- Do we close this issue since I understood from our last discussion that the navigation buttons will disappear in viz such as bubble tree and treemap per decision of implementing a breadcrumb instead, to navigate back and forth in the drilldown?

**Comment by cecilaki** [comment]
Closing since those navigation buttons to be replaced by breadcrumb as main navigation in a viz. 
To be fixed in #908
