### ISSUE TITLE
OS Viewer: Ability to update visualisation description / metadata

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#909]
Wondering from where this description would come from. 
Looks like there's a different description for each viz but what is the possibility offered to create/update it in the interface?  

<img width="941" alt="capture d ecran 2016-03-30 a 01 52 55" src="https://cloud.githubusercontent.com/assets/6681719/14128804/23e201c2-f61c-11e5-9be9-62ff551f04f7.png">

**Comment by pwalsh** [comment]
AFAIK, this is a just a description of the type of vis itself, and therefore is not open for user to edit. 

@smth is my assumption correct, as per your intention?

@kravets-levko these descriptions probably should be part of the babbage.ui API, if my assumption is correct.

**Comment by smth** [comment]
My intention was to give some context, especially when the visualisation is shared/embedded elsewhere. Ideally, I think this would reference the data, but failing that, a generic explanation might still be useful.

**Comment by cecilaki** [comment]
@smth I actually like very much the initial intention to give some context if the viz is shared, but also if the user creates multiple viz with different data configurations. If the viz are stored in the user account (is that the case?) it's a way to easily retrieve them. Not sure about the value of a generic explanation per viz.

**Comment by akariv** [comment]
@cecilaki I'm assigning this to you so you can spec it. 
It could contain the description of the dataset, a verbal description of the visualization (e.g. 'Area chart of approved measure in USD vs year'), a combination of both or anything else.

**Comment by cecilaki** [comment]
This box should be editable so the user can enter/edit

-  An appropriate title for the visualisation
-  Any description of her/his choice of the visualisation (not the dataset)

By default the **Title** field should contain a verbal description of the visualisation established with the 
- Viz type ( Eg: Bar Chart) 
- Measures selected in the viz (Eg: `phase` ) 
- Possible period/years if selected or detected in the dataset (if `datetime` applicable here )
- Currency 

The _Lorem ipsum_ text should be replaced by "_Add a description on how to read this viz_" 
When the user clicks on it, the text is replaced by the user's description. The user can leave this blank also.

**Comment by VictoriaVlad** [comment]
+1 to Cecile's description of the editable box/title
Would it possible to offer the user the opportunity to input data so one doesn't get the “Lorem ipsum dolor” default description?
