### ISSUE TITLE
OS Viewer should not need config for Cosmopolitan

### ISSUE THREAD

**Issue by pwalsh** [openspending/openspending#910]
https://github.com/openspending/os-viewer/blob/master/app/config/index.js#L16

Cosmopolitan is only a dependency for the views, in `babbage.ui`, not Viewer.

**Comment by pwalsh** [comment]
@akariv is this still relevant? Might be an easy one to pick up with @vitorbaptista is working on vis stuff.

**Comment by pwalsh** [comment]
@akariv pls confirm, or deny, or....

**Comment by akariv** [comment]
Just checked - os viewer only uses the URL as a config for the geo visualization.

**Comment by akariv** [comment]
@pwalsh we can close this.
