### ISSUE TITLE
Replace elasticsearch-py with elasticsearch-dsl in OS-API and OS-Conductor

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#918]
See here:
http://elasticsearch-dsl.readthedocs.org/en/latest/

**Comment by pwalsh** [comment]
@akariv is this still relevant?

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (>3 years) as part of #1478. Please feel free to re-open if this is still relevant.
