### ISSUE TITLE
OS-Viewer left panel: sorting and multi-level menus

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#919]
We need to design and implement the following:
 1. In some cases, we want to enable sorting based on a dimension / measure. 
    In these cases, a 'sorting' icon will appear next to each sortable dimension. This icon will have 3 states:
     - Disabled - only one 'sortable dimension' can be active at any time. This state is used to mark a dimension as 'sortable'.
     - Sorting enabled, ascending
     - Sorting enabled, descending
   
  Naturally, if you come up with a better solution with the same functionality go for it.

 1. The left panel should allow for one more nesting level. Here's a sample hierarchy in the left panel:

```
Measures
  Measure 1 (s)
  Measure 2 (s)
X-Axis
  Functional classification
    Dimension 1 (s)
    Dimension 2 (s)
  Administrative classification
    Dimension 3 (s)
Series
  Functional classification
    Dimension 1
    Dimension 2
  Administrative classification
    Dimension 3
Filters
  Functional classification
     Dimension 1
        Dimension 1 Value 1
        Dimension 1 Value 2
     Dimension 2
        Dimension 2 Value 1
        Dimension 2 Value 1
  Administrative classification
     Dimension 3
        Dimension 3 Value 1
        Dimension 3 Value 1
```
 - Only the filter values strictly need to be expandable. 
 - (s) means "sortable"

**Comment by smth** [comment]
I have put that example hierarchy into the existing design, and added new icons for sortable items.
https://trello-attachments.s3.amazonaws.com/5666c84ce46f5fcb518d75b9/2600x2672/d8b3bd47ecd753daf399d8cf69a5e9cb/viewer_03_sidebar_02.png

I'm not sure about the purpose of the "filters" heading in your example (which I have thus far omitted). Maybe in a different example it would appear more useful, but "filters" seems a little redundant (I'm thinking of "filters" in the respect that everything with the square icon is a filter).

If we do need that filter heading, perhaps the headings in my mockup should read: 
"Filter / Functional classification" 
"Filter / Administrative classification"

**Comment by smth** [comment]
Icon: https://github.com/openspending/os-style-guide/commit/92c08abe8f3bc703b8ad2c5687ffbcc22293dfe5

**Comment by akariv** [comment]
Hey @smth , I don't think that 'Filters' is redundant and I'll explain:
Let's take as an example a simple bar chart for the top funded projects in your area in 2014. 
You need to make three selections:
 1. Select a measure, for example 'Approved Budget'
 2. Select a dimension, for example 'Project Name'
 3. Filter the data, for example 'Year=2014 & Region=Brighton'

So filtering is on the same conceptual level as 'measures' and 'x-axis' selection, which is why I suggested they share the same design. Otherwise, one might conclude that selecting a measure is equivalent to filtering on functional classification, which makes little sense.

(btw, terminology aside, there's an essential difference between steps 1 & 2 - which select the columns to use - and step 3 - which filters data based on the actual values. Hence the need for different terms to describe the different steps)

**Comment by smth** [comment]
I can see we are looking at this from slightly different points of view. I wasn't considering that the user needs/wants to know whether you are selecting or filtering a column.

On the face of it, that example does nothing to convince me that I need to know what's happening, technically. I need to better understand the problem with seeing all the filters as equivalent. Is it a sequential thing, i.e one selection needs to be made before the other(s)? If so, I can certainly see the problem.

If it's that we want to be explicit about everything, does this suggestion work?
  "Filter / Functional classification"
  "Filter / Administrative classification"

**Comment by akariv** [comment]
I agree that the technical kind of filtering is not that important from a
usability point of view, but the fact that these menus behave very
differently.

For example, me might have situation where we have
 - the 'Hierarchies' menu (which in fact is 'select a hierarchy'), with
'Functional Classification' as a selectable item, and right after
 - a 'Functional Classification' header, with 'Level 1' as a sub item.

This is confusing as it's not clear what's the difference between both
instances of 'Functional Classification' appearing in different levels of
the hierarchy, as well as why 'Measures' (='select a measure') and 'Functional
Classification' appear on the same level.

Adding a 'Filter' prefix on every header might work, although I would much
prefer to enclose all these menus under one 'filter by value' header.
