### ISSUE TITLE
Viewer: Allow years in row in pivot tables

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#924]
I was challenged on the following usecase of the pivot table or table : 

- Selecting one phase measure (approved / executed etc.. )
- Select "Years" in rows
- Select an admin or eco measure to display

Bonus : add a % column 

![table_viz_usecase](https://cloud.githubusercontent.com/assets/6681719/14311674/2efc2226-fbae-11e5-81d6-d51949c4f5ad.png)

**Comment by akariv** [comment]
![screen shot 2016-04-06 at 12 35 17 pm](https://cloud.githubusercontent.com/assets/265333/14312233/197d1ff4-fbf4-11e5-825d-6a57e7d60152.png)

Let's open an issue for the '%' column as a future enhancement.

**Comment by akariv** [comment]
@cecilaki does that answer the question?

**Comment by cecilaki** [comment]
Yes @akariv thank you very much. 
Questions: 

a - Can we add by default the years/datetime in the columns if the conditions of having several years in the dataset is met, and was thinking of highlighting the default parameters somehow in the UI as well.
b - Wdyt of opening an issue for improvement for: being able to download the result of pivot table as CSV/export the result data?

**Comment by akariv** [comment]
(a) Yes, let's open an issue for that (perhaps make it more generic, to state what should be the default  in other cases (e.g. if no multiple years are present) and also to make sure that we're not selecting by default a dimension with more than X values (maybe we should disable them completely for selection as a column)
(b) Sure thing. Generally speaking, I always prefer an issue that we can discuss and sometimes choose not to implement over a forgotten good idea.
