### ISSUE TITLE
OS-Viewer / Babbage API

### ISSUE THREAD

**Issue by larjohn** [openspending/openspending#929]
Currently, the OS Viewer at herokuapp uses the dimension's label to select a cut. Specifically for this model: 

(http://next.openspending.org/api/3/cubes/405f5e1681d4b6673fbfc0ceb196fe47:boost-armenia-2006-2014/model)

this URL is called:

http://next.openspending.org/api/3/cubes/405f5e1681d4b6673fbfc0ceb196fe47:boost-armenia-2006-2014/aggregate?drilldown=activity.program&pagesize=30&cut=classification.econ_func%3A%22Economic%22&order=adjusted.sum%3Adesc

which means that the query parameters are:
```
drilldown:activity.program
pagesize:30
cut:classification.econ_func:"Economic"
order:adjusted.sum:desc
```

But in the model you can see this dimension:

```json
classification_econ_func ": {
"ref": "classification_econ_func",
"label_ref": "classification_econ_func.econ_func",
"key_ref": "classification_econ_func.econ_func",
"attributes": {
    "econ_func": {
        "label": "econ-func",
        "ref": "classification_econ_func.econ_func",
        "datatype": "string",
        "orig_attribute": "econ-func",
        "column": "econ_func"
    }
},
"key_attribute": "econ_func",
"label": "classification.econ_func",
"cardinality_class": null,
"label_attribute": "econ_func",
"orig_dimension": "classification",
"hierarchy": "classification"
}
```

Clearly, `classification.econ_func` is the dimension's label. Why not use the dimension's `ref `- what is the point in keeping so many similar 'safe-variable-name' attributes and eventually just use the label?

**Comment by akariv** [comment]
Right now the packager doesn't generate the `labelFor` attribute, so the viewer can't have two attributes describing the same thing. Once this is resolved in the packager it should also be resolved in the viewer as well.
