### ISSUE TITLE
Link and embed code generated in Viewer lead to homepage

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#932]
Link generated through "</>" option in the Viewer leads to OS homepage
![create link](https://cloud.githubusercontent.com/assets/17012538/14519990/b2393bd8-022a-11e6-80ee-cb2a081477aa.JPG)
Link leads to
![leads to oshomepage](https://cloud.githubusercontent.com/assets/17012538/14520022/e3b5aad4-022a-11e6-815e-e994794e946e.JPG)

The same with the embed code
![embed code leads to os homepage](https://cloud.githubusercontent.com/assets/17012538/14520168/a72f9c22-022b-11e6-9cd6-4226ec93e105.JPG)

**Comment by akariv** [comment]
We need to add 'basePath' to all embed links.

**Comment by VictoriaVlad** [comment]
hi! I've tried the link generated again and it did not work for me (http://next.openspending.org/embed/treemap/8c248ff162c3c3b957f487138850eaf2:school-data?measure=budget_per_student.sum&visualizations%5B%5D=Treemap&groups%5B%5D=entity.school_name&rows%5B%5D=datetime.year&columns%5B%5D=datetime.year&filters=location.rayon%7CBriceni)

**Comment by cecilaki** [comment]
Reproduced! Link didn't work for me either

**Comment by akariv** [comment]
The issue is closed, but the server wasn't updated with the code yet.
