### ISSUE TITLE
Duplications in colour pattern in treemap visualization

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#933]
I would expect the tree map viz colors to follow a patter. For example, the 17 thousand and 9 thousand amounts (both in the lower row) have the same color, I would see that different.
![treemap schools](https://cloud.githubusercontent.com/assets/17012538/14520284/527a6f4e-022c-11e6-9571-69df3312f5ed.JPG)

**Comment by cecilaki** [comment]
+1 @VictoriaVlad ! Also was wondering if it would be nice to add the currency near the amount. When viz embedded, could become relevant.

**Comment by akariv** [comment]
@cecilaki let's open a separate issue for the currencies plz.

**Comment by pwalsh** [comment]
This is done in latest work on colours.
