### ISSUE TITLE
Define a column dimension by default in the Pivot Tables

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#935]
A. Define a dimension by default that would apply if 

- no multiple years are present
- has no more than X values
- if has more than X values, then disable dimension completely for selection as a column
 
B. If multiple years are present:
 
- add this dimension as default in the columns

**Comment by akariv** [comment]
X = 50

**Comment by cecilaki** [comment]
With X = 50, I guess this will also fix the problem of pivot tables performing very poorly if a dimension selected has lots of possible values.

**Comment by akariv** [comment]
Yes, indeed
