### ISSUE TITLE
Add currency next to amount in Treemap

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#937]
Suggested after #933 

Add the currency near to amounts in Treemap viz

**Comment by kravets-levko** [comment]
This task is related to `babbage.ui` lib - first of all we need to add ability to use custom function for value formatting in `babbage.ui` components, and then we'll be able to implement this task in OS Viewer.
cc @akariv @pwalsh

**Comment by akariv** [comment]
Okay, that's a good plan.
Let's add these custom options when we get to work on this issue.

**Comment by cecilaki** [comment]
To give you a heads-up, this will probably become a requirement sooner or later given the number of feedback. @kravets-levko what are (could be) the other functionalities/features that are coming out of the ability to use custom function for value formatting in babbage.ui components?

**Comment by mlukasch** [comment]
Hello @cecilaki 
maybe you dont want the currency as letters but rather the Symbol like € or $ here. 
![currency_osviewer](https://cloud.githubusercontent.com/assets/17597578/16051033/511f698a-325e-11e6-9c3b-f699a7541e90.PNG)
http://stormy-wave-35321.herokuapp.com/525a389a219b4aa66f2b2b94311c76e5:flanders_2014_revenues_expenditures?measure=Bedrag.sum&order=Bedrag.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=administrative_classification_2.ESC_Niveau_A&rows%5B%5D=administrative_classification_2.ESC_Niveau_A&columns%5B%5D=administrative_classification_2.ESC_Niveau_A

**Comment by akariv** [comment]
Yes, for the few well known currencies (USD, GBP, EUR, JPY) we could hardcode replacement to symbol.

**Comment by mlukasch** [comment]
Is adapted.
http://stormy-wave-35321.herokuapp.com/8c248ff162c3c3b957f487138850eaf2:kisela-voda?measure=yznos.sum&order=yznos.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=classification_economic_stavka.stavka&rows%5B%5D=classification_economic_bylans.bylans&columns%5B%5D=classification_economic_bylans.bylans&filters=classification_economic_bylans.bylans%7C%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B8

http://stormy-wave-35321.herokuapp.com/583b10ad15f2e7f078afd3431c2c09ea:test?measure=adjusted.sum&order=adjusted.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=date_2.year&r
![currency_os_2](https://cloud.githubusercontent.com/assets/17597578/16084694/fca94422-3319-11e6-9be5-3eb5765a73fd.PNG)
ows%5B%5D=date_2.year&columns%5B%5D=date_2.year
![currency_os_1](https://cloud.githubusercontent.com/assets/17597578/16084683/f665658c-3319-11e6-80cb-e5274157e15f.PNG)

**Comment by mlukasch** [comment]
Please have a look if it is ok:
http://vast-caverns-82124.herokuapp.com/8c248ff162c3c3b957f487138850eaf2:kisela-voda?measure=yznos.sum&order=yznos.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=classification_economic_stavka.stavka&rows%5B%5D=classification_economic_bylans.bylans&columns%5B%5D=classification_economic_bylans.bylans&filters=classification_economic_bylans.bylans%7C%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B8

http://vast-caverns-82124.herokuapp.com/583b10ad15f2e7f078afd3431c2c09ea:test?measure=adjusted.sum&order=adjusted.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=date_2.year&rows%5B%5D=date_2.year&columns%5B%5D=date_2.year

![currency_os_1](https://cloud.githubusercontent.com/assets/17597578/16086156/d630f290-331e-11e6-8ea9-746044b2e765.PNG)
![currency_os_2](https://cloud.githubusercontent.com/assets/17597578/16086166/db11dfd6-331e-11e6-8e63-0240a6720dc5.PNG)
