### ISSUE TITLE
Sort the currencies in Fiscal Data Packager

### ISSUE THREAD

**Issue by stevage** [openspending/openspending#944]
The currencies in the drop down seem to be randomly sorted, which makes it hard to find the one you're looking for. 

<img width="191" alt="screenshot 2016-04-16 20 05 58" src="https://cloud.githubusercontent.com/assets/678344/14580394/ac766758-040e-11e6-985b-070983c0b3f5.png">

**Comment by akariv** [comment]
Yes, this was already fixed by levko in #900, will be deployed pretty soon I guess.

**Comment by stevage** [comment]
Ok, my build was out of date, sorry. (Sometimes I miss a step in git pull ; gulp ; hard refresh browser and bypass cache.)
