### ISSUE TITLE
OS-Explorer

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#947]
Create a simple search page for packages in OS.
Single page app, showing a simple search box in the middle of the screen.
Once the user starts typing, the search box is moved to the top right and results start showing as the user types (a-la instant search in chrome).
In this mode, advanced search options also appear, allowing to filter by continent, country etc.
Results appear in an ordered list below the search box. Each result shows important metadata on the package, e.g. author, geodata etc.
Clicking on a result sends the user to OS-Viewer for that specific dataset.
Until we have an official design, you can try and design this yourself, based on the OS theme.
As usual, make sure that external configuration can be loaded via environment variables. Also make sure that the site can be loaded in a relative path.

- [x] Get acquainted with the search API
- [x] Create a single page app, similar to OS-Viewer
- [x] Implement interaction and API use
- [x] Write simple test suite

**Comment by akariv** [comment]
See #892 for some inspiration (which you don't necessarily have to take)

**Comment by akariv** [comment]
Also @kravets-levko , to simplify things, let's keep it a frontend only app, and put all configuration (e.g. search endpoint) in a config.json file which won't be minified (so that it could be replaced with actual values after deployment).

**Comment by pwalsh** [comment]
I think that we need all the apps to be easily configurable for alternate OS installs, just like the other Viewer and Packager, which is why having the frontend code run in a lightweight mode app is so useful. Will we lose this here?

**Comment by akariv** [comment]
@pwalsh Doesn't it feel to you to be too much boilerplate just for passing a configuration variable to the app?
Isn't is simpler to run something like`echo '{"env":"$ENV_VAR"}' > app/config.json` before starting the app, thus allowing to serve it using nginx (and not node), avoid using two sets of templates and routing rules and heavier images?
(I'm honestly asking here, it's possible that I'm missing something...)

**Comment by pwalsh** [comment]
The other major thing is url routing.

**Comment by pwalsh** [comment]
For our OS install you use nginx heavily which is fine, but not sure it makes for an easy generic setup, esp. For those who just want to work with one app of the whole suite. It is easy now to use the Packager standalone, and not have to setup nginx locally etc etc.

**Comment by akariv** [comment]
Usually for local development it's very easy to work with `gulp watch` or `grunt serve` or any such contraption which builds, opens the browser with the app and reloads the app / injects new css whenever something changes. There's no need for nginx at all (unless you want a production setup, which is something different).

**Comment by pwalsh** [comment]
There is for url routing, that works consistently across browsers without hashes/hashbangs... But ok :).
