### ISSUE TITLE
Insuring OS-Packager and OS-Viewer all browsers compatibility

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#948]
Browsers compatibility should be:

| Safari        | Chrome           | FF  | IE |
| ------------- |:-------------:| -----:| -----:|
| Safari 9.1      | Chrome 49.0 | Firefox 38.7.1 | IE 10 + | 

Test on all browsers to validate/close this issue.

**Comment by cecilaki** [comment]
@akariv correct me if I'm wrong regarding browsers' standards at today's date.

**Comment by akariv** [comment]
No, that's about right.

**Comment by akariv** [comment]
@kravets-levko tested on the following browsers:
Chrome 50.0.2661.86 (64-bit), Firefox 45.0.2, IE10 and 11

Said no major issues found.

@cecilaki do you know which IE version is problematic?

**Comment by cecilaki** [comment]
@akariv yes it's IE 11. Can you screenshot this one? And then I'll ship it! thanks!

**Comment by akariv** [comment]
Hmm... I wish I could. @kravets-levko, seems that the viewer in IE11 is not working quite well (fails on `'Promise' is undefined`) - did you change anything to make it work?

**Comment by kravets-levko** [comment]
Hi @akariv and @cecilaki! I'll check app on IE11 once more, thanks for pointing on that issue.

**Comment by kravets-levko** [comment]
@akariv PR which fixes compatibility issues is waiting for merge: https://github.com/openspending/os-viewer/pull/99

**Comment by VictoriaVlad** [comment]
files in IE not working for me (I waiting for a few minutes, restarted a few times, logged in/out)
![ie not uploading](https://cloud.githubusercontent.com/assets/17012538/15118347/81686a12-1614-11e6-8bda-72d1b0c53f33.PNG)

**Comment by akariv** [comment]
Victoria, can you please say what was the file's size?
Also, which IE version did you use?

**Comment by VictoriaVlad** [comment]
@akariv I tried with small files (up to 100KB), in IE11.
