### ISSUE TITLE
Display FDP description below the Title in the Viewer

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#949]
If FDP description exists, then display it below the Title

**Comment by akariv** [comment]
How is this different from #940, already fixed and deployed?

**Comment by cecilaki** [comment]
Is #940 for the Packager only? Or does it also apply in the Viewer? 
My request was for the Viewer, but if #940 does both, then fine!

**Comment by cecilaki** [comment]
It does! sorry.
