### ISSUE TITLE
OS Viewer: Add user guidance in first step before selecting a viz type

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#950]
**Current state** 

- Viewer appears broken since users see "Views" and an empty space below.  They wonder why they don't actually see any chart or visualisation as they would expect after publishing. 

<img width="910" alt="capture d ecran 2016-04-21 a 11 03 49" src="https://cloud.githubusercontent.com/assets/6681719/14705311/c71ec00a-07b0-11e6-9610-7863be8ea49e.png">

**Expected**

- Add some guidance to help user create their first viualisation by adding 

"Create your first visualisation by clicking on the + button and select a visualisation type" 

(_Wording to be revised if necessary. Open to all suggestions_ )

- Add the viz types from the beginning to give the user a full overview of all the possibilities before his first action. 

![viewer_ux](https://cloud.githubusercontent.com/assets/6681719/14705639/7388fdd2-07b2-11e6-9a7c-1c7e95615842.png)

**Comment by akariv** [comment]
To simplify, I suggest we open by default the "select a visualization type"
popup in the case we open the viewer with a dataset selected but no
visualisation - which is the common case after publishing a dataset.

**Comment by cecilaki** [comment]
Can we skip the popup though?

**Comment by akariv** [comment]
What do you mean "skip the popup"?

**Comment by cecilaki** [comment]
I mean displaying directly the information in the page and not having a popup at all.

**Comment by akariv** [comment]
The popup does more than display information - it can be used to add and remove visualizations, and a couple of them in one go. If we're going to remove the pop-up we'll probably need to replace this functionality somewhere else.

**Comment by cecilaki** [comment]
Sure but I think there are some calls to action and indications on how to use them that are still important to indicate, and especially when users just published a dataset and are presented the Viewer with no indication at all on how to move forward. 

Like, create one or multiple viz. And here are the choices you have. Pick one and start!

Why not indicating those actual actions/functionalities into the page directly rather than in a popup? 
I think popups are intrusive when presented without notice. Like it's acceptable to have a popup to select a particular viz to pick up, but to present the types of viz available, it should be on the page directly.

**Comment by smth** [comment]
I like the suggestion of immediately presenting the popup/modal, especially if we feel that users will always want to add a visualisation. I'd suggest that even if we do this, we also add some text to the page, in case someone closes the modal without adding anything (there was some text in my design).

I can see that the modal could be slightly irritating, if you just want to look at the table (I don't know if we are considering that user story), but there are upsides, to weigh against that.

Either way, whether the *add visualisation* widget is in the flow of the page or a modal, I think it should be consistent.

**Comment by cecilaki** [comment]
Agree for consistency + adding some text to the page as per original mockups, and it will remove this feeling of anxiety experienced by all users landing in this page.  (_We don't even say welcome in the Viewer!:)_)

--> next steps: which text? 
Does the following but placed at the right place would fit? 

<img width="1211" alt="capture d ecran 2016-04-26 a 17 31 45" src="https://cloud.githubusercontent.com/assets/6681719/14826749/333e8322-0bd7-11e6-9491-aed2db94994b.png">

I though presenting all viz types could be nice to show what are the existing possibilities before making a choice, but the modal fills that role, so that's fine. But I just liked the idea of always have the type of visualisations available displayed. 

@smth What is the table you're mentioning here? ( I remember your original mocks containing a table, is that this one?) 
 
> _if you just want to look at the **table**_

**Comment by smth** [comment]
Could the available visualisations change, depending on what filters are active? If so, I think I see your reasoning for having the options always available. That said, I'm not sure a user would set out with the objective of "I want a treemap", I would guess, almost always it would be "I want a suitable visualisation for this data". Which makes this less of an issue in my mind.

Yes, that's the table I was referring to. My understanding is that a table is always present, by default.

**Comment by akariv** [comment]
@smth available visualisations change based on the data (e.g. do we have a
location dimension -> map) or by already existing visualisations (e.g. you
can't add a bar-chart along with a treemap, cause the data selection
options for both are different).

**Comment by smth** [comment]
So maybe it wouldn't hurt to add a small indication of what visualisations are available:
![viewer_03_default_02](https://cloud.githubusercontent.com/assets/1375708/14980375/f13a152e-111f-11e6-8191-769d5069475a.jpg)

**Comment by cecilaki** [comment]
To summarize, if I understand correctly, what is gonna be implemented in this issue is: 

After a dataset is selected, the Viewer by default is opening on:

- Dataset Title
- Dataset Description
- The _Add visualisation button & dialog_ box with the sentence "Create your first visualisation by clicking on the + button and select a visualisation type" centered.
- A small indication of what visualisations are available? (so all icons listed by default at opening?) 
- A table showing the original dataset and its different columns mapped in the Packager

Bonus: 
- A link to download/view the raw CSV and JSON files always at the bottom of the sidebar

**Comment by akariv** [comment]
Not quite...

What will appear is:
- Dataset Title & Description are already part of the view.
- The "The Add visualisation button" - based on Sam's mockup.

Adding the table is in issue #958 (unrelated to user guidance IMO)
Adding links to CSV and JSON - cool, but let's open a separate issue for that (again, unrelated to user guidance)

**Comment by cecilaki** [comment]
Ok. I assume Sam's mockup is: 

<img width="1015" alt="capture d ecran 2016-05-05 a 22 55 36" src="https://cloud.githubusercontent.com/assets/6681719/15057078/5ab6f110-1315-11e6-80a6-284d3a793229.png">

Can I insist on changing the wording to "Create visualisation and select a view of your choice", related to user guidance? 

And also, remove the « Add some Views by clicking on the + button and see all available options » currently in the sidebar cause it's redundant.

Agreed on adding table + links to CSV/JSON in separate issues.
