### ISSUE TITLE
Packager InvalidCast Error while publishing

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#951]
Error I get when try to publish [the following CSV file](https://drive.google.com/open?id=1Hr32VpbR5v_3YeX0vsy5u1-gJV61Ppn5cL0NKId_dKo)

`InvalidCastError(ValueError("invalid literal for int() with base 10: 'KUMPULAN WANG RIZAB NEGERI'",),)`

<img width="895" alt="capture d ecran 2016-04-24 a 15 15 10" src="https://cloud.githubusercontent.com/assets/6681719/14768084/631a675e-0a2f-11e6-9133-6072400e8b0f.png">

**Comment by akariv** [comment]
Can you please make sure that the 'Item' column was defined as 'string' and not 'integer'?

**Comment by cecilaki** [comment]
Indeed it validated. 

Then I came across another error that comes from the data itself: the time data as written in the file ( `01/01/16` ) does not match the standard format requirement `%Y-%m-%dT%H:%M:%SZ`

Which makes me think to:

1. List all requirements/format in which the data should be before upload so users can check that list.
2. Improve errors messages by suggesting a solution exactly like you just did.

**Comment by akariv** [comment]
There's no specific date format requirement - but currently the packager does not allow inputting the actual date format. A workaround for now is to specify 'string' instead of 'datetime' as type.
When #943 is complete, this will be fixed as well.

**Comment by cecilaki** [comment]
But if 'datetime' is not specified, then step 2 can't be validated?

**Comment by akariv** [comment]
I'm talking about the data type, not the concept:

![screen shot 2016-04-24 at 5 55 25 pm](https://cloud.githubusercontent.com/assets/265333/14768261/cdcc0042-0a45-11e6-9f64-51081c88b867.png)

**Comment by cecilaki** [comment]
Ah ok. But I don't have `string` as a choice in the datatype.
Can any other choice work?

<img width="292" alt="capture d ecran 2016-04-24 a 15 56 54" src="https://cloud.githubusercontent.com/assets/6681719/14768268/3a2f6622-0a35-11e6-882e-7d388fd39974.png">

**Comment by akariv** [comment]
You can try 'date', but it probably won't work :-|  this behaviour is one
of the reasons we're doing this change.

**Comment by cecilaki** [comment]
Yes I totally understand. So once implemented, users will be able to upload a dataset with any type of data format, and validate it as datatype : datetime + concept = Date / Time ? 

I've tried to modify the dataset to match the format, but it doesn't seem to work either.

**Comment by akariv** [comment]
Yes, that’s correct. 

BTW, the correct format would be `2016-01-01T00:00:00Z`
Another option is to change this column to '2016' and mark it as integer.

**Comment by cecilaki** [comment]
Mazel Tov, [Published!!](http://next.openspending.org/viewer/embed/treemap/525a389a219b4aa66f2b2b94311c76e5:peruntukan-kpd?measure=amount.sum&order=amount.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=classification_administrative.item&rows%5B%5D=classification_administrative.item&columns%5B%5D=classification_administrative.item) (_tried with both options - Clearly the 2d option with the year `2016` is the most readable_ ) 

I'm about to suggest a "successful published" status notification. It's not really clear at the moment that the action has successfully performed. 
<img width="918" alt="capture d ecran 2016-04-24 a 17 17 52" src="https://cloud.githubusercontent.com/assets/6681719/14768693/fe254406-0a40-11e6-81e8-e34e1d5b5411.png">

**Comment by akariv** [comment]
👍
