### ISSUE TITLE
Add a success alert box when DataPackage published

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#952]
**Current**

- Publishing status = no information given on the status to the user
- Link to OS Viewer not enough visible 
- Users are confused about what to do next and if their publication is successful 

<img width="905" alt="capture d ecran 2016-04-24 a 17 04 44" src="https://cloud.githubusercontent.com/assets/6681719/14768888/3044c9cc-0a44-11e6-8c86-c0f4ba83ef87.png">

**Expected**

- Remove the publish button since datapackage is published
- Add a success alert notification box
- Add a call to action button to go to OS-Viewer

Suggestion: 

<img width="785" alt="capture d ecran 2016-04-24 a 17 40 30" src="https://cloud.githubusercontent.com/assets/6681719/14768898/89eeebf6-0a44-11e6-91f7-6094f6d6d0c0.png">

**Comment by cecilaki** [comment]
Was wondering what was your opinion about it @smth

**Comment by smth** [comment]
Yes something like that sounds good.
