### ISSUE TITLE
JSON files upload issues

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#953]
Tried to upload some JSON files, however upload failed.

When trying to upload this file (https://drive.google.com/open?id=0B4mVvh--ffocWUdUeWdFOVRFdUU), there is an error message. The error message appears for less than a second, so I took a screenshot of the moment:
![screenshot_20160425-131433](https://cloud.githubusercontent.com/assets/17012538/14781013/83f6137e-0ae8-11e6-801d-7ca303373991.png)

When trying to upload this file: (JSON: https://drive.google.com/open?id=0B4mVvh--ffocMlRkVVRpdC1Rem8, CVS: https://drive.google.com/open?id=0B4mVvh--ffocR0cwMHNZdWRCNWM), got this error message:
![ed0c1015858fc4fa214c13b159f17f115215d5fedc9ec13c28 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17012538/14781042/c0d648d6-0ae8-11e6-822d-571fbd330a36.png)

**Comment by akariv** [comment]
@VictoriaVlad did this happen to you or someone else?
Why were you trying to upload a json file? 
Is the 2nd related to the first? It looks a lot like a network issue, can you please make sure that you're logged in and that there's no network firewall / proxy that might block the upload?

**Comment by VictoriaVlad** [comment]
@akariv Sinar project tried to upload data when they were not logged in, so in order to save progress they downloaded JSON files. The issue repeated even when they logged it. The screenshots are from a Skype call, when Sinar shared their screen.

**Comment by cecilaki** [comment]
Wait. Can we upload JSON files and not only CSV files in the packager?

**Comment by akariv** [comment]
JSON files are not supported, closing.
