### ISSUE TITLE
"Response for pre-flight is invalid" when uploading to S3

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#960]
Currently facing an error of publishing data package.

![screen shot 2016-04-29 at 6 56 48 pm](https://cloud.githubusercontent.com/assets/11497391/14914400/4bf7e0d6-0e3c-11e6-89c6-3468210b1787.png)

I was testing this on Chrome. Checked the Console Log and found these errors.

![screen shot 2016-04-29 at 6 50 58 pm](https://cloud.githubusercontent.com/assets/11497391/14914416/83217130-0e3c-11e6-9434-2e7faf5fd9c9.png)

Source file: https://docs.google.com/spreadsheets/d/1rYBrKF7n7AlSrEZj_6NTKwWsFi2n6uHE-KGmsegGskQ/pub?gid=2021601&single=true&output=csv

Background of the file: http://data.sinarproject.org/dataset/service-management-department-existing-budget-2016

HELP!

**Comment by akariv** [comment]
@Hazwany , thanks for this report!

If you could please help me debug this situation, I would be very happy if you could go into the 'Network' tab in the developer options, and send me screenshots for one of these requests - select the failing request and then the 'Headers' tab on the right. What's in there might give us a clue for why this is happening.

**Comment by Hazwany** [comment]
Here are the Network Headers

![screen shot 2016-04-29 at 7 55 43 pm](https://cloud.githubusercontent.com/assets/11497391/14915312/79fca77a-0e44-11e6-97e7-95fae43aa575.png)
![screen shot 2016-04-29 at 7 55 32 pm](https://cloud.githubusercontent.com/assets/11497391/14915310/79f251d0-0e44-11e6-8624-d293898cad09.png)
![screen shot 2016-04-29 at 7 55 22 pm](https://cloud.githubusercontent.com/assets/11497391/14915309/79ed11c0-0e44-11e6-9ef8-335ae2921ca3.png)
![screen shot 2016-04-29 at 7 55 12 pm](https://cloud.githubusercontent.com/assets/11497391/14915311/79fc0306-0e44-11e6-9ab2-cb432883220b.png)
![screen shot 2016-04-29 at 7 55 01 pm](https://cloud.githubusercontent.com/assets/11497391/14915307/79e79f2e-0e44-11e6-8e88-67cdebeecd9c.png)
![screen shot 2016-04-29 at 7 48 32 pm]

**Comment by akariv** [comment]
This is awesome @Hazwany , it really helps.

I'll try to get a fix as soon as possible.

**Comment by akariv** [comment]
Hi @Hazwany , I've made a few modifications - can you try to upload again and let me know if there's any change?

**Comment by Hazwany** [comment]
Hi @akariv, I still can't upload the data package.

**Comment by akariv** [comment]
Hi @Hazwany , can you try and follow the instructions here (http://stackoverflow.com/questions/27945501/307-redirect-when-loading-analytics-js-in-chrome), which indicate this might be an extension installed in your browser?
To test that assumption, you can also try and retry the upload from a 'private browsing' window, which disables all extensions by default.

**Comment by Hazwany** [comment]
Hi @akariv, I have tested that assumption. Disabled HTTPS Everywhere extension and allow pop-ups only from [http://next.openspending.org/packager/provide-data/], and it worked! Finally, I can publish! Thank you!

**Comment by akariv** [comment]
I'm delighted to hear @Hazwany , great news indeed 😄
