### ISSUE TITLE
File data should not be loaded completely into the browser's memory

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#961]
When providing a large file to the packager (think ~ 1GB), it should not be loaded into memory. Only a small prefix (a few MB-s)  should be loaded and used for modelling.
After that, the file should be uploaded via a streaming method (again, without loading it completely into memory)

**Comment by rgrp** [comment]
@akariv is this kind of functionality getting "pushed" upstream into the relevant generic JS libraries we have - i imagine this is common to a lot of stuff. For example, I'm doing CSV stream loading in https://github.com/okfn/datapackage-render-js/blob/master/datapackage.js#L142

If so, what are the "core" JS libraries we are reusing?

**Comment by akariv** [comment]
@rgrp we're using quite a few elements from the frictionless data suite - goodtables for file validation, jsontableschema for validating and inferring data types, datapackage-validate to validate the resulting fiscal data package and more.
This specific use case is not related directly to the subject, as we need to upload an unread file to a URL - it's much more low-level than the level where FD libraries usually operate.
