### ISSUE TITLE
additional instruction at metadata page uploader

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#965]
I suggest adding this text to the "And a short English name for your Data Package" _(lower case only)_. 

If the user puts in a capital letter, they get this error:
![lower case](https://cloud.githubusercontent.com/assets/17012538/14985544/a1335492-1150-11e6-8aa7-99c8c35414e9.PNG)

vs the change of "Test" to "test"
![lower case 1](https://cloud.githubusercontent.com/assets/17012538/14985559/aec381ae-1150-11e6-9cd5-f9900ae66795.PNG)

**Comment by cecilaki** [comment]
Aaaaah! That was why! I didn't understand either! 
Why only low cases letters by the way?

**Comment by akariv** [comment]
This is the identifier of the dataset which is then used as the "name of
the dataset" in the FDP.  (and is also used in URLs etc.).
The FDP spec requires it to be a "slug" - which means lowercase english and
no spaces.
