### ISSUE TITLE
Viewer: Add treemap details in list if all items don't fit in viz

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#967]
Quite often, smaller items of a treemap viz can't be represented correctly and are not readable.

Ex:
<img width="684" alt="capture d ecran 2016-05-05 a 23 25 20" src="https://cloud.githubusercontent.com/assets/6681719/15057803/065f8b6e-1319-11e6-8c68-38880e0bd4b7.png">

Idea: 

- List below the viz all items to make sure the user have all information in hand about all items represented in the treemap.
- After a certain size in the viz, don't add labels and amounts

Ex: 
<img width="606" alt="capture d ecran 2016-05-05 a 23 33 31" src="https://cloud.githubusercontent.com/assets/6681719/15057959/d70a763e-1319-11e6-9014-cd4cdaa37431.png">
Source: [offenerhaushalt.de](http://offenerhaushalt.de) 

Open to discussion @akariv @VictoriaVlad @smth

**Comment by akariv** [comment]
@mlukasch what do you think about this issue?

**Comment by mlukasch** [comment]
@akariv Sounds good. Will do it if you give me this task. Should I take the master-branch of: http://github.com/openspending/os-viewer.git I have checked some treemaps on the live site and in these ones the smaller boxes are already empty as requested. So it does not work only occassionally(?) Do you know maybe where I can find suitable test datasets? Thanks a lot.

**Comment by akariv** [comment]
@cecilaki can you add a link to os-viewer where this problem is visible.

**Comment by cecilaki** [comment]
Sure!

@mlukasch have a look at [this one](http://next.openspending.org/viewer/embed/treemap/405f5e1681d4b6673fbfc0ceb196fe47:boost-peru-2012?measure=executed.sum&order=executed.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=activity_project1.project1&rows%5B%5D=activity_project1.project1&columns%5B%5D=activity_project1.project1) or [this one too](http://next.openspending.org/viewer/embed/treemap/405f5e1681d4b6673fbfc0ceb196fe47:boost-tunisia-fr?measure=paye.sum&order=paye.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=classification_administrative_admin1.admin1&rows%5B%5D=activity_prog.prog&columns%5B%5D=activity_prog.prog)

**Comment by cecilaki** [comment]
By the way, another example where this is used in a CSO built [OpenSpending platform in Albania](http://www.spending.data.al/en/openspending/treemap/type/Plan#year:2015/lang:en/budgettype:plan)

<img width="690" alt="capture d ecran 2016-05-09 a 14 50 01" src="https://cloud.githubusercontent.com/assets/6681719/15113583/729bdbd2-15f5-11e6-96a5-37bea01f42b0.png">

**Comment by mlukasch** [comment]
@akariv Hi, sorry. If the babbage.ui-module was the right place for the Change (?) how would one build & release & pull it to the os-viewer. There is a grunt Task: deploy

**Comment by akariv** [comment]
Yes, babbage.ui is the right place. Make sure you're working on the
feature/modern branch.

As for using your version in os-viewer - simplest way is to change the
reference in package.json to point to your fork of babbage.ui on github, or
simply replace the node_modules/babbage.ui folder with your development
code.

**Comment by cecilaki** [comment]
Hi @mlukasch , any progress on this? 
Do you think you can present us your work by the plenary meeting next week? Would be awesome.

**Comment by mlukasch** [comment]
Hello @cecilaki and @akariv , not sure if I have done it technically right. Havent reused any table-component for the list. Treemap-List should show up, only if there is a text overlfow in one of the boxes.
![treemapsolution](https://cloud.githubusercontent.com/assets/17597578/15359562/2cb77920-1d0a-11e6-87b6-cd14d327a171.PNG)

**Comment by cecilaki** [comment]
Seems very nice @mlukasch ! Do you have a working link by any chance? 
When you say the list isn't sortable by any column, do you refer to the items of the list are not clickable to reflect the drill-down of the dataset? (for ex., what happens if you click on `sonstiger personalaufwand`?)

**Comment by mlukasch** [comment]
Hello @cecilaki ,
hope it is fine to make OS publically available on our test server:
http://eis-openbudgets.iais.fraunhofer.de/viewer/da34ef6cdb3c6dc3f21686ebcaa2f74b:test5?measure=amount.sum&order=amount.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=activity_2.from_name&rows%5B%5D=activity_2.from_name&columns%5B%5D=activity_2.from_name

**Comment by pwalsh** [comment]
@mlukasch it is fine and encouraged, but I don't know why we need it. We'll be wanting to run all the ob.eu data out of the canonical OpenSpending instance that OKI runs.

**Comment by mlukasch** [comment]
@pwalsh Im not sure where else I can run the small code change as a demo for you as requested so that you can check. The link I have given you does not work unfortunately. But it is still not finished. Forgot to add the entries as links.

**Comment by pwalsh** [comment]
@mlukasch Read the documentation: http://docs.openspending.org/en/latest/developers/viewer/#installation

Quoting:

    If you just want to hack on the Viewer (Suggest new features! Fix bugs!), or even run your own Viewer against a remote OpenSpending platform, then follow the standalone install.

It is possible to work on individual components of the platform, so in your case, you could just push the Viewer app to a free app host like Heroku and it will just work. Otherwise, you are doing large amounts of configuration for the entire platform, just to work on very small issues on a particular app.

**Comment by mlukasch** [comment]
Hi @kravets-levko, @pwalsh has suggested Heroku for showing changes. I have some problems here to deploy to Heroku when I do changes to babbage.ui. By default heroku does not include devdependencies. So that makes it bit difficult to build the babbage.ui-module from the source-files, if I use the git-URL of babbage.ui as a dependency in the package.json of os-viewer. Maybe you have figured out a good workflow for deploying os-viewer to Heroku for changes on the babbage.ui-module which you can share with me. Thanks a lot.

**Comment by mlukasch** [comment]
Hi @cecilaki , just a short sign of life. Still not working for all datasets. Some bugs in the Aggregate-function in babbage.ui. Here a preview: http://stormy-wave-35321.herokuapp.com/525a389a219b4aa66f2b2b94311c76e5:tret?measure=amount.sum&order=amount.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=administrative_classification_2.level1_id&rows%5B%5D=administrative_classification_2.level1_id&columns%5B%5D=date_2.budget_date

**Comment by mlukasch** [comment]
Hello @cecilaki , it can be tested now on: http://stormy-wave-35321.herokuapp.com/
Atm the items in the list do not reference to somewhere else. Should the items in the list be clickable? In this case to where should they reference/redirect?
If everything is fine, should I add the list also to the pie-chart now?
@akariv sometimes I get a 400 from the server. So the treemap cannot get shown... Should I investigate here?
![os_fehler](https://cloud.githubusercontent.com/assets/17597578/15644799/5e1427b2-2655-11e6-99e7-9a45d6f5e822.PNG)
Thanks

**Comment by akariv** [comment]
@mlukasch can you please attach here a few failing requests so I can investigate?

**Comment by mlukasch** [comment]
@akariv 

http://next.openspending.org/api/3/cubes/0f1b4f6e8d34fdf966e45dd0e3d2c8e7:central-budget-2010-2016/aggregate?drilldown=activity.opys&pagesize=30&order=yznos.sum%3Adesc

http://next.openspending.org/api/3/cubes/583b10ad15f2e7f078afd3431c2c09ea:fghfgh/aggregate?drilldown=date_2.dt_fscl_yr&pagesize=30&order=yznos.sum%3Adesc

http://next.openspending.org/api/3/cubes/086ba4db0d87a68374d5625177ae5153:revtest26may/aggregate?drilldown=date_2.Year&pagesize=30&order=yznos.sum%3Adesc

**Comment by akariv** [comment]
So opening each of these links actually produces a quite clear error
message - e.g for the first one:
`Invalid sorting criterion: ['yznos.sum', ':', 'desc']`

This means that the sorting criterion is not part of the model, and indeed
there's no such measure (`yznos`) in your model. So the question is how
this measure got in your query...
Are you using the latest version of OS-Viewer? If not, please rebase and
see if this still happens.
If you still see these issues in the latest version, could you please open
an issue with exact reproduction steps on how to get the extraneous measure
in the query?

**Comment by mlukasch** [comment]
@akariv The latest version would probably be the master-branch in the os-viewer(?)
Apparently this "yzno" is caused by the url of the dataset:
525a389a219b4aa66f2b2b94311c76e5:tret?measure=amount.sum&order=yznos.sum|desc&groups[]=administrative_classification_2.level1_id&rows[]=administrative_classification_2.level1_id&columns[]=administrative_classification_2.level1_id

**Comment by akariv** [comment]
1. Yes, master branch.
2. I saw that - the question is at which point exactly it got there.

**Comment by cecilaki** [comment]
Hi @mlukasch a quick styling adjustment, could you make the table borders less thick and dark? 
Something like  `border: 1px solid #ddd;` ? 
And looks like the list numbers don't have the correct branding style.
See [style guide](http://labs.openspending.org/os-style-guide/)

Also, ideally, all items should show on the list, not only the smallest under 3%.

**Comment by mlukasch** [comment]
@cecilaki Have removed now the "show small items" and "hide small items" option and now all items show up initially. Had used monospace font for the numbers in order to improve their alignment in a row. But the orignal font is used now again. Please have a look here:  http://stormy-wave-35321.herokuapp.com/23cdc48554ae8648deff7837c025d8c0:service_management_department_existing?measure=Amount.sum&order=Amount.sum%7Cdesc&visualizations%5B%5D=Treemap&groups%5B%5D=administrative_classification_2.ID&rows%5B%5D=administrative_classification_2.ID&columns%5B%5D=administrative_classification_2.ID

**Comment by cecilaki** [comment]
@mlukasch Thank you!
Can you update the code with the following: 
- Always have the list of all items present below the treemap
- Option to show/hide the list
- If the amount is smaller than 2%, then the box is empty from content. 
- If the text overflow is too big for the square box, then the square box remains empty too
