### ISSUE TITLE
Viewer: improve Bubble Tree viz design

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#968]
**Current**
Bubble Tree visualisation can sometimes be challenging to read when:
- There is to many items
- Items are overriding
- Items are cut
- Amounts are not indicated
- Items are sometimes inside and sometimes outside of the bubble

Examples:
<img width="590" alt="design_improve_bubble_tree" src="https://cloud.githubusercontent.com/assets/6681719/15065439/ede11214-135f-11e6-8671-8260a31fc1a3.png">

Too many items
<img width="423" alt="capture d ecran 2016-05-06 a 07 57 04" src="https://cloud.githubusercontent.com/assets/6681719/15065490/80e10f42-1360-11e6-9b8e-524f3c3e36bd.png">

Items override each other
<img width="466" alt="capture d ecran 2016-05-06 a 07 57 26" src="https://cloud.githubusercontent.com/assets/6681719/15065497/8a369bfc-1360-11e6-9e36-37fb986ad4cc.png">

**Expected**
- A more clear visualisation that cover those cases.
- Adding a list of items below the viz

**Comment by smth** [comment]
The first thing I would suggest, that would go a long way to fixing this, is that the number of items is limited, by default the highest values would remain, but would be good if this was configurable. Absent items could (optionally) be grouped into "other", which could of course be drilled down into. This would leave us with something we can realistically polish.

I imagine this actually applies to all visualisation types.

A list may not be necessary with the above approach.

I agree about consistency, I think labels should always be outside of the circles.

**Comment by cecilaki** [comment]
- +1 on a limited number of items to be displayed.

 ( X = ? ) 
- +1 on absent items be grouped into "Other" with the possibility to drill down.
- +1 on labels to always be outside of the circles.

That is a nice first round!

About the configuration, happy to explore this pathway. On one hand this will add more steps to the creation of a visualisation ( select a viz type --> select bubble tree --> choose how many items to be displayed --> validate ) but give a better experience in creating a relevant viz.

At this point, if such settings are offered to the user, I would add the option to display a list of items or not. 
We could maybe align or iron this possibility with other visualisation types.

_This list is currently displayed by default below the pie chart for instance:_

<img width="629" alt="capture d ecran 2016-05-06 a 08 02 30" src="https://cloud.githubusercontent.com/assets/6681719/15066491/c65e6e30-1369-11e6-9751-dced898ec855.png">

**Comment by smth** [comment]
I think the number we show may need a bit of trial and error, but I've mocked up what I think is a nice example, which displays 5 (with numbers) and a further 5 without numbers and with smaller labels:
![bubble-tree](https://cloud.githubusercontent.com/assets/1375708/15067970/0a851d3c-136c-11e6-88f6-227193e64a60.png)

**Comment by cecilaki** [comment]
Moving forward with this approach to give a limitation of number of bubbles displayed:
- 5 big bubbles with amount displayed in the bubble + title highlighted 
- 5 smaller bubbles with no amount displayed + title highlighted 

I'm wondering:
1 - How do we technically and visually handle the case where there are more than 10 bubbles / items to show? Do we create a bubble called "Other", which is ultimately clickable and will display the rest of the items?  @smth @akariv 

2 - Legend / List of items. 
Not sure what's the best way moving forward. 
I like the legend, but currently it doesn't show enough information. I would add the amount, currency and share in %, but then, it'll look more of a list. What do you think @smth ?
