### ISSUE TITLE
Packager: Inform user they need to log in so they can publish a dataset

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#969]
Currently it's not clear in the process that users need to log in to publish a dataset. 
They go all the way along, and at the very last moment, they can't publish the file they've mapped and don't understand why. The `publish` button is deactivated and there is no error message. 

**Expected**

- Indicate clearly at the beginning in `Step 1 Provide your data` that being logged is necessary to be able to publish in the Viewer
- Add an error message in `Step 4` saying they need to log in before publish if it hasn't been done at en earlier stage of the process. 

Totally open to discuss other ways to fix it @akariv

**Comment by smth** [comment]
We can add note about needing to log in here:
![steps](https://cloud.githubusercontent.com/assets/1375708/15104462/bc2dd39e-15b0-11e6-8eb4-caeab166119c.jpg)

and change the text in the button when not logged in 
![actions](https://cloud.githubusercontent.com/assets/1375708/15104466/cc64c48e-15b0-11e6-9f76-0b4d0eb11f64.jpg)

**Comment by akariv** [comment]
Thanks @smth , looks good.

**Comment by cecilaki** [comment]
I like it too. I would also really like to see something similar in the packager itself, assuming not all users will have as entry point to upload the landing page of the Packager.

**Comment by cecilaki** [comment]
@akariv  Before deployment, making sure the "**login to publish**" message also appear in the `provide-data.html` page, which is where most users will start their "upload journey"

Maybe add a message like this in the Information box >
<img width="804" alt="capture d ecran 2016-05-16 a 13 49 16" src="https://cloud.githubusercontent.com/assets/6681719/15288768/9ab17d66-1b6d-11e6-9fb1-14d7102ddeed.png">

**Comment by akariv** [comment]
Why is this important at this stage? You can log in after modelling, right before publishing.

**Comment by cecilaki** [comment]
IMHO The users need to be aware they need to login at some point in order to publish their file, and above all, before they start the process, so they have it in mind. 
Then it's their choice to actually login whenever they want.
