### ISSUE TITLE
Sort by datetime doesn't work for time graphs

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#972]
1. Time series graphs often get sorted by the measure and not the datetime dimension.
2. The sorting control doesn't appear (which is OK). However, clicking the measure (in the sidebar) changes the sort direction (toggles ascending and descending), which is simply weird.

**Comment by cecilaki** [comment]
I experienced that in the[ following dataset](http://next.openspending.org/viewer/embed/linechart/boost:boost-moldova-2005-2014?measure=executed.sum&order=economic_classification_econ1.econ1%7Casc&visualizations%5B%5D=LineChart&groups%5B%5D=economic_classification_econ1.econ1&rows%5B%5D=date_2.year&columns%5B%5D=date_2.year) (Boost Moldova, but also Boost Tunisia). 
 
<img width="915" alt="capture d ecran 2016-05-11 a 22 44 17" src="https://cloud.githubusercontent.com/assets/6681719/15214862/cc6dbf98-184f-11e6-86d6-afc8e1985f3e.png">

**Expected**
Have the datetime dimension on the x axis for line charts
