### ISSUE TITLE
OS Packager - amount/value column format

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#974]
I got this error when uploading a file with the Amount column formatted as "Number".
![error number format](https://cloud.githubusercontent.com/assets/17012538/15141335/43d16c1e-16a8-11e6-8e9a-3bf5cecbe21b.PNG)
After I formatted as "General" the file went through.

**Comment by akariv** [comment]
Could you please attach a link to the problematic file?

**Comment by akariv** [comment]
This is due to the ',' group separator in this file.
