### ISSUE TITLE
Close vis popup if there are no more available visualisations to add

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#978]

**Comment by cecilaki** [comment]
The modal should disappear once the vis has been chosen and applied. 
Doesn't require and additional "close" action by the user.

<img width="949" alt="capture d ecran 2016-05-16 a 10 24 28" src="https://cloud.githubusercontent.com/assets/6681719/15284230/6dd67e26-1b50-11e6-9959-f045988d0bbb.png">
