### ISSUE TITLE
Viewer: Round figures in Treemap / Bubble Tree / Bar Chart / Line Charts

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#979]
Amount figures should be rounded to Billions or Millions when displayed in viz types Bubble Trees / Treemaps / Bar Charts / Line Charts. 

Bubble Trees are already being handled.

**1 - Treemaps**

_From old OpenSpending treemaps_
<img width="1001" alt="capture d ecran 2016-05-16 a 10 39 05" src="https://cloud.githubusercontent.com/assets/6681719/15284593/79a4dda4-1b52-11e6-9d44-9a3be171c468.png">

**2 - Bar Charts**

Add an Y-Axis label that say `-currency symbol- [Billions]`

<img width="350" alt="capture d ecran 2016-05-16 a 10 18 17" src="https://cloud.githubusercontent.com/assets/6681719/15284683/1f88bba0-1b53-11e6-9a4a-b777313f3049.png">

**Comment by pwalsh** [comment]
@akariv @vitorbaptista is this still relevant? I think related work happened in the recent tasks Vitor did?
