### ISSUE TITLE
OS-Admin - spec ideas

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#981]
<Placeholder>

**Comment by akariv** [comment]
This is a 'Profile' page which:
 - Shows info about the user
 - Allows modifying some properties of the user
 - Shows all datasets for the user
 - For each dataset:
   - Shows information about the dataset
   - Shows whether it's published or not (and allows toggling it)
   - Has a link to the viewer to visualize it
   - Has a link to the packager to the remodelling flow (see #982)
   - Has download links to the raw datapackage.json and resources.

Related tickets: #989, #990

**Comment by cecilaki** [comment]
Great! A few comments to help me understand a bit the spec of the User Accounts:

- **Shows info about the user / Allows modifying some properties of the user**
+1. Which Info? 
First name / Last name / Email ? 
1 - Do we want users to be able to set up a Username of their choice? 
2 - Do we want users to be able to change their password and connect other than through G. accounts? 
3 - Do we want to let users manage email notifications and alerts through `Email`?  
Eg A: do we want users to get an instant email on every update made on their dataset, with possibility to change the email notifications in the settings.) 
Eg B: Users might get updates for their favorite/selected datasets.
(if Possibility to follow/favorite a dataset implemented)
Followers are people that take interested in a following a specific dataset.

- **Inviting People**
All OS Users should ne able to invite other people on OS by email. 

- Is there a plan to have a "User Profile Page" somewhere where users can fill up more info and get a public list of datasets published? Can work for Administrations/Entities/Organisations too for ex? 

- **About user edit rights of the datasets they published**

All {Data Publishing Users} can edit the dataset description, title and metadata. 
All {Data Publishing Users} are presented the possibility to hide from public/delete a dataset. 

- **Example of Table with all dataset information available to the user**

| Dataset Title  | Publication Status  | Viewer Link  | Edit your dataset (Packager Link)  | Download (links to the raw datapackage.json)  | Last updated  | Created on (date of upload)  | Storage?  |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| BOOST Moldova 2005-2014  | Published | http://next.openspending.org/viewer/boost:boost-moldova-2005-2014 | http://next.openspending.org/packager/  | http://datastore.openspending.org/boost/boost-moldova-2005-2014/  | 14-06-2016  | 21-04-2016  | 35 GB  |


- **Teams / Potentially useful for {Platform Administrators}**
Creation of a "Team" to represent work related teams within an organisation or administration, taking in account that all users are not necessarily individuals and most Open Spending projects are the result of a team work.
Teams can be shown on every person's profile page and lists the people in their immediate team. 
Each OS User can potentially create a Team.
Each user in a team has the rights to edit / modify metadata of all team datasets and hide/publish but not delete..? ( not sure about that) 

- **Admins**
Do we want some privileged OS Users (like the tech admin team) who can: 
- Edit Users Details
- Disable (not Delete) OS-Users (with extra recovering rights)
- Once a user is disabled, they can no longer publish to OS.
- Edit all data sets

**Comment by akariv** [comment]
1. Currently the only user modifiable property would be `username`.
    We're not planning any feature around other authentication methods or notifications (both can be discussed, obviously).
2. Inviting people - not sure I follow
3. Basically this would also serve as the public user profile page (although not in this iteration), showing users' info and public datasets.
4. Teams/Organisations/Admins - not in the scope of this ticket (although all good ideas and will be done eventually)

**Comment by cecilaki** [comment]
_1. Currently the only user modifiable property would be `username`._
Ok! That's fine. Just wanted to know. As long as there are no other ways to login, there's no need to change a password. 

_2. Inviting people - not sure I follow_
As a {Data Publishing User}, I want to be able to invite other contacts of mine by email to connect to OS so they can know about the project and upload their datasets.  

_3. Basically this would also serve as the public user profile page (although not in this iteration), showing users' info and public datasets._
Ok. Good to know. And probably add @smth to design the public user profile for next iteration. 
Actually would be nice to have @smth mock the user-admin page as well. 

_4. Teams/Organisations/Admins - not in the scope of this ticket_ 
Ok! For Admin Accounts - Round 2 /

**Comment by cecilaki** [comment]
Suggestion to have 2 sections: 

## 1 - My profile

- Display User email
- Display Username with possibility to modify

![os_admin_user_profile_page](https://cloud.githubusercontent.com/assets/6681719/15984823/fcf0e8fc-2fd8-11e6-9796-b868da3e9f4f.png)

## 2 - My datasets

- Have a view on all the datasets published
- Be able to search / filter them by status and/or date
- Shows whether it's published or not (and allows toggling it)
- Hide a dataset that is already added as Public
- Edit the modeling of a dataset already imported ( link to the packager remodelling flow)
- Edit the metadata / description / title of a dataset already imported
- Delete a published dataset

+

- Show a link to the viewer 
- Show download links to the raw datapackage.json and resources.
( _doesn't show in the table below but should be there too_)

![os_admin_my_datasets_page](https://cloud.githubusercontent.com/assets/6681719/15984872/7f7b4a78-2fda-11e6-8ec9-b9b22c30bca1.png)


Question: do we also want to have an edit page **per** dataset with all information as in the table?
