### ISSUE TITLE
Enhance Search API to support autocomplete and multiple fields

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#987]

**Comment by pwalsh** [comment]
@akariv I wonder if we can do this as part of platform improvements soon? Can you write a little spec to flesh out what needs to be done.

**Comment by pwalsh** [comment]
@akariv can you please write a spec for this.

**Comment by pwalsh** [comment]
@akariv can you write a spec.

**Comment by sglavoie** [comment]
**WONTFIX/CLEANUP**: Closing old issue without recent activity (~3 years) as part of #1478. Label `prioritized` was removed a long time ago. Please feel free to re-open if this is still relevant.
