### ISSUE TITLE
Load into normalised unified table

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#996]
<Placeholder>

**Comment by pwalsh** [comment]
@akariv 

We really need to know:

1. Progress
2. Estimate for work left in days
3. A spec here that others can read

**Comment by pwalsh** [comment]
@akariv can this be closed now?

cc @brew

**Comment by akariv** [comment]
@pwalsh 
Previous work regarding this took the approach of doing the normalization in the api server itself, while loading the data. Some work was done there (mainly for generating the babbage model) but it was not completed.

Now I think that the best approach would be to consolidate the pipelines server that we already and the api loader so that it's basically the same entity - the pipelines server would load data into the database (and elasticsearch) directly.

This should simplify the development (as pipelines are more powerful already than the loader) and will eventually reduce the number of maintained assets in OS.

I guess this should take about 10-20 development days.

(anyway it's done now - above text was written but never sent for some reason...)
