### ISSUE TITLE
Change login flow to end in admin page for new users.

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#998]
Make sure that a user logging in is redirected to the admin page.
The URL will contain a query parameter with the original `next`.
The OS-Admin UI will show a 'Back to what you were doing' message in case this parameter is available.

**Comment by pwalsh** [comment]
@akariv still relevant?

**Comment by pwalsh** [comment]
@akariv is this still relevant?

**Comment by akariv** [comment]
No, we can close this.
