### ISSUE TITLE
Debt: refactor viewer logic

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#999]
Make the logic for selecting dimensions / measures / filters etc. to be more modular and better designed.

**Comment by kravets-levko** [comment]
In my opinion, this is a list of top-level items that should be refactored in OS Viewer:

1. Services that are working with `babbage` API: improve code structure.

2. Application structure: build entire app in CommonJS style.

3. UI: make it more modular and make each UI component more independent from other ones and from global state.

**Comment by akariv** [comment]
Also:
Capture the logic for each visualisation type in a separate component, which can be unit tested and verified.
